INET Framework for OMNeT++/OMNEST: LSA.h File Reference
LSA.h File Reference
#include <math.h>
#include <vector>
#include "OSPFcommon.h"
#include "OSPFPacket_m.h"
Classes
struct OSPF::NextHop
class OSPF::RoutingInfo
class OSPF::LSATrackingInfo
class OSPF::RouterLSA
class OSPF::NetworkLSA
class OSPF::SummaryLSA
class OSPF::ASExternalLSA
Namespaces
namespace OSPF
All OSPF classes are in this namespace.
Functions
bool operator< (const OSPFLSAHeader &leftLSA, const OSPFLSAHeader &rightLSA)
Returns true if leftLSA is older than rightLSA.
bool operator== (const OSPFLSAHeader &leftLSA, const OSPFLSAHeader &rightLSA)
Returns true if leftLSA is the same age as rightLSA.
bool operator== (const OSPFOptions &leftOptions, const OSPFOptions &rightOptions)
bool operator!= (const OSPFOptions &leftOptions, const OSPFOptions &rightOptions)
bool operator== (const OSPF::NextHop &leftHop, const OSPF::NextHop &rightHop)
bool operator!= (const OSPF::NextHop &leftHop, const OSPF::NextHop &rightHop)
unsigned int calculateLSASize (const OSPFRouterLSA *routerLSA)
unsigned int calculateLSASize (const OSPFNetworkLSA *networkLSA)
unsigned int calculateLSASize (const OSPFSummaryLSA *summaryLSA)
unsigned int calculateLSASize (const OSPFASExternalLSA *asExternalLSA)
void printLSAHeader (const OSPFLSAHeader &lsaHeader, std::ostream &output)
std::ostream & operator<< (std::ostream &ostr, const OSPFLSA &lsa)
std::ostream & operator<< (std::ostream &ostr, const OSPFNetworkLSA &lsa)
std::ostream & operator<< (std::ostream &ostr, const TOSData &tos)
std::ostream & operator<< (std::ostream &ostr, const Link &link)
std::ostream & operator<< (std::ostream &ostr, const OSPFRouterLSA &lsa)
std::ostream & operator<< (std::ostream &ostr, const OSPFSummaryLSA &lsa)
std::ostream & operator<< (std::ostream &ostr, const ExternalTOSInfo &tos)
std::ostream & operator<< (std::ostream &ostr, const OSPFASExternalLSA &lsa)
Function Documentation
unsigned int calculateLSASize (const OSPFRouterLSA * routerLSA)
Referenced by OSPF::Interface::createUpdatePacket(), and OSPF::Neighbor::retransmitUpdatePacket().
{
    unsigned int   lsaLength = OSPF_LSA_HEADER_LENGTH + OSPF_ROUTERLSA_HEADER_LENGTH;
    unsigned short linkCount = routerLSA->getLinksArraySize();
    for (unsigned short i = 0; i < linkCount; i++) {
        const Link& link = routerLSA->getLinks(i);
        lsaLength += OSPF_LINK_HEADER_LENGTH + (link.getTosDataArraySize() * OSPF_TOS_LENGTH);
    }
    return lsaLength;
}
unsigned int calculateLSASize (const OSPFNetworkLSA * networkLSA)
{
    return (OSPF_LSA_HEADER_LENGTH + OSPF_NETWORKLSA_MASK_LENGTH +
            (networkLSA->getAttachedRoutersArraySize() * OSPF_NETWORKLSA_ADDRESS_LENGTH));
}
unsigned int calculateLSASize (const OSPFSummaryLSA * summaryLSA)
{
    return (OSPF_LSA_HEADER_LENGTH + OSPF_SUMMARYLSA_HEADER_LENGTH +
            (summaryLSA->getTosDataArraySize() * OSPF_TOS_LENGTH));
}
unsigned int calculateLSASize (const OSPFASExternalLSA * asExternalLSA)
{
    return (OSPF_LSA_HEADER_LENGTH + OSPF_ASEXTERNALLSA_HEADER_LENGTH +
            (asExternalLSA->getContents().getExternalTOSInfoArraySize() * OSPF_ASEXTERNALLSA_TOS_INFO_LENGTH));
}
bool operator!= (const OSPFOptions & leftOptions, const OSPFOptions & rightOptions) [inline]
{
    return (!(leftOptions == rightOptions));
}
bool operator!= (const OSPF::NextHop & leftHop, const OSPF::NextHop & rightHop) [inline]
{
    return (!(leftHop == rightHop));
}
bool operator< (const OSPFLSAHeader & leftLSA, const OSPFLSAHeader & rightLSA)
Returns true if leftLSA is older than rightLSA.
{
    long leftSequenceNumber = leftLSA.getLsSequenceNumber();
    long rightSequenceNumber = rightLSA.getLsSequenceNumber();
    if (leftSequenceNumber < rightSequenceNumber) {
        return true;
    }
    if (leftSequenceNumber == rightSequenceNumber) {
        unsigned short leftAge = leftLSA.getLsAge();
        unsigned short rightAge = rightLSA.getLsAge();
        if ((leftAge != MAX_AGE) && (rightAge == MAX_AGE)) {
            return true;
        }
        if ((leftAge == MAX_AGE) && (rightAge != MAX_AGE)) {
            return false;
        }
        if ((abs(leftAge - rightAge) > MAX_AGE_DIFF) && (leftAge > rightAge)) {
            return true;
        }
    }
    return false;
}
std::ostream& operator<< (std::ostream & ostr, const OSPFLSA & lsa) [inline]
{
    printLSAHeader(lsa.getHeader(), ostr);
    return ostr;
}
std::ostream& operator<< (std::ostream & ostr, const OSPFNetworkLSA & lsa)
{
    ostr << "Mask: " << lsa.getNetworkMask();
    unsigned int cnt = lsa.getAttachedRoutersArraySize();
    if (cnt) {
        ostr << ", Attached routers:";
        for (unsigned int i = 0; i < cnt; i++) {
            ostr << " " << lsa.getAttachedRouters(i);
        }
    }
    ostr << ", ";
    printLSAHeader(lsa.getHeader(), ostr);
    return ostr;
}
std::ostream& operator<< (std::ostream & ostr, const TOSData & tos)
{
    ostr << "tos: " << (int) tos.tos
         << "metric:";
    for (int i=0; i<3; i++) ostr << " " << (int)tos.tosMetric[i];
    return ostr;
}
std::ostream& operator<< (std::ostream & ostr, const Link & link)
{
    ostr << "ID: " << link.getLinkID().str(false)
         << ", data: ";
    unsigned long data = link.getLinkData();
    if ((data & 0xFF000000) != 0)
        ostr << IPv4Address(data).str(false);
    else
        ostr << data;
    ostr << ", cost: " << link.getLinkCost();
    unsigned int cnt = link.getTosDataArraySize();
    if (cnt)
    {
        ostr << ", tos: {";
        for (unsigned int i = 0; i < cnt; i++) {
            ostr << " " << link.getTosData(i);
        }
        ostr << "}";
    }
    return ostr;
}
std::ostream& operator<< (std::ostream & ostr, const OSPFRouterLSA & lsa)
{
    if (lsa.getV_VirtualLinkEndpoint()) ostr << "V, ";
    if (lsa.getE_ASBoundaryRouter()) ostr << "E, ";
    if (lsa.getB_AreaBorderRouter()) ostr << "B, ";
    ostr << "numberOfLinks: " << lsa.getNumberOfLinks() << ", ";
    unsigned int cnt = lsa.getLinksArraySize();
    if (cnt) {
        ostr << "Links: {";
        for (unsigned int i = 0; i < cnt; i++){
            ostr << " {" << lsa.getLinks(i) << "}";
        }
        ostr << "}, ";
    }
    printLSAHeader(lsa.getHeader(), ostr);
    return ostr;
}
std::ostream& operator<< (std::ostream & ostr, const OSPFSummaryLSA & lsa)
{
    ostr << "Mask: " << lsa.getNetworkMask()
         << ", Cost: " << lsa.getRouteCost() << ", ";
    unsigned int cnt = lsa.getTosDataArraySize();
    if (cnt) {
        ostr << ", tosData: {";
        for (unsigned int i = 0; i < cnt; i++) {
            ostr << " " << lsa.getTosData(i);
        }
        ostr << "}, ";
    }
    printLSAHeader(lsa.getHeader(), ostr);
    return ostr;
}
std::ostream& operator<< (std::ostream & ostr, const ExternalTOSInfo & tos)
{
    ostr << "TOSData: {" << tos.tosData
         << "}, MetricType: " << tos.E_ExternalMetricType
         << ", fwAddr: " << tos.forwardingAddress
         << ", extRouteTag: " << tos.externalRouteTag;
    return ostr;
}
std::ostream& operator<< (std::ostream & ostr, const OSPFASExternalLSA & lsa)
{
    const OSPFASExternalLSAContents& contents = lsa.getContents();
    ostr << "Mask: " << contents.getNetworkMask()
         << ", Cost: " << contents.getRouteCost()
         << ", MetricType: " << contents.getE_ExternalMetricType()
         << ", Forward: " << contents.getForwardingAddress()
         << ", ExtRouteTag: " << contents.getExternalRouteTag()
         << ", ";
    unsigned int cnt = contents.getExternalTOSInfoArraySize();
    if (cnt) {
        ostr << ", tosData: {";
        for (unsigned int i = 0; i < cnt; i++) {
            ostr << " " << contents.getExternalTOSInfo(i);
        }
        ostr << "}, ";
    }
    printLSAHeader(lsa.getHeader(), ostr);
    return ostr;
}
bool operator== (const OSPFLSAHeader & leftLSA, const OSPFLSAHeader & rightLSA)
Returns true if leftLSA is the same age as rightLSA.
{
    long           leftSequenceNumber = leftLSA.getLsSequenceNumber();
    long           rightSequenceNumber = rightLSA.getLsSequenceNumber();
    unsigned short leftAge = leftLSA.getLsAge();
    unsigned short rightAge = rightLSA.getLsAge();
    if ((leftSequenceNumber == rightSequenceNumber) &&
        (((leftAge == MAX_AGE) && (rightAge == MAX_AGE)) ||
         (((leftAge != MAX_AGE) && (rightAge != MAX_AGE)) &&
          (abs(leftAge - rightAge) <= MAX_AGE_DIFF))))
    {
        return true;
    }
    else {
        return false;
    }
}
bool operator== (const OSPFOptions & leftOptions, const OSPFOptions & rightOptions)
{
    return ((leftOptions.E_ExternalRoutingCapability == rightOptions.E_ExternalRoutingCapability) &&
            (leftOptions.MC_MulticastForwarding == rightOptions.MC_MulticastForwarding) &&
            (leftOptions.NP_Type7LSA == rightOptions.NP_Type7LSA) &&
            (leftOptions.EA_ForwardExternalLSAs == rightOptions.EA_ForwardExternalLSAs) &&
            (leftOptions.DC_DemandCircuits == rightOptions.DC_DemandCircuits));
}
bool operator== (const OSPF::NextHop & leftHop, const OSPF::NextHop & rightHop) [inline]
{
    return ((leftHop.ifIndex == rightHop.ifIndex) &&
            (leftHop.hopAddress == rightHop.hopAddress) &&
            (leftHop.advertisingRouter == rightHop.advertisingRouter));
}
void printLSAHeader (const OSPFLSAHeader & lsaHeader, std::ostream & output)
Referenced by operator<<(), OSPF::MessageHandler::printDatabaseDescriptionPacket(), OSPF::MessageHandler::printLinkStateAcknowledgementPacket(), OSPF::MessageHandler::printLinkStateUpdatePacket(), OSPF::DatabaseDescriptionHandler::processDDPacket(), OSPF::LinkStateAcknowledgementHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{
    output << "LSAHeader: age=" << lsaHeader.getLsAge()
           << ", type=";
    switch (lsaHeader.getLsType()) {
        case ROUTERLSA_TYPE:                     output << "RouterLSA";                     break;
        case NETWORKLSA_TYPE:                    output << "NetworkLSA";                    break;
        case SUMMARYLSA_NETWORKS_TYPE:           output << "SummaryLSA_Networks";           break;
        case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:  output << "SummaryLSA_ASBoundaryRouters";  break;
        case AS_EXTERNAL_LSA_TYPE:               output << "ASExternalLSA";                 break;
        default:                                 output << "Unknown";                       break;
    }
    output << ", LSID=" << lsaHeader.getLinkStateID().str(false)
           << ", advertisingRouter=" << lsaHeader.getAdvertisingRouter().str(false)
           << ", seqNumber=" << lsaHeader.getLsSequenceNumber();
    output << endl;
}