INET Framework for OMNeT++/OMNEST: ModuleAccess.cc File Reference
ModuleAccess.cc File Reference
#include "ModuleAccess.h"
Functions
bool _isNode (cModule *mod)
bool isNode (cModule *mod)
Checks if the module is node, i.e.
cModule * findModuleWherever (const char *name, cModule *from)
Find a module with given name, and "closest" to module "from".
cModule * findModuleWhereverInNode (const char *name, cModule *from)
Find a module with given name, and "closest" to module "from".
cModule * findModuleSomewhereUp (const char *name, cModule *from)
Find a module with given name, and "closest" to module "from".
cModule * findContainingNode (cModule *from)
Find the node containing the given module.
Function Documentation
bool _isNode (cModule * mod) [inline]
Referenced by findContainingNode(), findModuleWhereverInNode(), and isNode().
{
    cProperties *props = mod->getProperties();
    return props && props->getAsBool("node");
}
cModule* findContainingNode (cModule * from)
Find the node containing the given module.
Returns NULL, if no containing node.
Referenced by DHCPClient::getContainingNode(), InterfaceTable::getHostModule(), RoutingTable::getHostModule(), OSPFRouting::loadConfigFromXML(), and NetAnimTrace::receiveSignal().
{
    for (cModule *curmod=from; curmod; curmod=curmod->getParentModule())
    {
        if (_isNode(curmod))
            return curmod;
    }
    return NULL;
}
cModule* findModuleSomewhereUp (const char * name, cModule * from)
Find a module with given name, and "closest" to module "from".
Operation: gradually rises in the module hierarchy, and looks for a submodule of the given name.
{
    cModule *mod = NULL;
    for (cModule *curmod=from; !mod && curmod; curmod=curmod->getParentModule())
        mod = curmod->getSubmodule(name);
    return mod;
}
cModule* findModuleWherever (const char * name, cModule * from)
Find a module with given name, and "closest" to module "from".
Operation: gradually rises in the module hierarchy, and searches recursively among all submodules at every level.
{
    cModule *mod = NULL;
    for (cModule *curmod=from; !mod && curmod; curmod=curmod->getParentModule())
        mod = findSubmodRecursive(curmod, name);
    return mod;
}
cModule* findModuleWhereverInNode (const char * name, cModule * from)
Find a module with given name, and "closest" to module "from".
Operation: gradually rises in the module hierarchy up to the module, and searches recursively among all submodules at every level.
Referenced by ModuleAccess< xMIPv6 >::get(), ModuleAccess< xMIPv6 >::getIfExists(), TraCITestApp::handlePositionUpdate(), and PPP::~PPP().
{
    cModule *mod = NULL;
    for (cModule *curmod=from; curmod; curmod=curmod->getParentModule())
    {
        mod = findSubmodRecursive(curmod, name);
        if (mod || _isNode(curmod))
            break;
    }
    return mod;
}
bool isNode (cModule * mod)
Checks if the module is node, i.e.
it has a attribute.
{
    return (mod != NULL) ? _isNode(mod) : false;
}