INET Framework for OMNeT++/OMNEST: ModuleAccess.h File Reference
ModuleAccess.h File Reference
#include "INETDefs.h"
Classes
class ModuleAccess< T >
Finds and returns the pointer to a module of type T and name N.
Functions
INET_API cModule * findModuleWherever (const char *name, cModule *from)
Find a module with given name, and "closest" to module "from".
INET_API cModule * findModuleWhereverInNode (const char *name, cModule *from)
Find a module with given name, and "closest" to module "from".
INET_API cModule * findModuleSomewhereUp (const char *name, cModule *from)
Find a module with given name, and "closest" to module "from".
bool isNode (cModule *mod)
Checks if the module is node, i.e.
INET_API cModule * findContainingNode (cModule *from)
Find the node containing the given module.
Function Documentation
INET_API cModule* findContainingNode (cModule * from)
Find the node containing the given module.
Returns NULL, if no containing node.
Referenced by DHCPClient::getContainingNode(), InterfaceTable::getHostModule(), RoutingTable::getHostModule(), OSPFRouting::loadConfigFromXML(), and NetAnimTrace::receiveSignal().
{
    for (cModule *curmod=from; curmod; curmod=curmod->getParentModule())
    {
        if (_isNode(curmod))
            return curmod;
    }
    return NULL;
}
INET_API cModule* findModuleSomewhereUp (const char * name, cModule * from)
Find a module with given name, and "closest" to module "from".
Operation: gradually rises in the module hierarchy, and looks for a submodule of the given name.
{
    cModule *mod = NULL;
    for (cModule *curmod=from; !mod && curmod; curmod=curmod->getParentModule())
        mod = curmod->getSubmodule(name);
    return mod;
}
INET_API cModule* findModuleWherever (const char * name, cModule * from)
Find a module with given name, and "closest" to module "from".
Operation: gradually rises in the module hierarchy, and searches recursively among all submodules at every level.
{
    cModule *mod = NULL;
    for (cModule *curmod=from; !mod && curmod; curmod=curmod->getParentModule())
        mod = findSubmodRecursive(curmod, name);
    return mod;
}
INET_API cModule* findModuleWhereverInNode (const char * name, cModule * from)
Find a module with given name, and "closest" to module "from".
Operation: gradually rises in the module hierarchy up to the module, and searches recursively among all submodules at every level.
Referenced by ModuleAccess< xMIPv6 >::get(), ModuleAccess< xMIPv6 >::getIfExists(), TraCITestApp::handlePositionUpdate(), and PPP::~PPP().
{
    cModule *mod = NULL;
    for (cModule *curmod=from; curmod; curmod=curmod->getParentModule())
    {
        mod = findSubmodRecursive(curmod, name);
        if (mod || _isNode(curmod))
            break;
    }
    return mod;
}
bool isNode (cModule * mod)
Checks if the module is node, i.e.
it has a attribute.
{
    return (mod != NULL) ? _isNode(mod) : false;
}