INET Framework for OMNeT++/OMNEST: TCPSegment.h File Reference
TCPSegment.h File Reference
#include <list>
#include "INETDefs.h"
#include "TCPSegment_m.h"
Classes
class Sack
class TCPSegment
Represents a TCP segment.
Functions
Comparing sequence numbers
bool seqLess (uint32 a, uint32 b)
bool seqLE (uint32 a, uint32 b)
bool seqGreater (uint32 a, uint32 b)
bool seqGE (uint32 a, uint32 b)
uint32 seqMin (uint32 a, uint32 b)
uint32 seqMax (uint32 a, uint32 b)
Function Documentation
bool seqGE (uint32 a, uint32 b) [inline]
Referenced by TCPConnection::addSacks(), TCPVirtualDataRcvQueue::extractTo(), TCPVirtualDataRcvQueue::insertBytesFromSegment(), TCPConnection::isLost(), TcpLwipMsgBasedReceiveQueue::notifyAboutIncomingSegmentProcessing(), TCPConnection::processAckInEstabEtc(), TCPReno::receivedDataAck(), TCPNewReno::receivedDataAck(), TCPReno::receivedDuplicateAck(), TCPConnection::sendSegment(), TCPSACKRexmitQueue::setSackedBit(), and TCPConnection::updateRcvWnd().
{return (a - b) < (1UL << 31);}
bool seqGreater (uint32 a, uint32 b) [inline]
Referenced by TCPConnection::processAckInEstabEtc(), TCPConnection::processSACKOption(), TCPConnection::processSegment1stThru8th(), TCPConnection::processSegmentInSynSent(), TCPConnection::retransmitOneSegment(), TCPConnection::sendData(), TCPConnection::sendOneNewSegment(), TCPConnection::sendSegmentDuringLossRecoveryPhase(), TCPByteStreamRcvQueue::Region::split(), TCPVirtualDataRcvQueue::Region::split(), and TCPSegment::truncateSegment().
{return a != b && (a - b) < (1UL << 31);}
bool seqLE (uint32 a, uint32 b) [inline]
Referenced by TCPConnection::addSacks(), TCPSACKRexmitQueue::checkRexmitQueueForSackedOrRexmittedSegments(), TCPSACKRexmitQueue::checkSackBlock(), Sack::contains(), TCPByteStreamSendQueue::createSegmentWithBytes(), TCPVirtualDataSendQueue::createSegmentWithBytes(), TCPMsgBasedSendQueue::createSegmentWithBytes(), TcpLwipMsgBasedSendQueue::createSegmentWithBytes(), TcpLwipMsgBasedSendQueue::discardAckedBytes(), TCPByteStreamSendQueue::discardUpTo(), TCPVirtualDataSendQueue::discardUpTo(), TCPMsgBasedSendQueue::discardUpTo(), TCPSACKRexmitQueue::discardUpTo(), TCPSACKRexmitQueue::enqueueSentData(), TcpLwipMsgBasedReceiveQueue::extractBytesUpTo(), TCPVirtualDataRcvQueue::extractTo(), TCPSACKRexmitQueue::getAmountOfSackedBytes(), TCPVirtualDataRcvQueue::getLE(), TCPVirtualDataRcvQueue::Region::getLengthTo(), TCPSACKRexmitQueue::getNumOfDiscontiguousSacks(), TCPVirtualDataRcvQueue::getRE(), TCPSACKRexmitQueue::getSackedBit(), TCPMsgBasedRcvQueue::insertBytesFromSegment(), TCPConnection::isSegmentAcceptable(), TcpLwipMsgBasedReceiveQueue::notifyAboutIncomingSegmentProcessing(), TCPConnection::processAckInEstabEtc(), TCPConnection::processSACKOption(), TCPConnection::processSegment1stThru8th(), TCPConnection::processSegmentInSynSent(), TCPConnection::processTSOption(), TCPConnection::sendSegmentDuringLossRecoveryPhase(), TCPSACKRexmitQueue::setSackedBit(), and TCPConnection::updateWndInfo().
{return (b - a) < (1UL << 31);}
bool seqLess (uint32 a, uint32 b) [inline]
Referenced by TCPConnection::addSacks(), TCPSACKRexmitQueue::checkQueue(), TCPSACKRexmitQueue::checkRexmitQueueForSackedOrRexmittedSegments(), TCPSACKRexmitQueue::checkSackBlock(), TCPVirtualDataRcvQueue::Region::compare(), TCPSACKRexmitQueue::discardUpTo(), TCPVirtualDataSendQueue::enqueueAppData(), TCPMsgBasedSendQueue::enqueueAppData(), TCPSACKRexmitQueue::enqueueSentData(), TCPMsgBasedRcvQueue::extractBytesUpTo(), TCPSACKRexmitQueue::getAmountOfSackedBytes(), TCPSendQueue::getBytesAvailable(), TCPVirtualDataRcvQueue::getLE(), TCPVirtualDataRcvQueue::Region::getLengthTo(), TCPVirtualDataRcvQueue::getRE(), TCPSACKRexmitQueue::getSackedBit(), TCPMsgBasedRcvQueue::insertBytesFromSegment(), TCPConnection::isSegmentAcceptable(), TCPByteStreamRcvQueue::Region::merge(), TCPVirtualDataRcvQueue::Region::merge(), TCPConnection::nextSeg(), TcpLwipMsgBasedReceiveQueue::notifyAboutIncomingSegmentProcessing(), TCPConnection::processAckInEstabEtc(), TCPConnection::processSegment1stThru8th(), TCPConnection::processTSOption(), TCPBaseAlg::receivedDataAck(), TCPConnection::sendSegmentDuringLossRecoveryPhase(), TCPConnection::setPipe(), TCPSACKRexmitQueue::setSackedBit(), TCPByteStreamRcvQueue::Region::split(), TCPVirtualDataRcvQueue::Region::split(), TCPSegment::truncateSegment(), and TCPConnection::updateWndInfo().
{return a != b && (b - a) < (1UL << 31);}
uint32 seqMax (uint32 a, uint32 b) [inline]
Referenced by TCPVirtualDataRcvQueue::insertBytesFromSegment(), and TCPByteStreamRcvQueue::Region::merge().
{return ((a - b) < (1UL << 31)) ? a : b;}
uint32 seqMin (uint32 a, uint32 b) [inline]
Referenced by TCPVirtualDataRcvQueue::insertBytesFromSegment(), and TCPByteStreamRcvQueue::Region::merge().
{return ((b - a) < (1UL << 31)) ? a : b;}