INET Framework for OMNeT++/OMNEST: Utils.h File Reference
Utils.h File Reference
#include <vector>
#include "INETDefs.h"
#include "IntServ.h"
Functions
EroVector routeToEro (IPAddressVector rro)
std::string vectorToString (IPAddressVector vec)
std::string vectorToString (IPAddressVector vec, const char *delim)
std::string vectorToString (EroVector vec)
std::string vectorToString (EroVector vec, const char *delim)
void removeDuplicates (std::vector< int > &vec)
TODO documentation.
bool find (std::vector< int > &vec, int value)
TODO documentation.
bool find (const IPAddressVector &vec, IPv4Address addr)
TODO documentation.
void append (std::vector< int > &dest, const std::vector< int > &src)
TODO documentation.
int find (const EroVector &ERO, IPv4Address node)
TODO documentation.
cModule * getPayloadOwner (cPacket *msg)
XXX function appears to be unused.
Function Documentation
void append (std::vector< int > & dest, const std::vector< int > & src)
TODO documentation.
{
    for (unsigned int i = 0; i < src.size(); i++)
        dest.push_back(src[i]);
}
bool find (std::vector< int > & vec, int value)
TODO documentation.
{
    for (unsigned int i = 0; i < vec.size(); i++)
        if (vec[i] == value)
            return true;
    return false;
}
bool find (const IPAddressVector & vec, IPv4Address addr)
TODO documentation.
{
    for (unsigned int i = 0; i < vec.size(); i++)
        if (vec[i] == addr)
            return true;
    return false;
}
int find (const EroVector & ERO, IPv4Address node)
TODO documentation.
Referenced by SchedulerBase::addListener(), PassiveQueueBase::addListener(), IPv4NetworkConfigurator::assignAddresses(), TED::calculateShortestPath(), MessageChecker::checkFieldValue(), contains(), RTP::createProfile(), RTPProfile::createSenderModule(), RTPProfile::dataIn(), Topology::deleteNode(), find(), DYMOUM::getNextHopGroup(), OLSR::getNextHopGroup(), IPv4InterfaceData::hasMulticastListener(), Ieee80211MgmtAdhocWithEtx::initialize(), RoutingTable::internalRemoveMulticastRoute(), RoutingTable::internalRemoveRoute(), IPv4InterfaceData::isMemberOfMulticastGroup(), ph_srt_find(), RSVP::refreshResv(), SCTP::removeAssociation(), SchedulerBase::removeListener(), PassiveQueueBase::removeListener(), RoutingTable6::removeRoute(), IPv4NetworkConfigurator::RoutingTableInfo::removeRouteInfo(), FailureManager::replaceNode(), LinkStateRouting::sendToPeers(), NotificationBoard::subscribe(), xMIPv6::triggerRouteOptimization(), Topology::unlinkFromDestNode(), Topology::unlinkFromSourceNode(), and NotificationBoard::unsubscribe().
{
    for (unsigned int i = 0; i < ERO.size(); i++)
        if (ERO[i].node == node)
            return i;
    ASSERT(false);
    return -1; // to prevent warning
}
cModule* getPayloadOwner (cPacket * msg)
XXX function appears to be unused.
{
    while (msg->getEncapsulatedPacket())
        msg = msg->getEncapsulatedPacket();
    if (msg->hasPar("owner"))
        return simulation.getModule(msg->par("owner"));
    else
        return NULL;
}
void removeDuplicates (std::vector< int > & vec)
TODO documentation.
{
    for (unsigned int i = 0; i < vec.size(); i++)
    {
        unsigned int j;
        for (j = 0; j < i; j++)
            if (vec[j] == vec[i])
                break;
        if (j < i)
        {
            vec.erase(vec.begin() + i);
            --i;
        }
    }
}
EroVector routeToEro (IPAddressVector rro)
{
    EroVector ero;
    for (unsigned int i = 0; i < rro.size(); i++)
    {
        EroObj_t hop;
        hop.L = false;
        hop.node = rro[i];
        ero.push_back(hop);
    }
    return ero;
}
std::string vectorToString (IPAddressVector vec)
Referenced by RSVP::print(), and vectorToString().
{
    return vectorToString(vec, ", ");
}
std::string vectorToString (IPAddressVector vec, const char * delim)
{
  std::ostringstream stream;
  for (unsigned int i = 0; i < vec.size(); i++)
  {
      stream << vec[i];
      if (i < vec.size() - 1)
        stream << delim;
  }
  stream << std::flush;
  std::string str(stream.str());
  return str;
}
std::string vectorToString (EroVector vec)
{
    return vectorToString(vec, ", ");
}
std::string vectorToString (EroVector vec, const char * delim)
{
    std::ostringstream stream;
    for (unsigned int i = 0; i < vec.size(); i++)
    {
        stream << vec[i].node;
        if (i < vec.size() - 1)
            stream << delim;
    }
    stream << std::flush;
    std::string str(stream.str());
    return str;
}