INET Framework for OMNeT++/OMNEST: ICMP Class Reference
ICMP Class Reference
ICMP module.
#include <ICMP.h>
Public Member Functions
virtual void sendErrorMessage (IPv4Datagram *datagram, ICMPType type, ICMPCode code)
This method can be called from other modules to send an ICMP error packet in response to a received bogus packet.
virtual void sendErrorMessage (cPacket *transportPacket, IPv4ControlInfo *ctrl, ICMPType type, ICMPCode code)
This method can be called from other modules to send an ICMP error packet in response to a received bogus packet from the transport layer (like UDP).
Protected Types
typedef std::map< long, int > PingMap
Protected Member Functions
virtual void processICMPMessage (ICMPMessage *)
virtual void errorOut (ICMPMessage *)
virtual void processEchoRequest (ICMPMessage *)
virtual void processEchoReply (ICMPMessage *)
virtual void sendEchoRequest (PingPayload *)
virtual void sendToIP (ICMPMessage *, const IPv4Address &dest)
virtual void sendToIP (ICMPMessage *msg)
virtual void handleMessage (cMessage *msg)
Protected Attributes
RoutingTableAccess routingTableAccess
PingMap pingMap
Detailed Description
ICMP module.
Member Typedef Documentation
typedef std::map<long,int> ICMP::PingMap [protected]
Member Function Documentation
void ICMP::errorOut (ICMPMessage * icmpmsg) [protected, virtual]
Referenced by processICMPMessage().
{
    send(icmpmsg, "errorOut");
}
void ICMP::handleMessage (cMessage * msg) [protected, virtual]
{
    cGate *arrivalGate = msg->getArrivalGate();
    // process arriving ICMP message
    if (!strcmp(arrivalGate->getName(), "localIn"))
    {
        processICMPMessage(check_and_cast<ICMPMessage *>(msg));
        return;
    }
    // request from application
    if (!strcmp(arrivalGate->getName(), "pingIn"))
    {
        sendEchoRequest(check_and_cast<PingPayload *>(msg));
        return;
    }
}
void ICMP::processEchoReply (ICMPMessage * reply) [protected, virtual]
Referenced by processICMPMessage().
{
    IPv4ControlInfo *ctrl = check_and_cast<IPv4ControlInfo*>(reply->removeControlInfo());
    PingPayload *payload = check_and_cast<PingPayload *>(reply->decapsulate());
    payload->setControlInfo(ctrl);
    delete reply;
    long originatorId = payload->getOriginatorId();
    PingMap::iterator i = pingMap.find(originatorId);
    if (i != pingMap.end())
        send(payload, "pingOut", i->second);
    else
    {
        EV << "Received ECHO REPLY has an unknown originator ID: " << originatorId << ", packet dropped." << endl;
        delete payload;
    }
}
void ICMP::processEchoRequest (ICMPMessage * request) [protected, virtual]
Referenced by processICMPMessage().
{
    // turn request into a reply
    ICMPMessage *reply = request;
    reply->setName((std::string(request->getName())+"-reply").c_str());
    reply->setType(ICMP_ECHO_REPLY);
    // swap src and dest
    // TBD check what to do if dest was multicast etc?
    IPv4ControlInfo *ctrl = check_and_cast<IPv4ControlInfo *>(reply->getControlInfo());
    IPv4Address src = ctrl->getSrcAddr();
    IPv4Address dest = ctrl->getDestAddr();
    // A. Ariza Modification 5/1/2011 clean the interface id, this forces the use of routing table in the IPv4 layer
    ctrl->setInterfaceId(-1);
    ctrl->setSrcAddr(dest);
    ctrl->setDestAddr(src);
    sendToIP(reply);
}
void ICMP::processICMPMessage (ICMPMessage * icmpmsg) [protected, virtual]
Referenced by handleMessage(), and sendErrorMessage().
{
    switch (icmpmsg->getType())
    {
        case ICMP_DESTINATION_UNREACHABLE:
            errorOut(icmpmsg);
            break;
        case ICMP_REDIRECT:
            errorOut(icmpmsg);
            break;
        case ICMP_TIME_EXCEEDED:
            errorOut(icmpmsg);
            break;
        case ICMP_PARAMETER_PROBLEM:
            errorOut(icmpmsg);
            break;
        case ICMP_ECHO_REQUEST:
            processEchoRequest(icmpmsg);
            break;
        case ICMP_ECHO_REPLY:
            processEchoReply(icmpmsg);
            break;
        case ICMP_TIMESTAMP_REQUEST:
            processEchoRequest(icmpmsg);
            break;
        case ICMP_TIMESTAMP_REPLY:
            processEchoReply(icmpmsg);
            break;
        default:
            throw cRuntimeError("Unknown ICMP type %d", icmpmsg->getType());
    }
}
void ICMP::sendEchoRequest (PingPayload * msg) [protected, virtual]
Referenced by handleMessage().
{
    cGate *arrivalGate = msg->getArrivalGate();
    int i = arrivalGate->getIndex();
    pingMap[msg->getOriginatorId()] = i;
    IPv4ControlInfo *ctrl = check_and_cast<IPv4ControlInfo*>(msg->removeControlInfo());
    ctrl->setProtocol(IP_PROT_ICMP);
    ICMPMessage *request = new ICMPMessage(msg->getName());
    request->setType(ICMP_ECHO_REQUEST);
    request->encapsulate(msg);
    request->setControlInfo(ctrl);
    sendToIP(request);
}
void ICMP::sendErrorMessage (IPv4Datagram * datagram, ICMPType type, ICMPCode code) [virtual]
This method can be called from other modules to send an ICMP error packet in response to a received bogus packet.
Referenced by IPv4::fragmentAndSend(), IPv4::handlePacketFromNetwork(), IPv4FragBuf::purgeStaleFragments(), IPv4::reassembleAndDeliver(), IPv4::routeUnicastPacket(), sendErrorMessage(), and ManetRoutingBase::sendICMP().
{
    Enter_Method("sendErrorMessage(datagram, type=%d, code=%d)", type, code);
    // get ownership
    take(origDatagram);
    // don't send ICMP error messages for multicast messages
    if (origDatagram->getDestAddress().isMulticast())
    {
        EV << "won't send ICMP error messages for multicast message " << origDatagram << endl;
        delete origDatagram;
        return;
    }
    // do not reply with error message to error message
    if (origDatagram->getTransportProtocol() == IP_PROT_ICMP)
    {
        ICMPMessage *recICMPMsg = check_and_cast<ICMPMessage *>(origDatagram->getEncapsulatedPacket());
        if (recICMPMsg->getType()<128)
        {
            EV << "ICMP error received -- do not reply to it" << endl;
            delete origDatagram;
            return;
        }
    }
    // assemble a message name
    char msgname[32];
    static long ctr;
    sprintf(msgname, "ICMP-error-#%ld-type%d-code%d", ++ctr, type, code);
    // debugging information
    EV << "sending ICMP error " << msgname << endl;
    // create and send ICMP packet
    ICMPMessage *errorMessage = new ICMPMessage(msgname);
    errorMessage->setType(type);
    errorMessage->setCode(code);
    errorMessage->encapsulate(origDatagram);
    // ICMP message length: the internet header plus the first 8 bytes of
    // the original datagram's data is returned to the sender.
    //
    // NOTE: since we just overwrite the errorMessage length without actually
    // truncating origDatagram, one can get "packet length became negative"
    // error when decapsulating the origDatagram on the receiver side.
    // A workaround is to avoid decapsulation, or to manually set the
    // errorMessage length to be larger than the encapsulated message.
    int dataLength = origDatagram->getByteLength() - origDatagram->getHeaderLength();
    int truncatedDataLength = dataLength <= 8 ? dataLength : 8;
    errorMessage->setByteLength(8 + origDatagram->getHeaderLength() + truncatedDataLength);
    // if srcAddr is not filled in, we're still in the src node, so we just
    // process the ICMP message locally, right away
    if (origDatagram->getSrcAddress().isUnspecified())
    {
        // pretend it came from the IPv4 layer
        IPv4ControlInfo *controlInfo = new IPv4ControlInfo();
        controlInfo->setSrcAddr(IPv4Address::LOOPBACK_ADDRESS); // FIXME maybe use configured loopback address
        controlInfo->setProtocol(IP_PROT_ICMP);
        errorMessage->setControlInfo(controlInfo);
        // then process it locally
        processICMPMessage(errorMessage);
    }
    else
    {
        sendToIP(errorMessage, origDatagram->getSrcAddress());
    }
}
void ICMP::sendErrorMessage (cPacket * transportPacket, IPv4ControlInfo * ctrl, ICMPType type, ICMPCode code) [virtual]
This method can be called from other modules to send an ICMP error packet in response to a received bogus packet from the transport layer (like UDP).
The ICMP error packet needs to include (part of) the original IPv4 datagram, so this function will wrap back the transport packet into the IPv4 datagram based on its IPv4ControlInfo.
{
    Enter_Method("sendErrorMessage(transportPacket, ctrl, type=%d, code=%d)", type, code);
    IPv4Datagram *datagram = ctrl->removeOrigDatagram();
    take(transportPacket);
    take(datagram);
    datagram->encapsulate(transportPacket);
    sendErrorMessage(datagram, type, code);
}
void ICMP::sendToIP (ICMPMessage * msg, const IPv4Address & dest) [protected, virtual]
Referenced by processEchoRequest(), sendEchoRequest(), and sendErrorMessage().
{
    IPv4ControlInfo *controlInfo = new IPv4ControlInfo();
    controlInfo->setDestAddr(dest);
    controlInfo->setProtocol(IP_PROT_ICMP);
    msg->setControlInfo(controlInfo);
    send(msg, "sendOut");
}
void ICMP::sendToIP (ICMPMessage * msg) [protected, virtual]
{
    // assumes IPv4ControlInfo is already attached
    send(msg, "sendOut");
}
Member Data Documentation
PingMap ICMP::pingMap [protected]
Referenced by processEchoReply(), and sendEchoRequest().
RoutingTableAccess ICMP::routingTableAccess [protected]
The documentation for this class was generated from the following files:
ICMP.h
ICMP.cc