INET Framework for OMNeT++/OMNEST: RoutingTable Class Reference
RoutingTable Class Reference
Represents the routing table.
#include <RoutingTable.h>
Public Member Functions
RoutingTable ()
virtual ~RoutingTable ()
virtual void printRoutingTable () const
For debugging.
virtual void printMulticastRoutingTable () const
For debugging.
virtual cModule * getHostModule ()
Returns the host or router this routing table lives in.
virtual bool isIPForwardingEnabled ()
IPv4 forwarding on/off.
virtual bool isMulticastForwardingEnabled ()
IPv4 multicast forwarding on/off.
virtual IPv4Address getRouterId ()
Returns routerId.
virtual void setRouterId (IPv4Address a)
Sets routerId.
Interfaces
virtual void configureInterfaceForIPv4 (InterfaceEntry *ie)
virtual InterfaceEntry * getInterfaceByAddress (const IPv4Address &address) const
Returns an interface given by its address.
Routing functions (query the route table)
virtual bool isLocalAddress (const IPv4Address &dest) const
Checks if the address is a local one, i.e.
virtual bool isLocalBroadcastAddress (const IPv4Address &dest) const
Checks if the address is a local network broadcast address, i.e.
virtual InterfaceEntry * findInterfaceByLocalBroadcastAddress (const IPv4Address &dest) const
Returns the interface entry having the specified address as its local broadcast address.
virtual IPv4Route * findBestMatchingRoute (const IPv4Address &dest) const
The routing function.
virtual InterfaceEntry * getInterfaceForDestAddr (const IPv4Address &dest) const
Convenience function based on findBestMatchingRoute().
virtual IPv4Address getGatewayForDestAddr (const IPv4Address &dest) const
Convenience function based on findBestMatchingRoute().
Multicast routing functions
virtual bool isLocalMulticastAddress (const IPv4Address &dest) const
Checks if the address is in one of the local multicast group address list.
virtual const IPv4MulticastRoute * findBestMatchingMulticastRoute (const IPv4Address &origin, const IPv4Address &group) const
Returns route for a multicast source and multicast group.
Route table manipulation
virtual int getNumRoutes () const
Returns the total number of routes (unicast, multicast, plus the default route).
virtual IPv4Route * getRoute (int k) const
Returns the kth route.
virtual IPv4Route * getDefaultRoute () const
Finds and returns the default route, or NULL if it doesn't exist.
virtual void addRoute (IPv4Route *entry)
Adds a route to the routing table.
virtual IPv4Route * removeRoute (IPv4Route *entry)
Removes the given route from the routing table, and returns it.
virtual bool deleteRoute (IPv4Route *entry)
Deletes the given route from the routing table.
virtual int getNumMulticastRoutes () const
Returns the total number of multicast routes.
virtual IPv4MulticastRoute * getMulticastRoute (int k) const
Returns the kth multicast route.
virtual void addMulticastRoute (IPv4MulticastRoute *entry)
Adds a multicast route to the routing table.
virtual IPv4MulticastRoute * removeMulticastRoute (IPv4MulticastRoute *entry)
Removes the given route from the routing table, and returns it.
virtual bool deleteMulticastRoute (IPv4MulticastRoute *entry)
Deletes the given multicast route from the routing table.
virtual void purge ()
Deletes invalid routes from the routing table.
virtual std::vector< IPv4Address > gatherAddresses () const
Utility function: Returns a vector of all addresses of the node.
virtual void routeChanged (IPv4Route *entry, int fieldCode)
To be called from route objects whenever a field changes.
virtual void multicastRouteChanged (IPv4MulticastRoute *entry, int fieldCode)
To be called from multicast route objects whenever a field changes.
Protected Types
typedef std::vector< IPv4Route * > RouteVector
typedef std::vector
< IPv4MulticastRoute * > MulticastRouteVector
typedef
IPv4MulticastRoute::ChildInterface ChildInterface
typedef
IPv4MulticastRoute::ChildInterfaceVector ChildInterfaceVector
typedef std::map< IPv4Address,
IPv4Route * > RoutingCache
typedef std::set< IPv4Address > AddressSet
Protected Member Functions
virtual void configureLoopbackForIPv4 ()
virtual void configureRouterId ()
virtual void updateNetmaskRoutes ()
virtual void updateDisplayString ()
virtual void deleteInterfaceRoutes (InterfaceEntry *entry)
virtual void invalidateCache ()
void internalAddRoute (IPv4Route *entry)
IPv4Route * internalRemoveRoute (IPv4Route *entry)
void internalAddMulticastRoute (IPv4MulticastRoute *entry)
IPv4MulticastRoute * internalRemoveMulticastRoute (IPv4MulticastRoute *entry)
virtual int numInitStages () const
virtual void initialize (int stage)
virtual void handleMessage (cMessage *)
Raises an error.
virtual void receiveChangeNotification (int category, const cObject *details)
Called by the NotificationBoard whenever a change of a category occurs to which this client has subscribed.
Static Protected Member Functions
static bool routeLessThan (const IPv4Route *a, const IPv4Route *b)
static bool multicastRouteLessThan (const IPv4MulticastRoute *a, const IPv4MulticastRoute *b)
Protected Attributes
IInterfaceTable * ift
NotificationBoard * nb
IPv4Address routerId
bool IPForward
bool multicastForward
RouteVector routes
MulticastRouteVector multicastRoutes
RoutingCache routingCache
AddressSet localAddresses
AddressSet localBroadcastAddresses
Detailed Description
Represents the routing table.
This object has one instance per host or router. It has methods to manage the route table and the interface table, so one can achieve functionality similar to the "route" and "ifconfig" commands.
See the NED documentation for general overview.
This is a simple module without gates, it requires function calls to it (message handling does nothing). Methods are provided for reading and updating the interface table and the route table, as well as for unicast and multicast routing.
Interfaces are dynamically registered: at the start of the simulation, every L2 module adds its own interface entry to the table.
The route table is read from a file (RoutingTableParser); the file can also fill in or overwrite interface settings. The route table can also be read and modified during simulation, typically by routing protocol implementations (e.g. OSPF).
Entries in the route table are represented by IPv4Route objects. IPv4Route objects can be polymorphic: if a routing protocol needs to store additional data, it can simply subclass from IPv4Route, and add the derived object to the table.
Uses RoutingTableParser to read routing files (.irt, .mrt).
See also:
InterfaceEntry, IPv4InterfaceData, IPv4Route
Member Typedef Documentation
typedef std::set<IPv4Address> RoutingTable::AddressSet [protected]
typedef IPv4MulticastRoute::ChildInterface RoutingTable::ChildInterface [protected]
typedef IPv4MulticastRoute::ChildInterfaceVector RoutingTable::ChildInterfaceVector [protected]
typedef std::vector<IPv4MulticastRoute*> RoutingTable::MulticastRouteVector [protected]
typedef std::vector<IPv4Route *> RoutingTable::RouteVector [protected]
typedef std::map<IPv4Address, IPv4Route *> RoutingTable::RoutingCache [protected]
Constructor & Destructor Documentation
RoutingTable::RoutingTable ()
{
    ift = NULL;
    nb = NULL;
}
RoutingTable::~RoutingTable () [virtual]
{
    for (unsigned int i=0; i<routes.size(); i++)
        delete routes[i];
    for (unsigned int i=0; i<multicastRoutes.size(); i++)
        delete multicastRoutes[i];
}
Member Function Documentation
void RoutingTable::addMulticastRoute (IPv4MulticastRoute * entry) [virtual]
Adds a multicast route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implements IRoutingTable.
{
    Enter_Method("addMulticastRoute(...)");
    internalAddMulticastRoute(entry);
    invalidateCache();
    updateDisplayString();
    nb->fireChangeNotification(NF_IPv4_MROUTE_ADDED, entry);
}
void RoutingTable::addRoute (IPv4Route * entry) [virtual]
Adds a route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implements IRoutingTable.
{
    Enter_Method("addRoute(...)");
    internalAddRoute(entry);
    invalidateCache();
    updateDisplayString();
    nb->fireChangeNotification(NF_IPv4_ROUTE_ADDED, entry);
}
void RoutingTable::configureInterfaceForIPv4 (InterfaceEntry * ie) [virtual]
Implements IRoutingTable.
Referenced by initialize().
{
    IPv4InterfaceData *d = new IPv4InterfaceData();
    ie->setIPv4Data(d);
    // metric: some hints: OSPF cost (2e9/bps value), MS KB article Q299540, ...
    d->setMetric((int)ceil(2e9/ie->getDatarate())); // use OSPF cost as default
    // join "224.0.0.1" and "224.0.0.2" (if router) multicast groups automatically
    if (ie->isMulticast())
    {
        d->joinMulticastGroup(IPv4Address::ALL_HOSTS_MCAST);
        if (IPForward)
            d->joinMulticastGroup(IPv4Address::ALL_ROUTERS_MCAST);
    }
}
void RoutingTable::configureLoopbackForIPv4 () [protected, virtual]
Referenced by initialize().
{
    InterfaceEntry *ie = ift->getFirstLoopbackInterface();
    // add IPv4 info. Set 127.0.0.1/8 as address by default --
    // we may reconfigure later it to be the routerId
    IPv4InterfaceData *d = new IPv4InterfaceData();
    d->setIPAddress(IPv4Address::LOOPBACK_ADDRESS);
    d->setNetmask(IPv4Address::LOOPBACK_NETMASK);
    d->setMetric(1);
    ie->setIPv4Data(d);
}
void RoutingTable::configureRouterId () [protected, virtual]
Referenced by initialize().
{
    if (routerId.isUnspecified())  // not yet configured
    {
        const char *routerIdStr = par("routerId").stringValue();
        if (!strcmp(routerIdStr, "auto"))  // non-"auto" cases already handled in stage 1
        {
            // choose highest interface address as routerId
            for (int i=0; i<ift->getNumInterfaces(); ++i)
            {
                InterfaceEntry *ie = ift->getInterface(i);
                if (!ie->isLoopback() && ie->ipv4Data()->getIPAddress().getInt() > routerId.getInt())
                    routerId = ie->ipv4Data()->getIPAddress();
            }
        }
    }
    else // already configured
    {
        // if there is no interface with routerId yet, assign it to the loopback address;
        // TODO find out if this is a good practice, in which situations it is useful etc.
        if (getInterfaceByAddress(routerId)==NULL)
        {
            InterfaceEntry *lo0 = ift->getFirstLoopbackInterface();
            lo0->ipv4Data()->setIPAddress(routerId);
            lo0->ipv4Data()->setNetmask(IPv4Address::ALLONES_ADDRESS);
        }
    }
}
void RoutingTable::deleteInterfaceRoutes (InterfaceEntry * entry) [protected, virtual]
Referenced by receiveChangeNotification().
{
    bool changed = false;
    // delete unicast routes using this interface
    for (RouteVector::iterator it = routes.begin(); it != routes.end(); )
    {
        IPv4Route *route = *it;
        if (route->getInterface() == entry)
        {
            it = routes.erase(it);
            ASSERT(route->getRoutingTable() == this); // still filled in, for the listeners' benefit
            nb->fireChangeNotification(NF_IPv4_ROUTE_DELETED, route);
            delete route;
            changed = true;
        }
        else
            ++it;
    }
    // delete or update multicast routes:
    //   1. delete routes has entry as parent
    //   2. remove entry from children list
    for (MulticastRouteVector::iterator it = multicastRoutes.begin(); it != multicastRoutes.end(); )
    {
        IPv4MulticastRoute *route = *it;
        if (route->getParent() == entry)
        {
            it = multicastRoutes.erase(it);
            ASSERT(route->getRoutingTable() == this); // still filled in, for the listeners' benefit
            nb->fireChangeNotification(NF_IPv4_MROUTE_DELETED, route);
            delete route;
            changed = true;
        }
        else
        {
            bool removed = route->removeChild(entry);
            if (removed)
            {
                nb->fireChangeNotification(NF_IPv4_MROUTE_CHANGED, route);
                changed = true;
            }
            ++it;
        }
    }
    if (changed)
    {
        invalidateCache();
        updateDisplayString();
    }
}
bool RoutingTable::deleteMulticastRoute (IPv4MulticastRoute * entry) [virtual]
Deletes the given multicast route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implements IRoutingTable.
{
    Enter_Method("deleteMulticastRoute(...)");
    entry = internalRemoveMulticastRoute(entry);
    if (entry != NULL)
    {
        invalidateCache();
        updateDisplayString();
        ASSERT(entry->getRoutingTable() == this); // still filled in, for the listeners' benefit
        nb->fireChangeNotification(NF_IPv4_MROUTE_DELETED, entry);
        delete entry;
    }
    return entry != NULL;
}
bool RoutingTable::deleteRoute (IPv4Route * entry) [virtual]
Deletes the given route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implements IRoutingTable.
Referenced by internalAddRoute().
{
    Enter_Method("deleteRoute(...)");
    entry = internalRemoveRoute(entry);
    if (entry != NULL)
    {
        invalidateCache();
        updateDisplayString();
        ASSERT(entry->getRoutingTable() == this); // still filled in, for the listeners' benefit
        nb->fireChangeNotification(NF_IPv4_ROUTE_DELETED, entry);
        delete entry;
    }
    return entry != NULL;
}
const IPv4MulticastRoute * RoutingTable::findBestMatchingMulticastRoute (const IPv4Address & origin, const IPv4Address & group) const [virtual]
Returns route for a multicast source and multicast group.
Implements IRoutingTable.
{
    Enter_Method("getMulticastRoutesFor(%u.%u.%u.%u, %u.%u.%u.%u)",
            origin.getDByte(0), origin.getDByte(1), origin.getDByte(2), origin.getDByte(3),
            group.getDByte(0), group.getDByte(1), group.getDByte(2), group.getDByte(3)); // note: str().c_str() too slow here here
    // TODO caching?
    for (MulticastRouteVector::const_iterator i=multicastRoutes.begin(); i!=multicastRoutes.end(); ++i)
    {
        const IPv4MulticastRoute *e = *i;
        if (e->isValid() && e->matches(origin, group))
            return e;
    }
    return NULL;
}
IPv4Route * RoutingTable::findBestMatchingRoute (const IPv4Address & dest) const [virtual]
The routing function.
Performs longest prefix match for the given destination address, and returns the resulting route. Returns NULL if there is no matching route.
Implements IRoutingTable.
Referenced by getGatewayForDestAddr(), and getInterfaceForDestAddr().
{
    Enter_Method("findBestMatchingRoute(%u.%u.%u.%u)", dest.getDByte(0), dest.getDByte(1), dest.getDByte(2), dest.getDByte(3)); // note: str().c_str() too slow here
    RoutingCache::iterator it = routingCache.find(dest);
    if (it != routingCache.end())
    {
        if (it->second==NULL || it->second->isValid())
            return it->second;
    }
    // find best match (one with longest prefix)
    // default route has zero prefix length, so (if exists) it'll be selected as last resort
    IPv4Route *bestRoute = NULL;
    for (RouteVector::const_iterator i=routes.begin(); i!=routes.end(); ++i)
    {
        IPv4Route *e = *i;
        if (e->isValid())
        {
            if (IPv4Address::maskedAddrAreEqual(dest, e->getDestination(), e->getNetmask())) // match
            {
                bestRoute = const_cast<IPv4Route *>(e);
                break;
            }
        }
    }
    routingCache[dest] = bestRoute;
    return bestRoute;
}
InterfaceEntry * RoutingTable::findInterfaceByLocalBroadcastAddress (const IPv4Address & dest) const [virtual]
Returns the interface entry having the specified address as its local broadcast address.
Implements IRoutingTable.
{
    for (int i=0; i<ift->getNumInterfaces(); i++)
    {
        InterfaceEntry *ie = ift->getInterface(i);
        IPv4Address interfaceAddr = ie->ipv4Data()->getIPAddress();
        IPv4Address broadcastAddr = interfaceAddr.getBroadcastAddress(ie->ipv4Data()->getNetmask());
        if (broadcastAddr == dest)
            return ie;
    }
    return NULL;
}
std::vector< IPv4Address > RoutingTable::gatherAddresses () const [virtual]
Utility function: Returns a vector of all addresses of the node.
Implements IRoutingTable.
{
    std::vector<IPv4Address> addressvector;
    for (int i=0; i<ift->getNumInterfaces(); ++i)
        addressvector.push_back(ift->getInterface(i)->ipv4Data()->getIPAddress());
    return addressvector;
}
IPv4Route * RoutingTable::getDefaultRoute () const [virtual]
Finds and returns the default route, or NULL if it doesn't exist.
Implements IRoutingTable.
Referenced by internalAddRoute().
{
    // if exists default route entry, it is the last valid entry
    for (RouteVector::const_reverse_iterator i=routes.rbegin(); i!=routes.rend() && (*i)->getNetmask().isUnspecified(); ++i)
    {
        if ((*i)->isValid())
            return *i;
    }
    return NULL;
}
IPv4Address RoutingTable::getGatewayForDestAddr (const IPv4Address & dest) const [virtual]
Convenience function based on findBestMatchingRoute().
Returns the gateway for the destination address. Returns the unspecified address if the destination is not in routing table or the gateway field is not filled in in the route.
Implements IRoutingTable.
{
    Enter_Method("getGatewayForDestAddr(%u.%u.%u.%u)", dest.getDByte(0), dest.getDByte(1), dest.getDByte(2), dest.getDByte(3)); // note: str().c_str() too slow here
    const IPv4Route *e = findBestMatchingRoute(dest);
    return e ? e->getGateway() : IPv4Address();
}
cModule * RoutingTable::getHostModule () [virtual]
Returns the host or router this routing table lives in.
Implements IRoutingTable.
{
    return findContainingNode(this);
}
InterfaceEntry * RoutingTable::getInterfaceByAddress (const IPv4Address & address) const [virtual]
Returns an interface given by its address.
Returns NULL if not found.
Implements IRoutingTable.
Referenced by configureRouterId().
{
    Enter_Method("getInterfaceByAddress(%u.%u.%u.%u)", addr.getDByte(0), addr.getDByte(1), addr.getDByte(2), addr.getDByte(3)); // note: str().c_str() too slow here
    if (addr.isUnspecified())
        return NULL;
    for (int i=0; i<ift->getNumInterfaces(); ++i)
    {
        InterfaceEntry *ie = ift->getInterface(i);
        if (ie->ipv4Data()->getIPAddress()==addr)
            return ie;
    }
    return NULL;
}
InterfaceEntry * RoutingTable::getInterfaceForDestAddr (const IPv4Address & dest) const [virtual]
Convenience function based on findBestMatchingRoute().
Returns the output interface for the packets with dest as destination address, or NULL if the destination is not in routing table.
Implements IRoutingTable.
{
    Enter_Method("getInterfaceForDestAddr(%u.%u.%u.%u)", dest.getDByte(0), dest.getDByte(1), dest.getDByte(2), dest.getDByte(3)); // note: str().c_str() too slow here
    const IPv4Route *e = findBestMatchingRoute(dest);
    return e ? e->getInterface() : NULL;
}
virtual IPv4MulticastRoute* RoutingTable::getMulticastRoute (int k) const [inline, virtual]
Returns the kth multicast route.
Implements IRoutingTable.
Referenced by printMulticastRoutingTable().
{ return k < (int)multicastRoutes.size() ? multicastRoutes[k] : NULL; }
virtual int RoutingTable::getNumMulticastRoutes () const [inline, virtual]
Returns the total number of multicast routes.
Implements IRoutingTable.
Referenced by printMulticastRoutingTable().
{ return multicastRoutes.size(); }
virtual int RoutingTable::getNumRoutes () const [inline, virtual]
Returns the total number of routes (unicast, multicast, plus the default route).
Implements IRoutingTable.
Referenced by printRoutingTable().
{ return routes.size(); }
IPv4Route * RoutingTable::getRoute (int k) const [virtual]
Returns the kth route.
Implements IRoutingTable.
Referenced by printRoutingTable().
{
    if (k < (int)routes.size())
        return routes[k];
    return NULL;
}
virtual IPv4Address RoutingTable::getRouterId () [inline, virtual]
Returns routerId.
Implements IRoutingTable.
{return routerId;}
void RoutingTable::handleMessage (cMessage * msg) [protected, virtual]
Raises an error.
{
    throw cRuntimeError("This module doesn't process messages");
}
void RoutingTable::initialize (int stage) [protected, virtual]
{
    if (stage==0)
    {
        // get a pointer to the NotificationBoard module and IInterfaceTable
        nb = NotificationBoardAccess().get();
        ift = InterfaceTableAccess().get();
        IPForward = par("IPForward").boolValue();
        multicastForward = par("forwardMulticast");
        nb->subscribe(this, NF_INTERFACE_CREATED);
        nb->subscribe(this, NF_INTERFACE_DELETED);
        nb->subscribe(this, NF_INTERFACE_STATE_CHANGED);
        nb->subscribe(this, NF_INTERFACE_CONFIG_CHANGED);
        nb->subscribe(this, NF_INTERFACE_IPv4CONFIG_CHANGED);
        WATCH_PTRVECTOR(routes);
        WATCH_PTRVECTOR(multicastRoutes);
        WATCH(IPForward);
        WATCH(routerId);
    }
    else if (stage==1)
    {
        // L2 modules register themselves in stage 0, so we can only configure
        // the interfaces in stage 1.
        const char *filename = par("routingFile");
        // At this point, all L2 modules have registered themselves (added their
        // interface entries). Create the per-interface IPv4 data structures.
        IInterfaceTable *interfaceTable = InterfaceTableAccess().get();
        for (int i=0; i<interfaceTable->getNumInterfaces(); ++i)
            configureInterfaceForIPv4(interfaceTable->getInterface(i));
        configureLoopbackForIPv4();
        // read routing table file (and interface configuration)
        RoutingTableParser parser(ift, this);
        if (*filename && parser.readRoutingTableFromFile(filename)==-1)
            error("Error reading routing table file %s", filename);
        // set routerId if param is not "" (==no routerId) or "auto" (in which case we'll
        // do it later in stage 3, after network configurators configured the interfaces)
        const char *routerIdStr = par("routerId").stringValue();
        if (strcmp(routerIdStr, "") && strcmp(routerIdStr, "auto"))
            routerId = IPv4Address(routerIdStr);
    }
    else if (stage==3)
    {
        // routerID selection must be after stage==2 when network autoconfiguration
        // assigns interface addresses
        configureRouterId();
        // we don't use notifications during initialize(), so we do it manually.
        // Should be in stage=3 because autoconfigurator runs in stage=2.
        updateNetmaskRoutes();
        //printRoutingTable();
    }
}
void RoutingTable::internalAddMulticastRoute (IPv4MulticastRoute * entry) [protected]
Referenced by addMulticastRoute(), and multicastRouteChanged().
{
    if (!entry->getOriginNetmask().isValidNetmask())
        error("addMulticastRoute(): wrong netmask %s in multicast route", entry->getOriginNetmask().str().c_str());
    if ((entry->getOrigin().getInt() & ~entry->getOriginNetmask().getInt()) != 0)
        error("addMulticastRoute(): suspicious route: origin IP address %s has bits set outside netmask %s",
                entry->getOrigin().str().c_str(), entry->getOriginNetmask().str().c_str());
    if (!entry->getMulticastGroup().isUnspecified() && !entry->getMulticastGroup().isMulticast())
        error("addMulticastRoute(): group address (%s) is not a multicast address",
                entry->getMulticastGroup().str().c_str());
    // check that the interface exists
    if (entry->getParent() && !entry->getParent()->isMulticast())
        error("addMulticastRoute(): parent interface must be multicast capable");
    const ChildInterfaceVector &children = entry->getChildren();
    for (ChildInterfaceVector::const_iterator it = children.begin(); it != children.end(); ++it)
    {
        if (!(*it))
            error("addMulticastRoute(): child interface cannot be NULL");
        else if (!(*it)->getInterface()->isMulticast())
            error("addMulticastRoute(): child interface must be multicast capable");
        else if ((*it)->getInterface() == entry->getParent())
            error("addMulticastRoute(): child interface cannot be the same as the parent");
    }
    // add to tables
    // we keep entries sorted by netmask desc, metric asc in routeList, so that we can
    // stop at the first match when doing the longest netmask matching
    MulticastRouteVector::iterator pos =
            upper_bound(multicastRoutes.begin(), multicastRoutes.end(), entry, multicastRouteLessThan);
    multicastRoutes.insert(pos, entry);
    entry->setRoutingTable(this);
}
void RoutingTable::internalAddRoute (IPv4Route * entry) [protected]
Referenced by addRoute(), and routeChanged().
{
    if (!entry->getNetmask().isValidNetmask())
        error("addRoute(): wrong netmask %s in route", entry->getNetmask().str().c_str());
    if ((entry->getDestination().getInt() & ~entry->getNetmask().getInt()) != 0)
        error("addRoute(): suspicious route: destination IP address %s has bits set outside netmask %s",
                entry->getDestination().str().c_str(), entry->getNetmask().str().c_str());
    // check that the interface exists
    if (!entry->getInterface())
        error("addRoute(): interface cannot be NULL");
    // if this is a default route, remove old default route (we're replacing it)
    if (entry->getNetmask().isUnspecified())
    {
        IPv4Route *oldDefaultRoute = getDefaultRoute();
        if (oldDefaultRoute != NULL)
            deleteRoute(oldDefaultRoute);
    }
    // add to tables
    // we keep entries sorted by netmask desc, metric asc in routeList, so that we can
    // stop at the first match when doing the longest netmask matching
    RouteVector::iterator pos = upper_bound(routes.begin(), routes.end(), entry, routeLessThan);
    routes.insert(pos, entry);
    entry->setRoutingTable(this);
}
IPv4MulticastRoute * RoutingTable::internalRemoveMulticastRoute (IPv4MulticastRoute * entry) [protected]
Referenced by deleteMulticastRoute(), multicastRouteChanged(), and removeMulticastRoute().
{
    MulticastRouteVector::iterator i = std::find(multicastRoutes.begin(), multicastRoutes.end(), entry);
    if (i!=multicastRoutes.end())
    {
        multicastRoutes.erase(i);
        return entry;
    }
    return NULL;
}
IPv4Route * RoutingTable::internalRemoveRoute (IPv4Route * entry) [protected]
Referenced by deleteRoute(), removeRoute(), and routeChanged().
{
    RouteVector::iterator i = std::find(routes.begin(), routes.end(), entry);
    if (i!=routes.end())
    {
        routes.erase(i);
        return entry;
    }
    return NULL;
}
void RoutingTable::invalidateCache () [protected, virtual]
Referenced by addMulticastRoute(), addRoute(), deleteInterfaceRoutes(), deleteMulticastRoute(), deleteRoute(), multicastRouteChanged(), purge(), receiveChangeNotification(), removeMulticastRoute(), removeRoute(), routeChanged(), and updateNetmaskRoutes().
{
    routingCache.clear();
    localAddresses.clear();
    localBroadcastAddresses.clear();
}
virtual bool RoutingTable::isIPForwardingEnabled () [inline, virtual]
IPv4 forwarding on/off.
Implements IRoutingTable.
{return IPForward;}
bool RoutingTable::isLocalAddress (const IPv4Address & dest) const [virtual]
Checks if the address is a local one, i.e.
one of the host's.
Implements IRoutingTable.
{
    Enter_Method("isLocalAddress(%u.%u.%u.%u)", dest.getDByte(0), dest.getDByte(1), dest.getDByte(2), dest.getDByte(3)); // note: str().c_str() too slow here
    if (localAddresses.empty())
    {
        // collect interface addresses if not yet done
        for (int i=0; i<ift->getNumInterfaces(); i++)
        {
            IPv4Address interfaceAddr = ift->getInterface(i)->ipv4Data()->getIPAddress();
            localAddresses.insert(interfaceAddr);
        }
    }
    AddressSet::iterator it = localAddresses.find(dest);
    return it!=localAddresses.end();
}
bool RoutingTable::isLocalBroadcastAddress (const IPv4Address & dest) const [virtual]
Checks if the address is a local network broadcast address, i.e.
one of the broadcast addresses derived from the interface addresses and netmasks.
Implements IRoutingTable.
{
    Enter_Method("isLocalBroadcastAddress(%u.%u.%u.%u)", dest.getDByte(0), dest.getDByte(1), dest.getDByte(2), dest.getDByte(3)); // note: str().c_str() too slow here
    if (localBroadcastAddresses.empty())
    {
        // collect interface addresses if not yet done
        for (int i=0; i<ift->getNumInterfaces(); i++)
        {
            IPv4Address interfaceAddr = ift->getInterface(i)->ipv4Data()->getIPAddress();
            IPv4Address broadcastAddr = interfaceAddr.getBroadcastAddress(ift->getInterface(i)->ipv4Data()->getNetmask());
            if (!broadcastAddr.isUnspecified())
            {
                 localBroadcastAddresses.insert(broadcastAddr);
            }
        }
    }
    AddressSet::iterator it = localBroadcastAddresses.find(dest);
    return it!=localBroadcastAddresses.end();
}
bool RoutingTable::isLocalMulticastAddress (const IPv4Address & dest) const [virtual]
Checks if the address is in one of the local multicast group address list.
Implements IRoutingTable.
{
    Enter_Method("isLocalMulticastAddress(%u.%u.%u.%u)", dest.getDByte(0), dest.getDByte(1), dest.getDByte(2), dest.getDByte(3)); // note: str().c_str() too slow here
    for (int i=0; i<ift->getNumInterfaces(); i++)
    {
        InterfaceEntry *ie = ift->getInterface(i);
        if (ie->ipv4Data()->isMemberOfMulticastGroup(dest))
            return true;
    }
    return false;
}
virtual bool RoutingTable::isMulticastForwardingEnabled () [inline, virtual]
IPv4 multicast forwarding on/off.
Implements IRoutingTable.
{ return multicastForward; }
void RoutingTable::multicastRouteChanged (IPv4MulticastRoute * entry, int fieldCode) [virtual]
To be called from multicast route objects whenever a field changes.
Used for maintaining internal data structures and firing "routing table changed" notifications.
Implements IRoutingTable.
{
    if (fieldCode==IPv4MulticastRoute::F_ORIGIN || fieldCode==IPv4MulticastRoute::F_ORIGINMASK ||
            fieldCode==IPv4MulticastRoute::F_MULTICASTGROUP || fieldCode==IPv4MulticastRoute::F_METRIC) // our data structures depend on these fields
    {
        entry = internalRemoveMulticastRoute(entry);
        ASSERT(entry != NULL);  // failure means inconsistency: route was not found in this routing table
        internalAddMulticastRoute(entry);
        invalidateCache();
        updateDisplayString();
    }
    nb->fireChangeNotification(NF_IPv4_MROUTE_CHANGED, entry); // TODO include fieldCode in the notification
}
bool RoutingTable::multicastRouteLessThan (const IPv4MulticastRoute * a, const IPv4MulticastRoute * b) [static, protected]
Referenced by internalAddMulticastRoute().
{
    // We want routes with longer
    // prefixes to be at front, so we compare them as "less".
    if (a->getOriginNetmask() != b->getOriginNetmask())
        return a->getOriginNetmask() > b->getOriginNetmask();
    // For metric, a smaller value is better (we report that as "less").
    if (a->getOrigin() != b->getOrigin())
        return a->getOrigin() < b->getOrigin();
    // put the unspecified group after the specified ones
    if (a->getMulticastGroup() != b->getMulticastGroup())
        return a->getMulticastGroup() > b->getMulticastGroup();
    return a->getMetric() < b->getMetric();
}
virtual int RoutingTable::numInitStages () const [inline, protected, virtual]
{return 4;}
void RoutingTable::printMulticastRoutingTable () const [virtual]
For debugging.
Implements IRoutingTable.
{
    EV << "-- Multicast routing table --\n";
    ev.printf("%-16s %-16s %-16s %-6s %-6s %s\n",
              "Source", "Netmask", "Group", "Metric", "In", "Outs");
    for (int i=0; i<getNumMulticastRoutes(); i++) {
        IPv4MulticastRoute *route = getMulticastRoute(i);
        ev.printf("%-16s %-16s %-16s %-6d %-6s ",
                  route->getOrigin().isUnspecified() ? "*" : route->getOrigin().str().c_str(),
                  route->getOriginNetmask().isUnspecified() ? "*" : route->getOriginNetmask().str().c_str(),
                  route->getMulticastGroup().isUnspecified() ? "*" : route->getMulticastGroup().str().c_str(),
                  route->getMetric(),
                  !route->getParent() ? "*" : route->getParent()->getName());
        const ChildInterfaceVector &children = route->getChildren();
        for (ChildInterfaceVector::const_iterator it = children.begin(); it != children.end(); ++it)
        {
            if (it != children.begin())
                EV << ",";
            EV << (*it)->getInterface()->getName();
        }
        EV << "\n";
    }
    EV << "\n";
}
void RoutingTable::printRoutingTable () const [virtual]
For debugging.
Implements IRoutingTable.
{
    EV << "-- Routing table --\n";
    ev.printf("%-16s %-16s %-16s %-4s %-16s %s\n",
              "Destination", "Netmask", "Gateway", "Iface", "", "Metric");
    for (int i=0; i<getNumRoutes(); i++) {
        IPv4Route *route = getRoute(i);
        InterfaceEntry *interfacePtr = route->getInterface();
        ev.printf("%-16s %-16s %-16s %-4s (%s) %d\n",
                  route->getDestination().isUnspecified() ? "*" : route->getDestination().str().c_str(),
                  route->getNetmask().isUnspecified() ? "*" : route->getNetmask().str().c_str(),
                  route->getGateway().isUnspecified() ? "*" : route->getGateway().str().c_str(),
                  !interfacePtr ? "*" : interfacePtr->getName(),
                  !interfacePtr ? "*  " : interfacePtr->ipv4Data()->getIPAddress().str().c_str(),
                  route->getMetric());
    }
    EV << "\n";
}
void RoutingTable::purge () [virtual]
Deletes invalid routes from the routing table.
Invalid routes are those where the isValid() method returns false.
Implements IRoutingTable.
{
    bool deleted = false;
    // purge unicast routes
    for (RouteVector::iterator it = routes.begin(); it != routes.end(); )
    {
        IPv4Route *route = *it;
        if (route->isValid())
            ++it;
        else
        {
            it = routes.erase(it);
            ASSERT(route->getRoutingTable() == this); // still filled in, for the listeners' benefit
            nb->fireChangeNotification(NF_IPv4_ROUTE_DELETED, route);
            delete route;
            deleted = true;
        }
    }
    // purge multicast routes
    for (MulticastRouteVector::iterator it = multicastRoutes.begin(); it != multicastRoutes.end(); )
    {
        IPv4MulticastRoute *route = *it;
        if (route->isValid())
            ++it;
        else
        {
            it = multicastRoutes.erase(it);
            ASSERT(route->getRoutingTable() == this); // still filled in, for the listeners' benefit
            nb->fireChangeNotification(NF_IPv4_MROUTE_DELETED, route);
            delete route;
            deleted = true;
        }
    }
    if (deleted)
    {
        invalidateCache();
        updateDisplayString();
    }
}
void RoutingTable::receiveChangeNotification (int category, const cObject * details) [protected, virtual]
Called by the NotificationBoard whenever a change of a category occurs to which this client has subscribed.
Implements INotifiable.
{
    if (simulation.getContextType()==CTX_INITIALIZE)
        return;  // ignore notifications during initialize
    Enter_Method_Silent();
    printNotificationBanner(category, details);
    if (category==NF_INTERFACE_CREATED)
    {
        // add netmask route for the new interface
        updateNetmaskRoutes();
    }
    else if (category==NF_INTERFACE_DELETED)
    {
        // remove all routes that point to that interface
        InterfaceEntry *entry = check_and_cast<InterfaceEntry*>(details);
        deleteInterfaceRoutes(entry);
    }
    else if (category==NF_INTERFACE_STATE_CHANGED)
    {
        invalidateCache();
    }
    else if (category==NF_INTERFACE_CONFIG_CHANGED)
    {
        invalidateCache();
    }
    else if (category==NF_INTERFACE_IPv4CONFIG_CHANGED)
    {
        // if anything IPv4-related changes in the interfaces, interface netmask
        // based routes have to be re-built.
        updateNetmaskRoutes();
    }
}
IPv4MulticastRoute * RoutingTable::removeMulticastRoute (IPv4MulticastRoute * entry) [virtual]
Removes the given route from the routing table, and returns it.
NULL is returned of the route was not in the routing table.
Implements IRoutingTable.
{
    Enter_Method("removeMulticastRoute(...)");
    entry = internalRemoveMulticastRoute(entry);
    if (entry != NULL)
    {
        invalidateCache();
        updateDisplayString();
        ASSERT(entry->getRoutingTable() == this); // still filled in, for the listeners' benefit
        nb->fireChangeNotification(NF_IPv4_MROUTE_DELETED, entry);
        entry->setRoutingTable(NULL);
    }
    return entry;
}
IPv4Route * RoutingTable::removeRoute (IPv4Route * entry) [virtual]
Removes the given route from the routing table, and returns it.
NULL is returned of the route was not in the routing table.
Implements IRoutingTable.
{
    Enter_Method("removeRoute(...)");
    entry = internalRemoveRoute(entry);
    if (entry != NULL)
    {
        invalidateCache();
        updateDisplayString();
        ASSERT(entry->getRoutingTable() == this); // still filled in, for the listeners' benefit
        nb->fireChangeNotification(NF_IPv4_ROUTE_DELETED, entry);
        entry->setRoutingTable(NULL);
    }
    return entry;
}
void RoutingTable::routeChanged (IPv4Route * entry, int fieldCode) [virtual]
To be called from route objects whenever a field changes.
Used for maintaining internal data structures and firing "routing table changed" notifications.
Implements IRoutingTable.
{
    if (fieldCode==IPv4Route::F_DESTINATION || fieldCode==IPv4Route::F_NETMASK || fieldCode==IPv4Route::F_METRIC) // our data structures depend on these fields
    {
        entry = internalRemoveRoute(entry);
        ASSERT(entry != NULL);  // failure means inconsistency: route was not found in this routing table
        internalAddRoute(entry);
        invalidateCache();
        updateDisplayString();
    }
    nb->fireChangeNotification(NF_IPv4_ROUTE_CHANGED, entry); // TODO include fieldCode in the notification
}
bool RoutingTable::routeLessThan (const IPv4Route * a, const IPv4Route * b) [static, protected]
Referenced by internalAddRoute(), and updateNetmaskRoutes().
{
    // helper for sort() in addRoute(). We want routes with longer
    // prefixes to be at front, so we compare them as "less".
    // For metric, a smaller value is better (we report that as "less").
    if (a->getNetmask() != b->getNetmask())
        return a->getNetmask() > b->getNetmask();
    if (a->getDestination() != b->getDestination())
        return a->getDestination() < b->getDestination();
    return a->getMetric() < b->getMetric();
}
void RoutingTable::setRouterId (IPv4Address a) [virtual]
Sets routerId.
Implements IRoutingTable.
{
    routerId = a;
}
void RoutingTable::updateDisplayString () [protected, virtual]
Referenced by addMulticastRoute(), addRoute(), deleteInterfaceRoutes(), deleteMulticastRoute(), deleteRoute(), multicastRouteChanged(), purge(), removeMulticastRoute(), removeRoute(), routeChanged(), and updateNetmaskRoutes().
{
    if (!ev.isGUI())
        return;
    char buf[80];
    if (routerId.isUnspecified())
        sprintf(buf, "%d+%d routes", (int)routes.size(), (int)multicastRoutes.size());
    else
        sprintf(buf, "routerId: %s\n%d+%d routes", routerId.str().c_str(), (int)routes.size(), (int)multicastRoutes.size());
    getDisplayString().setTagArg("t", 0, buf);
}
void RoutingTable::updateNetmaskRoutes () [protected, virtual]
Referenced by initialize(), and receiveChangeNotification().
{
    // first, delete all routes with src=IFACENETMASK
    for (unsigned int k=0; k<routes.size(); k++)
    {
        if (routes[k]->getSource()==IPv4Route::IFACENETMASK)
        {
            std::vector<IPv4Route *>::iterator it = routes.begin()+(k--);  // '--' is necessary because indices shift down
            IPv4Route *route = *it;
            routes.erase(it);
            ASSERT(route->getRoutingTable() == this); // still filled in, for the listeners' benefit
            nb->fireChangeNotification(NF_IPv4_ROUTE_DELETED, route);
            delete route;
        }
    }
    // then re-add them, according to actual interface configuration
    // TODO: say there's a node somewhere in the network that belongs to the interface's subnet
    // TODO: and it is not on the same link, and the gateway does not use proxy ARP, how will packets reach that node?
    for (int i=0; i<ift->getNumInterfaces(); i++)
    {
        InterfaceEntry *ie = ift->getInterface(i);
        if (ie->ipv4Data()->getNetmask()!=IPv4Address::ALLONES_ADDRESS)
        {
            IPv4Route *route = new IPv4Route();
            route->setSource(IPv4Route::IFACENETMASK);
            route->setDestination(ie->ipv4Data()->getIPAddress().doAnd(ie->ipv4Data()->getNetmask()));
            route->setNetmask(ie->ipv4Data()->getNetmask());
            route->setGateway(IPv4Address());
            route->setMetric(ie->ipv4Data()->getMetric());
            route->setInterface(ie);
            route->setRoutingTable(this);
            RouteVector::iterator pos = upper_bound(routes.begin(), routes.end(), route, routeLessThan);
            routes.insert(pos, route);
            nb->fireChangeNotification(NF_IPv4_ROUTE_ADDED, route);
        }
    }
    invalidateCache();
    updateDisplayString();
}
Member Data Documentation
IInterfaceTable* RoutingTable::ift [protected]
Referenced by configureLoopbackForIPv4(), configureRouterId(), findInterfaceByLocalBroadcastAddress(), gatherAddresses(), getInterfaceByAddress(), initialize(), isLocalAddress(), isLocalBroadcastAddress(), isLocalMulticastAddress(), RoutingTable(), and updateNetmaskRoutes().
bool RoutingTable::IPForward [protected]
Referenced by configureInterfaceForIPv4(), and initialize().
AddressSet RoutingTable::localAddresses [mutable, protected]
Referenced by invalidateCache(), and isLocalAddress().
AddressSet RoutingTable::localBroadcastAddresses [mutable, protected]
Referenced by invalidateCache(), and isLocalBroadcastAddress().
bool RoutingTable::multicastForward [protected]
Referenced by initialize().
MulticastRouteVector RoutingTable::multicastRoutes [protected]
Referenced by deleteInterfaceRoutes(), findBestMatchingMulticastRoute(), initialize(), internalAddMulticastRoute(), internalRemoveMulticastRoute(), purge(), updateDisplayString(), and ~RoutingTable().
NotificationBoard* RoutingTable::nb [protected]
IPv4Address RoutingTable::routerId [protected]
Referenced by configureRouterId(), initialize(), setRouterId(), and updateDisplayString().
RouteVector RoutingTable::routes [protected]
Referenced by deleteInterfaceRoutes(), findBestMatchingRoute(), getDefaultRoute(), getRoute(), initialize(), internalAddRoute(), internalRemoveRoute(), purge(), updateDisplayString(), updateNetmaskRoutes(), and ~RoutingTable().
RoutingCache RoutingTable::routingCache [mutable, protected]
Referenced by findBestMatchingRoute(), and invalidateCache().
The documentation for this class was generated from the following files:
RoutingTable.h
RoutingTable.cc