INET Framework for OMNeT++/OMNEST: InterfaceEntry Class Reference
InterfaceEntry Class Reference
Interface entry for the interface table in IInterfaceTable.
#include <InterfaceEntry.h>
Public Member Functions
virtual void setInterfaceTable (IInterfaceTable *t)
virtual void setInterfaceId (int id)
InterfaceEntry (cModule *interfaceModule)
virtual ~InterfaceEntry ()
virtual std::string info () const
virtual std::string detailedInfo () const
virtual std::string getFullPath () const
IInterfaceTable * getInterfaceTable () const
Returns the IInterfaceTable this interface is in, or NULL.
Field getters. Note they are non-virtual and inline, for performance reasons.
int getInterfaceId () const
cModule * getInterfaceModule () const
int getNetworkLayerGateIndex () const
int getNodeOutputGateId () const
int getNodeInputGateId () const
int getMTU () const
bool isDown () const
bool isBroadcast () const
bool isMulticast () const
bool isPointToPoint () const
bool isLoopback () const
double getDatarate () const
const MACAddress & getMacAddress () const
const InterfaceToken & getInterfaceToken () const
Field setters
virtual void setName (const char *s)
virtual void setNetworkLayerGateIndex (int i)
virtual void setNodeOutputGateId (int i)
virtual void setNodeInputGateId (int i)
virtual void setMtu (int m)
virtual void setDown (bool b)
virtual void setBroadcast (bool b)
virtual void setMulticast (bool b)
virtual void setPointToPoint (bool b)
virtual void setLoopback (bool b)
virtual void setDatarate (double d)
virtual void setMACAddress (const MACAddress &addr)
virtual void setInterfaceToken (const InterfaceToken &t)
Accessing protocol-specific interface data. Note methods are non-virtual, for performance reasons.
IPv4InterfaceData * ipv4Data () const
IPv6InterfaceData * ipv6Data () const
InterfaceProtocolData * getProtocol3Data () const
InterfaceProtocolData * getProtocol4Data () const
Installing protocol-specific interface data
virtual void setIPv4Data (IPv4InterfaceData *p)
virtual void setIPv6Data (IPv6InterfaceData *p)
virtual void setProtocol3Data (InterfaceProtocolData *p)
virtual void setProtocol4Data (InterfaceProtocolData *p)
access to the cost process estimation
virtual bool setEstimateCostProcess (int, MacEstimateCostProcess *p)
virtual MacEstimateCostProcess * getEstimateCostProcess (int)
Protected Member Functions
virtual void configChanged ()
virtual void stateChanged ()
virtual void changed (int category)
Protected Attributes
IInterfaceTable * ownerp
IInterfaceTable that contains this interface, or NULL.
cModule * interfaceModule
interface module, or NULL
int interfaceId
identifies the interface in the IInterfaceTable
int nwLayerGateIndex
index of ifIn[],ifOut[] gates to that interface (or -1 if virtual interface)
int nodeOutputGateId
id of the output gate of this host/router (or -1 if this is a virtual interface)
int nodeInputGateId
id of the input gate of this host/router (or -1 if this is a virtual interface)
int mtu
Maximum Transmission Unit (e.g. 1500 on Ethernet)
bool down
current state (up or down)
bool broadcast
interface supports broadcast
bool multicast
interface supports multicast
bool pointToPoint
interface is point-to-point link
bool loopback
interface is loopback interface
double datarate
data rate in bit/s
MACAddress macAddr
link-layer address (for now, only IEEE 802 MAC addresses are supported)
InterfaceToken token
for IPv6 stateless autoconfig (RFC 1971), interface identifier (RFC 2462)
IPv4InterfaceData * ipv4data
IPv4-specific interface info (IPv4 address, etc)
IPv6InterfaceData * ipv6data
IPv6-specific interface info (IPv6 addresses, etc)
InterfaceProtocolData * protocol3data
extension point: data for a 3rd network-layer protocol
InterfaceProtocolData * protocol4data
extension point: data for a 4th network-layer protocol
std::vector
< MacEstimateCostProcess * > estimateCostProcessArray
Private Member Functions
InterfaceEntry (const InterfaceEntry &obj)
InterfaceEntry & operator= (const InterfaceEntry &obj)
Friends
class InterfaceProtocolData
Detailed Description
Interface entry for the interface table in IInterfaceTable.
See also:
IInterfaceTable
Constructor & Destructor Documentation
InterfaceEntry::InterfaceEntry (const InterfaceEntry & obj) [private]
InterfaceEntry::InterfaceEntry (cModule * interfaceModule)
{
    ownerp = NULL;
    interfaceModule = ifmod;
    nwLayerGateIndex = -1;
    nodeOutputGateId = -1;
    nodeInputGateId = -1;
    mtu = 0;
    down = false;
    broadcast = false;
    multicast = false;
    pointToPoint = false;
    loopback = false;
    datarate = 0;
    ipv4data = NULL;
    ipv6data = NULL;
    protocol3data = NULL;
    protocol4data = NULL;
    estimateCostProcessArray.clear();
}
virtual InterfaceEntry::~InterfaceEntry () [inline, virtual]
{}
Member Function Documentation
void InterfaceEntry::changed (int category) [protected, virtual]
Referenced by InterfaceProtocolData::changed().
{
    if (ownerp)
        ownerp->interfaceChanged(this, category);
}
virtual void InterfaceEntry::configChanged () [inline, protected, virtual]
Referenced by setIPv4Data(), and setIPv6Data().
{changed(NF_INTERFACE_CONFIG_CHANGED);}
std::string InterfaceEntry::detailedInfo () const [virtual]
{
    std::stringstream out;
    out << "name:" << (getName()[0] ? getName() : "*");
    if (getNetworkLayerGateIndex()==-1)
        out << "  on:-";
    else
        out << "  on:nwLayer.ifOut[" << getNetworkLayerGateIndex() << "]";
    out << "MTU: " << getMTU() << " \t";
    if (isDown()) out << "DOWN ";
    if (isBroadcast()) out << "BROADCAST ";
    if (isMulticast()) out << "MULTICAST ";
    if (isPointToPoint()) out << "POINTTOPOINT ";
    if (isLoopback()) out << "LOOPBACK ";
    out << "\n";
    out << "  macAddr:";
    if (getMacAddress().isUnspecified())
        out << "n/a";
    else
        out << getMacAddress();
    out << "\n";
    if (ipv4data)
        out << " " << ((cObject*)ipv4data)->info() << "\n"; // Khmm...
    if (ipv6data)
        out << " " << ((cObject*)ipv6data)->info() << "\n"; // Khmm...
    if (protocol3data)
        out << " " << protocol3data->info() << "\n";
    if (protocol4data)
        out << " " << protocol4data->info() << "\n";
    return out.str();
}
double InterfaceEntry::getDatarate () const [inline]
Referenced by RoutingTable::configureInterfaceForIPv4(), and DiffservUtil::getInterfaceDatarate().
{return datarate;}
MacEstimateCostProcess * InterfaceEntry::getEstimateCostProcess (int position) [virtual]
{
    ASSERT(position >= 0);
    if ((size_t)position < estimateCostProcessArray.size())
    {
        return estimateCostProcessArray[position];
    }
    return NULL;
}
std::string InterfaceEntry::getFullPath () const [virtual]
Referenced by IPv4NetworkConfigurator::addStaticRoutes(), IPv4NetworkConfigurator::assignAddresses(), IPv4NetworkConfigurator::collectCompatibleInterfaces(), and IPv4NetworkConfigurator::extractWirelessTopology().
{
    return ownerp == NULL ? getFullName() : ownerp->getHostModule()->getFullPath() + "." + getFullName();
}
int InterfaceEntry::getInterfaceId () const [inline]
Referenced by FlatNetworkConfigurator6::addOwnAdvPrefixRoutes(), FlatNetworkConfigurator6::addStaticRoutes(), OLSR::check_packet(), RoutingTable6::configureInterfaceForIPv6(), xMIPv6::createAndSendBAMessage(), xMIPv6::createAndSendBRRMessage(), xMIPv6::createAndSendBUMessage(), IPv6NeighbourDiscovery::createAndSendNSPacket(), IPv6NeighbourDiscovery::createAndSendRAPacket(), IPv6NeighbourDiscovery::createAndSendRSPacket(), xMIPv6::createBCEntryExpiryTimer(), xMIPv6::createBRRTimer(), xMIPv6::createBULEntryExpiryTimer(), xMIPv6::createBUTimer(), IPv6NeighbourDiscovery::createRATimer(), xMIPv6::createTestInitTimer(), xMIPv6::createTokenEntryExpiryTimer(), IPv6::decapsulate(), IPv4::decapsulate(), BGPRouting::decisionProcess(), InterfaceTable::deleteInterface(), IPv6NeighbourDiscovery::fetchAdvIfEntry(), xMIPv6::fetchBUTransmitIfEntry(), IPv6NeighbourDiscovery::fetchRDEntry(), IGMPv2::getHostInterfaceData(), DYMOUM::getNextHop(), OLSR_ETX::getNextHop(), OLSR::getNextHop(), getNextHop(), DYMOUM::getNextHopGroup(), OLSR::getNextHopGroup(), DYMO::getNextHopInterface(), IGMPv2::getRouterInterfaceData(), IPv4::handleARP(), xMIPv6::handleBCExpiry(), xMIPv6::handleBULExpiry(), DSDV_2::handleMessage(), xMIPv6::handleTokenExpiry(), RoutingTable6::initialize(), LDP::initialize(), DSRUU::initialize(), IPv6NeighbourDiscovery::initiateDAD(), IPv6NeighbourDiscovery::initiateRouterDiscovery(), UDPSocket::joinLocalMulticastGroups(), OSPFRouting::loadExternalRoute(), OSPFRouting::loadHostRoute(), OSPFRouting::loadInterfaceParameters(), xMIPv6::processBAMessage(), IPv6NeighbourDiscovery::processNAPacket(), IPv6NeighbourDiscovery::processNSWithSpecifiedSrcAddr(), IPv6NeighbourDiscovery::processRAForRouterUpdates(), IPv6NeighbourDiscovery::processRAPrefixInfo(), IGMPv2::receiveChangeNotification(), recvAODVUUPacket(), DYMOUM::recvDYMOUMPacket(), OSPFRouting::resolveInterfaceName(), xMIPv6::returningHome(), IPv4::sendDatagramToOutput(), xMIPv6::sendPeriodicBRR(), IPv6NeighbourDiscovery::sendSolicitedNA(), xMIPv6::sendTestInit(), ManetRoutingBase::sendToIp(), IGMPv2::sendToIP(), DHCPServer::sendToUDP(), DHCPClient::sendToUDP(), IPv6NeighbourDiscovery::sendUnsolicitedNA(), and UDPBasicApp::setSocketOptions().
{return interfaceId;}
cModule* InterfaceEntry::getInterfaceModule () const [inline]
Referenced by InterfaceTable::discoverConnectingGates(), and IPv4NetworkConfigurator::getWirelessId().
{return interfaceModule;}
IInterfaceTable* InterfaceEntry::getInterfaceTable () const [inline]
Returns the IInterfaceTable this interface is in, or NULL.
Referenced by IPv4NetworkConfigurator::addMulticastGroups(), IPv4NetworkConfigurator::dumpAddresses(), IPv4NetworkConfigurator::findInterfaceOnLinkByNode(), IPv4NetworkConfigurator::findInterfaceOnLinkByNodeAddress(), IPv4NetworkConfigurator::getWirelessId(), IPv4NetworkConfigurator::linkContainsMatchingHostExcept(), IPv4NetworkConfigurator::InterfaceMatcher::matches(), and IPv4NetworkConfigurator::readAddressConfiguration().
{return ownerp;}
const InterfaceToken& InterfaceEntry::getInterfaceToken () const [inline]
Referenced by IPv6NeighbourDiscovery::assignLinkLocalAddress(), RoutingTable6::assignRequiredNodeAddresses(), and FlatNetworkConfigurator6::configureAdvPrefixes().
{return token;}
const MACAddress& InterfaceEntry::getMacAddress () const [inline]
Referenced by IPv6NeighbourDiscovery::createAndSendNSPacket(), IPv6NeighbourDiscovery::createAndSendRAPacket(), IPv6NeighbourDiscovery::createAndSendRSPacket(), detailedInfo(), OLSR::getIfaceAddressFromIndex(), info(), DHCPClient::initialize(), ARP::initialize(), Ieee80211Etx::initialize(), Batman::initialize(), DYMOUM::initialize(), DSRUU::initialize(), Ieee80211Mac::isInterfaceRegistered(), ManetRoutingBase::isLocalAddress(), recvAODVUUPacket(), ManetRoutingBase::registerRoutingModule(), ARP::sendARPRequest(), IPv6NeighbourDiscovery::sendSolicitedNA(), and IPv6NeighbourDiscovery::sendUnsolicitedNA().
{return macAddr;}
int InterfaceEntry::getMTU () const [inline]
Referenced by detailedInfo(), IPv6::fragmentAndSend(), IPv4::fragmentAndSend(), info(), SCTPAssociation::pmStartPathManagement(), RTP::resolveMTU(), SCTPPathVariables::SCTPPathVariables(), and OSPF::Interface::setIfIndex().
{return mtu;}
int InterfaceEntry::getNetworkLayerGateIndex () const [inline]
Referenced by FlatNetworkConfigurator6::configureAdvPrefixes(), detailedInfo(), info(), ARP::processOutboundPacket(), LDP::rebuildFecList(), IPv6::sendDatagramToOutput(), and ARP::sendPacketToNIC().
{return nwLayerGateIndex;}
int InterfaceEntry::getNodeInputGateId () const [inline]
Referenced by InterfaceTable::getInterfaceByInterfaceModule().
{return nodeInputGateId;}
int InterfaceEntry::getNodeOutputGateId () const [inline]
Referenced by IPvXAddressResolver::addressOf(), IPv4NetworkConfigurator::extractWiredTopology(), InterfaceTable::getInterfaceByInterfaceModule(), OSPFRouting::getInterfaceByXMLAttributesOf(), TED::initialize(), and InterfaceTable::updateLinkDisplayString().
{return nodeOutputGateId;}
InterfaceProtocolData* InterfaceEntry::getProtocol3Data () const [inline]
{return protocol3data;}
InterfaceProtocolData* InterfaceEntry::getProtocol4Data () const [inline]
{return protocol4data;}
std::string InterfaceEntry::info () const [virtual]
Referenced by IPv4NetworkConfigurator::dumpAddresses(), and operator<<().
{
    std::stringstream out;
    out << (getName()[0] ? getName() : "*");
    if (getNetworkLayerGateIndex()==-1)
        out << "  on:-";
    else
        out << "  on:nwLayer.ifOut[" << getNetworkLayerGateIndex() << "]";
    out << "  MTU:" << getMTU();
    if (isDown()) out << " DOWN";
    if (isBroadcast()) out << " BROADCAST";
    if (isMulticast()) out << " MULTICAST";
    if (isPointToPoint()) out << " POINTTOPOINT";
    if (isLoopback()) out << " LOOPBACK";
    out << "  macAddr:";
    if (getMacAddress().isUnspecified())
        out << "n/a";
    else
        out << getMacAddress();
    if (ipv4data)
        out << " " << ((cObject*)ipv4data)->info(); // Khmm...
    if (ipv6data)
        out << " " << ((cObject*)ipv6data)->info(); // Khmm...
    if (protocol3data)
        out << " " << protocol3data->info();
    if (protocol4data)
        out << " " << protocol4data->info();
    return out.str();
}
IPv4InterfaceData* InterfaceEntry::ipv4Data () const [inline]
Referenced by Batman::add_del_interface_rules(), UDP::addMulticastAddressToInterface(), IPv4NetworkConfigurator::addMulticastGroups(), IPv4NetworkConfigurator::addStaticRoutes(), FlatNetworkConfigurator::assignAddresses(), IPv4NetworkConfigurator::assignAddresses(), DHCPClient::changeFSMState(), RoutingTable::configureRouterId(), IPv4NetworkConfigurator::createInterfaceInfo(), BGPRouting::createSession(), IPv4NetworkConfigurator::dumpConfig(), RSVP::evalNextHopInterface(), RoutingTable::findInterfaceByLocalBroadcastAddress(), IPv4NetworkConfigurator::findInterfaceOnLinkByNodeAddress(), BGPRouting::findMyAS(), IPv4::forwardMulticastPacket(), IPv4::fragmentAndSend(), RoutingTable::gatherAddresses(), PingTestApp::getAllAddresses(), OLSR::getIfaceAddressFromIndex(), RoutingTable::getInterfaceByAddress(), IPvXAddressResolver::getInterfaceIPv4Address(), IPvXAddressResolver::getIPv4AddressFrom(), DSDV_2::handleMessage(), Batman::handleMessage(), DSRUU::handleMessage(), IPv4::handlePacketFromNetwork(), IPv4Route::info(), TED::initialize(), DSDV_2::initialize(), LinkStateRouting::initialize(), ARP::initialize(), Batman::initialize(), DYMOUM::initialize(), DSRUU::initialize(), BGPRouting::isInInterfaceTable(), RoutingTable::isLocalAddress(), RoutingTable::isLocalBroadcastAddress(), RoutingTable::isLocalMulticastAddress(), UDPSocket::joinLocalMulticastGroups(), OSPFRouting::joinMulticastGroups(), UDPSocket::leaveLocalMulticastGroups(), locality(), BGPRouting::openTCPConnectionToPeer(), RoutingTableParser::parseInterfaces(), RoutingTableParser::parseMulticastGroups(), RoutingTable::printRoutingTable(), SCTPAssociation::processInitArrived(), IGMPv2::processLeaveTimer(), ARP::processOutboundPacket(), DHCPServer::processPacket(), DYMOUM::processPacket(), processPacket(), IGMPv2::processV2Report(), IPv4NetworkConfigurator::readAddressConfiguration(), LDP::rebuildFecList(), RoutingTableRecorder::recordInterfaceChange(), recvAODVUUPacket(), ManetRoutingBase::registerRoutingModule(), IPv4NetworkConfigurator::resolveInterfaceAndGateway(), Batman::send_udp_packet(), DHCPServer::sendACK(), ARP::sendARPRequest(), ManetRoutingBase::sendICMP(), SCTPAssociation::sendInit(), DHCPServer::sendOffer(), ManetRoutingBase::sendToIp(), ARP::setChangeAddress(), OSPF::Interface::setIfIndex(), RSVP::setupHello(), HostAutoConfigurator::setupNetworkLayer(), InterfaceTable::updateLinkDisplayString(), RoutingTable::updateNetmaskRoutes(), and BGPRouting::updateSendProcess().
{return ipv4data;}
IPv6InterfaceData* InterfaceEntry::ipv6Data () const [inline]
Referenced by UDP::addMulticastAddressToInterface(), FlatNetworkConfigurator6::addOwnAdvPrefixRoutes(), FlatNetworkConfigurator6::addStaticRoutes(), IPv6NeighbourDiscovery::assignLinkLocalAddress(), RoutingTable6::assignRequiredNodeAddresses(), xMIPv6::cancelEntries(), FlatNetworkConfigurator6::configureAdvPrefixes(), RoutingTable6::configureInterfaceFromXML(), xMIPv6::createAndSendBRRMessage(), xMIPv6::createAndSendBUMessage(), IPv6NeighbourDiscovery::createAndSendRAPacket(), IPv6NeighbourDiscovery::createAndSendRSPacket(), xMIPv6::createBUTimer(), xMIPv6::createDeregisterBUTimer(), IPv6NeighbourDiscovery::createRATimer(), xMIPv6::createTestInitTimer(), IPv6Tunneling::decapsulateDatagram(), IPv6::fragmentAndSend(), PingTestApp::getAllAddresses(), RoutingTable6::getInterfaceByAddress(), IPvXAddressResolver::getInterfaceIPv6Address(), IPvXAddressResolver::getIPv6AddressFrom(), xMIPv6::handleBULExpiry(), xMIPv6::handleTokenExpiry(), RoutingTable6::initialize(), IPv6NeighbourDiscovery::initialize(), IPv6NeighbourDiscovery::initiateAddressResolution(), IPv6NeighbourDiscovery::initiateDAD(), xMIPv6::initiateMIPv6Protocol(), IPv6NeighbourDiscovery::initiateNeighbourUnreachabilityDetection(), IPv6NeighbourDiscovery::initiateRouterDiscovery(), BindingUpdateList::isCareOfTokenAvailable(), BindingUpdateList::isHomeTokenAvailable(), RoutingTable6::isLocalAddress(), IPv6NeighbourDiscovery::makeTentativeAddressPermanent(), IPv6NeighbourDiscovery::processARTimeout(), xMIPv6::processBAMessage(), xMIPv6::processCoTMessage(), IPv6NeighbourDiscovery::processDADTimeout(), xMIPv6::processHoTMessage(), SCTPAssociation::processInitArrived(), IPv6NeighbourDiscovery::processNAForIncompleteNCEState(), IPv6NeighbourDiscovery::processNAForOtherNCEStates(), IPv6NeighbourDiscovery::processNAPacket(), IPv6NeighbourDiscovery::processNSPacket(), IPv6NeighbourDiscovery::processRAForRouterUpdates(), IPv6NeighbourDiscovery::processRAPacket(), IPv6NeighbourDiscovery::processRAPrefixInfoForAddrAutoConf(), IPv6NeighbourDiscovery::processRDTimeout(), IPv6NeighbourDiscovery::processRSPacket(), BindingUpdateList::recentlySentCOTI(), BindingUpdateList::recentlySentHOTI(), xMIPv6::resetBUIfEntry(), xMIPv6::returningHome(), IPv6::routePacket(), SCTPAssociation::sendInit(), xMIPv6::sendPeriodicBU(), IPv6NeighbourDiscovery::sendPeriodicRA(), IPv6NeighbourDiscovery::sendSolicitedNA(), xMIPv6::sendTestInit(), IPv6NeighbourDiscovery::sendUnsolicitedNA(), xMIPv6::triggerRouteOptimization(), InterfaceTable::updateLinkDisplayString(), xMIPv6::validateBAck(), and xMIPv6::validateCoTMessage().
{return ipv6data;}
bool InterfaceEntry::isBroadcast () const [inline]
Referenced by detailedInfo(), info(), ARP::processOutboundPacket(), and IPv4::routeUnicastPacket().
{return broadcast;}
bool InterfaceEntry::isDown () const [inline]
Referenced by Batman::add_del_interface_rules(), Batman::check_active_inactive_interfaces(), Batman::check_active_interfaces(), Batman::check_inactive_interfaces(), detailedInfo(), and info().
{return down;}
bool InterfaceEntry::isLoopback () const [inline]
Referenced by Batman::add_del_interface_rules(), FlatNetworkConfigurator::addDefaultRoutes(), FlatNetworkConfigurator6::addOwnAdvPrefixRoutes(), FlatNetworkConfigurator6::addStaticRoutes(), IPv4NetworkConfigurator::addStaticRoutes(), FlatNetworkConfigurator::assignAddresses(), IPv6NeighbourDiscovery::assignLinkLocalAddress(), RoutingTable6::assignRequiredNodeAddresses(), FlatNetworkConfigurator6::configureAdvPrefixes(), RoutingTable6::configureInterfaceForIPv6(), RoutingTable::configureRouterId(), detailedInfo(), IPv4NetworkConfigurator::determineGatewayForLink(), NetworkInfo::dumpRoutingInfo(), IPv4NetworkConfigurator::extractWiredTopology(), IPv4NetworkConfigurator::extractWirelessTopology(), IPv4::fragmentAndSend(), PingTestApp::getAllAddresses(), IPvXAddressResolver::getIPv4AddressFrom(), IPvXAddressResolver::getIPv6AddressFrom(), IPv4::handleMessageFromHL(), IPv4::handlePacketFromNetwork(), info(), TED::initialize(), ARP::initialize(), RoutingTable6::initialize(), IPv6NeighbourDiscovery::initialize(), xMIPv6::initiateMIPv6Protocol(), IPv6NeighbourDiscovery::makeTentativeAddressPermanent(), IPv6::routeMulticastPacket(), IPv4::sendDatagramToOutput(), and HostAutoConfigurator::setupNetworkLayer().
{return loopback;}
bool InterfaceEntry::isMulticast () const [inline]
Referenced by IPv4NetworkConfigurator::addManualMulticastRoutes(), RoutingTable::configureInterfaceForIPv4(), detailedInfo(), info(), IGMPv2::initialize(), LDP::initialize(), RoutingTable::internalAddMulticastRoute(), IGMPv2::multicastGroupJoined(), IGMPv2::multicastGroupLeft(), IGMPv2::processLeave(), IGMPv2::processQuery(), IGMPv2::processV2Report(), IGMPv2::receiveChangeNotification(), and IGMPv2::sendToIP().
{return multicast;}
bool InterfaceEntry::isPointToPoint () const [inline]
Referenced by detailedInfo(), info(), IPv6NeighbourDiscovery::processIPv6Datagram(), and IPv6::routePacket().
{return pointToPoint;}
InterfaceEntry& InterfaceEntry::operator= (const InterfaceEntry & obj) [private]
virtual void InterfaceEntry::setBroadcast (bool b) [inline, virtual]
Referenced by RoutingTableParser::parseInterfaces(), EtherMACBase::registerInterface(), Ieee80211Mac::registerInterface(), and HostAutoConfigurator::setupNetworkLayer().
{broadcast = b; configChanged();}
virtual void InterfaceEntry::setDatarate (double d) [inline, virtual]
Referenced by EtherMACBase::readChannelParameters(), PPP::refreshOutGateConnection(), and PPP::registerInterface().
{datarate = d; configChanged();}
virtual void InterfaceEntry::setDown (bool b) [inline, virtual]
Referenced by PPP::initialize(), EtherMACBase::readChannelParameters(), and PPP::refreshOutGateConnection().
{down = b; stateChanged();}
bool InterfaceEntry::setEstimateCostProcess (int position, MacEstimateCostProcess * p) [virtual]
Referenced by Ieee80211Etx::initialize().
{
    ASSERT(position >= 0);
    if (estimateCostProcessArray.size() <= (size_t)position)
    {
        estimateCostProcessArray.resize(position+1, NULL);
    }
    if (estimateCostProcessArray[position]!=NULL)
        return false;
    estimateCostProcessArray[position] = p;
    return true;
}
virtual void InterfaceEntry::setInterfaceId (int id) [inline, virtual]
Referenced by InterfaceTable::addInterface().
{interfaceId = id;}
virtual void InterfaceEntry::setInterfaceTable (IInterfaceTable * t) [inline, virtual]
Referenced by InterfaceTable::addInterface().
{ownerp = t;}
virtual void InterfaceEntry::setInterfaceToken (const InterfaceToken & t) [inline, virtual]
Referenced by PPP::registerInterface(), EtherMACBase::registerInterface(), and Ieee80211Mac::registerInterface().
{token = t; configChanged();}
void InterfaceEntry::setIPv4Data (IPv4InterfaceData * p) [virtual]
Referenced by RoutingTable::configureInterfaceForIPv4(), and RoutingTable::configureLoopbackForIPv4().
{
#ifdef WITH_IPv4
    ipv4data = p;
    p->ownerp = this;
    configChanged();
#else
    throw cRuntimeError(this, "setIPv4Data(): INET was compiled without IPv4 support");
#endif
}
void InterfaceEntry::setIPv6Data (IPv6InterfaceData * p) [virtual]
Referenced by RoutingTable6::configureInterfaceForIPv6().
{
#ifdef WITH_IPv6
    ipv6data = p;
    p->ownerp = this;
    configChanged();
#else
    throw cRuntimeError(this, "setIPv4Data(): INET was compiled without IPv6 support");
#endif
}
virtual void InterfaceEntry::setLoopback (bool b) [inline, virtual]
Referenced by InterfaceTable::initialize().
{loopback = b; configChanged();}
virtual void InterfaceEntry::setMACAddress (const MACAddress & addr) [inline, virtual]
Referenced by EtherMACBase::registerInterface(), and Ieee80211Mac::registerInterface().
{macAddr = addr; configChanged();}
virtual void InterfaceEntry::setMtu (int m) [inline, virtual]
Referenced by InterfaceTable::initialize(), RoutingTableParser::parseInterfaces(), IPv4NetworkConfigurator::readAddressConfiguration(), ExtInterface::registerInterface(), PPP::registerInterface(), EtherMACBase::registerInterface(), and Ieee80211Mac::registerInterface().
{mtu = m; configChanged();}
virtual void InterfaceEntry::setMulticast (bool b) [inline, virtual]
Referenced by RoutingTableParser::parseInterfaces(), ExtInterface::registerInterface(), PPP::registerInterface(), EtherMACBase::registerInterface(), and Ieee80211Mac::registerInterface().
{multicast = b; configChanged();}
virtual void InterfaceEntry::setName (const char * s) [inline, virtual]
Referenced by InterfaceTable::initialize(), ExtInterface::registerInterface(), PPP::registerInterface(), EtherMACBase::registerInterface(), and Ieee80211Mac::registerInterface().
{cNamedObject::setName(s); configChanged();}
virtual void InterfaceEntry::setNetworkLayerGateIndex (int i) [inline, virtual]
Referenced by InterfaceTable::discoverConnectingGates().
{nwLayerGateIndex = i; configChanged();}
virtual void InterfaceEntry::setNodeInputGateId (int i) [inline, virtual]
Referenced by InterfaceTable::discoverConnectingGates().
{nodeInputGateId = i; configChanged();}
virtual void InterfaceEntry::setNodeOutputGateId (int i) [inline, virtual]
Referenced by InterfaceTable::discoverConnectingGates().
{nodeOutputGateId = i; configChanged();}
virtual void InterfaceEntry::setPointToPoint (bool b) [inline, virtual]
Referenced by RoutingTableParser::parseInterfaces(), ExtInterface::registerInterface(), PPP::registerInterface(), and Ieee80211Mac::registerInterface().
{pointToPoint = b; configChanged();}
virtual void InterfaceEntry::setProtocol3Data (InterfaceProtocolData * p) [inline, virtual]
{protocol3data = p; configChanged();}
virtual void InterfaceEntry::setProtocol4Data (InterfaceProtocolData * p) [inline, virtual]
{protocol4data = p; configChanged();}
virtual void InterfaceEntry::stateChanged () [inline, protected, virtual]
{changed(NF_INTERFACE_STATE_CHANGED);}
Friends And Related Function Documentation
friend class InterfaceProtocolData [friend]
Member Data Documentation
bool InterfaceEntry::broadcast [protected]
interface supports broadcast
Referenced by InterfaceEntry().
double InterfaceEntry::datarate [protected]
data rate in bit/s
Referenced by InterfaceEntry().
bool InterfaceEntry::down [protected]
current state (up or down)
Referenced by InterfaceEntry().
std::vector<MacEstimateCostProcess *> InterfaceEntry::estimateCostProcessArray [protected]
Referenced by getEstimateCostProcess(), InterfaceEntry(), and setEstimateCostProcess().
int InterfaceEntry::interfaceId [protected]
identifies the interface in the IInterfaceTable
cModule* InterfaceEntry::interfaceModule [protected]
interface module, or NULL
Referenced by InterfaceEntry().
IPv4InterfaceData* InterfaceEntry::ipv4data [protected]
IPv4-specific interface info (IPv4 address, etc)
Referenced by detailedInfo(), info(), InterfaceEntry(), and setIPv4Data().
IPv6InterfaceData* InterfaceEntry::ipv6data [protected]
IPv6-specific interface info (IPv6 addresses, etc)
Referenced by detailedInfo(), info(), InterfaceEntry(), and setIPv6Data().
bool InterfaceEntry::loopback [protected]
interface is loopback interface
Referenced by InterfaceEntry().
MACAddress InterfaceEntry::macAddr [protected]
link-layer address (for now, only IEEE 802 MAC addresses are supported)
Referenced by IPv6::fragmentAndSend().
int InterfaceEntry::mtu [protected]
Maximum Transmission Unit (e.g. 1500 on Ethernet)
Referenced by InterfaceEntry().
bool InterfaceEntry::multicast [protected]
interface supports multicast
Referenced by InterfaceEntry().
int InterfaceEntry::nodeInputGateId [protected]
id of the input gate of this host/router (or -1 if this is a virtual interface)
Referenced by InterfaceEntry().
int InterfaceEntry::nodeOutputGateId [protected]
id of the output gate of this host/router (or -1 if this is a virtual interface)
Referenced by InterfaceEntry().
int InterfaceEntry::nwLayerGateIndex [protected]
index of ifIn[],ifOut[] gates to that interface (or -1 if virtual interface)
Referenced by InterfaceEntry().
IInterfaceTable* InterfaceEntry::ownerp [protected]
IInterfaceTable that contains this interface, or NULL.
Referenced by changed(), getFullPath(), InterfaceProtocolData::getInterfaceEntry(), InterfaceEntry(), and InterfaceProtocolData::InterfaceProtocolData().
bool InterfaceEntry::pointToPoint [protected]
interface is point-to-point link
Referenced by InterfaceEntry().
InterfaceProtocolData* InterfaceEntry::protocol3data [protected]
extension point: data for a 3rd network-layer protocol
Referenced by detailedInfo(), info(), and InterfaceEntry().
InterfaceProtocolData* InterfaceEntry::protocol4data [protected]
extension point: data for a 4th network-layer protocol
Referenced by detailedInfo(), info(), and InterfaceEntry().
InterfaceToken InterfaceEntry::token [protected]
for IPv6 stateless autoconfig (RFC 1971), interface identifier (RFC 2462)
The documentation for this class was generated from the following files:
InterfaceEntry.h
InterfaceEntry.cc