INET Framework for OMNeT++/OMNEST: RTP Class Reference
RTP Class Reference
An RTP is the center of the RTP layer of an endsystem.
#include <RTP.h>
Protected Member Functions
virtual void initialize ()
Initializes variables.
virtual void handleMessage (cMessage *msg)
Handles incoming messages.
virtual void handleMessageFromApp (cMessage *msg)
Handles messages received from the applicaiton.
virtual void handleMessageFromProfile (cMessage *msg)
Handles messages received from the profile module.
virtual void handleMessageFromRTCP (cMessage *msg)
Handles messages received from the rtcp module.
virtual void handleMessagefromUDP (cMessage *msg)
Handles messages received from the UDP layer.
virtual void enterSession (RTPCIEnterSession *rifp)
Creates the profile module and initializes it.
virtual void leaveSession (RTPCILeaveSession *rifp)
Destroys the profile module and orders the rtcp module to send an rtcp bye packet.
virtual void createSenderModule (RTPCICreateSenderModule *rifp)
virtual void deleteSenderModule (RTPCIDeleteSenderModule *rifp)
virtual void senderModuleControl (RTPCISenderControl *rifp)
virtual void profileInitialized (RTPInnerPacket *rinp)
Called when the profile module is initialized.
virtual void senderModuleCreated (RTPInnerPacket *rinp)
virtual void senderModuleDeleted (RTPInnerPacket *rinp)
virtual void senderModuleInitialized (RTPInnerPacket *rinp)
virtual void senderModuleStatus (RTPInnerPacket *rinp)
virtual void dataOut (RTPInnerPacket *rinp)
Sends a RTP data packet to the UDP layer and a copy of it to the rtcp module.
virtual void rtcpInitialized (RTPInnerPacket *rinp)
Informs the application that the session is entered.
virtual void sessionLeft (RTPInnerPacket *rinp)
Informs the application that this end system has left the RTP session.
virtual void createProfile ()
Creates the profile module.
virtual void createSocket ()
Requests a server socket from the UDP layer.
virtual void socketRet ()
Called when the socket layer returns a socket.
virtual void connectRet ()
Called when the socket layer has connected a socket.
virtual void readRet (cMessage *sifp)
Called when data from the socket layer has been received.
virtual void initializeProfile ()
Initializes the profile module.
virtual void initializeRTCP ()
Initializes the rtcp module-.
virtual int resolveMTU ()
Determines the maximum transmission unit that can be uses for RTP.
Protected Attributes
const char * _commonName
The CNAME of this end system.
const char * _profileName
The name of the profile used in this session.
int _bandwidth
The available bandwidth for this session.
IPv4Address _destinationAddress
The destination address.
int _port
The RTP port.
int _mtu
The maximum size of a packet.
int _rtcpPercentage
The percentage of the bandwidth used for rtcp.
UDPSocket _udpSocket
The UDP socket.
bool _leaveSession
True when this end system is about to leave the session.
int appInGate
int profileInGate
int rtcpInGate
int udpInGate
Static Protected Attributes
static simsignal_t rcvdPkSignal = SIMSIGNAL_NULL
Detailed Description
An RTP is the center of the RTP layer of an endsystem.
It creates the profile module, sends and receives RTP data packets and forwards messages. It also communicates with the application.
Member Function Documentation
void RTP::connectRet () [protected, virtual]
Called when the socket layer has connected a socket.
Referenced by createSocket().
{
    initializeRTCP();
}
void RTP::createProfile () [protected, virtual]
Creates the profile module.
Referenced by enterSession().
{
    cModuleType *moduleType = cModuleType::find(_profileName);
    if (moduleType == NULL)
        error("Profile type `%s' not found", _profileName);
    RTPProfile *profile = check_and_cast<RTPProfile *>(moduleType->create("Profile", this));
    profile->finalizeParameters();
    profile->setGateSize("payloadReceiverOut", 30);
    profile->setGateSize("payloadReceiverIn", 30);
    this->gate("profileOut")->connectTo(profile->gate("rtpIn"));
    profile->gate("rtpOut")->connectTo(this->gate("profileIn"));
    profile->callInitialize();
    profile->scheduleStart(simTime());
}
void RTP::createSenderModule (RTPCICreateSenderModule * rifp) [protected, virtual]
Referenced by handleMessageFromApp().
{
    RTPInnerPacket *rinp = new RTPInnerPacket("createSenderModule()");
    ev << rifp->getSsrc()<<endl;
    rinp->setCreateSenderModulePkt(rifp->getSsrc(), rifp->getPayloadType(), rifp->getFileName());
    send(rinp, "profileOut");
    delete rifp;
}
void RTP::createSocket () [protected, virtual]
Requests a server socket from the UDP layer.
Referenced by profileInitialized().
{
    _udpSocket.bind(_port);
    _udpSocket.joinLocalMulticastGroups(); //TODO make it parameter-dependent
    connectRet();
}
void RTP::dataOut (RTPInnerPacket * rinp) [protected, virtual]
Sends a RTP data packet to the UDP layer and a copy of it to the rtcp module.
Referenced by handleMessageFromProfile().
{
    RTPPacket *msg = check_and_cast<RTPPacket *>(rinp->getEncapsulatedPacket()->dup());
    _udpSocket.sendTo(msg, _destinationAddress, _port);
    // RTCP module must be informed about sent rtp data packet
    send(rinp, "rtcpOut");
}
void RTP::deleteSenderModule (RTPCIDeleteSenderModule * rifp) [protected, virtual]
Referenced by handleMessageFromApp().
{
    RTPInnerPacket *rinp = new RTPInnerPacket("deleteSenderModule()");
    rinp->setDeleteSenderModulePkt(rifp->getSsrc());
    send(rinp, "profileOut");
    delete rifp;
}
void RTP::enterSession (RTPCIEnterSession * rifp) [protected, virtual]
Creates the profile module and initializes it.
Referenced by handleMessageFromApp().
{
    _profileName = rifp->getProfileName();
    _commonName = rifp->getCommonName();
    _bandwidth = rifp->getBandwidth();
    _destinationAddress = rifp->getDestinationAddress();
    _port = rifp->getPort();
    if (_port & 1)
        _port--;
    _mtu = resolveMTU();
    createProfile();
    initializeProfile();
    delete rifp;
}
void RTP::handleMessage (cMessage * msg) [protected, virtual]
Handles incoming messages.
{
    if (msg->getArrivalGateId() == appInGate)
    {
        handleMessageFromApp(msg);
    }
    else if (msg->getArrivalGateId() == profileInGate)
    {
        handleMessageFromProfile(msg);
    }
    else if (msg->getArrivalGateId() == rtcpInGate)
    {
        handleMessageFromRTCP(msg);
    }
    else if (msg->getArrivalGateId() == udpInGate)
    {
        handleMessagefromUDP(msg);
    }
    else
    {
        error("Message from unknown gate");
    }
}
void RTP::handleMessageFromApp (cMessage * msg) [protected, virtual]
Handles messages received from the applicaiton.
Referenced by handleMessage().
{
    RTPControlInfo * ci = check_and_cast<RTPControlInfo *>(msg->removeControlInfo());
    delete msg;
    switch (ci->getType())
    {
    case RTP_IFP_ENTER_SESSION:
        enterSession(check_and_cast<RTPCIEnterSession *>(ci));
        break;
    case RTP_IFP_CREATE_SENDER_MODULE:
        createSenderModule(check_and_cast<RTPCICreateSenderModule *>(ci));
        break;
    case RTP_IFP_DELETE_SENDER_MODULE:
        deleteSenderModule(check_and_cast<RTPCIDeleteSenderModule *>(ci));
        break;
    case RTP_IFP_SENDER_CONTROL:
        senderModuleControl(check_and_cast<RTPCISenderControl *>(ci));
        break;
    case RTP_IFP_LEAVE_SESSION:
        leaveSession(check_and_cast<RTPCILeaveSession *>(ci));
        break;
    default:
        throw cRuntimeError("Unknown RTPControlInfo type from application");
    }
}
void RTP::handleMessageFromProfile (cMessage * msg) [protected, virtual]
Handles messages received from the profile module.
Referenced by handleMessage().
{
    RTPInnerPacket *rinp = check_and_cast<RTPInnerPacket *>(msg);
    switch (rinp->getType())
    {
    case RTP_INP_PROFILE_INITIALIZED:
        profileInitialized(rinp);
        break;
    case RTP_INP_SENDER_MODULE_CREATED:
        senderModuleCreated(rinp);
        break;
    case RTP_INP_SENDER_MODULE_DELETED:
        senderModuleDeleted(rinp);
        break;
    case RTP_INP_SENDER_MODULE_INITIALIZED:
        senderModuleInitialized(rinp);
        break;
    case RTP_INP_SENDER_MODULE_STATUS:
        senderModuleStatus(rinp);
        break;
    case RTP_INP_DATA_OUT:
        dataOut(rinp);
        break;
    default:
        throw cRuntimeError("Unknown RTPInnerPacket type %d from profile", rinp->getType());
    }
    ev << "handleMessageFromProfile(cMessage *msg) Exit" << endl;
}
void RTP::handleMessageFromRTCP (cMessage * msg) [protected, virtual]
Handles messages received from the rtcp module.
Referenced by handleMessage().
{
    RTPInnerPacket *rinp = check_and_cast<RTPInnerPacket *>(msg);
    switch (rinp->getType())
    {
    case RTP_INP_RTCP_INITIALIZED:
        rtcpInitialized(rinp);
        break;
    case RTP_INP_SESSION_LEFT:
        sessionLeft(rinp);
        break;
    default:
        throw cRuntimeError("Unknown RTPInnerPacket type %d from rtcp", rinp->getType());
    }
}
void RTP::handleMessagefromUDP (cMessage * msg) [protected, virtual]
Handles messages received from the UDP layer.
Referenced by handleMessage().
{
    readRet(msg);
}
void RTP::initialize () [protected, virtual]
Initializes variables.
{
    _leaveSession = false;
    appInGate = findGate("appIn");
    profileInGate = findGate("profileIn");
    rtcpInGate = findGate("rtcpIn");
    udpInGate = findGate("udpIn");
    _udpSocket.setOutputGate(gate("udpOut"));
    rcvdPkSignal = registerSignal("rcvdPk");
}
void RTP::initializeProfile () [protected, virtual]
Initializes the profile module.
Referenced by enterSession().
{
    RTPInnerPacket *rinp = new RTPInnerPacket("initializeProfile()");
    rinp->setInitializeProfilePkt(_mtu);
    send(rinp, "profileOut");
}
void RTP::initializeRTCP () [protected, virtual]
Initializes the rtcp module-.
Referenced by connectRet().
{
    RTPInnerPacket *rinp = new RTPInnerPacket("initializeRTCP()");
    int rtcpPort = _port + 1;
    rinp->setInitializeRTCPPkt(_commonName, _mtu, _bandwidth, _rtcpPercentage, _destinationAddress, rtcpPort);
    send(rinp, "rtcpOut");
}
void RTP::leaveSession (RTPCILeaveSession * rifp) [protected, virtual]
Destroys the profile module and orders the rtcp module to send an rtcp bye packet.
Referenced by handleMessageFromApp().
{
    if (!_leaveSession)
    {
        _leaveSession = true;
        cModule *profileModule = gate("profileOut")->getNextGate()->getOwnerModule();
        profileModule->deleteModule();
        RTPInnerPacket *rinp = new RTPInnerPacket("leaveSession()");
        rinp->setLeaveSessionPkt();
        send(rinp, "rtcpOut");
    }
    delete rifp;
}
void RTP::profileInitialized (RTPInnerPacket * rinp) [protected, virtual]
Called when the profile module is initialized.
Referenced by handleMessageFromProfile().
{
    _rtcpPercentage = rinp->getRtcpPercentage();
    if (_port == PORT_UNDEF)
    {
        _port = rinp->getPort();
        if (_port & 1)
            _port--;
    }
    delete rinp;
    createSocket();
}
void RTP::readRet (cMessage * sifp) [protected, virtual]
Called when data from the socket layer has been received.
Referenced by handleMessagefromUDP().
{
    if ( ! _leaveSession)
    {
         RTPPacket *msg = check_and_cast<RTPPacket *>(sifp);
         emit(rcvdPkSignal, msg);
         msg->dump();
         RTPInnerPacket *rinp1 = new RTPInnerPacket("dataIn1()");
         rinp1->setDataInPkt(new RTPPacket(*msg), IPv4Address(_destinationAddress), _port);
         RTPInnerPacket *rinp2 = new RTPInnerPacket(*rinp1);
         send(rinp2, "rtcpOut");
         send(rinp1, "profileOut");
    }
    delete sifp;
}
int RTP::resolveMTU () [protected, virtual]
Determines the maximum transmission unit that can be uses for RTP.
This implementation assumes that we use an ethernet with 1500 bytes mtu. The returned value is 1500 bytes minus header sizes for ip and udp.
Referenced by enterSession().
{
    // it returns MTU bytelength (ethernet) minus ip
    // and udp headers
    // TODO: How to do get the valid length of IP and ETHERNET header?
    RoutingTableAccess routingTableAccess;
    const InterfaceEntry* rtie = routingTableAccess.get()->getInterfaceForDestAddr(_destinationAddress);
    if (rtie == NULL)
        throw cRuntimeError("No interface for remote address %s found!", _destinationAddress.str().c_str());
    int pmtu = rtie->getMTU();
    return pmtu - 20 - 8;
}
void RTP::rtcpInitialized (RTPInnerPacket * rinp) [protected, virtual]
Informs the application that the session is entered.
Referenced by handleMessageFromRTCP().
{
    RTPCISessionEntered* ci = new RTPCISessionEntered();
    ci->setSsrc(rinp->getSsrc());
    cMessage *msg = new RTPControlMsg("sessionEntered()");
    msg->setControlInfo(ci);
    send(msg, "appOut");
    delete rinp;
}
void RTP::senderModuleControl (RTPCISenderControl * rifp) [protected, virtual]
Referenced by handleMessageFromApp().
{
    RTPInnerPacket *rinp = new RTPInnerPacket("senderModuleControl()");
    RTPSenderControlMessage * scm = new RTPSenderControlMessage();
    scm->setCommand(rifp->getCommand());
    scm->setCommandParameter1(rifp->getCommandParameter1());
    scm->setCommandParameter2(rifp->getCommandParameter2());
    rinp->setSenderModuleControlPkt(rinp->getSsrc(), scm);
    send(rinp, "profileOut");
    delete rifp;
}
void RTP::senderModuleCreated (RTPInnerPacket * rinp) [protected, virtual]
Referenced by handleMessageFromProfile().
{
    RTPCISenderModuleCreated* ci = new RTPCISenderModuleCreated();
    ci->setSsrc(rinp->getSsrc());
    cMessage *msg = new RTPControlMsg("senderModuleCreated()");
    msg->setControlInfo(ci);
    send(msg, "appOut");
    delete rinp;
}
void RTP::senderModuleDeleted (RTPInnerPacket * rinp) [protected, virtual]
Referenced by handleMessageFromProfile().
{
    RTPCISenderModuleDeleted* ci = new RTPCISenderModuleDeleted();
    ci->setSsrc(rinp->getSsrc());
    cMessage *msg = new RTPControlMsg("senderModuleDeleted()");
    msg->setControlInfo(ci);
    send(msg, "appOut");
    // perhaps we should send a message to rtcp module
    delete rinp;
}
void RTP::senderModuleInitialized (RTPInnerPacket * rinp) [protected, virtual]
Referenced by handleMessageFromProfile().
{
    send(rinp, "rtcpOut");
}
void RTP::senderModuleStatus (RTPInnerPacket * rinp) [protected, virtual]
Referenced by handleMessageFromProfile().
{
    RTPSenderStatusMessage *ssm = (RTPSenderStatusMessage *)(rinp->decapsulate());
    RTPCISenderStatus* ci = new RTPCISenderStatus();
    ci->setSsrc(rinp->getSsrc());
    ci->setStatus(ssm->getStatus());
    ci->setTimeStamp(ssm->getTimeStamp());
    cMessage *msg = new RTPControlMsg("senderModuleStatus()");
    msg->setControlInfo(ci);
    send(msg, "appOut");
    delete ssm;
    delete rinp;
}
void RTP::sessionLeft (RTPInnerPacket * rinp) [protected, virtual]
Informs the application that this end system has left the RTP session.
Referenced by handleMessageFromRTCP().
{
    RTPCISessionLeft* ci = new RTPCISessionLeft();
    cMessage *msg = new RTPControlMsg("sessionLeft()");
    msg->setControlInfo(ci);
    send(msg, "appOut");
    delete rinp;
}
void RTP::socketRet () [protected, virtual]
Called when the socket layer returns a socket.
{
}
Member Data Documentation
int RTP::_bandwidth [protected]
The available bandwidth for this session.
Referenced by enterSession(), and initializeRTCP().
const char* RTP::_commonName [protected]
The CNAME of this end system.
Referenced by enterSession(), and initializeRTCP().
IPv4Address RTP::_destinationAddress [protected]
The destination address.
Referenced by dataOut(), enterSession(), initializeRTCP(), readRet(), and resolveMTU().
bool RTP::_leaveSession [protected]
True when this end system is about to leave the session.
Referenced by initialize(), leaveSession(), and readRet().
int RTP::_mtu [protected]
The maximum size of a packet.
Referenced by enterSession(), initializeProfile(), and initializeRTCP().
int RTP::_port [protected]
The RTP port.
Referenced by createSocket(), dataOut(), enterSession(), initializeRTCP(), profileInitialized(), and readRet().
const char* RTP::_profileName [protected]
The name of the profile used in this session.
Referenced by createProfile(), and enterSession().
int RTP::_rtcpPercentage [protected]
The percentage of the bandwidth used for rtcp.
Referenced by initializeRTCP(), and profileInitialized().
UDPSocket RTP::_udpSocket [protected]
The UDP socket.
Referenced by createSocket(), dataOut(), and initialize().
int RTP::appInGate [protected]
Referenced by handleMessage(), and initialize().
int RTP::profileInGate [protected]
Referenced by handleMessage(), and initialize().
simsignal_t RTP::rcvdPkSignal = SIMSIGNAL_NULL [static, protected]
Referenced by initialize(), and readRet().
int RTP::rtcpInGate [protected]
Referenced by handleMessage(), and initialize().
int RTP::udpInGate [protected]
Referenced by handleMessage(), and initialize().
The documentation for this class was generated from the following files:
RTP.h
RTP.cc