INET Framework for OMNeT++/OMNEST: SDESItem Class Reference
SDESItem Class Reference
The class SDESItem is used for storing a source description item (type of description, description string) for an RTP end system.
#include <sdes.h>
Public Types
enum SDES_ITEM_TYPE {
SDES_UNDEF = 0, SDES_CNAME = 1, SDES_NAME = 2, SDES_EMAIL = 3,
SDES_PHONE = 4, SDES_LOC = 5, SDES_TOOL = 6, SDES_NOTE = 7,
SDES_PRIV = 8
}
This enumeration holds the types of source description items as defined in the RFC.
Public Member Functions
SDESItem ()
Default constructor.
SDESItem (SDES_ITEM_TYPE type, const char *content)
Constructor which sets the entry.
SDESItem (const SDESItem &sdesItem)
Copy constructor.
virtual ~SDESItem ()
Destructor.
SDESItem & operator= (const SDESItem &sdesItem)
Assignment operator.
virtual SDESItem * dup () const
Duplicates theis SDESItem by calling the copy constructor.
virtual std::string info () const
Writes a short info about this SDESItem into the given string.
virtual void dump (std::ostream &os) const
Writes an info about this SDESItem into the give output stream.
virtual SDES_ITEM_TYPE getType () const
Returns the type of this sdes item.
virtual const char * getContent () const
Returns the stored sdes string.
virtual int getLength () const
This method returns the size of this SDESItem in bytes as it would be in the real world.
Protected Attributes
SDES_ITEM_TYPE _type
The type of this SDESItem.
int _length
The length of this SDESItem.
const char * _content
The sdes string.
Private Member Functions
void copy (const SDESItem &other)
void clean ()
Detailed Description
The class SDESItem is used for storing a source description item (type of description, description string) for an RTP end system.
Member Enumeration Documentation
enum SDESItem::SDES_ITEM_TYPE
This enumeration holds the types of source description items as defined in the RFC.
In this implementation only SDES_UNDEF and SDES_CNAME are usable.
Enumerator:
SDES_UNDEF
SDES_CNAME
SDES_NAME
SDES_EMAIL
SDES_PHONE
SDES_LOC
SDES_TOOL
SDES_NOTE
SDES_PRIV
    {
        SDES_UNDEF = 0,
        SDES_CNAME = 1,
        SDES_NAME = 2,
        SDES_EMAIL = 3,
        SDES_PHONE = 4,
        SDES_LOC = 5,
        SDES_TOOL = 6,
        SDES_NOTE = 7,
        SDES_PRIV = 8
    };
Constructor & Destructor Documentation
SDESItem::SDESItem ()
Default constructor.
Referenced by dup().
                   : cObject()
{
    _type = SDES_UNDEF;
    _length = 2;
    _content = "";
}
SDESItem::SDESItem (SDES_ITEM_TYPE type, const char * content)
Constructor which sets the entry.
                                                           : cObject()
{
    if (NULL == content)
        throw cRuntimeError("The content parameter must be a valid pointer.");
    _type = type;
    _content = content;
    // an sdes item requires one byte for the type field,
    // one byte for the length field and bytes for
    // the content string
    _length = 2 + strlen(_content);
}
SDESItem::SDESItem (const SDESItem & sdesItem)
Copy constructor.
                                           : cObject(sdesItem)
{
    copy(sdesItem);
}
SDESItem::~SDESItem () [virtual]
Destructor.
{
    clean();
}
Member Function Documentation
void SDESItem::clean () [inline, private]
Referenced by operator=(), and ~SDESItem().
{}     //FIXME The `_content' sometimes allocated, sometimes not allocated pointer.
void SDESItem::copy (const SDESItem & other) [private]
Referenced by operator=(), and SDESItem().
{
    _type = sdesItem._type;
    _length = sdesItem._length;
    _content = opp_strdup(sdesItem._content);
}
void SDESItem::dump (std::ostream & os) const [virtual]
Writes an info about this SDESItem into the give output stream.
{
    os << "SDESItem:" << endl;
    os << "  type = " << _type << endl;
    os << "  content = " << _content << endl;
}
SDESItem * SDESItem::dup () const [virtual]
Duplicates theis SDESItem by calling the copy constructor.
{
    return new SDESItem(*this);
}
const char * SDESItem::getContent () const [virtual]
Returns the stored sdes string.
{
    return opp_strdup(_content);
}
int SDESItem::getLength () const [virtual]
This method returns the size of this SDESItem in bytes as it would be in the real world.
Referenced by SDESChunk::addSDESItem().
{
    // bytes needed for this sdes item are
    // one byte for type, one for length
    // and the string
    return _length + 2;
}
SDESItem::SDES_ITEM_TYPE SDESItem::getType () const [virtual]
Returns the type of this sdes item.
Referenced by SDESChunk::addSDESItem().
{
    return _type;
}
std::string SDESItem::info () const [virtual]
Writes a short info about this SDESItem into the given string.
{
    std::stringstream out;
    out << "SDESItem=" << _content;
    return out.str();
}
SDESItem & SDESItem::operator= (const SDESItem & sdesItem)
Assignment operator.
{
    if (this == &sdesItem) return *this;
    clean();
    cObject::operator=(sdesItem);
    copy(sdesItem);
    return *this;
}
Member Data Documentation
const char* SDESItem::_content [protected]
The sdes string.
Referenced by copy(), dump(), getContent(), info(), and SDESItem().
int SDESItem::_length [protected]
The length of this SDESItem.
Referenced by copy(), getLength(), and SDESItem().
SDES_ITEM_TYPE SDESItem::_type [protected]
The type of this SDESItem.
Referenced by copy(), dump(), getType(), and SDESItem().
The documentation for this class was generated from the following files:
sdes.h
sdes.cc