INET Framework for OMNeT++/OMNEST: PassiveQueueBase Class Reference
PassiveQueueBase Class Reference
Abstract base class for passive queues.
#include <PassiveQueueBase.h>
Public Member Functions
virtual void requestPacket ()
The queue should send a packet whenever this method is invoked.
virtual int getNumPendingRequests ()
Returns number of pending requests.
virtual void clear ()
Clear all queued packets and stored requests.
virtual void addListener (IPassiveQueueListener *listener)
Implementation of IPassiveQueue::addListener().
virtual void removeListener (IPassiveQueueListener *listener)
Implementation of IPassiveQueue::removeListener().
Protected Types
typedef std::map< long, simtime_t > MsgId2TimeMap
Protected Member Functions
virtual void initialize ()
virtual void handleMessage (cMessage *msg)
virtual void finish ()
virtual void notifyListeners ()
virtual cMessage * enqueue (cMessage *msg)=0
Inserts packet into the queue or the priority queue, or drops it (or another packet).
virtual cMessage * dequeue ()=0
Returns a packet from the queue, or NULL if the queue is empty.
virtual void sendOut (cMessage *msg)=0
Should be redefined to send out the packet; e.g.
Protected Attributes
MsgId2TimeMap msgId2TimeMap
std::list
< IPassiveQueueListener * > listeners
int packetRequested
int numQueueReceived
int numQueueDropped
Static Protected Attributes
static simsignal_t rcvdPkSignal = SIMSIGNAL_NULL
Signal with packet when received it.
static simsignal_t enqueuePkSignal = SIMSIGNAL_NULL
Signal with packet when enqueued it.
static simsignal_t dequeuePkSignal = SIMSIGNAL_NULL
Signal with packet when sent out it.
static simsignal_t dropPkByQueueSignal = SIMSIGNAL_NULL
Signal with packet when dropped it.
static simsignal_t queueingTimeSignal = SIMSIGNAL_NULL
Signal with value of delaying time when sent out a packet.
Detailed Description
Abstract base class for passive queues.
Implements IPassiveQueue. Enqueue/dequeue have to be implemented in virtual functions in subclasses; the actual queue or piority queue data structure also goes into subclasses.
Member Typedef Documentation
typedef std::map<long, simtime_t> PassiveQueueBase::MsgId2TimeMap [protected]
Member Function Documentation
void PassiveQueueBase::addListener (IPassiveQueueListener * listener) [virtual]
Implementation of IPassiveQueue::addListener().
Implements IPassiveQueue.
{
    std::list<IPassiveQueueListener*>::iterator it = find(listeners.begin(), listeners.end(), listener);
    if (it == listeners.end())
        listeners.push_back(listener);
}
void PassiveQueueBase::clear () [virtual]
Clear all queued packets and stored requests.
Implements IPassiveQueue.
{
    cMessage *msg;
    while (NULL != (msg = dequeue()))
        delete msg;
    packetRequested = 0;
}
virtual cMessage* PassiveQueueBase::dequeue () [protected, pure virtual]
Returns a packet from the queue, or NULL if the queue is empty.
Implemented in Ieee80211MgmtBase, DropTailQueue, and FIFOQueue.
Referenced by clear(), and requestPacket().
virtual cMessage* PassiveQueueBase::enqueue (cMessage * msg) [protected, pure virtual]
Inserts packet into the queue or the priority queue, or drops it (or another packet).
Returns NULL if successful, or the pointer of the dropped packet.
Implemented in Ieee80211MgmtBase, DropTailQueue, and FIFOQueue.
Referenced by handleMessage().
void PassiveQueueBase::finish () [protected, virtual]
{
    msgId2TimeMap.clear();
}
virtual int PassiveQueueBase::getNumPendingRequests () [inline, virtual]
Returns number of pending requests.
Implements IPassiveQueue.
{ return packetRequested; }
void PassiveQueueBase::handleMessage (cMessage * msg) [protected, virtual]
Reimplemented in Ieee80211MgmtBase, and Ieee80211MgmtAdhocWithEtx.
{
    numQueueReceived++;
    emit(rcvdPkSignal, msg);
    if (packetRequested > 0)
    {
        packetRequested--;
        emit(enqueuePkSignal, msg);
        emit(dequeuePkSignal, msg);
        emit(queueingTimeSignal, 0L);
        sendOut(msg);
    }
    else
    {
        msgId2TimeMap[msg->getId()] = simTime();
        cMessage *droppedMsg = enqueue(msg);
        if (msg != droppedMsg)
            emit(enqueuePkSignal, msg);
        if (droppedMsg)
        {
            numQueueDropped++;
            emit(dropPkByQueueSignal, droppedMsg);
            msgId2TimeMap.erase(droppedMsg->getId());
            delete droppedMsg;
        }
        else
            notifyListeners();
    }
    if (ev.isGUI())
    {
        char buf[40];
        sprintf(buf, "q rcvd: %d\nq dropped: %d", numQueueReceived, numQueueDropped);
        getDisplayString().setTagArg("t", 0, buf);
    }
}
void PassiveQueueBase::initialize () [protected, virtual]
Reimplemented in FIFOQueue, and DropTailQueue.
Referenced by Ieee80211MgmtAdhoc::initialize(), Ieee80211MgmtAdhocWithEtx::initialize(), Ieee80211MgmtAPSimplified::initialize(), Ieee80211MgmtSTASimplified::initialize(), Ieee80211MgmtAPBase::initialize(), Ieee80211MgmtBase::initialize(), Ieee80211MgmtAP::initialize(), and Ieee80211MgmtSTA::initialize().
{
    // state
    packetRequested = 0;
    WATCH(packetRequested);
    // statistics
    numQueueReceived = 0;
    numQueueDropped = 0;
    WATCH(numQueueReceived);
    WATCH(numQueueDropped);
    rcvdPkSignal = registerSignal("rcvdPk");
    enqueuePkSignal = registerSignal("enqueuePk");
    dequeuePkSignal = registerSignal("dequeuePk");
    dropPkByQueueSignal = registerSignal("dropPkByQueue");
    queueingTimeSignal = registerSignal("queueingTime");
    msgId2TimeMap.clear();
}
void PassiveQueueBase::notifyListeners () [protected, virtual]
Referenced by handleMessage().
{
    for (std::list<IPassiveQueueListener*>::iterator it = listeners.begin(); it != listeners.end(); ++it)
        (*it)->packetEnqueued(this);
}
void PassiveQueueBase::removeListener (IPassiveQueueListener * listener) [virtual]
Implementation of IPassiveQueue::removeListener().
Implements IPassiveQueue.
{
    std::list<IPassiveQueueListener*>::iterator it = find(listeners.begin(), listeners.end(), listener);
    if (it != listeners.end())
        listeners.erase(it);
}
void PassiveQueueBase::requestPacket () [virtual]
The queue should send a packet whenever this method is invoked.
If the queue is currently empty, it should send a packet when when one becomes available.
Implements IPassiveQueue.
{
    Enter_Method("requestPacket()");
    cMessage *msg = dequeue();
    if (msg == NULL)
    {
        packetRequested++;
    }
    else
    {
        emit(dequeuePkSignal, msg);
        emit(queueingTimeSignal, simTime() - msgId2TimeMap[msg->getId()]);
        msgId2TimeMap.erase(msg->getId());
        sendOut(msg);
    }
}
virtual void PassiveQueueBase::sendOut (cMessage * msg) [protected, pure virtual]
Should be redefined to send out the packet; e.g.
send(msg,"out").
Implemented in Ieee80211MgmtBase, DropTailQueue, and FIFOQueue.
Referenced by handleMessage(), and requestPacket().
Member Data Documentation
simsignal_t PassiveQueueBase::dequeuePkSignal = SIMSIGNAL_NULL [static, protected]
Signal with packet when sent out it.
Referenced by handleMessage(), initialize(), and requestPacket().
simsignal_t PassiveQueueBase::dropPkByQueueSignal = SIMSIGNAL_NULL [static, protected]
Signal with packet when dropped it.
Referenced by handleMessage(), and initialize().
simsignal_t PassiveQueueBase::enqueuePkSignal = SIMSIGNAL_NULL [static, protected]
Signal with packet when enqueued it.
Referenced by handleMessage(), and initialize().
std::list<IPassiveQueueListener*> PassiveQueueBase::listeners [protected]
Referenced by addListener(), notifyListeners(), and removeListener().
MsgId2TimeMap PassiveQueueBase::msgId2TimeMap [protected]
Referenced by finish(), handleMessage(), initialize(), and requestPacket().
int PassiveQueueBase::numQueueDropped [protected]
Referenced by handleMessage(), and initialize().
int PassiveQueueBase::numQueueReceived [protected]
Referenced by handleMessage(), and initialize().
int PassiveQueueBase::packetRequested [protected]
Referenced by clear(), handleMessage(), initialize(), and requestPacket().
simsignal_t PassiveQueueBase::queueingTimeSignal = SIMSIGNAL_NULL [static, protected]
Signal with value of delaying time when sent out a packet.
Referenced by handleMessage(), initialize(), and requestPacket().
simsignal_t PassiveQueueBase::rcvdPkSignal = SIMSIGNAL_NULL [static, protected]
Signal with packet when received it.
Referenced by handleMessage(), and initialize().
The documentation for this class was generated from the following files:
PassiveQueueBase.h
PassiveQueueBase.cc