INET Framework for OMNeT++/OMNEST: IPv6ExtensionHeader Class Reference
IPv6ExtensionHeader Class Reference
Class generated from networklayer/ipv6/IPv6Datagram.msg by opp_msgc.
#include <IPv6Datagram_m.h>
Public Member Functions
IPv6ExtensionHeader ()
IPv6ExtensionHeader (const IPv6ExtensionHeader &other)
virtual ~IPv6ExtensionHeader ()
IPv6ExtensionHeader & operator= (const IPv6ExtensionHeader &other)
virtual IPv6ExtensionHeader * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual short getExtensionType () const
virtual void setExtensionType (short extensionType)
virtual short getByteLength () const
virtual void setByteLength (short byteLength)
Protected Member Functions
bool operator== (const IPv6ExtensionHeader &)
Protected Attributes
short extensionType_var
short byteLength_var
Private Member Functions
void copy (const IPv6ExtensionHeader &other)
Detailed Description
Class generated from networklayer/ipv6/IPv6Datagram.msg by opp_msgc.
 class IPv6ExtensionHeader
 {
     short extensionType;
     short byteLength = 8;
 }
Constructor & Destructor Documentation
IPv6ExtensionHeader::IPv6ExtensionHeader ()
IPv6ExtensionHeader::IPv6ExtensionHeader (const IPv6ExtensionHeader & other)
virtual IPv6ExtensionHeader::~IPv6ExtensionHeader () [virtual]
Member Function Documentation
void IPv6ExtensionHeader::copy (const IPv6ExtensionHeader & other) [private]
virtual IPv6ExtensionHeader* IPv6ExtensionHeader::dup () const [inline, virtual]
Reimplemented in HomeAddressOption_Base, IPv6EncapsulatingSecurityPayloadHeader, IPv6AuthenticationHeader, IPv6DestinationOptionsHeader, IPv6FragmentHeader, IPv6RoutingHeader_Base, IPv6HopByHopOptionsHeader, HomeAddressOption, and IPv6RoutingHeader.
{return new IPv6ExtensionHeader(*this);}
virtual short IPv6ExtensionHeader::getByteLength () const [virtual]
Referenced by IPv6::fragmentAndSend().
virtual short IPv6ExtensionHeader::getExtensionType () const [virtual]
Referenced by IPv6Datagram::addExtensionHeader(), and IPv6Datagram::getExtensionHeaderOrder().
IPv6ExtensionHeader& IPv6ExtensionHeader::operator= (const IPv6ExtensionHeader & other)
bool IPv6ExtensionHeader::operator== (const IPv6ExtensionHeader &) [protected]
virtual void IPv6ExtensionHeader::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in HomeAddressOption_Base, IPv6EncapsulatingSecurityPayloadHeader, IPv6AuthenticationHeader, IPv6DestinationOptionsHeader, IPv6FragmentHeader, IPv6RoutingHeader_Base, and IPv6HopByHopOptionsHeader.
Referenced by doPacking().
virtual void IPv6ExtensionHeader::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in HomeAddressOption_Base, IPv6EncapsulatingSecurityPayloadHeader, IPv6AuthenticationHeader, IPv6DestinationOptionsHeader, IPv6FragmentHeader, IPv6RoutingHeader_Base, and IPv6HopByHopOptionsHeader.
Referenced by doUnpacking().
virtual void IPv6ExtensionHeader::setByteLength (short byteLength) [virtual]
virtual void IPv6ExtensionHeader::setExtensionType (short extensionType) [virtual]
Member Data Documentation
short IPv6ExtensionHeader::byteLength_var [protected]
Referenced by IPv6RoutingHeader::setAddressArraySize().
short IPv6ExtensionHeader::extensionType_var [protected]
The documentation for this class was generated from the following file:
IPv6Datagram_m.h