INET Framework for OMNeT++/OMNEST: IPvXAddress Class Reference
IPvXAddress Class Reference
Stores an IPv4 or an IPv6 address.
#include <IPvXAddress.h>
Public Member Functions
IPvXAddress ()
Constructor for IPv4 addresses.
IPvXAddress (const IPv4Address &addr)
Constructor for IPv4 addresses.
IPvXAddress (const IPv6Address &addr)
Constructor for IPv6 addresses.
IPvXAddress (const char *addr)
Accepts string representations supported by IPv4Address (dotted decimal notation) and IPv6Address (hex string with colons).
IPvXAddress (const IPvXAddress &addr)
Copy constructor.
~IPvXAddress ()
Destructor.
bool isIPv6 () const
Is this an IPv6 address?
IPv4Address get4 () const
Get IPv4 address.
IPv6Address get6 () const
Get IPv6 address.
void set (const IPv4Address &addr)
Set to an IPv4 address.
void set (const IPv6Address &addr)
Set to an IPv6 address.
void set (const IPvXAddress &addr)
Assignment.
void set (const char *addr)
Accepts string representations supported by IPv4Address (dotted decimal notation) and IPv6Address (hex string with colons).
IPvXAddress & operator= (const IPv4Address &addr)
Assignment.
IPvXAddress & operator= (const IPv6Address &addr)
Assignment.
IPvXAddress & operator= (const IPvXAddress &addr)
Assignment.
bool tryParse (const char *addr)
Parses and assigns the given address and returns true if the string is recognized by IPv4Address or IPv6Address, otherwise just returns false.
std::string str () const
Returns the string representation of the address (e.g.
bool isUnspecified () const
True if the structure has not been assigned any address yet.
bool isMulticast () const
True if the stored address is a multicast address.
int wordCount () const
Returns length of internal binary representation of address, (count of 32-bit unsigned integers.)
const uint32 * words () const
Returns pointer to internal binary representation of address, four 32-bit unsigned integers.
bool equals (const IPv4Address &addr) const
Returns true if the two addresses are equal.
bool equals (const IPv6Address &addr) const
Returns true if the two addresses are equal.
bool equals (const IPvXAddress &addr) const
Returns true if the two addresses are equal.
bool operator== (const IPv4Address &addr) const
Returns equals(addr).
bool operator!= (const IPv4Address &addr) const
Returns !equals(addr).
bool operator== (const IPv6Address &addr) const
Returns equals(addr).
bool operator!= (const IPv6Address &addr) const
Returns !equals(addr).
bool operator== (const IPvXAddress &addr) const
Returns equals(addr).
bool operator!= (const IPvXAddress &addr) const
Returns !equals(addr).
bool operator< (const IPvXAddress &addr) const
Compares two addresses.
Protected Attributes
uint32 d [4]
bool isv6
Detailed Description
Stores an IPv4 or an IPv6 address.
This class should be used everywhere in transport layer and up, to guarantee IPv4/IPv6 transparency.
Storage is efficient: an object occupies size of an IPv6 address (128 bits=16 bytes) plus a bool.
Constructor & Destructor Documentation
IPvXAddress::IPvXAddress () [inline]
Constructor for IPv4 addresses.
{isv6 = false; d[0] = 0;}
IPvXAddress::IPvXAddress (const IPv4Address & addr) [inline]
Constructor for IPv4 addresses.
{set(addr);}
IPvXAddress::IPvXAddress (const IPv6Address & addr) [inline]
Constructor for IPv6 addresses.
{set(addr);}
IPvXAddress::IPvXAddress (const char * addr) [inline, explicit]
Accepts string representations supported by IPv4Address (dotted decimal notation) and IPv6Address (hex string with colons).
Throws an error if the format is not recognized.
{set(addr);}
IPvXAddress::IPvXAddress (const IPvXAddress & addr) [inline]
Copy constructor.
{set(addr);}
IPvXAddress::~IPvXAddress () [inline]
Destructor.
{}
Member Function Documentation
bool IPvXAddress::equals (const IPv4Address & addr) const [inline]
Returns true if the two addresses are equal.
{
        return !isv6 && d[0] == addr.getInt();
    }
bool IPvXAddress::equals (const IPv6Address & addr) const [inline]
Returns true if the two addresses are equal.
    {
        const uint32 *w = addr.words();
        return isv6 ? (d[3] == w[3] && d[2] == w[2] && d[1] == w[1] && d[0] == w[0]) : (isUnspecified() && addr.isUnspecified());
    }
bool IPvXAddress::equals (const IPvXAddress & addr) const [inline]
Returns true if the two addresses are equal.
    {
        return (isv6 == addr.isv6) && (d[0] == addr.d[0])
                && (!isv6 || (d[3] == addr.d[3] && d[2] == addr.d[2] && d[1] == addr.d[1]));
    }
IPv4Address IPvXAddress::get4 () const [inline]
Get IPv4 address.
Throws exception if this is an IPv6 address.
Referenced by IPv4NetworkConfigurator::addManualMulticastRoutes(), IPv4NetworkConfigurator::addManualRoutes(), UDP::addMulticastAddressToInterface(), Define_Module(), doPacking(), SCTPAssociation::getAddressLevel(), TCP_NSC::handleIpInputMessage(), TCP_lwIP::ip_output(), ipv4AddressFromAddressString(), ipv4NetmaskFromAddressString(), TCP_NSC::mapRemote2Nsc(), SCTPAssociation::pmStartPathManagement(), BGPRouting::processMessageFromTCP(), LDP::processMessageFromTCP(), recvAODVUUPacket(), DYMOUM::recvDYMOUMPacket(), IPv4NetworkConfigurator::resolveInterfaceAndGateway(), SCTPPathVariables::SCTPPathVariables(), SCTP::sendAbortFromMain(), UDP::sendDown(), SCTPAssociation::sendInit(), BGPSession::sendOpenMessage(), IPvXTrafGen::sendPacket(), SCTP::sendShutdownCompleteFromMain(), PingApp::sendToICMP(), PingTestApp::sendToICMP(), TCPSpoof::sendToIP(), TCP_NSC::sendToIP(), TCPConnection::sendToIP(), and SCTPAssociation::sendToIP().
    {
        if (isv6)
            throw cRuntimeError("IPvXAddress: cannot return IPv6 address %s as IPv4", str().c_str());
        return IPv4Address(d[0]);
    }
IPv6Address IPvXAddress::get6 () const [inline]
Get IPv6 address.
Throws exception if this is an IPv4 address.
Referenced by UDP::addMulticastAddressToInterface(), doPacking(), SCTPAssociation::getAddressLevel(), TCP_lwIP::ip_output(), UDP::sendDown(), IPvXTrafGen::sendPacket(), PingTestApp::sendToICMP(), PingApp::sendToICMP(), TCPSpoof::sendToIP(), TCP_NSC::sendToIP(), TCPConnection::sendToIP(), and SCTPAssociation::sendToIP().
    {
        if (!isv6)
        {
            if (d[0] == 0) // allow null address to be returned as IPv6
                return IPv6Address();
            throw cRuntimeError("IPvXAddress: cannot return IPv4 address %s as IPv6", str().c_str());
        }
        return IPv6Address(d[0], d[1], d[2], d[3]);
    }
bool IPvXAddress::isIPv6 () const [inline]
Is this an IPv6 address?
Referenced by MultiFieldClassifier::addFilter(), UDP::addMulticastAddressToInterface(), MultiFieldClassifier::configureFilters(), doPacking(), SCTPAssociation::getAddressLevel(), SCTPAssociation::processInitAckArrived(), SCTPAssociation::processInitArrived(), PacketDump::sctpDump(), UDP::sendDown(), SCTPAssociation::sendInit(), IPvXTrafGen::sendPacket(), PingApp::sendToICMP(), PingTestApp::sendToICMP(), TCPSpoof::sendToIP(), TCPConnection::sendToIP(), and SCTPAssociation::sendToIP().
{return isv6;}
bool IPvXAddress::isMulticast () const [inline]
True if the stored address is a multicast address.
Referenced by UDP::joinMulticastGroups().
    {
        return isv6 ? get6().isMulticast() : get4().isMulticast();
    }
bool IPvXAddress::isUnspecified () const [inline]
True if the structure has not been assigned any address yet.
Referenced by MultiFieldClassifier::addFilter(), SCTP::addLocalAddress(), SCTP::addLocalAddressToAllRemoteAddresses(), TCP::addSockPair(), UDP::connect(), UDPSocket::connect(), UDP::createSocket(), UDP::findSocketByLocalAddress(), UDP::findSocketForUnicastPacket(), UDP::findSocketsForMcastBcastPacket(), PingTestApp::handleMessage(), PingApp::handleMessage(), SCTPAssociation::process_ASSOCIATE(), TCP_lwIP::process_OPEN_ACTIVE(), TCP_NSC::process_OPEN_PASSIVE(), UDP::processPacketFromApp(), TCPConnection::processTCPSegment(), UDPVideoStreamCli::requestStream(), UDP::sendDown(), SCTPAssociation::sendInit(), TCPConnection::sendSyn(), and IPvXAddressResolver::tryResolve().
    {
        return !isv6 && d[0] == 0;
    }
bool IPvXAddress::operator!= (const IPv4Address & addr) const [inline]
Returns !equals(addr).
{return !equals(addr);}
bool IPvXAddress::operator!= (const IPv6Address & addr) const [inline]
Returns !equals(addr).
{return !equals(addr);}
bool IPvXAddress::operator!= (const IPvXAddress & addr) const [inline]
Returns !equals(addr).
{return !equals(addr);}
bool IPvXAddress::operator< (const IPvXAddress & addr) const [inline]
Compares two addresses.
    {
        if (isv6 != addr.isv6)
            return !isv6;
        else if (!isv6)
            return d[0] < addr.d[0];
        else
            return memcmp(&d, &addr.d, 16) < 0;  // this provides an ordering, though not surely the one one would expect
    }
IPvXAddress& IPvXAddress::operator= (const IPv4Address & addr) [inline]
Assignment.
{set(addr); return *this;}
IPvXAddress& IPvXAddress::operator= (const IPv6Address & addr) [inline]
Assignment.
{set(addr); return *this;}
IPvXAddress& IPvXAddress::operator= (const IPvXAddress & addr) [inline]
Assignment.
{set(addr); return *this;}
bool IPvXAddress::operator== (const IPv4Address & addr) const [inline]
Returns equals(addr).
{return equals(addr);}
bool IPvXAddress::operator== (const IPv6Address & addr) const [inline]
Returns equals(addr).
{return equals(addr);}
bool IPvXAddress::operator== (const IPvXAddress & addr) const [inline]
Returns equals(addr).
{return equals(addr);}
void IPvXAddress::set (const IPv4Address & addr) [inline]
Set to an IPv4 address.
Referenced by TCP_NSC_Connection::connect(), doUnpacking(), SCTP::findAssocForMessage(), TCP_NSC::handleIpInputMessage(), TCP_NSC_Connection::listen(), and TCP_NSC::sendToIP().
    {
        isv6 = false;
        d[0] = addr.getInt();
    }
void IPvXAddress::set (const IPv6Address & addr) [inline]
Set to an IPv6 address.
    {
        if (addr.isUnspecified())
        {
            // we always represent nulls as IPv4 null
            isv6 = false; d[0] = 0;
            return;
        }
        isv6 = true;
        const uint32 *w = addr.words();
        d[0] = w[0]; d[1] = w[1]; d[2] = w[2]; d[3] = w[3];
    }
void IPvXAddress::set (const IPvXAddress & addr) [inline]
Assignment.
    {
        isv6 = addr.isv6;
        d[0] = addr.d[0];
        if (isv6)
        {
            d[1] = addr.d[1]; d[2] = addr.d[2]; d[3] = addr.d[3];
        }
    }
void IPvXAddress::set (const char * addr)
Accepts string representations supported by IPv4Address (dotted decimal notation) and IPv6Address (hex string with colons).
Throws an error if the format is not recognized.
{
    if (!tryParse(addr))
        throw cRuntimeError("IPvXAddress: cannot interpret address string `%s'", addr);
}
std::string IPvXAddress::str () const [inline]
Returns the string representation of the address (e.g.
"152.66.86.92")
Referenced by TCP::addSockPair(), UDP::bind(), TCP_NSC_Connection::connect(), UDPSocket::getReceivedPacketInfo(), TCP_NSC::initialize(), operator<<(), SCTP::removeAssociation(), PacketDump::sctpDump(), and SCTPPathVariables::SCTPPathVariables().
    {
        if (isv6)
        {
            return get6().str();
        }
        else if (d[0] == 0)
        {
            return std::string("<unspec>");
        }
        else
        {
            return get4().str();
        }
    }
bool IPvXAddress::tryParse (const char * addr)
Parses and assigns the given address and returns true if the string is recognized by IPv4Address or IPv6Address, otherwise just returns false.
Referenced by set(), and IPvXAddressResolver::tryResolve().
{
    // try as IPv4
    if (IPv4Address::isWellFormed(addr))
    {
        set(IPv4Address(addr));
        return true;
    }
    // try as IPv6
    IPv6Address ipv6;
    if (ipv6.tryParse(addr))
    {
        set(ipv6);
        return true;
    }
    // no luck
    return false;
}
int IPvXAddress::wordCount () const [inline]
Returns length of internal binary representation of address, (count of 32-bit unsigned integers.)
Referenced by TCPSerializer::checksum().
{return isv6 ? 4 : 1;}
const uint32* IPvXAddress::words () const [inline]
Returns pointer to internal binary representation of address, four 32-bit unsigned integers.
Referenced by TCPSerializer::checksum().
{return d;}
Member Data Documentation
uint32 IPvXAddress::d[4] [protected]
Referenced by equals(), and operator<().
bool IPvXAddress::isv6 [protected]
Referenced by equals(), and operator<().
The documentation for this class was generated from the following files:
IPvXAddress.h
IPvXAddress.cc