INET Framework for OMNeT++/OMNEST: OSPF::Interface Class Reference
OSPF::Interface Class Reference
#include <OSPFInterface.h>
Public Types
enum InterfaceEventType {
INTERFACE_UP = 0, HELLO_TIMER = 1, WAIT_TIMER = 2, ACKNOWLEDGEMENT_TIMER = 3,
BACKUP_SEEN = 4, NEIGHBOR_CHANGE = 5, LOOP_INDICATION = 6, UNLOOP_INDICATION = 7,
INTERFACE_DOWN = 8
}
enum OSPFInterfaceType {
UNKNOWN_TYPE = 0, POINTTOPOINT = 1, BROADCAST = 2, NBMA = 3,
POINTTOMULTIPOINT = 4, VIRTUAL = 5
}
enum InterfaceStateType {
DOWN_STATE = 0, LOOPBACK_STATE = 1, WAITING_STATE = 2, POINTTOPOINT_STATE = 3,
NOT_DESIGNATED_ROUTER_STATE = 4, BACKUP_STATE = 5, DESIGNATED_ROUTER_STATE = 6
}
Public Member Functions
Interface (OSPFInterfaceType ifType=UNKNOWN_TYPE)
virtual ~Interface ()
void processEvent (InterfaceEventType event)
void reset ()
void sendHelloPacket (IPv4Address destination, short ttl=1)
void sendLSAcknowledgement (OSPFLSAHeader *lsaHeader, IPv4Address destination)
Neighbor * getNeighborByID (RouterID neighborID)
Neighbor * getNeighborByAddress (IPv4Address address)
void addNeighbor (Neighbor *neighbor)
InterfaceStateType getState () const
bool hasAnyNeighborInStates (int states) const
void removeFromAllRetransmissionLists (LSAKeyType lsaKey)
bool isOnAnyRetransmissionList (LSAKeyType lsaKey) const
bool floodLSA (OSPFLSA *lsa, Interface *intf=NULL, Neighbor *neighbor=NULL)
void addDelayedAcknowledgement (OSPFLSAHeader &lsaHeader)
void sendDelayedAcknowledgements ()
void ageTransmittedLSALists ()
OSPFLinkStateUpdatePacket * createUpdatePacket (OSPFLSA *lsa)
void setType (OSPFInterfaceType ifType)
OSPFInterfaceType getType () const
void setIfIndex (int index)
int getIfIndex () const
void setMTU (unsigned short ifMTU)
unsigned short getMTU () const
void setAreaID (AreaID areaId)
AreaID getAreaID () const
void setTransitAreaID (AreaID areaId)
AreaID getTransitAreaID () const
void setOutputCost (Metric cost)
Metric getOutputCost () const
void setRetransmissionInterval (short interval)
short getRetransmissionInterval () const
void setTransmissionDelay (short delay)
short getTransmissionDelay () const
void setAcknowledgementDelay (short delay)
short getAcknowledgementDelay () const
void setRouterPriority (unsigned char priority)
unsigned char getRouterPriority () const
void setHelloInterval (short interval)
short getHelloInterval () const
void setPollInterval (short interval)
short getPollInterval () const
void setRouterDeadInterval (short interval)
short getRouterDeadInterval () const
void setAuthenticationType (AuthenticationType type)
AuthenticationType getAuthenticationType () const
void setAuthenticationKey (AuthenticationKeyType key)
AuthenticationKeyType getAuthenticationKey () const
void setAddressRange (IPv4AddressRange range)
IPv4AddressRange getAddressRange () const
OSPFTimer * getHelloTimer ()
OSPFTimer * getWaitTimer ()
OSPFTimer * getAcknowledgementTimer ()
DesignatedRouterID getDesignatedRouter () const
DesignatedRouterID getBackupDesignatedRouter () const
unsigned long getNeighborCount () const
Neighbor * getNeighbor (unsigned long i)
const Neighbor * getNeighbor (unsigned long i) const
void setArea (Area *area)
Area * getArea ()
const Area * getArea () const
Static Public Member Functions
static const char * getStateString (InterfaceStateType stateType)
Private Member Functions
void changeState (InterfaceState *newState, InterfaceState *currentState)
Private Attributes
OSPFInterfaceType interfaceType
InterfaceState * state
InterfaceState * previousState
int ifIndex
unsigned short mtu
IPv4AddressRange interfaceAddressRange
AreaID areaID
AreaID transitAreaID
short helloInterval
short pollInterval
short routerDeadInterval
short interfaceTransmissionDelay
unsigned char routerPriority
OSPFTimer * helloTimer
OSPFTimer * waitTimer
OSPFTimer * acknowledgementTimer
std::map< RouterID, Neighbor * > neighboringRoutersByID
std::map< IPv4Address, Neighbor * > neighboringRoutersByAddress
std::vector< Neighbor * > neighboringRouters
std::map< IPv4Address,
std::list< OSPFLSAHeader > > delayedAcknowledgements
DesignatedRouterID designatedRouter
DesignatedRouterID backupDesignatedRouter
Metric interfaceOutputCost
short retransmissionInterval
short acknowledgementDelay
AuthenticationType authenticationType
AuthenticationKeyType authenticationKey
Area * parentArea
Friends
class InterfaceState
Member Enumeration Documentation
enum OSPF::Interface::InterfaceEventType
Enumerator:
INTERFACE_UP
HELLO_TIMER
WAIT_TIMER
ACKNOWLEDGEMENT_TIMER
BACKUP_SEEN
NEIGHBOR_CHANGE
LOOP_INDICATION
UNLOOP_INDICATION
INTERFACE_DOWN
{
        INTERFACE_UP          = 0,
        HELLO_TIMER           = 1,
        WAIT_TIMER            = 2,
        ACKNOWLEDGEMENT_TIMER = 3,
        BACKUP_SEEN           = 4,
        NEIGHBOR_CHANGE       = 5,
        LOOP_INDICATION       = 6,
        UNLOOP_INDICATION     = 7,
        INTERFACE_DOWN        = 8
    };
enum OSPF::Interface::InterfaceStateType
Enumerator:
DOWN_STATE
LOOPBACK_STATE
WAITING_STATE
POINTTOPOINT_STATE
NOT_DESIGNATED_ROUTER_STATE
BACKUP_STATE
DESIGNATED_ROUTER_STATE
{
        DOWN_STATE                = 0,
        LOOPBACK_STATE            = 1,
        WAITING_STATE             = 2,
        POINTTOPOINT_STATE        = 3,
        NOT_DESIGNATED_ROUTER_STATE = 4,
        BACKUP_STATE              = 5,
        DESIGNATED_ROUTER_STATE    = 6
    };
enum OSPF::Interface::OSPFInterfaceType
Enumerator:
UNKNOWN_TYPE
POINTTOPOINT
BROADCAST
NBMA
POINTTOMULTIPOINT
VIRTUAL
{
        UNKNOWN_TYPE       = 0,
        POINTTOPOINT      = 1,
        BROADCAST         = 2,
        NBMA              = 3,
        POINTTOMULTIPOINT = 4,
        VIRTUAL           = 5
    };
Constructor & Destructor Documentation
OSPF::Interface::Interface (OSPFInterfaceType ifType = UNKNOWN_TYPE)
                                                              :
    interfaceType(ifType),
    ifIndex(0),
    mtu(0),
    interfaceAddressRange(OSPF::NULL_IPV4ADDRESSRANGE),
    areaID(OSPF::BACKBONE_AREAID),
    transitAreaID(OSPF::BACKBONE_AREAID),
    helloInterval(10),
    pollInterval(120),
    routerDeadInterval(40),
    interfaceTransmissionDelay(1),
    routerPriority(0),
    designatedRouter(OSPF::NULL_DESIGNATEDROUTERID),
    backupDesignatedRouter(OSPF::NULL_DESIGNATEDROUTERID),
    interfaceOutputCost(1),
    retransmissionInterval(5),
    acknowledgementDelay(1),
    authenticationType(OSPF::NULL_TYPE),
    parentArea(NULL)
{
    state = new OSPF::InterfaceStateDown;
    previousState = NULL;
    helloTimer = new OSPFTimer();
    helloTimer->setTimerKind(INTERFACE_HELLO_TIMER);
    helloTimer->setContextPointer(this);
    helloTimer->setName("OSPF::Interface::InterfaceHelloTimer");
    waitTimer = new OSPFTimer();
    waitTimer->setTimerKind(INTERFACE_WAIT_TIMER);
    waitTimer->setContextPointer(this);
    waitTimer->setName("OSPF::Interface::InterfaceWaitTimer");
    acknowledgementTimer = new OSPFTimer();
    acknowledgementTimer->setTimerKind(INTERFACE_ACKNOWLEDGEMENT_TIMER);
    acknowledgementTimer->setContextPointer(this);
    acknowledgementTimer->setName("OSPF::Interface::InterfaceAcknowledgementTimer");
    memset(authenticationKey.bytes, 0, 8 * sizeof(char));
}
OSPF::Interface::~Interface () [virtual]
{
    MessageHandler* messageHandler = parentArea->getRouter()->getMessageHandler();
    messageHandler->clearTimer(helloTimer);
    delete helloTimer;
    messageHandler->clearTimer(waitTimer);
    delete waitTimer;
    messageHandler->clearTimer(acknowledgementTimer);
    delete acknowledgementTimer;
    if (previousState != NULL) {
        delete previousState;
    }
    delete state;
    long neighborCount = neighboringRouters.size();
    for (long i = 0; i < neighborCount; i++) {
        delete neighboringRouters[i];
    }
}
Member Function Documentation
void OSPF::Interface::addDelayedAcknowledgement (OSPFLSAHeader & lsaHeader)
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA().
{
    if (interfaceType == OSPF::Interface::BROADCAST) {
        if ((getState() == OSPF::Interface::DESIGNATED_ROUTER_STATE) ||
            (getState() == OSPF::Interface::BACKUP_STATE) ||
            (designatedRouter == OSPF::NULL_DESIGNATEDROUTERID))
        {
            delayedAcknowledgements[IPv4Address::ALL_OSPF_ROUTERS_MCAST].push_back(lsaHeader);
        } else {
            delayedAcknowledgements[IPv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST].push_back(lsaHeader);
        }
    } else {
        long neighborCount = neighboringRouters.size();
        for (long i = 0; i < neighborCount; i++) {
            if (neighboringRouters[i]->getState() >= OSPF::Neighbor::EXCHANGE_STATE) {
                delayedAcknowledgements[neighboringRouters[i]->getAddress()].push_back(lsaHeader);
            }
        }
    }
}
void OSPF::Interface::addNeighbor (OSPF::Neighbor * neighbor)
Referenced by OSPFRouting::loadInterfaceParameters(), OSPFRouting::loadVirtualLink(), and OSPF::HelloHandler::processPacket().
{
    neighboringRoutersByID[neighbor->getNeighborID()] = neighbor;
    neighboringRoutersByAddress[neighbor->getAddress()] = neighbor;
    neighbor->setInterface(this);
    neighboringRouters.push_back(neighbor);
}
void OSPF::Interface::ageTransmittedLSALists ()
{
    long neighborCount = neighboringRouters.size();
    for (long i = 0; i < neighborCount; i++) {
        neighboringRouters[i]->ageTransmittedLSAList();
    }
}
void OSPF::Interface::changeState (OSPF::InterfaceState * newState, OSPF::InterfaceState * currentState) [private]
Referenced by OSPF::InterfaceState::changeState().
{
    if (previousState != NULL) {
        delete previousState;
    }
    state = newState;
    previousState = currentState;
}
OSPFLinkStateUpdatePacket * OSPF::Interface::createUpdatePacket (OSPFLSA * lsa)
Referenced by OSPF::LinkStateRequestHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{
    LSAType lsaType = static_cast<LSAType> (lsa->getHeader().getLsType());
    OSPFRouterLSA* routerLSA = (lsaType == ROUTERLSA_TYPE) ? dynamic_cast<OSPFRouterLSA*> (lsa) : NULL;
    OSPFNetworkLSA* networkLSA = (lsaType == NETWORKLSA_TYPE) ? dynamic_cast<OSPFNetworkLSA*> (lsa) : NULL;
    OSPFSummaryLSA* summaryLSA = ((lsaType == SUMMARYLSA_NETWORKS_TYPE) ||
                                        (lsaType == SUMMARYLSA_ASBOUNDARYROUTERS_TYPE)) ? dynamic_cast<OSPFSummaryLSA*> (lsa) : NULL;
    OSPFASExternalLSA* asExternalLSA = (lsaType == AS_EXTERNAL_LSA_TYPE) ? dynamic_cast<OSPFASExternalLSA*> (lsa) : NULL;
    if (((lsaType == ROUTERLSA_TYPE) && (routerLSA != NULL)) ||
        ((lsaType == NETWORKLSA_TYPE) && (networkLSA != NULL)) ||
        (((lsaType == SUMMARYLSA_NETWORKS_TYPE) || (lsaType == SUMMARYLSA_ASBOUNDARYROUTERS_TYPE)) && (summaryLSA != NULL)) ||
        ((lsaType == AS_EXTERNAL_LSA_TYPE) && (asExternalLSA != NULL)))
    {
        OSPFLinkStateUpdatePacket* updatePacket = new OSPFLinkStateUpdatePacket();
        long packetLength = OSPF_HEADER_LENGTH + sizeof(uint32_t);  // OSPF header + place for number of advertisements
        updatePacket->setType(LINKSTATE_UPDATE_PACKET);
        updatePacket->setRouterID(IPv4Address(parentArea->getRouter()->getRouterID()));
        updatePacket->setAreaID(IPv4Address(areaID));
        updatePacket->setAuthenticationType(authenticationType);
        for (int j = 0; j < 8; j++) {
            updatePacket->setAuthentication(j, authenticationKey.bytes[j]);
        }
        updatePacket->setNumberOfLSAs(1);
        switch (lsaType) {
            case ROUTERLSA_TYPE:
                {
                    updatePacket->setRouterLSAsArraySize(1);
                    updatePacket->setRouterLSAs(0, *routerLSA);
                    unsigned short lsAge = updatePacket->getRouterLSAs(0).getHeader().getLsAge();
                    if (lsAge < MAX_AGE - interfaceTransmissionDelay) {
                        updatePacket->getRouterLSAs(0).getHeader().setLsAge(lsAge + interfaceTransmissionDelay);
                    } else {
                        updatePacket->getRouterLSAs(0).getHeader().setLsAge(MAX_AGE);
                    }
                    packetLength += calculateLSASize(routerLSA);
                }
                break;
            case NETWORKLSA_TYPE:
                {
                    updatePacket->setNetworkLSAsArraySize(1);
                    updatePacket->setNetworkLSAs(0, *networkLSA);
                    unsigned short lsAge = updatePacket->getNetworkLSAs(0).getHeader().getLsAge();
                    if (lsAge < MAX_AGE - interfaceTransmissionDelay) {
                        updatePacket->getNetworkLSAs(0).getHeader().setLsAge(lsAge + interfaceTransmissionDelay);
                    } else {
                        updatePacket->getNetworkLSAs(0).getHeader().setLsAge(MAX_AGE);
                    }
                    packetLength += calculateLSASize(networkLSA);
                }
                break;
            case SUMMARYLSA_NETWORKS_TYPE:
            case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
                {
                    updatePacket->setSummaryLSAsArraySize(1);
                    updatePacket->setSummaryLSAs(0, *summaryLSA);
                    unsigned short lsAge = updatePacket->getSummaryLSAs(0).getHeader().getLsAge();
                    if (lsAge < MAX_AGE - interfaceTransmissionDelay) {
                        updatePacket->getSummaryLSAs(0).getHeader().setLsAge(lsAge + interfaceTransmissionDelay);
                    } else {
                        updatePacket->getSummaryLSAs(0).getHeader().setLsAge(MAX_AGE);
                    }
                    packetLength += calculateLSASize(summaryLSA);
                }
                break;
            case AS_EXTERNAL_LSA_TYPE:
                {
                    updatePacket->setAsExternalLSAsArraySize(1);
                    updatePacket->setAsExternalLSAs(0, *asExternalLSA);
                    unsigned short lsAge = updatePacket->getAsExternalLSAs(0).getHeader().getLsAge();
                    if (lsAge < MAX_AGE - interfaceTransmissionDelay) {
                        updatePacket->getAsExternalLSAs(0).getHeader().setLsAge(lsAge + interfaceTransmissionDelay);
                    } else {
                        updatePacket->getAsExternalLSAs(0).getHeader().setLsAge(MAX_AGE);
                    }
                    packetLength += calculateLSASize(asExternalLSA);
                }
                break;
            default: throw cRuntimeError("Invalid LSA type: %d", lsaType);
        }
        updatePacket->setByteLength(packetLength);
        return updatePacket;
    }
    return NULL;
}
bool OSPF::Interface::floodLSA (OSPFLSA * lsa, OSPF::Interface * intf = NULL, OSPF::Neighbor * neighbor = NULL)
See also:
RFC2328 Section 13.3.
{
    bool floodedBackOut = false;
    if (
        (
         (lsa->getHeader().getLsType() == AS_EXTERNAL_LSA_TYPE) &&
         (interfaceType != OSPF::Interface::VIRTUAL) &&
         (parentArea->getExternalRoutingCapability())
        ) ||
        (
         (lsa->getHeader().getLsType() != AS_EXTERNAL_LSA_TYPE) &&
         (
          (
           (areaID != OSPF::BACKBONE_AREAID) &&
           (interfaceType != OSPF::Interface::VIRTUAL)
          ) ||
          (areaID == OSPF::BACKBONE_AREAID)
         )
        )
       )
    {
        long neighborCount = neighboringRouters.size();
        bool lsaAddedToRetransmissionList = false;
        OSPF::LinkStateID linkStateID = lsa->getHeader().getLinkStateID();
        OSPF::LSAKeyType lsaKey;
        lsaKey.linkStateID = linkStateID;
        lsaKey.advertisingRouter = lsa->getHeader().getAdvertisingRouter();
        for (long i = 0; i < neighborCount; i++) {  // (1)
            if (neighboringRouters[i]->getState() < OSPF::Neighbor::EXCHANGE_STATE) {   // (1) (a)
                continue;
            }
            if (neighboringRouters[i]->getState() < OSPF::Neighbor::FULL_STATE) {   // (1) (b)
                OSPFLSAHeader* requestLSAHeader = neighboringRouters[i]->findOnRequestList(lsaKey);
                if (requestLSAHeader != NULL) {
                    // operator< and operator== on OSPFLSAHeaders determines which one is newer(less means older)
                    if (lsa->getHeader() < (*requestLSAHeader)) {
                        continue;
                    }
                    if (operator==(lsa->getHeader(), (*requestLSAHeader))) {
                        neighboringRouters[i]->removeFromRequestList(lsaKey);
                        continue;
                    }
                    neighboringRouters[i]->removeFromRequestList(lsaKey);
                }
            }
            if (neighbor == neighboringRouters[i]) {     // (1) (c)
                continue;
            }
            neighboringRouters[i]->addToRetransmissionList(lsa);   // (1) (d)
            lsaAddedToRetransmissionList = true;
        }
        if (lsaAddedToRetransmissionList) {     // (2)
            if ((intf != this) ||
                ((neighbor != NULL) &&
                 (neighbor->getNeighborID() != designatedRouter.routerID) &&
                 (neighbor->getNeighborID() != backupDesignatedRouter.routerID)))  // (3)
            {
                if ((intf != this) || (getState() != OSPF::Interface::BACKUP_STATE)) {  // (4)
                    OSPFLinkStateUpdatePacket* updatePacket = createUpdatePacket(lsa);    // (5)
                    if (updatePacket != NULL) {
                        int ttl = (interfaceType == OSPF::Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
                        OSPF::MessageHandler* messageHandler = parentArea->getRouter()->getMessageHandler();
                        if (interfaceType == OSPF::Interface::BROADCAST) {
                            if ((getState() == OSPF::Interface::DESIGNATED_ROUTER_STATE) ||
                                (getState() == OSPF::Interface::BACKUP_STATE) ||
                                (designatedRouter == OSPF::NULL_DESIGNATEDROUTERID))
{
                                messageHandler->sendPacket(updatePacket, IPv4Address::ALL_OSPF_ROUTERS_MCAST, ifIndex, ttl);
                                for (long k = 0; k < neighborCount; k++) {
                                    neighboringRouters[k]->addToTransmittedLSAList(lsaKey);
                                    if (!neighboringRouters[k]->isUpdateRetransmissionTimerActive()) {
                                        neighboringRouters[k]->startUpdateRetransmissionTimer();
                                    }
                                }
                            } else {
                                messageHandler->sendPacket(updatePacket, IPv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST, ifIndex, ttl);
                                OSPF::Neighbor* dRouter = getNeighborByID(designatedRouter.routerID);
                                OSPF::Neighbor* backupDRouter = getNeighborByID(backupDesignatedRouter.routerID);
                                if (dRouter != NULL) {
                                    dRouter->addToTransmittedLSAList(lsaKey);
                                    if (!dRouter->isUpdateRetransmissionTimerActive()) {
                                        dRouter->startUpdateRetransmissionTimer();
                                    }
                                }
                                if (backupDRouter != NULL) {
                                    backupDRouter->addToTransmittedLSAList(lsaKey);
                                    if (!backupDRouter->isUpdateRetransmissionTimerActive()) {
                                        backupDRouter->startUpdateRetransmissionTimer();
                                    }
                                }
                            }
                        } else {
                            if (interfaceType == OSPF::Interface::POINTTOPOINT) {
                                messageHandler->sendPacket(updatePacket, IPv4Address::ALL_OSPF_ROUTERS_MCAST, ifIndex, ttl);
                                if (neighborCount > 0) {
                                    neighboringRouters[0]->addToTransmittedLSAList(lsaKey);
                                    if (!neighboringRouters[0]->isUpdateRetransmissionTimerActive()) {
                                        neighboringRouters[0]->startUpdateRetransmissionTimer();
                                    }
                                }
                            } else {
                                for (long m = 0; m < neighborCount; m++) {
                                    if (neighboringRouters[m]->getState() >= OSPF::Neighbor::EXCHANGE_STATE) {
                                        messageHandler->sendPacket(updatePacket, neighboringRouters[m]->getAddress(), ifIndex, ttl);
                                        neighboringRouters[m]->addToTransmittedLSAList(lsaKey);
                                        if (!neighboringRouters[m]->isUpdateRetransmissionTimerActive()) {
                                            neighboringRouters[m]->startUpdateRetransmissionTimer();
                                        }
                                    }
                                }
                            }
                        }
                        if (intf == this) {
                            floodedBackOut = true;
                        }
                    }
                }
            }
        }
    }
    return floodedBackOut;
}
short OSPF::Interface::getAcknowledgementDelay () const [inline]
Referenced by OSPF::InterfaceStateDown::processEvent().
{ return acknowledgementDelay; }
OSPFTimer* OSPF::Interface::getAcknowledgementTimer () [inline]
Referenced by OSPF::InterfaceStateDown::processEvent().
{ return acknowledgementTimer; }
IPv4AddressRange OSPF::Interface::getAddressRange () const [inline]
Referenced by OSPF::InterfaceState::changeState(), OSPF::NeighborState::changeState(), OSPF::Area::originateNetworkLSA(), OSPF::Area::originateRouterLSA(), and OSPF::HelloHandler::processPacket().
{ return interfaceAddressRange; }
Area* OSPF::Interface::getArea () [inline]
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::InterfaceState::changeState(), OSPF::NeighborState::changeState(), OSPF::DatabaseDescriptionHandler::processDDPacket(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateDown::processEvent(), OSPF::NeighborStateAttempt::processEvent(), OSPF::InterfaceStateDown::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStateDesignatedRouter::processEvent(), OSPF::InterfaceStateBackup::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::LinkStateRequestHandler::processPacket(), and OSPF::HelloHandler::processPacket().
{ return parentArea; }
const Area* OSPF::Interface::getArea () const [inline]
{ return parentArea; }
AreaID OSPF::Interface::getAreaID () const [inline]
Referenced by OSPFRouting::loadVirtualLink().
{ return areaID; }
AuthenticationKeyType OSPF::Interface::getAuthenticationKey () const [inline]
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA().
{ return authenticationKey; }
AuthenticationType OSPF::Interface::getAuthenticationType () const [inline]
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA().
{ return authenticationType; }
DesignatedRouterID OSPF::Interface::getBackupDesignatedRouter () const [inline]
Referenced by OSPF::InterfaceStateNotDesignatedRouter::processEvent().
{ return backupDesignatedRouter; }
DesignatedRouterID OSPF::Interface::getDesignatedRouter () const [inline]
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::Area::originateRouterLSA(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::LinkStateRequestHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{ return designatedRouter; }
short OSPF::Interface::getHelloInterval () const [inline]
Referenced by OSPF::InterfaceStateBackup::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStateDesignatedRouter::processEvent(), and OSPF::HelloHandler::processPacket().
{ return helloInterval; }
OSPFTimer* OSPF::Interface::getHelloTimer () [inline]
Referenced by OSPF::InterfaceStateBackup::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStateDown::processEvent(), and OSPF::InterfaceStateDesignatedRouter::processEvent().
{ return helloTimer; }
int OSPF::Interface::getIfIndex () const [inline]
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::Area::originateRouterLSA(), OSPF::MessageHandler::printEvent(), OSPF::LinkStateRequestHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{ return ifIndex; }
unsigned short OSPF::Interface::getMTU () const [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processPacket().
{ return mtu; }
Neighbor* OSPF::Interface::getNeighbor (unsigned long i) [inline]
Referenced by OSPF::Area::calculateShortestPathTree(), OSPF::Area::originateNetworkLSA(), OSPF::Area::originateRouterLSA(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStateDown::processEvent(), OSPF::InterfaceStateDesignatedRouter::processEvent(), OSPF::InterfaceStateBackup::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), and OSPF::HelloHandler::processPacket().
{ return neighboringRouters[i]; }
const Neighbor* OSPF::Interface::getNeighbor (unsigned long i) const [inline]
{ return neighboringRouters[i]; }
OSPF::Neighbor * OSPF::Interface::getNeighborByAddress (IPv4Address address)
Referenced by OSPF::Area::originateRouterLSA(), OSPF::HelloHandler::processPacket(), and OSPF::MessageHandler::processPacket().
{
    std::map<IPv4Address, OSPF::Neighbor*>::iterator neighborIt =
            neighboringRoutersByAddress.find(address);
    if (neighborIt != neighboringRoutersByAddress.end()) {
        return (neighborIt->second);
    }
    else {
        return NULL;
    }
}
OSPF::Neighbor * OSPF::Interface::getNeighborByID (OSPF::RouterID neighborID)
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::HelloHandler::processPacket(), and OSPF::MessageHandler::processPacket().
{
    std::map<OSPF::RouterID, OSPF::Neighbor*>::iterator neighborIt = neighboringRoutersByID.find(neighborID);
    if (neighborIt != neighboringRoutersByID.end()) {
        return (neighborIt->second);
    }
    else {
        return NULL;
    }
}
unsigned long OSPF::Interface::getNeighborCount () const [inline]
Referenced by OSPF::Area::ageDatabase(), OSPF::Area::originateNetworkLSA(), OSPF::Area::originateRouterLSA(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStateDown::processEvent(), OSPF::InterfaceStateDesignatedRouter::processEvent(), OSPF::InterfaceStateBackup::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), and OSPF::HelloHandler::processPacket().
{ return neighboringRouters.size(); }
Metric OSPF::Interface::getOutputCost () const [inline]
Referenced by OSPF::Area::originateRouterLSA().
{ return interfaceOutputCost; }
short OSPF::Interface::getPollInterval () const [inline]
Referenced by OSPF::NeighborStateAttempt::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateExchange::processEvent(), and OSPF::NeighborStateDown::processEvent().
{ return pollInterval; }
short OSPF::Interface::getRetransmissionInterval () const [inline]
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), and OSPF::NeighborStateExchangeStart::processEvent().
{ return retransmissionInterval; }
short OSPF::Interface::getRouterDeadInterval () const [inline]
Referenced by OSPF::InterfaceStateDown::processEvent(), and OSPF::HelloHandler::processPacket().
{ return routerDeadInterval; }
unsigned char OSPF::Interface::getRouterPriority () const [inline]
Referenced by OSPF::InterfaceStateDown::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), and OSPF::HelloHandler::processPacket().
{ return routerPriority; }
OSPF::Interface::InterfaceStateType OSPF::Interface::getState () const
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::Area::ageDatabase(), OSPF::InterfaceState::calculateDesignatedRouter(), OSPF::Area::calculateShortestPathTree(), OSPF::NeighborState::changeState(), OSPF::Area::originateRouterLSA(), OSPF::MessageHandler::printEvent(), OSPF::LinkStateRequestHandler::processPacket(), OSPF::HelloHandler::processPacket(), OSPF::LinkStateUpdateHandler::processPacket(), and OSPF::MessageHandler::processPacket().
{
    return state->getState();
}
const char * OSPF::Interface::getStateString (InterfaceStateType stateType) [static]
Referenced by OSPF::MessageHandler::printEvent().
{
    switch (stateType) {
        case DOWN_STATE:                 return "Down";
        case LOOPBACK_STATE:             return "Loopback";
        case WAITING_STATE:              return "Waiting";
        case POINTTOPOINT_STATE:         return "PointToPoint";
        case NOT_DESIGNATED_ROUTER_STATE:  return "NotDesignatedRouter";
        case BACKUP_STATE:               return "Backup";
        case DESIGNATED_ROUTER_STATE:     return "DesignatedRouter";
        default:                        ASSERT(false); break;
    }
    return "";
}
AreaID OSPF::Interface::getTransitAreaID () const [inline]
Referenced by OSPF::Area::calculateShortestPathTree(), and OSPF::MessageHandler::processPacket().
{ return transitAreaID; }
short OSPF::Interface::getTransmissionDelay () const [inline]
{ return interfaceTransmissionDelay; }
OSPFInterfaceType OSPF::Interface::getType () const [inline]
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::Area::calculateNextHops(), OSPF::InterfaceState::changeState(), OSPF::Area::originateRouterLSA(), OSPF::MessageHandler::printEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateAttempt::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::NeighborStateDown::processEvent(), OSPF::NeighborStateExchange::processEvent(), OSPF::InterfaceStateDesignatedRouter::processEvent(), OSPF::InterfaceStateBackup::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::InterfaceStateDown::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::LinkStateRequestHandler::processPacket(), OSPF::HelloHandler::processPacket(), OSPF::LinkStateUpdateHandler::processPacket(), and OSPF::MessageHandler::processPacket().
{ return interfaceType; }
OSPFTimer* OSPF::Interface::getWaitTimer () [inline]
Referenced by OSPF::InterfaceStateDown::processEvent().
{ return waitTimer; }
bool OSPF::Interface::hasAnyNeighborInStates (int states) const
Referenced by OSPF::Area::ageDatabase(), OSPF::Area::originateNetworkLSA(), and OSPF::Area::originateRouterLSA().
{
    long neighborCount = neighboringRouters.size();
    for (long i = 0; i < neighborCount; i++) {
        OSPF::Neighbor::NeighborStateType neighborState = neighboringRouters[i]->getState();
        if (neighborState & states) {
            return true;
        }
    }
    return false;
}
bool OSPF::Interface::isOnAnyRetransmissionList (OSPF::LSAKeyType lsaKey) const
{
    long neighborCount = neighboringRouters.size();
    for (long i = 0; i < neighborCount; i++) {
        if (neighboringRouters[i]->isLinkStateRequestListEmpty(lsaKey)) {
            return true;
        }
    }
    return false;
}
void OSPF::Interface::processEvent (InterfaceEventType event)
Referenced by OSPF::Area::calculateShortestPathTree(), OSPF::MessageHandler::handleTimer(), OSPFRouting::loadInterfaceParameters(), and OSPF::HelloHandler::processPacket().
{
    state->processEvent(this, event);
}
void OSPF::Interface::removeFromAllRetransmissionLists (OSPF::LSAKeyType lsaKey)
{
    long neighborCount = neighboringRouters.size();
    for (long i = 0; i < neighborCount; i++) {
        neighboringRouters[i]->removeFromRetransmissionList(lsaKey);
    }
}
void OSPF::Interface::reset ()
Referenced by OSPF::InterfaceStateBackup::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStateLoopback::processEvent(), OSPF::InterfaceStateDown::processEvent(), and OSPF::InterfaceStateDesignatedRouter::processEvent().
{
    MessageHandler* messageHandler = parentArea->getRouter()->getMessageHandler();
    messageHandler->clearTimer(helloTimer);
    messageHandler->clearTimer(waitTimer);
    messageHandler->clearTimer(acknowledgementTimer);
    designatedRouter = NULL_DESIGNATEDROUTERID;
    backupDesignatedRouter = NULL_DESIGNATEDROUTERID;
    long neighborCount = neighboringRouters.size();
    for (long i = 0; i < neighborCount; i++) {
        neighboringRouters[i]->processEvent(OSPF::Neighbor::KILL_NEIGHBOR);
    }
}
void OSPF::Interface::sendDelayedAcknowledgements ()
Referenced by OSPF::InterfaceStateBackup::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), and OSPF::InterfaceStateDesignatedRouter::processEvent().
{
    OSPF::MessageHandler* messageHandler = parentArea->getRouter()->getMessageHandler();
    long maxPacketSize = ((IP_MAX_HEADER_BYTES + OSPF_HEADER_LENGTH + OSPF_LSA_HEADER_LENGTH) > mtu) ? IPV4_DATAGRAM_LENGTH : mtu;
    for (std::map<IPv4Address, std::list<OSPFLSAHeader> >::iterator delayIt = delayedAcknowledgements.begin();
         delayIt != delayedAcknowledgements.end();
         delayIt++)
    {
        int ackCount = delayIt->second.size();
        if (ackCount > 0) {
            while (!(delayIt->second.empty())) {
                OSPFLinkStateAcknowledgementPacket* ackPacket = new OSPFLinkStateAcknowledgementPacket();
                long packetSize = IP_MAX_HEADER_BYTES + OSPF_HEADER_LENGTH;
                ackPacket->setType(LINKSTATE_ACKNOWLEDGEMENT_PACKET);
                ackPacket->setRouterID(IPv4Address(parentArea->getRouter()->getRouterID()));
                ackPacket->setAreaID(IPv4Address(areaID));
                ackPacket->setAuthenticationType(authenticationType);
                for (int i = 0; i < 8; i++) {
                    ackPacket->setAuthentication(i, authenticationKey.bytes[i]);
                }
                while ((!(delayIt->second.empty())) && (packetSize <= (maxPacketSize - OSPF_LSA_HEADER_LENGTH))) {
                    unsigned long headerCount = ackPacket->getLsaHeadersArraySize();
                    ackPacket->setLsaHeadersArraySize(headerCount + 1);
                    ackPacket->setLsaHeaders(headerCount, *(delayIt->second.begin()));
                    delayIt->second.pop_front();
                    packetSize += OSPF_LSA_HEADER_LENGTH;
                }
                ackPacket->setByteLength(packetSize - IP_MAX_HEADER_BYTES);
                int ttl = (interfaceType == OSPF::Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
                if (interfaceType == OSPF::Interface::BROADCAST) {
                    if ((getState() == OSPF::Interface::DESIGNATED_ROUTER_STATE) ||
                        (getState() == OSPF::Interface::BACKUP_STATE) ||
                        (designatedRouter == OSPF::NULL_DESIGNATEDROUTERID))
                    {
                        messageHandler->sendPacket(ackPacket, IPv4Address::ALL_OSPF_ROUTERS_MCAST, ifIndex, ttl);
                    } else {
                        messageHandler->sendPacket(ackPacket, IPv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST, ifIndex, ttl);
                    }
                } else {
                    if (interfaceType == OSPF::Interface::POINTTOPOINT) {
                        messageHandler->sendPacket(ackPacket, IPv4Address::ALL_OSPF_ROUTERS_MCAST, ifIndex, ttl);
                    } else {
                        messageHandler->sendPacket(ackPacket, delayIt->first, ifIndex, ttl);
                    }
                }
            }
        }
    }
    messageHandler->startTimer(acknowledgementTimer, acknowledgementDelay);
}
void OSPF::Interface::sendHelloPacket (IPv4Address destination, short ttl = 1)
Referenced by OSPF::InterfaceStateBackup::processEvent(), OSPF::NeighborStateDown::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStateDesignatedRouter::processEvent(), and OSPF::HelloHandler::processPacket().
{
    OSPFOptions options;
    OSPFHelloPacket* helloPacket = new OSPFHelloPacket();
    std::vector<IPv4Address> neighbors;
    helloPacket->setRouterID(IPv4Address(parentArea->getRouter()->getRouterID()));
    helloPacket->setAreaID(IPv4Address(parentArea->getAreaID()));
    helloPacket->setAuthenticationType(authenticationType);
    for (int i = 0; i < 8; i++) {
        helloPacket->setAuthentication(i, authenticationKey.bytes[i]);
    }
    if (((interfaceType == POINTTOPOINT) &&
         (interfaceAddressRange.address == OSPF::NULL_IPV4ADDRESS)) ||
        (interfaceType == VIRTUAL))
    {
        helloPacket->setNetworkMask(OSPF::NULL_IPV4ADDRESS);
    } else {
        helloPacket->setNetworkMask(interfaceAddressRange.mask);
    }
    memset(&options, 0, sizeof(OSPFOptions));
    options.E_ExternalRoutingCapability = parentArea->getExternalRoutingCapability();
    helloPacket->setOptions(options);
    helloPacket->setHelloInterval(helloInterval);
    helloPacket->setRouterPriority(routerPriority);
    helloPacket->setRouterDeadInterval(routerDeadInterval);
    helloPacket->setDesignatedRouter(designatedRouter.ipInterfaceAddress);
    helloPacket->setBackupDesignatedRouter(backupDesignatedRouter.ipInterfaceAddress);
    long neighborCount = neighboringRouters.size();
    for (long j = 0; j < neighborCount; j++) {
        if (neighboringRouters[j]->getState() >= OSPF::Neighbor::INIT_STATE) {
            neighbors.push_back(neighboringRouters[j]->getAddress());
        }
    }
    unsigned int initedNeighborCount = neighbors.size();
    helloPacket->setNeighborArraySize(initedNeighborCount);
    for (unsigned int k = 0; k < initedNeighborCount; k++) {
        helloPacket->setNeighbor(k, neighbors[k]);
    }
    helloPacket->setByteLength(OSPF_HEADER_LENGTH + OSPF_HELLO_HEADER_LENGTH + initedNeighborCount*4);
    parentArea->getRouter()->getMessageHandler()->sendPacket(helloPacket, destination, ifIndex, ttl);
}
void OSPF::Interface::sendLSAcknowledgement (OSPFLSAHeader * lsaHeader, IPv4Address destination)
Referenced by OSPF::LinkStateUpdateHandler::processPacket().
{
    OSPFOptions options;
    OSPFLinkStateAcknowledgementPacket* lsAckPacket = new OSPFLinkStateAcknowledgementPacket();
    lsAckPacket->setType(LINKSTATE_ACKNOWLEDGEMENT_PACKET);
    lsAckPacket->setRouterID(IPv4Address(parentArea->getRouter()->getRouterID()));
    lsAckPacket->setAreaID(IPv4Address(parentArea->getAreaID()));
    lsAckPacket->setAuthenticationType(authenticationType);
    for (int i = 0; i < 8; i++) {
        lsAckPacket->setAuthentication(i, authenticationKey.bytes[i]);
    }
    lsAckPacket->setLsaHeadersArraySize(1);
    lsAckPacket->setLsaHeaders(0, *lsaHeader);
    lsAckPacket->setByteLength(OSPF_HEADER_LENGTH + OSPF_LSA_HEADER_LENGTH);
    int ttl = (interfaceType == OSPF::Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
    parentArea->getRouter()->getMessageHandler()->sendPacket(lsAckPacket, destination, ifIndex, ttl);
}
void OSPF::Interface::setAcknowledgementDelay (short delay) [inline]
{ acknowledgementDelay = delay; }
void OSPF::Interface::setAddressRange (IPv4AddressRange range) [inline]
Referenced by OSPF::Area::calculateShortestPathTree().
{ interfaceAddressRange = range; }
void OSPF::Interface::setArea (Area * area) [inline]
Referenced by OSPF::Area::addInterface().
{ parentArea = area; }
void OSPF::Interface::setAreaID (AreaID areaId) [inline]
Referenced by OSPFRouting::loadInterfaceParameters().
{ areaID = areaId; }
void OSPF::Interface::setAuthenticationKey (AuthenticationKeyType key) [inline]
Referenced by OSPFRouting::loadAuthenticationConfig().
{ authenticationKey = key; }
void OSPF::Interface::setAuthenticationType (AuthenticationType type) [inline]
Referenced by OSPFRouting::loadAuthenticationConfig().
{ authenticationType = type; }
void OSPF::Interface::setHelloInterval (short interval) [inline]
Referenced by OSPFRouting::loadInterfaceParameters(), and OSPFRouting::loadVirtualLink().
{ helloInterval = interval; }
void OSPF::Interface::setIfIndex (int index)
Referenced by OSPF::Area::calculateShortestPathTree(), and OSPFRouting::loadInterfaceParameters().
{
    ifIndex = index;
    if (interfaceType == OSPF::Interface::UNKNOWN_TYPE) {
        InterfaceEntry* routingInterface = InterfaceTableAccess().get()->getInterfaceById(ifIndex);
        interfaceAddressRange.address = routingInterface->ipv4Data()->getIPAddress();
        interfaceAddressRange.mask = routingInterface->ipv4Data()->getNetmask();
        mtu = routingInterface->getMTU();
    }
}
void OSPF::Interface::setMTU (unsigned short ifMTU) [inline]
{ mtu = ifMTU; }
void OSPF::Interface::setOutputCost (Metric cost) [inline]
Referenced by OSPF::Area::calculateShortestPathTree(), and OSPFRouting::loadInterfaceParameters().
{ interfaceOutputCost = cost; }
void OSPF::Interface::setPollInterval (short interval) [inline]
Referenced by OSPFRouting::loadInterfaceParameters().
{ pollInterval = interval; }
void OSPF::Interface::setRetransmissionInterval (short interval) [inline]
Referenced by OSPFRouting::loadInterfaceParameters(), and OSPFRouting::loadVirtualLink().
{ retransmissionInterval = interval; }
void OSPF::Interface::setRouterDeadInterval (short interval) [inline]
Referenced by OSPFRouting::loadInterfaceParameters(), and OSPFRouting::loadVirtualLink().
{ routerDeadInterval = interval; }
void OSPF::Interface::setRouterPriority (unsigned char priority) [inline]
Referenced by OSPFRouting::loadInterfaceParameters().
{ routerPriority = priority; }
void OSPF::Interface::setTransitAreaID (AreaID areaId) [inline]
Referenced by OSPFRouting::loadVirtualLink().
{ transitAreaID = areaId; }
void OSPF::Interface::setTransmissionDelay (short delay) [inline]
Referenced by OSPFRouting::loadInterfaceParameters(), and OSPFRouting::loadVirtualLink().
{ interfaceTransmissionDelay = delay; }
void OSPF::Interface::setType (OSPFInterfaceType ifType) [inline]
Referenced by OSPFRouting::loadInterfaceParameters(), and OSPFRouting::loadVirtualLink().
{ interfaceType = ifType; }
Friends And Related Function Documentation
friend class InterfaceState [friend]
Member Data Documentation
short OSPF::Interface::acknowledgementDelay [private]
Referenced by getAcknowledgementDelay(), and setAcknowledgementDelay().
OSPFTimer* OSPF::Interface::acknowledgementTimer [private]
Referenced by getAcknowledgementTimer(), and Interface().
AreaID OSPF::Interface::areaID [private]
Referenced by getAreaID(), and setAreaID().
AuthenticationKeyType OSPF::Interface::authenticationKey [private]
Referenced by getAuthenticationKey(), Interface(), and setAuthenticationKey().
AuthenticationType OSPF::Interface::authenticationType [private]
Referenced by getAuthenticationType(), and setAuthenticationType().
DesignatedRouterID OSPF::Interface::backupDesignatedRouter [private]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), and getBackupDesignatedRouter().
std::map<IPv4Address, std::list<OSPFLSAHeader> > OSPF::Interface::delayedAcknowledgements [private]
DesignatedRouterID OSPF::Interface::designatedRouter [private]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), and getDesignatedRouter().
short OSPF::Interface::helloInterval [private]
Referenced by getHelloInterval(), and setHelloInterval().
OSPFTimer* OSPF::Interface::helloTimer [private]
Referenced by getHelloTimer(), and Interface().
int OSPF::Interface::ifIndex [private]
Referenced by getIfIndex().
IPv4AddressRange OSPF::Interface::interfaceAddressRange [private]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), getAddressRange(), and setAddressRange().
Metric OSPF::Interface::interfaceOutputCost [private]
Referenced by getOutputCost(), and setOutputCost().
short OSPF::Interface::interfaceTransmissionDelay [private]
Referenced by getTransmissionDelay(), and setTransmissionDelay().
OSPFInterfaceType OSPF::Interface::interfaceType [private]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), getType(), and setType().
unsigned short OSPF::Interface::mtu [private]
Referenced by getMTU(), and setMTU().
std::vector<Neighbor*> OSPF::Interface::neighboringRouters [private]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), getNeighbor(), and getNeighborCount().
std::map<IPv4Address, Neighbor*> OSPF::Interface::neighboringRoutersByAddress [private]
std::map<RouterID, Neighbor*> OSPF::Interface::neighboringRoutersByID [private]
Area* OSPF::Interface::parentArea [private]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), getArea(), and setArea().
short OSPF::Interface::pollInterval [private]
Referenced by getPollInterval(), and setPollInterval().
InterfaceState* OSPF::Interface::previousState [private]
Referenced by Interface().
short OSPF::Interface::retransmissionInterval [private]
Referenced by getRetransmissionInterval(), and setRetransmissionInterval().
short OSPF::Interface::routerDeadInterval [private]
Referenced by getRouterDeadInterval(), and setRouterDeadInterval().
unsigned char OSPF::Interface::routerPriority [private]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), getRouterPriority(), and setRouterPriority().
InterfaceState* OSPF::Interface::state [private]
Referenced by Interface().
AreaID OSPF::Interface::transitAreaID [private]
Referenced by getTransitAreaID(), and setTransitAreaID().
OSPFTimer* OSPF::Interface::waitTimer [private]
Referenced by getWaitTimer(), and Interface().
The documentation for this class was generated from the following files:
OSPFInterface.h
OSPFInterface.cc