INET Framework for OMNeT++/OMNEST: IPv6NeighbourCache Class Reference
IPv6NeighbourCache Class Reference
Copyright (C) 2005 Andras Varga Copyright (C) 2005 Wei Yang, Ng.
#include <IPv6NeighbourCache.h>
Classes
class DefaultRouterList
struct Key
Key into neighbour cache.
struct Neighbour
Stores a neighbour (or router) entry.
Public Types
enum ReachabilityState {
INCOMPLETE, REACHABLE, STALE, DELAY,
PROBE
}
Neighbour's reachability state.
typedef std::vector< cMessage * > MsgPtrVector
typedef std::map< Key, Neighbour > NeighbourMap
The std::map underlying the Neighbour Cache data structure.
typedef NeighbourMap::iterator iterator
Public Member Functions
IPv6NeighbourCache (cSimpleModule &neighbourDiscovery)
virtual ~IPv6NeighbourCache ()
virtual Neighbour * lookup (const IPv6Address &addr, int interfaceID)
Returns a neighbour entry, or NULL.
virtual const Key * lookupKeyAddr (Key &key)
Experimental code.
DefaultRouterList & getDefaultRouterList ()
iterator begin ()
For iteration on the internal std::map.
iterator end ()
For iteration on the internal std::map.
virtual Neighbour * addNeighbour (const IPv6Address &addr, int interfaceID)
Creates and initializes a neighbour entry with isRouter=false, state=INCOMPLETE.
virtual Neighbour * addNeighbour (const IPv6Address &addr, int interfaceID, MACAddress macAddress)
Creates and initializes a neighbour entry with isRouter=false, MAC address and state=STALE.
virtual Neighbour * addRouter (const IPv6Address &addr, int interfaceID, MACAddress macAddress, simtime_t expiryTime, bool isHomeAgent=false)
Creates and initializes a router entry (isRouter=isDefaultRouter=true), MAC address and state=STALE.
virtual void remove (const IPv6Address &addr, int interfaceID)
Deletes the given neighbour from the cache.
virtual void invalidateEntriesForInterfaceID (int interfaceID)
Set status of all neighbours on given interface to state PROBE.
virtual void invalidateAllEntries ()
Set status of all neighbours to state PROBE.
virtual void remove (NeighbourMap::iterator it)
Deletes the given neighbour from the cache.
Static Public Member Functions
static const char * stateName (ReachabilityState state)
Returns the name of the given state as string.
Protected Attributes
cSimpleModule & neighbourDiscovery
NeighbourMap neighbourMap
DefaultRouterList defaultRouterList
Detailed Description
Copyright (C) 2005 Andras Varga Copyright (C) 2005 Wei Yang, Ng.
This program is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this program; if not, see <http://www.gnu.org/licenses/>. IPv6 Neighbour Cache (RFC 2461 Neighbor Discovery for IPv6). Used internally by the IPv6NeighbourDiscovery simple module.
This is just a plain container class -- the IPv6NeighbourDiscovery module is free to manipulate the contents of the Neighbour entries as it pleases.
NOTE: IPv6NeighbourCache also stores the Default Router List. A router becomes a default router by calling getDefaultRouterList().add(router) and stops to be a default router after getDefaultRouterList().remove(router) has been called. References to default routers are stored in a circular list to ease round-robin selection.
Member Typedef Documentation
typedef NeighbourMap::iterator IPv6NeighbourCache::iterator
typedef std::vector<cMessage*> IPv6NeighbourCache::MsgPtrVector
typedef std::map<Key,Neighbour> IPv6NeighbourCache::NeighbourMap
The std::map underlying the Neighbour Cache data structure.
Member Enumeration Documentation
enum IPv6NeighbourCache::ReachabilityState
Neighbour's reachability state.
Enumerator:
INCOMPLETE
REACHABLE
STALE
DELAY
PROBE
{INCOMPLETE, REACHABLE, STALE, DELAY, PROBE};
Constructor & Destructor Documentation
IPv6NeighbourCache::IPv6NeighbourCache (cSimpleModule & neighbourDiscovery)
    : neighbourDiscovery(neighbourDiscovery)
{
    WATCH_MAP(neighbourMap);
}
virtual IPv6NeighbourCache::~IPv6NeighbourCache () [inline, virtual]
{}
Member Function Documentation
IPv6NeighbourCache::Neighbour * IPv6NeighbourCache::addNeighbour (const IPv6Address & addr, int interfaceID) [virtual]
Creates and initializes a neighbour entry with isRouter=false, state=INCOMPLETE.
Referenced by IPv6NeighbourDiscovery::processIPv6Datagram(), IPv6NeighbourDiscovery::processNSWithSpecifiedSrcAddr(), and IPv6NeighbourDiscovery::processRAForRouterUpdates().
{
    Key key(addr, interfaceID);
    ASSERT(neighbourMap.find(key) == neighbourMap.end()); // entry must not exist yet
    Neighbour& nbor = neighbourMap[key];
    nbor.nceKey = lookupKeyAddr(key);
    nbor.isRouter = false;
    nbor.isHomeAgent = false;
    nbor.reachabilityState = INCOMPLETE;
    return &nbor;
}
IPv6NeighbourCache::Neighbour * IPv6NeighbourCache::addNeighbour (const IPv6Address & addr, int interfaceID, MACAddress macAddress) [virtual]
Creates and initializes a neighbour entry with isRouter=false, MAC address and state=STALE.
{
    Key key(addr, interfaceID);
    ASSERT(neighbourMap.find(key) == neighbourMap.end()); // entry must not exist yet
    Neighbour& nbor = neighbourMap[key];
    nbor.nceKey = lookupKeyAddr(key);
    nbor.macAddress = macAddress;
    nbor.isRouter = false;
    nbor.isHomeAgent = false;
    nbor.reachabilityState = STALE;
    return &nbor;
}
IPv6NeighbourCache::Neighbour * IPv6NeighbourCache::addRouter (const IPv6Address & addr, int interfaceID, MACAddress macAddress, simtime_t expiryTime, bool isHomeAgent = false) [virtual]
Creates and initializes a router entry (isRouter=isDefaultRouter=true), MAC address and state=STALE.
Update by CB: Added an optional parameter which is false by default. Specifies whether a router is also a home agent.
Referenced by IPv6NeighbourDiscovery::processRAForRouterUpdates().
{
    Key key(addr, interfaceID);
    ASSERT(neighbourMap.find(key) == neighbourMap.end()); // entry must not exist yet
    Neighbour& nbor = neighbourMap[key];
    nbor.nceKey = lookupKeyAddr(key);
    nbor.macAddress = macAddress;
    nbor.isRouter = true;
    nbor.isHomeAgent = isHomeAgent;
    nbor.reachabilityState = STALE;
    nbor.routerExpiryTime = expiryTime;
    defaultRouterList.add(nbor);
    return &nbor;
}
iterator IPv6NeighbourCache::begin () [inline]
For iteration on the internal std::map.
{return neighbourMap.begin();}
iterator IPv6NeighbourCache::end () [inline]
For iteration on the internal std::map.
{return neighbourMap.end();}
DefaultRouterList& IPv6NeighbourCache::getDefaultRouterList () [inline]
Referenced by IPv6NeighbourDiscovery::processNAForIncompleteNCEState(), IPv6NeighbourDiscovery::processNAForOtherNCEStates(), and IPv6NeighbourDiscovery::selectDefaultRouter().
{ return defaultRouterList; }
void IPv6NeighbourCache::invalidateAllEntries () [virtual]
Set status of all neighbours to state PROBE.
{
    while (!neighbourMap.empty())
    {
        NeighbourMap::iterator it = neighbourMap.begin();
        remove(it);
    }
    defaultRouterList.clear();
    /*
    int size = neighbourMap.size();
    EV << "size: " << size << endl;
    for (NeighbourMap::iterator it = neighbourMap.begin(); it != neighbourMap.end(); it++)
    {
        it->second.reachabilityState = PROBE; // we make sure this neighbour is not used anymore in the future, unless reachability can be confirmed
    }
    */
}
void IPv6NeighbourCache::invalidateEntriesForInterfaceID (int interfaceID) [virtual]
Set status of all neighbours on given interface to state PROBE.
{
    for (NeighbourMap::iterator it = neighbourMap.begin(); it != neighbourMap.end(); it++)
    {
        if (it->first.interfaceID == interfaceID)
        {
            it->second.reachabilityState = PROBE; // we make sure this neighbour is not used anymore in the future, unless reachability can be confirmed
            neighbourDiscovery.cancelAndDelete(it->second.nudTimeoutEvent); // 20.9.07 - CB
            it->second.nudTimeoutEvent = NULL;
        }
    }
}
IPv6NeighbourCache::Neighbour * IPv6NeighbourCache::lookup (const IPv6Address & addr, int interfaceID) [virtual]
Returns a neighbour entry, or NULL.
Referenced by IPv6NeighbourDiscovery::processIPv6Datagram(), IPv6NeighbourDiscovery::processNAPacket(), IPv6NeighbourDiscovery::processNSWithSpecifiedSrcAddr(), IPv6NeighbourDiscovery::processRAForRouterUpdates(), IPv6NeighbourDiscovery::reachabilityConfirmed(), and IPv6NeighbourDiscovery::resolveNeighbour().
{
    Key key(addr, interfaceID);
    NeighbourMap::iterator i = neighbourMap.find(key);
    return i==neighbourMap.end() ? NULL : &(i->second);
}
const IPv6NeighbourCache::Key * IPv6NeighbourCache::lookupKeyAddr (Key & key) [virtual]
Experimental code.
Referenced by addNeighbour(), and addRouter().
{
    NeighbourMap::iterator i = neighbourMap.find(key);
    return &(i->first);
}
void IPv6NeighbourCache::remove (const IPv6Address & addr, int interfaceID) [virtual]
Deletes the given neighbour from the cache.
Referenced by IPv6NeighbourDiscovery::dropQueuedPacketsAwaitingAR(), IPv6NeighbourDiscovery::processNUDTimeout(), IPv6NeighbourDiscovery::selectDefaultRouter(), and IPv6NeighbourDiscovery::timeoutDefaultRouter().
{
    Key key(addr, interfaceID);
    NeighbourMap::iterator it = neighbourMap.find(key);
    ASSERT(it!=neighbourMap.end()); // entry must exist
    neighbourDiscovery.cancelAndDelete(it->second.nudTimeoutEvent);
    it->second.nudTimeoutEvent = NULL;
    if (it->second.isDefaultRouter())
        defaultRouterList.remove(it->second);
    neighbourMap.erase(it);
}
void IPv6NeighbourCache::remove (NeighbourMap::iterator it) [virtual]
Deletes the given neighbour from the cache.
{
    //delete it->second.nudTimeoutEvent;
    neighbourDiscovery.cancelAndDelete(it->second.nudTimeoutEvent); // 20.9.07 - CB
    it->second.nudTimeoutEvent = NULL;
    if (it->second.isDefaultRouter())
        defaultRouterList.remove(it->second);
    neighbourMap.erase(it);
}
const char * IPv6NeighbourCache::stateName (ReachabilityState state) [static]
Returns the name of the given state as string.
Referenced by operator<<().
{
    switch (state)
    {
        case INCOMPLETE: return "INCOMPLETE";
        case REACHABLE:  return "REACHABLE";
        case STALE:      return "STALE";
        case DELAY:      return "DELAY";
        case PROBE:      return "PROBE";
        default:         return "???";
    }
}
Member Data Documentation
DefaultRouterList IPv6NeighbourCache::defaultRouterList [protected]
Referenced by addRouter(), invalidateAllEntries(), and remove().
cSimpleModule& IPv6NeighbourCache::neighbourDiscovery [protected]
Referenced by invalidateEntriesForInterfaceID(), and remove().
NeighbourMap IPv6NeighbourCache::neighbourMap [protected]
Referenced by addNeighbour(), addRouter(), invalidateAllEntries(), invalidateEntriesForInterfaceID(), IPv6NeighbourCache(), lookup(), lookupKeyAddr(), and remove().
The documentation for this class was generated from the following files:
IPv6NeighbourCache.h
IPv6NeighbourCache.cc