INET Framework for OMNeT++/OMNEST: RSVPResvMsg Class Reference
RSVPResvMsg Class Reference
RSVP RESV message.
#include <RSVPResvMsg.h>
Public Member Functions
RSVPResvMsg (const char *name=NULL, int kind=RESV_MESSAGE)
RSVPResvMsg (const RSVPResvMsg &other)
RSVPResvMsg & operator= (const RSVPResvMsg &other)
virtual RSVPResvMsg * dup () const
IPv4Address getNHOP ()
IPv4Address getLIH ()
Detailed Description
RSVP RESV message.
This class adds convenience get() and set() methods to the generated base class, but no extra data.
Constructor & Destructor Documentation
RSVPResvMsg::RSVPResvMsg (const char * name = NULL, int kind = RESV_MESSAGE) [inline]
Referenced by dup().
: RSVPResvMsg_Base(name, kind) {}
RSVPResvMsg::RSVPResvMsg (const RSVPResvMsg & other) [inline]
: RSVPResvMsg_Base(other) {}
Member Function Documentation
virtual RSVPResvMsg* RSVPResvMsg::dup () const [inline, virtual]
Reimplemented from RSVPResvMsg_Base.
{return new RSVPResvMsg(*this);}
IPv4Address RSVPResvMsg::getLIH () [inline]
Referenced by RSVP::createRSB(), and RSVP::processResvMsg().
{return getHop().Logical_Interface_Handle;}
IPv4Address RSVPResvMsg::getNHOP () [inline]
Referenced by RSVP::createRSB(), and RSVP::processResvMsg().
{return getHop().Next_Hop_Address;}
RSVPResvMsg& RSVPResvMsg::operator= (const RSVPResvMsg & other) [inline]
{RSVPResvMsg_Base::operator=(other); return *this;}
The documentation for this class was generated from the following file:
RSVPResvMsg.h