INET Framework for OMNeT++/OMNEST: TCPSegment Class Reference
TCPSegment Class Reference
Represents a TCP segment.
#include <TCPSegment.h>
Public Member Functions
TCPSegment (const char *name=NULL, int kind=0)
TCPSegment (const TCPSegment &other)
~TCPSegment ()
TCPSegment & operator= (const TCPSegment &other)
virtual TCPSegment * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setPayloadArraySize (unsigned int size)
Generated but unused method, should not be called.
virtual void setPayload (unsigned int k, const TCPPayloadMessage &payload_var)
Generated but unused method, should not be called.
virtual unsigned int getPayloadArraySize () const
Returns the number of payload messages in this TCP segment.
virtual TCPPayloadMessage & getPayload (unsigned int k)
Returns the kth payload message in this TCP segment.
virtual void addPayloadMessage (cPacket *msg, uint32 endSequenceNo)
Adds a message object to the TCP segment.
virtual cPacket * removeFirstPayloadMessage (uint32 &outEndSequenceNo)
Removes and returns the first message object in this TCP segment.
virtual void truncateSegment (uint32 firstSeqNo, uint32 endSeqNo)
Truncate segment.
virtual unsigned short getOptionsArrayLength ()
Calculate Length of Options Array in bytes.
Protected Types
typedef std::list
< TCPPayloadMessage > PayloadList
Protected Member Functions
virtual void truncateData (unsigned int truncleft, unsigned int truncright)
Truncate segment data.
Protected Attributes
PayloadList payloadList
Private Member Functions
void copy (const TCPSegment &other)
void clean ()
Detailed Description
Represents a TCP segment.
More info in the TCPSegment.msg file (and the documentation generated from it).
Member Typedef Documentation
typedef std::list<TCPPayloadMessage> TCPSegment::PayloadList [protected]
Constructor & Destructor Documentation
TCPSegment::TCPSegment (const char * name = NULL, int kind = 0) [inline]
: TCPSegment_Base(name, kind) {}
TCPSegment::TCPSegment (const TCPSegment & other) [inline]
: TCPSegment_Base(other) { copy(other); }
TCPSegment::~TCPSegment ()
{
    clean();
}
Member Function Documentation
void TCPSegment::addPayloadMessage (cPacket * msg, uint32 endSequenceNo) [virtual]
Adds a message object to the TCP segment.
The sequence number + 1 of the last byte of the message should be passed as 2nd argument
Referenced by copy(), TCPMsgBasedSendQueue::createSegmentWithBytes(), and TcpLwipMsgBasedSendQueue::createSegmentWithBytes().
{
    take(msg);
    TCPPayloadMessage payload;
    payload.endSequenceNo = endSequenceNo;
    payload.msg = msg;
    payloadList.push_back(payload);
}
void TCPSegment::clean () [private]
Referenced by operator=(), and ~TCPSegment().
{
    while (!payloadList.empty())
    {
        cPacket *msg = payloadList.front().msg;
        payloadList.pop_front();
        dropAndDelete(msg);
    }
}
void TCPSegment::copy (const TCPSegment & other) [private]
Referenced by operator=().
{
    for (PayloadList::const_iterator i = other.payloadList.begin(); i != other.payloadList.end(); ++i)
        addPayloadMessage(i->msg->dup(), i->endSequenceNo);
}
virtual TCPSegment* TCPSegment::dup () const [inline, virtual]
Reimplemented from TCPSegment_Base.
{return new TCPSegment(*this);}
unsigned short TCPSegment::getOptionsArrayLength () [virtual]
Calculate Length of Options Array in bytes.
Referenced by TCPConnection::addSacks(), and TCPConnection::writeHeaderOptions().
{
    unsigned short usedLength = 0;
    for (uint i = 0; i < getOptionsArraySize(); i++)
        usedLength += getOptions(i).getLength();
    return usedLength;
}
TCPPayloadMessage & TCPSegment::getPayload (unsigned int k) [virtual]
Returns the kth payload message in this TCP segment.
Implements TCPSegment_Base.
{
    PayloadList::iterator i = payloadList.begin();
    while (k>0 && i!=payloadList.end())
        (++i, --k);
    return *i;
}
unsigned int TCPSegment::getPayloadArraySize () const [virtual]
Returns the number of payload messages in this TCP segment.
Implements TCPSegment_Base.
Referenced by TCPMsgBasedSendQueue::createSegmentWithBytes(), and TcpLwipMsgBasedSendQueue::createSegmentWithBytes().
{
    return payloadList.size();
}
TCPSegment & TCPSegment::operator= (const TCPSegment & other)
{
    if (this == &other) return *this;
    clean();
    TCPSegment_Base::operator=(other);
    copy(other);
    return *this;
}
void TCPSegment::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TCPSegment_Base.
{
    TCPSegment_Base::parsimPack(b);
    doPacking(b, payloadList);
}
void TCPSegment::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TCPSegment_Base.
{
    TCPSegment_Base::parsimUnpack(b);
    doUnpacking(b, payloadList);
}
cPacket * TCPSegment::removeFirstPayloadMessage (uint32 & outEndSequenceNo) [virtual]
Removes and returns the first message object in this TCP segment.
It also returns the sequence number + 1 of its last octet in outEndSequenceNo.
Referenced by TCPMsgBasedRcvQueue::insertBytesFromSegment(), and TcpLwipMsgBasedReceiveQueue::notifyAboutIncomingSegmentProcessing().
{
    if (payloadList.empty())
        return NULL;
    cPacket *msg = payloadList.front().msg;
    endSequenceNo = payloadList.front().endSequenceNo;
    payloadList.pop_front();
    drop(msg);
    return msg;
}
void TCPSegment::setPayload (unsigned int k, const TCPPayloadMessage & payload_var) [virtual]
Generated but unused method, should not be called.
Implements TCPSegment_Base.
{
    throw cRuntimeError(this, "setPayload() not supported, use addPayloadMessage()");
}
void TCPSegment::setPayloadArraySize (unsigned int size) [virtual]
Generated but unused method, should not be called.
Implements TCPSegment_Base.
{
    throw cRuntimeError(this, "setPayloadArraySize() not supported, use addPayloadMessage()");
}
void TCPSegment::truncateData (unsigned int truncleft, unsigned int truncright) [protected, virtual]
Truncate segment data.
Called from truncateSegment().
Parameters:
truncleft,: number of bytes for truncate from begin of data
truncright,: number of bytes for truncate from end of data
Referenced by truncateSegment().
{
    ASSERT(payloadLength_var >= truncleft + truncright);
    if (0 != byteArray_var.getDataArraySize())
        byteArray_var.truncateData(truncleft, truncright);
    while (!payloadList.empty() && (payloadList.front().endSequenceNo - sequenceNo_var) <= truncleft)
    {
        cPacket *msg = payloadList.front().msg;
        payloadList.pop_front();
        dropAndDelete(msg);
    }
    sequenceNo_var += truncleft;
    payloadLength_var -= truncleft + truncright;
    // truncate payload data correctly
    while (!payloadList.empty() && (payloadList.back().endSequenceNo - sequenceNo_var) > payloadLength_var)
    {
        cPacket *msg = payloadList.back().msg;
        payloadList.pop_back();
        dropAndDelete(msg);
    }
}
void TCPSegment::truncateSegment (uint32 firstSeqNo, uint32 endSeqNo) [virtual]
Truncate segment.
Parameters:
firstSeqNo,: sequence no of new first byte
endSeqNo,: sequence no of new last byte + 1
Referenced by TCPConnection::processSegment1stThru8th().
{
    ASSERT(payloadLength_var > 0);
    // must have common part:
#ifndef NDEBUG
    if (!(seqLess(sequenceNo_var, endSeqNo) && seqLess(firstSeqNo, sequenceNo_var + payloadLength_var)))
    {
        throw cRuntimeError(this, "truncateSegment(%u,%u) called on [%u, %u) segment\n",
                firstSeqNo, endSeqNo, sequenceNo_var, sequenceNo_var + payloadLength_var);
    }
#endif
    unsigned int truncleft = 0;
    unsigned int truncright = 0;
    if (seqLess(sequenceNo_var, firstSeqNo))
    {
        truncleft = firstSeqNo - sequenceNo_var;
    }
    if (seqGreater(sequenceNo_var + payloadLength_var, endSeqNo))
    {
        truncright = sequenceNo_var + payloadLength_var - endSeqNo;
    }
    truncateData(truncleft, truncright);
}
Member Data Documentation
PayloadList TCPSegment::payloadList [protected]
Referenced by addPayloadMessage(), clean(), copy(), getPayload(), getPayloadArraySize(), parsimPack(), parsimUnpack(), removeFirstPayloadMessage(), and truncateData().
The documentation for this class was generated from the following files:
TCPSegment.h
TCPSegment.cc