INET Framework for OMNeT++/OMNEST: OSPF::NeighborState Class Reference
OSPF::NeighborState Class Reference
#include <OSPFNeighborState.h>
Public Member Functions
virtual ~NeighborState ()
virtual void processEvent (Neighbor *neighbor, Neighbor::NeighborEventType event)=0
virtual Neighbor::NeighborStateType getState () const =0
Protected Member Functions
void changeState (Neighbor *neighbor, NeighborState *newState, NeighborState *currentState)
Constructor & Destructor Documentation
virtual OSPF::NeighborState::~NeighborState () [inline, virtual]
{}
Member Function Documentation
void OSPF::NeighborState::changeState (OSPF::Neighbor * neighbor, OSPF::NeighborState * newState, OSPF::NeighborState * currentState) [protected]
Referenced by OSPF::NeighborStateAttempt::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateExchange::processEvent(), and OSPF::NeighborStateDown::processEvent().
{
    OSPF::Neighbor::NeighborStateType oldState = currentState->getState();
    OSPF::Neighbor::NeighborStateType nextState = newState->getState();
    bool shouldRebuildRoutingTable = false;
    neighbor->changeState(newState, currentState);
    if ((oldState == OSPF::Neighbor::FULL_STATE) || (nextState == OSPF::Neighbor::FULL_STATE)) {
        OSPF::RouterID routerID = neighbor->getInterface()->getArea()->getRouter()->getRouterID();
        OSPF::RouterLSA* routerLSA = neighbor->getInterface()->getArea()->findRouterLSA(routerID);
        if (routerLSA != NULL) {
            long sequenceNumber = routerLSA->getHeader().getLsSequenceNumber();
            if (sequenceNumber == MAX_SEQUENCE_NUMBER) {
                routerLSA->getHeader().setLsAge(MAX_AGE);
                neighbor->getInterface()->getArea()->floodLSA(routerLSA);
                routerLSA->incrementInstallTime();
            } else {
                OSPF::RouterLSA* newLSA = neighbor->getInterface()->getArea()->originateRouterLSA();
                newLSA->getHeader().setLsSequenceNumber(sequenceNumber + 1);
                shouldRebuildRoutingTable |= routerLSA->update(newLSA);
                delete newLSA;
                neighbor->getInterface()->getArea()->floodLSA(routerLSA);
            }
        }
        if (neighbor->getInterface()->getState() == OSPF::Interface::DESIGNATED_ROUTER_STATE) {
            OSPF::NetworkLSA* networkLSA = neighbor->getInterface()->getArea()->findNetworkLSA(neighbor->getInterface()->getAddressRange().address);
            if (networkLSA != NULL) {
                long sequenceNumber = networkLSA->getHeader().getLsSequenceNumber();
                if (sequenceNumber == MAX_SEQUENCE_NUMBER) {
                    networkLSA->getHeader().setLsAge(MAX_AGE);
                    neighbor->getInterface()->getArea()->floodLSA(networkLSA);
                    networkLSA->incrementInstallTime();
                } else {
                    OSPF::NetworkLSA* newLSA = neighbor->getInterface()->getArea()->originateNetworkLSA(neighbor->getInterface());
                    if (newLSA != NULL) {
                        newLSA->getHeader().setLsSequenceNumber(sequenceNumber + 1);
                        shouldRebuildRoutingTable |= networkLSA->update(newLSA);
                        delete newLSA;
                    } else {    // no neighbors on the network -> old NetworkLSA must be flushed
                        networkLSA->getHeader().setLsAge(MAX_AGE);
                        networkLSA->incrementInstallTime();
                    }
                    neighbor->getInterface()->getArea()->floodLSA(networkLSA);
                }
            }
        }
    }
    if (shouldRebuildRoutingTable) {
        neighbor->getInterface()->getArea()->getRouter()->rebuildRoutingTable();
    }
}
virtual Neighbor::NeighborStateType OSPF::NeighborState::getState () const [pure virtual]
Implemented in OSPF::NeighborStateAttempt, OSPF::NeighborStateDown, OSPF::NeighborStateExchange, OSPF::NeighborStateExchangeStart, OSPF::NeighborStateFull, OSPF::NeighborStateInit, OSPF::NeighborStateLoading, and OSPF::NeighborStateTwoWay.
Referenced by changeState().
virtual void OSPF::NeighborState::processEvent (Neighbor * neighbor, Neighbor::NeighborEventType event) [pure virtual]
Implemented in OSPF::NeighborStateAttempt, OSPF::NeighborStateDown, OSPF::NeighborStateExchange, OSPF::NeighborStateExchangeStart, OSPF::NeighborStateFull, OSPF::NeighborStateInit, OSPF::NeighborStateLoading, and OSPF::NeighborStateTwoWay.
The documentation for this class was generated from the following files:
OSPFNeighborState.h
OSPFNeighborState.cc