INET Framework for OMNeT++/OMNEST: IRadioModel Class Reference
IRadioModel Class Reference
Abstract class to encapsulate the calculation of received power of a radio transmission.
#include <IRadioModel.h>
Public Member Functions
virtual void initializeFrom (cModule *radioModule)=0
Allows parameters to be read from the module parameters of a module that contains this object.
virtual ~IRadioModel ()
Virtual destructor.
virtual double calculateDuration (AirFrame *)=0
Should be defined to calculate the duration of the AirFrame.
virtual bool isReceivedCorrectly (AirFrame *airframe, const SnrList &receivedList)=0
Should be defined to calculate whether the frame has been received correctly.
virtual bool haveTestFrame ()=0
virtual double calculateDurationTestFrame (AirFrame *airframe)=0
virtual double getTestFrameError (double snirMin, double bitrate)=0
virtual int getTestFrameSize ()=0
Detailed Description
Abstract class to encapsulate the calculation of received power of a radio transmission.
The calculation may include the effects of path loss, antenna gain, etc.
Constructor & Destructor Documentation
virtual IRadioModel::~IRadioModel () [inline, virtual]
Virtual destructor.
{}
Member Function Documentation
virtual double IRadioModel::calculateDuration (AirFrame *) [pure virtual]
Should be defined to calculate the duration of the AirFrame.
Usually the duration is just the frame length divided by the bitrate. However, in some cases, notably IEEE 802.11, the header has a different modulation (and thus a different bitrate) than the rest of the message.
Implemented in Ieee80211RadioModel, and GenericRadioModel.
Referenced by Radio::encapsulatePacket().
virtual double IRadioModel::calculateDurationTestFrame (AirFrame * airframe) [pure virtual]
Implemented in Ieee80211RadioModel, and GenericRadioModel.
Referenced by Radio::sendUp().
virtual double IRadioModel::getTestFrameError (double snirMin, double bitrate) [pure virtual]
Implemented in Ieee80211RadioModel, and GenericRadioModel.
Referenced by Radio::sendUp().
virtual int IRadioModel::getTestFrameSize () [pure virtual]
Implemented in Ieee80211RadioModel, and GenericRadioModel.
Referenced by Radio::sendUp().
virtual bool IRadioModel::haveTestFrame () [pure virtual]
Implemented in Ieee80211RadioModel, and GenericRadioModel.
Referenced by Radio::sendUp().
virtual void IRadioModel::initializeFrom (cModule * radioModule) [pure virtual]
Allows parameters to be read from the module parameters of a module that contains this object.
Implemented in Ieee80211RadioModel, and GenericRadioModel.
Referenced by Radio::initialize().
virtual bool IRadioModel::isReceivedCorrectly (AirFrame * airframe, const SnrList & receivedList) [pure virtual]
Should be defined to calculate whether the frame has been received correctly.
Input is the signal-noise ratio over the duration of the frame. The calculation may take into account the modulation scheme, possible error correction code, etc.
Implemented in Ieee80211RadioModel, and GenericRadioModel.
Referenced by Radio::handleLowerMsgEnd().
The documentation for this class was generated from the following file:
IRadioModel.h