INET Framework for OMNeT++/OMNEST: UDPSocket Class Reference
UDPSocket Class Reference
UDPSocket is a convenience class, to make it easier to send and receive UDP packets from your application models.
#include <UDPSocket.h>
Public Member Functions
UDPSocket ()
Constructor.
~UDPSocket ()
Destructor.
int getSocketId () const
Returns the internal socket Id.
Opening and closing connections, sending data
void setOutputGate (cGate *toUdp)
Sets the gate on which to send to UDP.
void bind (int localPort)
Bind the socket to a local port number.
void bind (IPvXAddress localAddr, int localPort)
Bind the socket to a local port number and IP address (useful with multi-homing or multicast addresses).
void connect (IPvXAddress remoteAddr, int remotePort)
Connects to a remote UDP socket.
void setTimeToLive (int ttl)
Set the TTL (IPv6: Hop Limit) field on sent packets.
void setTypeOfService (unsigned char tos)
Sets the IPv4 Type of Service / IPv6 Traffic Class fields of packets sent from the UDP socket.
void setBroadcast (bool broadcast)
Set the Broadcast option on the UDP socket.
void setMulticastLoop (bool value)
The boolean value specifies whether sent multicast packets should be looped back to the local sockets (like the Unix IP_MULTICAST_LOOP socket option).
void setMulticastOutputInterface (int interfaceId)
Set the output interface for sending multicast packets (like the Unix IP_MULTICAST_IF socket option).
void joinMulticastGroup (const IPvXAddress &multicastAddr, int interfaceId=-1)
Adds the socket to the given multicast group, that is, UDP packets arriving to the given multicast address will be passed up to the socket.
void joinLocalMulticastGroups ()
Joins the socket to each multicast group that are registered with any of the interfaces.
void leaveMulticastGroup (const IPvXAddress &multicastAddr)
Causes the socket to leave the given multicast group, i.e.
void leaveLocalMulticastGroups ()
Causes the socket to leave each multicast groups that are registered with any of the interfaces.
void sendTo (cPacket *msg, IPvXAddress destAddr, int destPort)
Sends a data packet to the given address and port.
void sendTo (cPacket *msg, IPvXAddress destAddr, int destPort, int outInterface)
Sends a data packet to the given address and port using the provided interface.
void send (cPacket *msg)
Sends a data packet to the address and port specified previously in a connect() call.
void close ()
Unbinds the socket.
Static Public Member Functions
static int generateSocketId ()
Generates a new socket id.
Protected Member Functions
void sendToUDP (cMessage *msg)
Protected Attributes
int sockId
cGate * gateToUdp
Handling of messages arriving from UDP
bool belongsToSocket (cMessage *msg)
Returns true if the message belongs to this socket instance (message has a UDPControlInfo as getControlInfo(), and the sockId in it matches that of the socket.)
static bool belongsToAnyUDPSocket (cMessage *msg)
Returns true if the message belongs to any UDPSocket instance.
static std::string getReceivedPacketInfo (cPacket *pk)
Utility function: returns a line of information about a packet received via UDP.
Detailed Description
UDPSocket is a convenience class, to make it easier to send and receive UDP packets from your application models.
You'd have one (or more) UDPSocket object(s) in your application simple module class, and call its member functions (bind(), connect(), sendTo(), etc.) to create and configure a socket, and to send datagrams.
UDPSocket chooses and remembers the sockId for you, assembles and sends command packets such as UDP_C_BIND to UDP, and can also help you deal with packets and notification messages arriving from UDP.
Here is a code fragment that creates an UDP socket and sends a 1K packet over it (the code can be placed in your handleMessage() or activity()):
   UDPSocket socket;
   socket.setOutputGate(gate("udpOut"));
   socket.connect(IPvXAddress("10.0.0.2"), 2000);
   cPacket *pk = new cPacket("dgram");
   pk->setByteLength(1024);
   socket.send(pk);
   socket.close();
Processing messages sent up by the UDP module is relatively straightforward. You only need to distinguish between data packets and error notifications, by checking the message kind (should be either UDP_I_DATA or UDP_I_ERROR), and casting the control info to UDPDataIndication or UDPErrorIndication. USPSocket provides some help for this with the belongsToSocket() and belongsToAnyUDPSocket() methods.
Constructor & Destructor Documentation
UDPSocket::UDPSocket ()
Constructor.
The getSocketId() method returns a valid Id right after constructor call.
{
    // don't allow user-specified sockIds because they may conflict with
    // automatically assigned ones.
    sockId = generateSocketId();
    gateToUdp = NULL;
}
UDPSocket::~UDPSocket () [inline]
Destructor.
{}
Member Function Documentation
bool UDPSocket::belongsToAnyUDPSocket (cMessage * msg) [static]
Returns true if the message belongs to any UDPSocket instance.
(This basically checks if the message has an UDPControlInfo attached to it as getControlInfo().)
{
    return dynamic_cast<UDPControlInfo *>(msg->getControlInfo());
}
bool UDPSocket::belongsToSocket (cMessage * msg)
Returns true if the message belongs to this socket instance (message has a UDPControlInfo as getControlInfo(), and the sockId in it matches that of the socket.)
{
    return dynamic_cast<UDPControlInfo *>(msg->getControlInfo()) &&
           ((UDPControlInfo *)(msg->getControlInfo()))->getSockId()==sockId;
}
void UDPSocket::bind (int localPort)
Bind the socket to a local port number.
Use port=0 for ephemeral port.
Referenced by SCTP::bindPortForUDP(), RTCP::createSocket(), RTP::createSocket(), UDPEchoApp::initialize(), UDPSink::initialize(), VoIPSourceApp::initialize(), VoIPSinkApp::initialize(), UDPBasicApp::initialize(), DHCPServer::initialize(), DHCPClient::initialize(), UDPVideoStreamSvr::initialize(), UDPBasicBurst::initialize(), LDP::initialize(), UDPVideoStreamCli::requestStream(), and TraCIDemo::setupLowerLayer().
{
    bind(IPvXAddress(), localPort);
}
void UDPSocket::bind (IPvXAddress localAddr, int localPort)
Bind the socket to a local port number and IP address (useful with multi-homing or multicast addresses).
Use port=0 for an ephemeral port.
{
    if (localPort<-1 || localPort>65535)  // -1: ephemeral port
        throw cRuntimeError("UDPSocket::bind(): invalid port number %d", localPort);
    UDPBindCommand *ctrl = new UDPBindCommand();
    ctrl->setSockId(sockId);
    ctrl->setLocalAddr(localAddr);
    ctrl->setLocalPort(localPort);
    cMessage *msg = new cMessage("BIND", UDP_C_BIND);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::close ()
Unbinds the socket.
Once closed, a closed socket may be bound to another (or the same) port, and reused.
{
    cMessage *msg = new cMessage("CLOSE", UDP_C_CLOSE);
    UDPCloseCommand *ctrl = new UDPCloseCommand();
    ctrl->setSockId(sockId);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::connect (IPvXAddress remoteAddr, int remotePort)
Connects to a remote UDP socket.
This has two effects: (1) this socket will only receive packets from specified address/port, and (2) you can use send() (as opposed to sendTo()) to send packets.
{
    if (addr.isUnspecified())
        throw cRuntimeError("UDPSocket::connect(): unspecified remote address");
    if (port<=0 || port>65535)
        throw cRuntimeError("UDPSocket::connect(): invalid remote port number %d", port);
    UDPConnectCommand *ctrl = new UDPConnectCommand();
    ctrl->setSockId(sockId);
    ctrl->setRemoteAddr(addr);
    ctrl->setRemotePort(port);
    cMessage *msg = new cMessage("CONNECT", UDP_C_CONNECT);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
int UDPSocket::generateSocketId () [static]
Generates a new socket id.
Referenced by UDPSocket().
{
    return ev.getUniqueNumber();
}
std::string UDPSocket::getReceivedPacketInfo (cPacket * pk) [static]
Utility function: returns a line of information about a packet received via UDP.
Referenced by UDPSink::processPacket(), UDPBasicApp::processPacket(), UDPBasicBurst::processPacket(), and UDPVideoStreamCli::receiveStream().
{
    UDPDataIndication *ctrl = check_and_cast<UDPDataIndication *>(pk->getControlInfo());
    IPvXAddress srcAddr = ctrl->getSrcAddr();
    IPvXAddress destAddr = ctrl->getDestAddr();
    int srcPort = ctrl->getSrcPort();
    int destPort = ctrl->getDestPort();
    int interfaceID = ctrl->getInterfaceId();
    int ttl = ctrl->getTtl();
    int tos = ctrl->getTypeOfService();
    std::stringstream os;
    os << pk << " (" << pk->getByteLength() << " bytes) ";
    os << srcAddr << ":" << srcPort << " --> " << destAddr << ":" << destPort;
    os << " TTL=" << ttl << " ToS=" << tos << " on ifID=" << interfaceID;
    return os.str();
}
int UDPSocket::getSocketId () const [inline]
Returns the internal socket Id.
{return sockId;}
void UDPSocket::joinLocalMulticastGroups ()
Joins the socket to each multicast group that are registered with any of the interfaces.
Referenced by RTCP::createSocket(), RTP::createSocket(), UDPEchoApp::initialize(), UDPSink::initialize(), UDPBasicApp::setSocketOptions(), and TraCIDemo::setupLowerLayer().
{
    IInterfaceTable *ift = InterfaceTableAccess().get();
    unsigned int numOfAddresses = 0;
    for (int i = 0; i < ift->getNumInterfaces(); ++i)
    {
        InterfaceEntry *ie = ift->getInterface(i);
#ifdef WITH_IPv4
        if (ie->ipv4Data())
            numOfAddresses += ie->ipv4Data()->getJoinedMulticastGroups().size();
#endif
#ifdef WITH_IPv6
        // TODO
#endif
    }
    if (numOfAddresses > 0)
    {
        UDPJoinMulticastGroupsCommand *ctrl = new UDPJoinMulticastGroupsCommand();
        ctrl->setSockId(sockId);
        ctrl->setMulticastAddrArraySize(numOfAddresses);
        ctrl->setInterfaceIdArraySize(numOfAddresses);
        unsigned int k = 0;
        for (int i=0; i<ift->getNumInterfaces(); ++i)
        {
            InterfaceEntry *ie = ift->getInterface(i);
            int interfaceId = ie->getInterfaceId();
#ifdef WITH_IPv4
            if (ie->ipv4Data())
            {
                const IPv4InterfaceData::IPv4AddressVector &addresses = ie->ipv4Data()->getJoinedMulticastGroups();
                for (unsigned int j = 0; j < addresses.size(); ++j, ++k)
                {
                    ctrl->setMulticastAddr(k, addresses[j]);
                    ctrl->setInterfaceId(k, interfaceId);
                }
            }
#endif
#ifdef WITH_IPv6
            // TODO
#endif
        }
        cMessage *msg = new cMessage("JoinMulticastGroups", UDP_C_SETOPTION);
        msg->setControlInfo(ctrl);
        sendToUDP(msg);
    }
}
void UDPSocket::joinMulticastGroup (const IPvXAddress & multicastAddr, int interfaceId = -1)
Adds the socket to the given multicast group, that is, UDP packets arriving to the given multicast address will be passed up to the socket.
One can also optionally specify the output interface for packets sent to that address.
{
    cMessage *msg = new cMessage("JoinMulticastGroups", UDP_C_SETOPTION);
    UDPJoinMulticastGroupsCommand *ctrl = new UDPJoinMulticastGroupsCommand();
    ctrl->setSockId(sockId);
    ctrl->setMulticastAddrArraySize(1);
    ctrl->setMulticastAddr(0, multicastAddr);
    ctrl->setInterfaceIdArraySize(1);
    ctrl->setInterfaceId(0, interfaceId);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::leaveLocalMulticastGroups ()
Causes the socket to leave each multicast groups that are registered with any of the interfaces.
{
    IInterfaceTable *ift = InterfaceTableAccess().get();
    unsigned int numOfAddresses = 0;
    for (int i = 0; i < ift->getNumInterfaces(); ++i)
    {
        InterfaceEntry *ie = ift->getInterface(i);
#ifdef WITH_IPv4
        if (ie->ipv4Data())
            numOfAddresses += ie->ipv4Data()->getJoinedMulticastGroups().size();
#endif
#ifdef WITH_IPv6
        // TODO
#endif
    }
    if (numOfAddresses > 0)
    {
        UDPLeaveMulticastGroupsCommand *ctrl = new UDPLeaveMulticastGroupsCommand();
        ctrl->setSockId(sockId);
        ctrl->setMulticastAddrArraySize(numOfAddresses);
        unsigned int k = 0;
        for (int i=0; i<ift->getNumInterfaces(); ++i)
        {
            InterfaceEntry *ie = ift->getInterface(i);
#ifdef WITH_IPv4
            if (ie->ipv4Data())
            {
                const IPv4InterfaceData::IPv4AddressVector &addresses = ie->ipv4Data()->getJoinedMulticastGroups();
                for (unsigned int j = 0; j < addresses.size(); ++j, ++k)
                {
                    ctrl->setMulticastAddr(k, addresses[j]);
                }
            }
#endif
#ifdef WITH_IPv6
            // TODO
#endif
        }
        cMessage *msg = new cMessage("LeaveMulticastGroups", UDP_C_SETOPTION);
        msg->setControlInfo(ctrl);
        sendToUDP(msg);
    }
}
void UDPSocket::leaveMulticastGroup (const IPvXAddress & multicastAddr)
Causes the socket to leave the given multicast group, i.e.
UDP packets arriving to the given multicast address will no longer passed up to the socket.
{
    cMessage *msg = new cMessage("LeaveMulticastGroups", UDP_C_SETOPTION);
    UDPLeaveMulticastGroupsCommand *ctrl = new UDPLeaveMulticastGroupsCommand();
    ctrl->setSockId(sockId);
    ctrl->setMulticastAddrArraySize(1);
    ctrl->setMulticastAddr(0, multicastAddr);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::send (cPacket * msg)
Sends a data packet to the address and port specified previously in a connect() call.
Referenced by sendToUDP().
{
    pk->setKind(UDP_C_DATA);
    UDPSendCommand *ctrl = new UDPSendCommand();
    ctrl->setSockId(sockId);
    pk->setControlInfo(ctrl);
    sendToUDP(pk);
}
void UDPSocket::sendTo (cPacket * msg, IPvXAddress destAddr, int destPort)
Sends a data packet to the given address and port.
Referenced by RTCP::createPacket(), RTP::dataOut(), UDPBasicBurst::generateBurst(), UDPEchoApp::handleMessage(), VoIPSourceApp::handleMessage(), UDPVideoStreamCli::requestStream(), SCTP::sendAbortFromMain(), LDP::sendHelloTo(), TraCIDemo::sendMessage(), UDPBasicApp::sendPacket(), UDPVideoStreamSvr::sendStreamData(), SCTPAssociation::sendToIP(), DHCPServer::sendToUDP(), and DHCPClient::sendToUDP().
{
    pk->setKind(UDP_C_DATA);
    UDPSendCommand *ctrl = new UDPSendCommand();
    ctrl->setSockId(sockId);
    ctrl->setDestAddr(destAddr);
    ctrl->setDestPort(destPort);
    pk->setControlInfo(ctrl);
    sendToUDP(pk);
}
void UDPSocket::sendTo (cPacket * msg, IPvXAddress destAddr, int destPort, int outInterface)
Sends a data packet to the given address and port using the provided interface.
{
    pk->setKind(UDP_C_DATA);
    UDPSendCommand *ctrl = new UDPSendCommand();
    ctrl->setSockId(sockId);
    ctrl->setDestAddr(destAddr);
    ctrl->setDestPort(destPort);
    ctrl->setInterfaceId(outInterface);
    pk->setControlInfo(ctrl);
    sendToUDP(pk);
}
void UDPSocket::sendToUDP (cMessage * msg) [protected]
Referenced by bind(), close(), connect(), joinLocalMulticastGroups(), joinMulticastGroup(), leaveLocalMulticastGroups(), leaveMulticastGroup(), send(), sendTo(), setBroadcast(), setMulticastLoop(), setMulticastOutputInterface(), setTimeToLive(), and setTypeOfService().
{
    if (!gateToUdp)
        throw cRuntimeError("UDPSocket: setOutputGate() must be invoked before socket can be used");
    check_and_cast<cSimpleModule *>(gateToUdp->getOwnerModule())->send(msg, gateToUdp);
}
void UDPSocket::setBroadcast (bool broadcast)
Set the Broadcast option on the UDP socket.
This will cause the socket to receive broadcast packets as well.
Referenced by DHCPServer::initialize(), DHCPClient::initialize(), UDPBasicApp::setSocketOptions(), and TraCIDemo::setupLowerLayer().
{
    cMessage *msg = new cMessage("SetBroadcast", UDP_C_SETOPTION);
    UDPSetBroadcastCommand *ctrl = new UDPSetBroadcastCommand();
    ctrl->setSockId(sockId);
    ctrl->setBroadcast(broadcast);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::setMulticastLoop (bool value)
The boolean value specifies whether sent multicast packets should be looped back to the local sockets (like the Unix IP_MULTICAST_LOOP socket option).
{
    cMessage *msg = new cMessage("SetMulticastLoop", UDP_C_SETOPTION);
    UDPSetMulticastLoopCommand *ctrl = new UDPSetMulticastLoopCommand();
    ctrl->setSockId(sockId);
    ctrl->setLoop(value);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::setMulticastOutputInterface (int interfaceId)
Set the output interface for sending multicast packets (like the Unix IP_MULTICAST_IF socket option).
The argument is the interface's ID in InterfaceTable.
Referenced by UDPBasicApp::setSocketOptions().
{
    cMessage *msg = new cMessage("SetMulticastOutputIf", UDP_C_SETOPTION);
    UDPSetMulticastInterfaceCommand *ctrl = new UDPSetMulticastInterfaceCommand();
    ctrl->setSockId(sockId);
    ctrl->setInterfaceId(interfaceId);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::setOutputGate (cGate * toUdp) [inline]
Sets the gate on which to send to UDP.
Must be invoked before socket can be used. Example: socket.setOutputGate(gate("udpOut"));
Referenced by SCTP::bindPortForUDP(), UDPEchoApp::initialize(), UDPSink::initialize(), RTP::initialize(), VoIPSourceApp::initialize(), RTCP::initialize(), VoIPSinkApp::initialize(), UDPBasicApp::initialize(), DHCPServer::initialize(), DHCPClient::initialize(), UDPVideoStreamSvr::initialize(), UDPBasicBurst::initialize(), LDP::initialize(), UDPVideoStreamCli::requestStream(), and TraCIDemo::setupLowerLayer().
{gateToUdp = toUdp;}
void UDPSocket::setTimeToLive (int ttl)
Set the TTL (IPv6: Hop Limit) field on sent packets.
Referenced by UDPBasicApp::setSocketOptions().
{
    cMessage *msg = new cMessage("SetTTL", UDP_C_SETOPTION);
    UDPSetTimeToLiveCommand *ctrl = new UDPSetTimeToLiveCommand();
    ctrl->setSockId(sockId);
    ctrl->setTtl(ttl);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
void UDPSocket::setTypeOfService (unsigned char tos)
Sets the IPv4 Type of Service / IPv6 Traffic Class fields of packets sent from the UDP socket.
Referenced by UDPBasicApp::setSocketOptions().
{
    cMessage *msg = new cMessage("SetTOS", UDP_C_SETOPTION);
    UDPSetTypeOfServiceCommand *ctrl = new UDPSetTypeOfServiceCommand();
    ctrl->setSockId(sockId);
    ctrl->setTos(tos);
    msg->setControlInfo(ctrl);
    sendToUDP(msg);
}
Member Data Documentation
cGate* UDPSocket::gateToUdp [protected]
Referenced by sendToUDP(), and UDPSocket().
int UDPSocket::sockId [protected]
Referenced by belongsToSocket(), bind(), close(), connect(), joinLocalMulticastGroups(), joinMulticastGroup(), leaveLocalMulticastGroups(), leaveMulticastGroup(), send(), sendTo(), setBroadcast(), setMulticastLoop(), setMulticastOutputInterface(), setTimeToLive(), setTypeOfService(), and UDPSocket().
The documentation for this class was generated from the following files:
UDPSocket.h
UDPSocket.cc