INET Framework for OMNeT++/OMNEST: NetAnimTrace Class Reference
NetAnimTrace Class Reference
Records a NetAnim trace.
#include <NetAnimTrace.h>
Protected Member Functions
virtual void initialize ()
virtual void handleMessage (cMessage *msg)
virtual void finish ()
virtual void dump ()
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj)
virtual bool isRelevantModule (cModule *mod)
virtual void resolveNodeCoordinates (cModule *mod, double &x, double &y)
virtual void addNode (cModule *mod)
virtual void addLink (cGate *gate)
Protected Attributes
std::ofstream f
Static Protected Attributes
static simsignal_t messageSentSignal = SIMSIGNAL_NULL
static simsignal_t mobilityStateChangedSignal = SIMSIGNAL_NULL
Detailed Description
Records a NetAnim trace.
See NED file for more information.
Author:
andras
Member Function Documentation
void NetAnimTrace::addLink (cGate * gate) [protected, virtual]
Referenced by dump(), and receiveSignal().
{
    f << simTime() << " L " << gate->getOwnerModule()->getId() << " " << gate->getNextGate()->getOwnerModule()->getId() << "\n";
}
void NetAnimTrace::addNode (cModule * mod) [protected, virtual]
Referenced by dump(), and receiveSignal().
{
    double x, y;
    resolveNodeCoordinates(mod, x, y);
    f << simTime() << " N " << mod->getId() << " " << x << " " << y << "\n";
}
void NetAnimTrace::dump () [protected, virtual]
Referenced by initialize().
{
    cModule *parent = simulation.getSystemModule();
    for (cModule::SubmoduleIterator it(parent); !it.end(); it++)
        if (it() != this)
            addNode(it());
    for (cModule::SubmoduleIterator it(parent); !it.end(); it++)
        if (it() != this)
            for (cModule::GateIterator ig(it()); !ig.end(); ig++)
                if (ig()->getType()==cGate::OUTPUT && ig()->getNextGate())
                    addLink(ig());
}
void NetAnimTrace::finish () [protected, virtual]
{
    f.close();
}
void NetAnimTrace::handleMessage (cMessage * msg) [protected, virtual]
{
    throw cRuntimeError("This module does not handle messages");
}
void NetAnimTrace::initialize () [protected, virtual]
{
    if (!par("enabled").boolValue())
        return;
    const char *filename = par("filename");
    f.open(filename, std::ios::out | std::ios::trunc);
    if (f.fail())
        throw cRuntimeError("Cannot open file \"%s\" for writing", filename);
    dump();
    messageSentSignal = registerSignal("messageSent");
    mobilityStateChangedSignal = registerSignal("mobilityStateChanged");
    simulation.getSystemModule()->subscribe(POST_MODEL_CHANGE, this);
    simulation.getSystemModule()->subscribe(messageSentSignal, this);
    simulation.getSystemModule()->subscribe(mobilityStateChangedSignal, this);
}
bool NetAnimTrace::isRelevantModule (cModule * mod) [protected, virtual]
Referenced by receiveSignal().
{
    return mod->getParentModule() == simulation.getSystemModule();
}
void NetAnimTrace::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj) [protected, virtual]
{
    if (signalID == messageSentSignal && !source->isModule())
    {
        // record a "packet sent" line
        cChannel *channel = (cChannel *)source;
        cModule *srcModule = channel->getSourceGate()->getOwnerModule();
        if (isRelevantModule(srcModule))
        {
            cModule *destModule = channel->getSourceGate()->getNextGate()->getOwnerModule();
            cITimestampedValue *v = check_and_cast<cITimestampedValue *>(obj);
            if (dynamic_cast<cDatarateChannel *>(channel))
            {
                cDatarateChannel *datarateChannel = (cDatarateChannel *)channel;
                cMessage *msg = check_and_cast<cMessage *>(v->objectValue(signalID));
                simtime_t duration = msg->isPacket() ? ((cPacket*)msg)->getBitLength() / datarateChannel->getDatarate() : 0.0;
                simtime_t delay = datarateChannel->getDelay();
                simtime_t fbTx = v->getTimestamp(signalID);
                simtime_t lbTx = fbTx + duration;
                simtime_t fbRx = fbTx + delay;
                simtime_t lbRx = lbTx + delay;
                f << fbTx << " P " << srcModule->getId() << " " << destModule->getId() << " " << lbTx << " " << fbRx << " " << lbRx << "\n";
            }
            else if (dynamic_cast<cDelayChannel *>(channel))
            {
                cDelayChannel *delayChannel = (cDelayChannel *)channel;
                simtime_t fbTx = v->getTimestamp(signalID);
                simtime_t fbRx = fbTx + delayChannel->getDelay();
                f << fbTx << " P " << srcModule->getId() << " " << destModule->getId() << " " << fbTx << " " << fbRx << " " << fbRx << "\n";
            }
        }
    }
    else if (signalID == mobilityStateChangedSignal)
    {
        IMobility* mobility = dynamic_cast<IMobility*>(source);
        if (mobility)
        {
            Coord c = mobility->getCurrentPosition();
            cModule *mod = findContainingNode(dynamic_cast<cModule*>(source));
            if (mod && isRelevantModule(mod))
                f << simTime() << " N " << mod->getId() << " " << c.x << " " << c.y << "\n";
        }
    }
    else if (signalID == POST_MODEL_CHANGE)
    {
        // record dynamic "node created" and "link created" lines.
        // note: at the time of writing, NetAnim did not support "link removed" and "node removed" lines
        if (dynamic_cast<cPostModuleAddNotification *>(obj))
        {
            cPostModuleAddNotification *notification = (cPostModuleAddNotification *)obj;
            if (isRelevantModule(notification->module))
                addNode(notification->module);
        }
        else if (dynamic_cast<cPostGateConnectNotification *>(obj))
        {
            cPostGateConnectNotification *notification = (cPostGateConnectNotification *)obj;
            if (isRelevantModule(notification->gate->getOwnerModule()))
                addLink(notification->gate);
        }
    }
}
void NetAnimTrace::resolveNodeCoordinates (cModule * mod, double & x, double & y) [protected, virtual]
Referenced by addNode().
{
    // choose some defaults
    x = 600 * dblrand();
    y = 400 * dblrand();
    // and be content with them if there is no "p" tag in the display string
    cDisplayString& ds = submod->getDisplayString();
    if (!ds.containsTag("p"))
        return;
    // the following code is based on Tkenv (modinsp.cc, getSubmoduleCoords())
    // read x,y coordinates from "p" tag
    x = toDouble(ds.getTagArg("p", 0), x);
    y = toDouble(ds.getTagArg("p", 1), y);
    double sx = 20;
    double sy = 20;
    const char *layout = ds.getTagArg("p", 2); // matrix, row, column, ring, exact etc.
    // modify x,y using predefined layouts
    if (!layout || !*layout)
    {
        // we're happy
    }
    else if (!strcmp(layout, "e") || !strcmp(layout, "x") || !strcmp(layout, "exact"))
    {
        int dx = toDouble(ds.getTagArg("p", 3), 0);
        int dy = toDouble(ds.getTagArg("p", 4), 0);
        x += dx;
        y += dy;
    }
    else if (!strcmp(layout, "r") || !strcmp(layout, "row"))
    {
        int dx = toDouble(ds.getTagArg("p", 3), 2*sx);
        x += submod->getIndex()*dx;
    }
    else if (!strcmp(layout, "c") || !strcmp(layout, "col") || !strcmp(layout, "column"))
    {
        int dy = toDouble(ds.getTagArg("p", 3), 2*sy);
        y += submod->getIndex()*dy;
    }
    else if (!strcmp(layout, "m") || !strcmp(layout, "matrix"))
    {
        int columns = toDouble(ds.getTagArg("p", 3), 5);
        int dx = toDouble(ds.getTagArg("p", 4), 2*sx);
        int dy = toDouble(ds.getTagArg("p", 5), 2*sy);
        x += (submod->getIndex() % columns)*dx;
        y += (submod->getIndex() / columns)*dy;
    }
    else if (!strcmp(layout, "i") || !strcmp(layout, "ri") || !strcmp(layout, "ring"))
    {
        int rx = toDouble(ds.getTagArg("p", 3), (sx+sy)*submod->size()/4);
        int ry = toDouble(ds.getTagArg("p", 4), rx);
        x += (int) floor(rx - rx*sin(submod->getIndex()*2*PI/submod->size()));
        y += (int) floor(ry - ry*cos(submod->getIndex()*2*PI/submod->size()));
    }
    else
    {
        throw cRuntimeError("Invalid layout `%s' in `p' tag of display string", layout);
    }
}
Member Data Documentation
std::ofstream NetAnimTrace::f [protected]
Referenced by addLink(), addNode(), finish(), initialize(), and receiveSignal().
simsignal_t NetAnimTrace::messageSentSignal = SIMSIGNAL_NULL [static, protected]
Referenced by initialize(), and receiveSignal().
simsignal_t NetAnimTrace::mobilityStateChangedSignal = SIMSIGNAL_NULL [static, protected]
Referenced by initialize(), and receiveSignal().
The documentation for this class was generated from the following files:
NetAnimTrace.h
NetAnimTrace.cc