INET Framework for OMNeT++/OMNEST: OSPF::Neighbor Class Reference
OSPF::Neighbor Class Reference
#include <OSPFNeighbor.h>
Classes
struct DDPacketID
struct TransmittedLSA
Public Types
enum NeighborEventType {
HELLO_RECEIVED = 0, START = 1, TWOWAY_RECEIVED = 2, NEGOTIATION_DONE = 3,
EXCHANGE_DONE = 4, BAD_LINK_STATE_REQUEST = 5, LOADING_DONE = 6, IS_ADJACENCY_OK = 7,
SEQUENCE_NUMBER_MISMATCH = 8, ONEWAY_RECEIVED = 9, KILL_NEIGHBOR = 10, INACTIVITY_TIMER = 11,
POLL_TIMER = 12, LINK_DOWN = 13, DD_RETRANSMISSION_TIMER = 14, UPDATE_RETRANSMISSION_TIMER = 15,
REQUEST_RETRANSMISSION_TIMER = 16
}
enum NeighborStateType {
DOWN_STATE = 0, ATTEMPT_STATE = 1, INIT_STATE = 2, TWOWAY_STATE = 4,
EXCHANGE_START_STATE = 8, EXCHANGE_STATE = 16, LOADING_STATE = 32, FULL_STATE = 64
}
enum DatabaseExchangeRelationshipType { MASTER = 0, SLAVE = 1 }
Public Member Functions
Neighbor (RouterID neighbor=NULL_ROUTERID)
virtual ~Neighbor ()
void processEvent (NeighborEventType event)
void reset ()
void initFirstAdjacency ()
NeighborStateType getState () const
void sendDatabaseDescriptionPacket (bool init=false)
bool retransmitDatabaseDescriptionPacket ()
void createDatabaseSummary ()
void sendLinkStateRequestPacket ()
void retransmitUpdatePacket ()
bool needAdjacency ()
void addToRetransmissionList (OSPFLSA *lsa)
If the LSA is already on the retransmission list then it is replaced, else a copy of the LSA is added to the end of the retransmission list.
void removeFromRetransmissionList (LSAKeyType lsaKey)
bool isLinkStateRequestListEmpty (LSAKeyType lsaKey) const
OSPFLSA * findOnRetransmissionList (LSAKeyType lsaKey)
void startUpdateRetransmissionTimer ()
void clearUpdateRetransmissionTimer ()
void addToRequestList (OSPFLSAHeader *lsaHeader)
void removeFromRequestList (LSAKeyType lsaKey)
bool isLSAOnRequestList (LSAKeyType lsaKey) const
OSPFLSAHeader * findOnRequestList (LSAKeyType lsaKey)
void startRequestRetransmissionTimer ()
void clearRequestRetransmissionTimer ()
void addToTransmittedLSAList (LSAKeyType lsaKey)
bool isOnTransmittedLSAList (LSAKeyType lsaKey) const
void ageTransmittedLSAList ()
unsigned long getUniqueULong ()
void deleteLastSentDDPacket ()
void setNeighborID (RouterID id)
RouterID getNeighborID () const
void setPriority (unsigned char priority)
unsigned char getPriority () const
void setAddress (IPv4Address address)
IPv4Address getAddress () const
void setDesignatedRouter (DesignatedRouterID routerID)
DesignatedRouterID getDesignatedRouter () const
void setBackupDesignatedRouter (DesignatedRouterID routerID)
DesignatedRouterID getBackupDesignatedRouter () const
void setRouterDeadInterval (short interval)
short getRouterDeadInterval () const
void setDDSequenceNumber (unsigned long sequenceNumber)
unsigned long getDDSequenceNumber () const
void setOptions (OSPFOptions options)
OSPFOptions getOptions () const
void setLastReceivedDDPacket (DDPacketID packetID)
DDPacketID getLastReceivedDDPacket () const
void setDatabaseExchangeRelationship (DatabaseExchangeRelationshipType relation)
DatabaseExchangeRelationshipType getDatabaseExchangeRelationship () const
void setInterface (Interface *intf)
Interface * getInterface ()
const Interface * getInterface () const
OSPFTimer * getInactivityTimer ()
OSPFTimer * getPollTimer ()
OSPFTimer * getDDRetransmissionTimer ()
OSPFTimer * getUpdateRetransmissionTimer ()
bool isUpdateRetransmissionTimerActive () const
bool isRequestRetransmissionTimerActive () const
bool isFirstAdjacencyInited () const
bool designatedRoutersAreSetUp () const
void setupDesignatedRouters (bool setUp)
unsigned long getDatabaseSummaryListCount () const
void incrementDDSequenceNumber ()
bool isLinkStateRequestListEmpty () const
bool isLinkStateRetransmissionListEmpty () const
void popFirstLinkStateRequest ()
Static Public Member Functions
static const char * getStateString (NeighborStateType stateType)
Private Member Functions
void changeState (NeighborState *newState, NeighborState *currentState)
Private Attributes
NeighborState * state
NeighborState * previousState
OSPFTimer * inactivityTimer
OSPFTimer * pollTimer
OSPFTimer * ddRetransmissionTimer
OSPFTimer * updateRetransmissionTimer
bool updateRetransmissionTimerActive
OSPFTimer * requestRetransmissionTimer
bool requestRetransmissionTimerActive
DatabaseExchangeRelationshipType databaseExchangeRelationship
bool firstAdjacencyInited
unsigned long ddSequenceNumber
DDPacketID lastReceivedDDPacket
RouterID neighborID
unsigned char neighborPriority
IPv4Address neighborIPAddress
OSPFOptions neighborOptions
DesignatedRouterID neighborsDesignatedRouter
DesignatedRouterID neighborsBackupDesignatedRouter
bool designatedRoutersSetUp
short neighborsRouterDeadInterval
std::list< OSPFLSA * > linkStateRetransmissionList
std::list< OSPFLSAHeader * > databaseSummaryList
std::list< OSPFLSAHeader * > linkStateRequestList
std::list< TransmittedLSA > transmittedLSAs
OSPFDatabaseDescriptionPacket * lastTransmittedDDPacket
Interface * parentInterface
Static Private Attributes
static unsigned long ddSequenceNumberInitSeed = 0
Friends
class NeighborState
Member Enumeration Documentation
enum OSPF::Neighbor::DatabaseExchangeRelationshipType
Enumerator:
MASTER
SLAVE
{
        MASTER = 0,
        SLAVE = 1
    };
enum OSPF::Neighbor::NeighborEventType
Enumerator:
HELLO_RECEIVED
START
TWOWAY_RECEIVED
NEGOTIATION_DONE
EXCHANGE_DONE
BAD_LINK_STATE_REQUEST
LOADING_DONE
IS_ADJACENCY_OK
SEQUENCE_NUMBER_MISMATCH
ONEWAY_RECEIVED
KILL_NEIGHBOR
INACTIVITY_TIMER
POLL_TIMER
LINK_DOWN
DD_RETRANSMISSION_TIMER
UPDATE_RETRANSMISSION_TIMER
REQUEST_RETRANSMISSION_TIMER
{
        HELLO_RECEIVED               = 0,
        START                       = 1,
        TWOWAY_RECEIVED              = 2,
        NEGOTIATION_DONE             = 3,
        EXCHANGE_DONE                = 4,
        BAD_LINK_STATE_REQUEST         = 5,
        LOADING_DONE                 = 6,
        IS_ADJACENCY_OK               = 7,
        SEQUENCE_NUMBER_MISMATCH      = 8,
        ONEWAY_RECEIVED              = 9,
        KILL_NEIGHBOR                = 10,
        INACTIVITY_TIMER             = 11,
        POLL_TIMER                   = 12,
        LINK_DOWN                    = 13,
        DD_RETRANSMISSION_TIMER       = 14,
        UPDATE_RETRANSMISSION_TIMER   = 15,
        REQUEST_RETRANSMISSION_TIMER  = 16
    };
enum OSPF::Neighbor::NeighborStateType
Enumerator:
DOWN_STATE
ATTEMPT_STATE
INIT_STATE
TWOWAY_STATE
EXCHANGE_START_STATE
EXCHANGE_STATE
LOADING_STATE
FULL_STATE
{
        DOWN_STATE          = 0,
        ATTEMPT_STATE       = 1,
        INIT_STATE          = 2,
        TWOWAY_STATE        = 4,
        EXCHANGE_START_STATE = 8,
        EXCHANGE_STATE      = 16,
        LOADING_STATE       = 32,
        FULL_STATE          = 64
    };
Constructor & Destructor Documentation
OSPF::Neighbor::Neighbor (RouterID neighbor = NULL_ROUTERID)
                                        :
    updateRetransmissionTimerActive(false),
    requestRetransmissionTimerActive(false),
    firstAdjacencyInited(false),
    ddSequenceNumber(0),
    neighborID(neighbor),
    neighborPriority(0),
    neighborIPAddress(OSPF::NULL_IPV4ADDRESS),
    neighborsDesignatedRouter(OSPF::NULL_DESIGNATEDROUTERID),
    neighborsBackupDesignatedRouter(OSPF::NULL_DESIGNATEDROUTERID),
    designatedRoutersSetUp(false),
    neighborsRouterDeadInterval(40),
    lastTransmittedDDPacket(NULL)
{
    memset(&lastReceivedDDPacket, 0, sizeof(OSPF::Neighbor::DDPacketID));
    // setting only I and M bits is invalid -> good initializer
    lastReceivedDDPacket.ddOptions.I_Init = true;
    lastReceivedDDPacket.ddOptions.M_More = true;
    inactivityTimer = new OSPFTimer();
    inactivityTimer->setTimerKind(NEIGHBOR_INACTIVITY_TIMER);
    inactivityTimer->setContextPointer(this);
    inactivityTimer->setName("OSPF::Neighbor::NeighborInactivityTimer");
    pollTimer = new OSPFTimer();
    pollTimer->setTimerKind(NEIGHBOR_POLL_TIMER);
    pollTimer->setContextPointer(this);
    pollTimer->setName("OSPF::Neighbor::NeighborPollTimer");
    ddRetransmissionTimer = new OSPFTimer();
    ddRetransmissionTimer->setTimerKind(NEIGHBOR_DD_RETRANSMISSION_TIMER);
    ddRetransmissionTimer->setContextPointer(this);
    ddRetransmissionTimer->setName("OSPF::Neighbor::NeighborDDRetransmissionTimer");
    updateRetransmissionTimer = new OSPFTimer();
    updateRetransmissionTimer->setTimerKind(NEIGHBOR_UPDATE_RETRANSMISSION_TIMER);
    updateRetransmissionTimer->setContextPointer(this);
    updateRetransmissionTimer->setName("OSPF::Neighbor::Neighbor::NeighborUpdateRetransmissionTimer");
    requestRetransmissionTimer = new OSPFTimer();
    requestRetransmissionTimer->setTimerKind(NEIGHBOR_REQUEST_RETRANSMISSION_TIMER);
    requestRetransmissionTimer->setContextPointer(this);
    requestRetransmissionTimer->setName("OSPF::Neighbor::NeighborRequestRetransmissionTimer");
    state = new OSPF::NeighborStateDown;
    previousState = NULL;
}
OSPF::Neighbor::~Neighbor () [virtual]
{
    reset();
    MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    messageHandler->clearTimer(inactivityTimer);
    messageHandler->clearTimer(pollTimer);
    delete inactivityTimer;
    delete pollTimer;
    delete ddRetransmissionTimer;
    delete updateRetransmissionTimer;
    delete requestRetransmissionTimer;
    if (previousState != NULL) {
        delete previousState;
    }
    delete state;
}
Member Function Documentation
void OSPF::Neighbor::addToRequestList (OSPFLSAHeader * lsaHeader)
Referenced by OSPF::DatabaseDescriptionHandler::processDDPacket().
{
    linkStateRequestList.push_back(new OSPFLSAHeader(*lsaHeader));
}
void OSPF::Neighbor::addToRetransmissionList (OSPFLSA * lsa)
If the LSA is already on the retransmission list then it is replaced, else a copy of the LSA is added to the end of the retransmission list.
Parameters:
lsa [in] The LSA to be added.
{
    std::list<OSPFLSA*>::iterator it;
    for (it = linkStateRetransmissionList.begin(); it != linkStateRetransmissionList.end(); it++) {
        if (((*it)->getHeader().getLinkStateID() == lsa->getHeader().getLinkStateID()) &&
            ((*it)->getHeader().getAdvertisingRouter().getInt() == lsa->getHeader().getAdvertisingRouter().getInt()))
        {
            break;
        }
    }
    OSPFLSA* lsaCopy = NULL;
    switch (lsa->getHeader().getLsType()) {
        case ROUTERLSA_TYPE:
            lsaCopy = new OSPFRouterLSA(*(check_and_cast<OSPFRouterLSA*> (lsa)));
            break;
        case NETWORKLSA_TYPE:
            lsaCopy = new OSPFNetworkLSA(*(check_and_cast<OSPFNetworkLSA*> (lsa)));
            break;
        case SUMMARYLSA_NETWORKS_TYPE:
        case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
            lsaCopy = new OSPFSummaryLSA(*(check_and_cast<OSPFSummaryLSA*> (lsa)));
            break;
        case AS_EXTERNAL_LSA_TYPE:
            lsaCopy = new OSPFASExternalLSA(*(check_and_cast<OSPFASExternalLSA*> (lsa)));
            break;
        default:
            ASSERT(false); // error
            break;
    }
    if (it != linkStateRetransmissionList.end()) {
        delete (*it);
        *it = static_cast<OSPFLSA*> (lsaCopy);
    } else {
        linkStateRetransmissionList.push_back(static_cast<OSPFLSA*> (lsaCopy));
    }
}
void OSPF::Neighbor::addToTransmittedLSAList (OSPF::LSAKeyType lsaKey)
Referenced by OSPF::Interface::floodLSA().
{
    TransmittedLSA transmit;
    transmit.lsaKey = lsaKey;
    transmit.age = 0;
    transmittedLSAs.push_back(transmit);
}
void OSPF::Neighbor::ageTransmittedLSAList ()
{
    std::list<TransmittedLSA>::iterator it = transmittedLSAs.begin();
    while ((it != transmittedLSAs.end()) && (it->age == MIN_LS_ARRIVAL)) {
        transmittedLSAs.pop_front();
        it = transmittedLSAs.begin();
    }
    for (it = transmittedLSAs.begin(); it != transmittedLSAs.end(); it++) {
        it->age++;
    }
}
void OSPF::Neighbor::changeState (NeighborState * newState, NeighborState * currentState) [private]
Referenced by OSPF::NeighborState::changeState().
{
    if (previousState != NULL) {
        delete previousState;
    }
    state = newState;
    previousState = currentState;
}
void OSPF::Neighbor::clearRequestRetransmissionTimer ()
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateLoading::processEvent(), and OSPF::DatabaseDescriptionHandler::processPacket().
{
    MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    messageHandler->clearTimer(requestRetransmissionTimer);
    requestRetransmissionTimerActive = false;
}
void OSPF::Neighbor::clearUpdateRetransmissionTimer ()
Referenced by OSPF::LinkStateAcknowledgementHandler::processPacket().
{
    MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    messageHandler->clearTimer(updateRetransmissionTimer);
    updateRetransmissionTimerActive = false;
}
void OSPF::Neighbor::createDatabaseSummary ()
Referenced by OSPF::NeighborStateExchangeStart::processEvent().
{
    OSPF::Area* area = parentInterface->getArea();
    unsigned long routerLSACount = area->getRouterLSACount();
    /* Note: OSPF specification says:
     * "LSAs whose age is equal to MaxAge are instead added to the neighbor's
     *  Link state retransmission list."
     * But this task has been already done during the aging of the database. (???)
     * So we'll skip this.
     */
    for (unsigned long i = 0; i < routerLSACount; i++) {
        if (area->getRouterLSA(i)->getHeader().getLsAge() < MAX_AGE) {
            OSPFLSAHeader* routerLSA = new OSPFLSAHeader(area->getRouterLSA(i)->getHeader());
            databaseSummaryList.push_back(routerLSA);
        }
    }
    unsigned long networkLSACount = area->getNetworkLSACount();
    for (unsigned long j = 0; j < networkLSACount; j++) {
        if (area->getNetworkLSA(j)->getHeader().getLsAge() < MAX_AGE) {
            OSPFLSAHeader* networkLSA = new OSPFLSAHeader(area->getNetworkLSA(j)->getHeader());
            databaseSummaryList.push_back(networkLSA);
        }
    }
    unsigned long summaryLSACount = area->getSummaryLSACount();
    for (unsigned long k = 0; k < summaryLSACount; k++) {
        if (area->getSummaryLSA(k)->getHeader().getLsAge() < MAX_AGE) {
            OSPFLSAHeader* summaryLSA = new OSPFLSAHeader(area->getSummaryLSA(k)->getHeader());
            databaseSummaryList.push_back(summaryLSA);
        }
    }
    if ((parentInterface->getType() != OSPF::Interface::VIRTUAL) &&
        (area->getExternalRoutingCapability()))
    {
        OSPF::Router* router = area->getRouter();
        unsigned long asExternalLSACount = router->getASExternalLSACount();
        for (unsigned long m = 0; m < asExternalLSACount; m++) {
            if (router->getASExternalLSA(m)->getHeader().getLsAge() < MAX_AGE) {
                OSPFLSAHeader* asExternalLSA = new OSPFLSAHeader(router->getASExternalLSA(m)->getHeader());
                databaseSummaryList.push_back(asExternalLSA);
            }
        }
    }
}
void OSPF::Neighbor::deleteLastSentDDPacket ()
Referenced by OSPF::NeighborStateFull::processEvent(), and OSPF::NeighborStateLoading::processEvent().
{
    if (lastTransmittedDDPacket != NULL) {
        delete lastTransmittedDDPacket;
        lastTransmittedDDPacket = NULL;
    }
}
bool OSPF::Neighbor::designatedRoutersAreSetUp () const [inline]
Referenced by OSPF::HelloHandler::processPacket().
{ return designatedRoutersSetUp; }
OSPFLSAHeader * OSPF::Neighbor::findOnRequestList (OSPF::LSAKeyType lsaKey)
{
    for (std::list<OSPFLSAHeader*>::iterator it = linkStateRequestList.begin(); it != linkStateRequestList.end(); it++) {
        if (((*it)->getLinkStateID() == lsaKey.linkStateID) &&
            ((*it)->getAdvertisingRouter() == lsaKey.advertisingRouter))
        {
            return (*it);
        }
    }
    return NULL;
}
OSPFLSA * OSPF::Neighbor::findOnRetransmissionList (OSPF::LSAKeyType lsaKey)
Referenced by OSPF::LinkStateAcknowledgementHandler::processPacket().
{
    for (std::list<OSPFLSA*>::iterator it = linkStateRetransmissionList.begin(); it != linkStateRetransmissionList.end(); it++) {
        if (((*it)->getHeader().getLinkStateID() == lsaKey.linkStateID) &&
            ((*it)->getHeader().getAdvertisingRouter() == lsaKey.advertisingRouter))
        {
            return (*it);
        }
    }
    return NULL;
}
IPv4Address OSPF::Neighbor::getAddress () const [inline]
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::Interface::addNeighbor(), OSPF::InterfaceState::calculateDesignatedRouter(), OSPF::Area::calculateNextHops(), OSPF::Area::originateRouterLSA(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStateBackup::processEvent(), OSPF::NeighborStateDown::processEvent(), OSPF::InterfaceStateDesignatedRouter::processEvent(), OSPF::InterfaceStatePointToPoint::processEvent(), OSPF::HelloHandler::processPacket(), OSPF::LinkStateRequestHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{ return neighborIPAddress; }
DesignatedRouterID OSPF::Neighbor::getBackupDesignatedRouter () const [inline]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), and OSPF::HelloHandler::processPacket().
{ return neighborsBackupDesignatedRouter; }
DatabaseExchangeRelationshipType OSPF::Neighbor::getDatabaseExchangeRelationship () const [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processDDPacket(), and OSPF::DatabaseDescriptionHandler::processPacket().
{ return databaseExchangeRelationship; }
unsigned long OSPF::Neighbor::getDatabaseSummaryListCount () const [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processDDPacket().
{ return databaseSummaryList.size(); }
OSPFTimer* OSPF::Neighbor::getDDRetransmissionTimer () [inline]
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), and OSPF::NeighborStateExchangeStart::processEvent().
{ return ddRetransmissionTimer; }
unsigned long OSPF::Neighbor::getDDSequenceNumber () const [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processPacket().
{ return ddSequenceNumber; }
DesignatedRouterID OSPF::Neighbor::getDesignatedRouter () const [inline]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), and OSPF::HelloHandler::processPacket().
{ return neighborsDesignatedRouter; }
OSPFTimer* OSPF::Neighbor::getInactivityTimer () [inline]
Referenced by OSPF::NeighborStateAttempt::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateExchange::processEvent(), and OSPF::NeighborStateDown::processEvent().
{ return inactivityTimer; }
Interface* OSPF::Neighbor::getInterface () [inline]
Referenced by OSPF::NeighborState::changeState(), OSPF::MessageHandler::handleTimer(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateDown::processEvent(), OSPF::NeighborStateAttempt::processEvent(), and OSPF::NeighborStateTwoWay::processEvent().
{ return parentInterface; }
const Interface* OSPF::Neighbor::getInterface () const [inline]
{ return parentInterface; }
DDPacketID OSPF::Neighbor::getLastReceivedDDPacket () const [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processPacket().
{ return lastReceivedDDPacket; }
RouterID OSPF::Neighbor::getNeighborID () const [inline]
Referenced by OSPF::Interface::addNeighbor(), OSPF::InterfaceState::calculateDesignatedRouter(), OSPF::Area::calculateNextHops(), OSPF::Interface::floodLSA(), OSPF::Area::originateNetworkLSA(), OSPF::Area::originateRouterLSA(), OSPF::MessageHandler::printEvent(), OSPF::HelloHandler::processPacket(), and OSPF::DatabaseDescriptionHandler::processPacket().
{ return neighborID; }
OSPFOptions OSPF::Neighbor::getOptions () const [inline]
{ return neighborOptions; }
OSPFTimer* OSPF::Neighbor::getPollTimer () [inline]
Referenced by OSPF::NeighborStateAttempt::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateExchange::processEvent(), and OSPF::NeighborStateDown::processEvent().
{ return pollTimer; }
unsigned char OSPF::Neighbor::getPriority () const [inline]
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), OSPF::InterfaceStateWaiting::processEvent(), OSPF::InterfaceStateNotDesignatedRouter::processEvent(), OSPF::InterfaceStateDown::processEvent(), and OSPF::HelloHandler::processPacket().
{ return neighborPriority; }
short OSPF::Neighbor::getRouterDeadInterval () const [inline]
Referenced by OSPF::NeighborStateAttempt::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateExchange::processEvent(), and OSPF::NeighborStateDown::processEvent().
{ return neighborsRouterDeadInterval; }
OSPF::Neighbor::NeighborStateType OSPF::Neighbor::getState () const
Referenced by OSPF::InterfaceState::calculateDesignatedRouter(), OSPF::Area::originateNetworkLSA(), OSPF::Area::originateRouterLSA(), OSPF::MessageHandler::printEvent(), OSPF::LinkStateAcknowledgementHandler::processPacket(), OSPF::LinkStateRequestHandler::processPacket(), OSPF::HelloHandler::processPacket(), OSPF::DatabaseDescriptionHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{
    return state->getState();
}
const char * OSPF::Neighbor::getStateString (NeighborStateType stateType) [static]
Referenced by OSPF::MessageHandler::printEvent().
{
    switch (stateType) {
        case DOWN_STATE:           return "Down";
        case ATTEMPT_STATE:        return "Attempt";
        case INIT_STATE:           return "Init";
        case TWOWAY_STATE:         return "TwoWay";
        case EXCHANGE_START_STATE: return "ExchangeStart";
        case EXCHANGE_STATE:       return "Exchange";
        case LOADING_STATE:        return "Loading";
        case FULL_STATE:           return "Full";
        default:                   ASSERT(false); break;
    }
    return "";
}
unsigned long OSPF::Neighbor::getUniqueULong ()
{
    // FIXME!!! Should come from a global unique number generator module.
    return (ddSequenceNumberInitSeed++);
}
OSPFTimer* OSPF::Neighbor::getUpdateRetransmissionTimer () [inline]
{ return updateRetransmissionTimer; }
void OSPF::Neighbor::incrementDDSequenceNumber () [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processDDPacket(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), and OSPF::NeighborStateExchange::processEvent().
{ ddSequenceNumber++; }
void OSPF::Neighbor::initFirstAdjacency ()
Referenced by OSPF::NeighborStateInit::processEvent(), and OSPF::NeighborStateTwoWay::processEvent().
{
    ddSequenceNumber = getUniqueULong();
    firstAdjacencyInited = true;
}
bool OSPF::Neighbor::isFirstAdjacencyInited () const [inline]
Referenced by OSPF::NeighborStateInit::processEvent(), and OSPF::NeighborStateTwoWay::processEvent().
{ return firstAdjacencyInited; }
bool OSPF::Neighbor::isLinkStateRequestListEmpty (OSPF::LSAKeyType lsaKey) const
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::DatabaseDescriptionHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{
    for (std::list<OSPFLSA*>::const_iterator it = linkStateRetransmissionList.begin(); it != linkStateRetransmissionList.end(); it++) {
        const OSPFLSA* lsa = *it;
        if ((lsa->getHeader().getLinkStateID() == lsaKey.linkStateID) &&
            (lsa->getHeader().getAdvertisingRouter() == lsaKey.advertisingRouter))
        {
            return true;
        }
    }
    return false;
}
bool OSPF::Neighbor::isLinkStateRequestListEmpty () const [inline]
{ return linkStateRequestList.empty(); }
bool OSPF::Neighbor::isLinkStateRetransmissionListEmpty () const [inline]
Referenced by OSPF::LinkStateAcknowledgementHandler::processPacket().
{ return linkStateRetransmissionList.empty(); }
bool OSPF::Neighbor::isLSAOnRequestList (OSPF::LSAKeyType lsaKey) const
Referenced by OSPF::LinkStateUpdateHandler::processPacket().
{
    for (std::list<OSPFLSAHeader*>::const_iterator it = linkStateRequestList.begin(); it != linkStateRequestList.end(); it++) {
        const OSPFLSAHeader* lsaHeader = *it;
        if ((lsaHeader->getLinkStateID() == lsaKey.linkStateID) &&
            (lsaHeader->getAdvertisingRouter() == lsaKey.advertisingRouter))
        {
            return true;
        }
    }
    return false;
}
bool OSPF::Neighbor::isOnTransmittedLSAList (OSPF::LSAKeyType lsaKey) const
Referenced by OSPF::LinkStateUpdateHandler::processPacket().
{
    for (std::list<TransmittedLSA>::const_iterator it = transmittedLSAs.begin(); it != transmittedLSAs.end(); it++) {
        if ((it->lsaKey.linkStateID == lsaKey.linkStateID) &&
            (it->lsaKey.advertisingRouter == lsaKey.advertisingRouter))
        {
            return true;
        }
    }
    return false;
}
bool OSPF::Neighbor::isRequestRetransmissionTimerActive () const [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processPacket().
{ return requestRetransmissionTimerActive; }
bool OSPF::Neighbor::isUpdateRetransmissionTimerActive () const [inline]
Referenced by OSPF::Interface::floodLSA().
{ return updateRetransmissionTimerActive; }
bool OSPF::Neighbor::needAdjacency ()
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), and OSPF::NeighborStateExchangeStart::processEvent().
{
    OSPF::Interface::OSPFInterfaceType interfaceType = parentInterface->getType();
    OSPF::RouterID routerID = parentInterface->getArea()->getRouter()->getRouterID();
    OSPF::DesignatedRouterID dRouter = parentInterface->getDesignatedRouter();
    OSPF::DesignatedRouterID backupDRouter = parentInterface->getBackupDesignatedRouter();
    if ((interfaceType == OSPF::Interface::POINTTOPOINT) ||
        (interfaceType == OSPF::Interface::POINTTOMULTIPOINT) ||
        (interfaceType == OSPF::Interface::VIRTUAL) ||
        (dRouter.routerID == routerID) ||
        (backupDRouter.routerID == routerID) ||
        ((neighborsDesignatedRouter.routerID == dRouter.routerID) ||
         (!designatedRoutersSetUp &&
          (neighborsDesignatedRouter.ipInterfaceAddress == dRouter.ipInterfaceAddress))) ||
        ((neighborsBackupDesignatedRouter.routerID == backupDRouter.routerID) ||
         (!designatedRoutersSetUp &&
          (neighborsBackupDesignatedRouter.ipInterfaceAddress == backupDRouter.ipInterfaceAddress))))
    {
        return true;
    } else {
        return false;
    }
}
void OSPF::Neighbor::popFirstLinkStateRequest () [inline]
{ linkStateRequestList.pop_front(); }
void OSPF::Neighbor::processEvent (NeighborEventType event)
Referenced by OSPF::MessageHandler::handleTimer(), OSPF::DatabaseDescriptionHandler::processDDPacket(), OSPF::InterfaceStateDown::processEvent(), OSPF::LinkStateRequestHandler::processPacket(), OSPF::HelloHandler::processPacket(), OSPF::DatabaseDescriptionHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{
    state->processEvent(this, event);
}
void OSPF::Neighbor::removeFromRequestList (OSPF::LSAKeyType lsaKey)
{
    std::list<OSPFLSAHeader*>::iterator it = linkStateRequestList.begin();
    while (it != linkStateRequestList.end()) {
        if (((*it)->getLinkStateID() == lsaKey.linkStateID) &&
            ((*it)->getAdvertisingRouter() == lsaKey.advertisingRouter))
        {
            delete (*it);
            it = linkStateRequestList.erase(it);
        } else {
            it++;
        }
    }
    if ((getState() == OSPF::Neighbor::LOADING_STATE) && (linkStateRequestList.empty())) {
        clearRequestRetransmissionTimer();
        processEvent(OSPF::Neighbor::LOADING_DONE);
    }
}
void OSPF::Neighbor::removeFromRetransmissionList (OSPF::LSAKeyType lsaKey)
Referenced by OSPF::LinkStateAcknowledgementHandler::processPacket(), and OSPF::LinkStateUpdateHandler::processPacket().
{
    std::list<OSPFLSA*>::iterator it = linkStateRetransmissionList.begin();
    while (it != linkStateRetransmissionList.end()) {
        if (((*it)->getHeader().getLinkStateID() == lsaKey.linkStateID) &&
            ((*it)->getHeader().getAdvertisingRouter() == lsaKey.advertisingRouter))
        {
            delete (*it);
            it = linkStateRetransmissionList.erase(it);
        } else {
            it++;
        }
    }
}
void OSPF::Neighbor::reset ()
Referenced by OSPF::NeighborStateAttempt::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateExchangeStart::processEvent(), and OSPF::NeighborStateExchange::processEvent().
{
    for (std::list<OSPFLSA*>::iterator retIt = linkStateRetransmissionList.begin();
         retIt != linkStateRetransmissionList.end();
         retIt++)
    {
        delete (*retIt);
    }
    linkStateRetransmissionList.clear();
    std::list<OSPFLSAHeader*>::iterator it;
    for (it = databaseSummaryList.begin(); it != databaseSummaryList.end(); it++) {
        delete (*it);
    }
    databaseSummaryList.clear();
    for (it = linkStateRequestList.begin(); it != linkStateRequestList.end(); it++)
    {
        delete (*it);
    }
    linkStateRequestList.clear();
    parentInterface->getArea()->getRouter()->getMessageHandler()->clearTimer(ddRetransmissionTimer);
    clearUpdateRetransmissionTimer();
    clearRequestRetransmissionTimer();
    if (lastTransmittedDDPacket != NULL) {
        delete lastTransmittedDDPacket;
        lastTransmittedDDPacket = NULL;
    }
}
bool OSPF::Neighbor::retransmitDatabaseDescriptionPacket ()
Referenced by OSPF::NeighborStateExchangeStart::processEvent(), and OSPF::DatabaseDescriptionHandler::processPacket().
{
    if (lastTransmittedDDPacket != NULL) {
        OSPFDatabaseDescriptionPacket* ddPacket = new OSPFDatabaseDescriptionPacket(*lastTransmittedDDPacket);
        OSPF::MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
        int ttl = (parentInterface->getType() == OSPF::Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
        if (parentInterface->getType() == OSPF::Interface::POINTTOPOINT) {
            messageHandler->sendPacket(ddPacket, IPv4Address::ALL_OSPF_ROUTERS_MCAST, parentInterface->getIfIndex(), ttl);
        } else {
            messageHandler->sendPacket(ddPacket, neighborIPAddress, parentInterface->getIfIndex(), ttl);
        }
        return true;
    } else {
        return false;
    }
}
void OSPF::Neighbor::retransmitUpdatePacket ()
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateLoading::processEvent(), and OSPF::NeighborStateFull::processEvent().
{
    OSPFLinkStateUpdatePacket* updatePacket = new OSPFLinkStateUpdatePacket();
    updatePacket->setType(LINKSTATE_UPDATE_PACKET);
    updatePacket->setRouterID(IPv4Address(parentInterface->getArea()->getRouter()->getRouterID()));
    updatePacket->setAreaID(IPv4Address(parentInterface->getArea()->getAreaID()));
    updatePacket->setAuthenticationType(parentInterface->getAuthenticationType());
    OSPF::AuthenticationKeyType authKey = parentInterface->getAuthenticationKey();
    for (int i = 0; i < 8; i++) {
        updatePacket->setAuthentication(i, authKey.bytes[i]);
    }
    bool packetFull = false;
    unsigned short lsaCount = 0;
    unsigned long packetLength = IP_MAX_HEADER_BYTES + OSPF_LSA_HEADER_LENGTH;
    std::list<OSPFLSA*>::iterator it = linkStateRetransmissionList.begin();
    while (!packetFull && (it != linkStateRetransmissionList.end())) {
        LSAType lsaType = static_cast<LSAType> ((*it)->getHeader().getLsType());
        OSPFRouterLSA* routerLSA = (lsaType == ROUTERLSA_TYPE) ? dynamic_cast<OSPFRouterLSA*> (*it) : NULL;
        OSPFNetworkLSA* networkLSA = (lsaType == NETWORKLSA_TYPE) ? dynamic_cast<OSPFNetworkLSA*> (*it) : NULL;
        OSPFSummaryLSA* summaryLSA = ((lsaType == SUMMARYLSA_NETWORKS_TYPE) ||
                                            (lsaType == SUMMARYLSA_ASBOUNDARYROUTERS_TYPE)) ? dynamic_cast<OSPFSummaryLSA*> (*it) : NULL;
        OSPFASExternalLSA* asExternalLSA = (lsaType == AS_EXTERNAL_LSA_TYPE) ? dynamic_cast<OSPFASExternalLSA*> (*it) : NULL;
        long lsaSize = 0;
        bool includeLSA = false;
        switch (lsaType) {
            case ROUTERLSA_TYPE:
                if (routerLSA != NULL) {
                    lsaSize = calculateLSASize(routerLSA);
                }
                break;
            case NETWORKLSA_TYPE:
                if (networkLSA != NULL) {
                    lsaSize = calculateLSASize(networkLSA);
                }
                break;
            case SUMMARYLSA_NETWORKS_TYPE:
            case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
                if (summaryLSA != NULL) {
                    lsaSize = calculateLSASize(summaryLSA);
                }
                break;
            case AS_EXTERNAL_LSA_TYPE:
                if (asExternalLSA != NULL) {
                    lsaSize = calculateLSASize(asExternalLSA);
                }
                break;
            default: break;
        }
        if (packetLength + lsaSize < parentInterface->getMTU()) {
            includeLSA = true;
            lsaCount++;
        } else {
            if ((lsaCount == 0) && (packetLength + lsaSize < IPV4_DATAGRAM_LENGTH)) {
                includeLSA = true;
                lsaCount++;
                packetFull = true;
            }
        }
        if (includeLSA) {
            packetLength += lsaSize;
            switch (lsaType) {
                case ROUTERLSA_TYPE:
                    if (routerLSA != NULL) {
                        unsigned int routerLSACount = updatePacket->getRouterLSAsArraySize();
                        updatePacket->setRouterLSAsArraySize(routerLSACount + 1);
                        updatePacket->setRouterLSAs(routerLSACount, *routerLSA);
                        unsigned short lsAge = updatePacket->getRouterLSAs(routerLSACount).getHeader().getLsAge();
                        if (lsAge < MAX_AGE - parentInterface->getTransmissionDelay()) {
                            updatePacket->getRouterLSAs(routerLSACount).getHeader().setLsAge(lsAge + parentInterface->getTransmissionDelay());
                        } else {
                            updatePacket->getRouterLSAs(routerLSACount).getHeader().setLsAge(MAX_AGE);
                        }
                    }
                    break;
                case NETWORKLSA_TYPE:
                    if (networkLSA != NULL) {
                        unsigned int networkLSACount = updatePacket->getNetworkLSAsArraySize();
                        updatePacket->setNetworkLSAsArraySize(networkLSACount + 1);
                        updatePacket->setNetworkLSAs(networkLSACount, *networkLSA);
                        unsigned short lsAge = updatePacket->getNetworkLSAs(networkLSACount).getHeader().getLsAge();
                        if (lsAge < MAX_AGE - parentInterface->getTransmissionDelay()) {
                            updatePacket->getNetworkLSAs(networkLSACount).getHeader().setLsAge(lsAge + parentInterface->getTransmissionDelay());
                        } else {
                            updatePacket->getNetworkLSAs(networkLSACount).getHeader().setLsAge(MAX_AGE);
                        }
                    }
                    break;
                case SUMMARYLSA_NETWORKS_TYPE:
                case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
                    if (summaryLSA != NULL) {
                        unsigned int summaryLSACount = updatePacket->getSummaryLSAsArraySize();
                        updatePacket->setSummaryLSAsArraySize(summaryLSACount + 1);
                        updatePacket->setSummaryLSAs(summaryLSACount, *summaryLSA);
                        unsigned short lsAge = updatePacket->getSummaryLSAs(summaryLSACount).getHeader().getLsAge();
                        if (lsAge < MAX_AGE - parentInterface->getTransmissionDelay()) {
                            updatePacket->getSummaryLSAs(summaryLSACount).getHeader().setLsAge(lsAge + parentInterface->getTransmissionDelay());
                        } else {
                            updatePacket->getSummaryLSAs(summaryLSACount).getHeader().setLsAge(MAX_AGE);
                        }
                    }
                    break;
                case AS_EXTERNAL_LSA_TYPE:
                    if (asExternalLSA != NULL) {
                        unsigned int asExternalLSACount = updatePacket->getAsExternalLSAsArraySize();
                        updatePacket->setAsExternalLSAsArraySize(asExternalLSACount + 1);
                        updatePacket->setAsExternalLSAs(asExternalLSACount, *asExternalLSA);
                        unsigned short lsAge = updatePacket->getAsExternalLSAs(asExternalLSACount).getHeader().getLsAge();
                        if (lsAge < MAX_AGE - parentInterface->getTransmissionDelay()) {
                            updatePacket->getAsExternalLSAs(asExternalLSACount).getHeader().setLsAge(lsAge + parentInterface->getTransmissionDelay());
                        } else {
                            updatePacket->getAsExternalLSAs(asExternalLSACount).getHeader().setLsAge(MAX_AGE);
                        }
                    }
                    break;
                default: break;
            }
        }
        it++;
    }
    updatePacket->setByteLength(packetLength - IP_MAX_HEADER_BYTES);
    OSPF::MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    int ttl = (parentInterface->getType() == OSPF::Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
    messageHandler->sendPacket(updatePacket, neighborIPAddress, parentInterface->getIfIndex(), ttl);
}
void OSPF::Neighbor::sendDatabaseDescriptionPacket (bool init = false)
Referenced by OSPF::DatabaseDescriptionHandler::processDDPacket(), OSPF::NeighborStateExchangeStart::processEvent(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateInit::processEvent(), OSPF::NeighborStateFull::processEvent(), OSPF::NeighborStateTwoWay::processEvent(), OSPF::NeighborStateExchange::processEvent(), and OSPF::DatabaseDescriptionHandler::processPacket().
{
    OSPFDatabaseDescriptionPacket* ddPacket = new OSPFDatabaseDescriptionPacket();
    ddPacket->setType(DATABASE_DESCRIPTION_PACKET);
    ddPacket->setRouterID(IPv4Address(parentInterface->getArea()->getRouter()->getRouterID()));
    ddPacket->setAreaID(IPv4Address(parentInterface->getArea()->getAreaID()));
    ddPacket->setAuthenticationType(parentInterface->getAuthenticationType());
    OSPF::AuthenticationKeyType authKey = parentInterface->getAuthenticationKey();
    for (int i = 0; i < 8; i++) {
        ddPacket->setAuthentication(i, authKey.bytes[i]);
    }
    if (parentInterface->getType() != OSPF::Interface::VIRTUAL) {
        ddPacket->setInterfaceMTU(parentInterface->getMTU());
    } else {
        ddPacket->setInterfaceMTU(0);
    }
    OSPFOptions options;
    memset(&options, 0, sizeof(OSPFOptions));
    options.E_ExternalRoutingCapability = parentInterface->getArea()->getExternalRoutingCapability();
    ddPacket->setOptions(options);
    ddPacket->setDdSequenceNumber(ddSequenceNumber);
    long maxPacketSize = (((IP_MAX_HEADER_BYTES + OSPF_HEADER_LENGTH + OSPF_DD_HEADER_LENGTH + OSPF_LSA_HEADER_LENGTH) > parentInterface->getMTU()) ?
                          IPV4_DATAGRAM_LENGTH :
                          parentInterface->getMTU()) - IP_MAX_HEADER_BYTES;
    long packetSize = OSPF_HEADER_LENGTH + OSPF_DD_HEADER_LENGTH;
    if (init || databaseSummaryList.empty()) {
        ddPacket->setLsaHeadersArraySize(0);
    } else {
        // delete included LSAs from summary list
        // (they are still in lastTransmittedDDPacket)
        while ((!databaseSummaryList.empty()) && (packetSize <= (maxPacketSize - OSPF_LSA_HEADER_LENGTH))) {
            unsigned long headerCount = ddPacket->getLsaHeadersArraySize();
            OSPFLSAHeader* lsaHeader = *(databaseSummaryList.begin());
            ddPacket->setLsaHeadersArraySize(headerCount + 1);
            ddPacket->setLsaHeaders(headerCount, *lsaHeader);
            delete lsaHeader;
            databaseSummaryList.pop_front();
            packetSize += OSPF_LSA_HEADER_LENGTH;
        }
    }
    OSPFDDOptions ddOptions;
    memset(&ddOptions, 0, sizeof(OSPFDDOptions));
    if (init) {
        ddOptions.I_Init = true;
        ddOptions.M_More = true;
        ddOptions.MS_MasterSlave = true;
    } else {
        ddOptions.I_Init = false;
        ddOptions.M_More = (databaseSummaryList.empty()) ? false : true;
        ddOptions.MS_MasterSlave = (databaseExchangeRelationship == OSPF::Neighbor::MASTER) ? true : false;
    }
    ddPacket->setDdOptions(ddOptions);
    ddPacket->setByteLength(packetSize);
    OSPF::MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    int ttl = (parentInterface->getType() == OSPF::Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
    if (parentInterface->getType() == OSPF::Interface::POINTTOPOINT) {
        messageHandler->sendPacket(ddPacket, IPv4Address::ALL_OSPF_ROUTERS_MCAST, parentInterface->getIfIndex(), ttl);
    } else {
        messageHandler->sendPacket(ddPacket, neighborIPAddress, parentInterface->getIfIndex(), ttl);
    }
    if (lastTransmittedDDPacket != NULL) {
        delete lastTransmittedDDPacket;
    }
    lastTransmittedDDPacket = new OSPFDatabaseDescriptionPacket(*ddPacket);
}
void OSPF::Neighbor::sendLinkStateRequestPacket ()
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateLoading::processEvent(), and OSPF::DatabaseDescriptionHandler::processPacket().
{
    OSPFLinkStateRequestPacket* requestPacket = new OSPFLinkStateRequestPacket();
    requestPacket->setType(LINKSTATE_REQUEST_PACKET);
    requestPacket->setRouterID(IPv4Address(parentInterface->getArea()->getRouter()->getRouterID()));
    requestPacket->setAreaID(IPv4Address(parentInterface->getArea()->getAreaID()));
    requestPacket->setAuthenticationType(parentInterface->getAuthenticationType());
    OSPF::AuthenticationKeyType authKey = parentInterface->getAuthenticationKey();
    for (int i = 0; i < 8; i++) {
        requestPacket->setAuthentication(i, authKey.bytes[i]);
    }
    long maxPacketSize = (((IP_MAX_HEADER_BYTES + OSPF_HEADER_LENGTH + OSPF_REQUEST_LENGTH) > parentInterface->getMTU()) ?
                          IPV4_DATAGRAM_LENGTH :
                          parentInterface->getMTU()) - IP_MAX_HEADER_BYTES;
    long packetSize = OSPF_HEADER_LENGTH;
    if (linkStateRequestList.empty()) {
        requestPacket->setRequestsArraySize(0);
    } else {
        std::list<OSPFLSAHeader*>::iterator it = linkStateRequestList.begin();
        while ((it != linkStateRequestList.end()) && (packetSize <= (maxPacketSize - OSPF_REQUEST_LENGTH))) {
            unsigned long requestCount = requestPacket->getRequestsArraySize();
            OSPFLSAHeader* requestHeader = (*it);
            LSARequest request;
            request.lsType = requestHeader->getLsType();
            request.linkStateID = requestHeader->getLinkStateID();
            request.advertisingRouter = requestHeader->getAdvertisingRouter();
            requestPacket->setRequestsArraySize(requestCount + 1);
            requestPacket->setRequests(requestCount, request);
            packetSize += OSPF_REQUEST_LENGTH;
            it++;
        }
    }
    requestPacket->setByteLength(packetSize);
    OSPF::MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    int ttl = (parentInterface->getType() == OSPF::Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
    if (parentInterface->getType() == OSPF::Interface::POINTTOPOINT) {
        messageHandler->sendPacket(requestPacket, IPv4Address::ALL_OSPF_ROUTERS_MCAST, parentInterface->getIfIndex(), ttl);
    } else {
        messageHandler->sendPacket(requestPacket, neighborIPAddress, parentInterface->getIfIndex(), ttl);
    }
}
void OSPF::Neighbor::setAddress (IPv4Address address) [inline]
Referenced by OSPF::Area::calculateShortestPathTree(), OSPFRouting::loadInterfaceParameters(), and OSPF::HelloHandler::processPacket().
{ neighborIPAddress = address; }
void OSPF::Neighbor::setBackupDesignatedRouter (DesignatedRouterID routerID) [inline]
Referenced by OSPF::HelloHandler::processPacket().
{ neighborsBackupDesignatedRouter = routerID; }
void OSPF::Neighbor::setDatabaseExchangeRelationship (DatabaseExchangeRelationshipType relation) [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processPacket().
{ databaseExchangeRelationship = relation; }
void OSPF::Neighbor::setDDSequenceNumber (unsigned long sequenceNumber) [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processDDPacket(), and OSPF::DatabaseDescriptionHandler::processPacket().
{ ddSequenceNumber = sequenceNumber; }
void OSPF::Neighbor::setDesignatedRouter (DesignatedRouterID routerID) [inline]
Referenced by OSPF::HelloHandler::processPacket().
{ neighborsDesignatedRouter = routerID; }
void OSPF::Neighbor::setInterface (Interface * intf) [inline]
Referenced by OSPF::Interface::addNeighbor().
{ parentInterface = intf; }
void OSPF::Neighbor::setLastReceivedDDPacket (DDPacketID packetID) [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processPacket().
{ lastReceivedDDPacket = packetID; }
void OSPF::Neighbor::setNeighborID (RouterID id) [inline]
Referenced by OSPFRouting::loadVirtualLink(), and OSPF::HelloHandler::processPacket().
{ neighborID = id; }
void OSPF::Neighbor::setOptions (OSPFOptions options) [inline]
Referenced by OSPF::DatabaseDescriptionHandler::processPacket().
{ neighborOptions = options; }
void OSPF::Neighbor::setPriority (unsigned char priority) [inline]
Referenced by OSPFRouting::loadInterfaceParameters(), and OSPF::HelloHandler::processPacket().
{ neighborPriority = priority; }
void OSPF::Neighbor::setRouterDeadInterval (short interval) [inline]
Referenced by OSPF::HelloHandler::processPacket().
{ neighborsRouterDeadInterval = interval; }
void OSPF::Neighbor::setupDesignatedRouters (bool setUp) [inline]
Referenced by OSPF::HelloHandler::processPacket().
{ designatedRoutersSetUp = setUp; }
void OSPF::Neighbor::startRequestRetransmissionTimer ()
Referenced by OSPF::NeighborStateExchange::processEvent(), OSPF::NeighborStateLoading::processEvent(), and OSPF::DatabaseDescriptionHandler::processPacket().
{
    MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    messageHandler->startTimer(requestRetransmissionTimer, parentInterface->getRetransmissionInterval());
    requestRetransmissionTimerActive = true;
}
void OSPF::Neighbor::startUpdateRetransmissionTimer ()
Referenced by OSPF::Interface::floodLSA(), OSPF::NeighborStateLoading::processEvent(), OSPF::NeighborStateFull::processEvent(), and OSPF::NeighborStateExchange::processEvent().
{
    MessageHandler* messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
    messageHandler->startTimer(updateRetransmissionTimer, parentInterface->getRetransmissionInterval());
    updateRetransmissionTimerActive = true;
}
Friends And Related Function Documentation
friend class NeighborState [friend]
Member Data Documentation
DatabaseExchangeRelationshipType OSPF::Neighbor::databaseExchangeRelationship [private]
Referenced by getDatabaseExchangeRelationship(), and setDatabaseExchangeRelationship().
std::list<OSPFLSAHeader*> OSPF::Neighbor::databaseSummaryList [private]
Referenced by getDatabaseSummaryListCount().
OSPFTimer* OSPF::Neighbor::ddRetransmissionTimer [private]
Referenced by getDDRetransmissionTimer(), and Neighbor().
unsigned long OSPF::Neighbor::ddSequenceNumber [private]
Referenced by getDDSequenceNumber(), incrementDDSequenceNumber(), and setDDSequenceNumber().
unsigned long OSPF::Neighbor::ddSequenceNumberInitSeed = 0 [static, private]
bool OSPF::Neighbor::designatedRoutersSetUp [private]
Referenced by designatedRoutersAreSetUp(), and setupDesignatedRouters().
bool OSPF::Neighbor::firstAdjacencyInited [private]
Referenced by isFirstAdjacencyInited().
OSPFTimer* OSPF::Neighbor::inactivityTimer [private]
Referenced by getInactivityTimer(), and Neighbor().
DDPacketID OSPF::Neighbor::lastReceivedDDPacket [private]
Referenced by getLastReceivedDDPacket(), Neighbor(), and setLastReceivedDDPacket().
OSPFDatabaseDescriptionPacket* OSPF::Neighbor::lastTransmittedDDPacket [private]
std::list<OSPFLSAHeader*> OSPF::Neighbor::linkStateRequestList [private]
Referenced by isLinkStateRequestListEmpty(), and popFirstLinkStateRequest().
std::list<OSPFLSA*> OSPF::Neighbor::linkStateRetransmissionList [private]
Referenced by isLinkStateRetransmissionListEmpty().
RouterID OSPF::Neighbor::neighborID [private]
Referenced by getNeighborID(), and setNeighborID().
IPv4Address OSPF::Neighbor::neighborIPAddress [private]
Referenced by getAddress(), and setAddress().
OSPFOptions OSPF::Neighbor::neighborOptions [private]
Referenced by getOptions(), and setOptions().
unsigned char OSPF::Neighbor::neighborPriority [private]
Referenced by getPriority(), and setPriority().
DesignatedRouterID OSPF::Neighbor::neighborsBackupDesignatedRouter [private]
Referenced by getBackupDesignatedRouter(), and setBackupDesignatedRouter().
DesignatedRouterID OSPF::Neighbor::neighborsDesignatedRouter [private]
Referenced by getDesignatedRouter(), and setDesignatedRouter().
short OSPF::Neighbor::neighborsRouterDeadInterval [private]
Referenced by getRouterDeadInterval(), and setRouterDeadInterval().
Interface* OSPF::Neighbor::parentInterface [private]
Referenced by getInterface(), and setInterface().
OSPFTimer* OSPF::Neighbor::pollTimer [private]
Referenced by getPollTimer(), and Neighbor().
NeighborState* OSPF::Neighbor::previousState [private]
Referenced by Neighbor().
OSPFTimer* OSPF::Neighbor::requestRetransmissionTimer [private]
Referenced by Neighbor().
bool OSPF::Neighbor::requestRetransmissionTimerActive [private]
Referenced by isRequestRetransmissionTimerActive().
NeighborState* OSPF::Neighbor::state [private]
Referenced by Neighbor().
std::list<TransmittedLSA> OSPF::Neighbor::transmittedLSAs [private]
OSPFTimer* OSPF::Neighbor::updateRetransmissionTimer [private]
Referenced by getUpdateRetransmissionTimer(), and Neighbor().
bool OSPF::Neighbor::updateRetransmissionTimerActive [private]
Referenced by isUpdateRetransmissionTimerActive().
The documentation for this class was generated from the following files:
OSPFNeighbor.h
OSPFNeighbor.cc