INET Framework for OMNeT++/OMNEST: OSPFRouting Class Reference
OSPFRouting Class Reference
OMNeT++ module class acting as a facade for the OSPF data structure.
#include <OSPFRouting.h>
Public Member Functions
OSPFRouting ()
virtual ~OSPFRouting ()
void insertExternalRoute (int ifIndex, const OSPF::IPv4AddressRange &netAddr)
Insert a route learn by BGP in OSPF routingTable as an external route.
bool checkExternalRoute (const IPv4Address &route)
Return true if the route is in OSPF external LSA Table, false else.
Protected Member Functions
virtual int numInitStages () const
virtual void initialize (int stage)
OMNeT++ init method.
virtual void handleMessage (cMessage *msg)
Forwards OSPF messages to the message handler object of the OSPF data structure.
Private Member Functions
int getIntAttrOrPar (const cXMLElement &ifConfig, const char *name) const
bool getBoolAttrOrPar (const cXMLElement &ifConfig, const char *name) const
const char * getStrAttrOrPar (const cXMLElement &ifConfig, const char *name) const
int resolveInterfaceName (const std::string &name) const
Looks up the interface name in IInterfaceTable, and returns interfaceId a.k.a ifIndex.
InterfaceEntry * getInterfaceByXMLAttributesOf (const cXMLElement &ifConfig)
Search an InterfaceEntry in IInterfaceTable by interface name or toward module name an returns the InterfaceEntry pointer or throws an error.
void getAreaListFromXML (const cXMLElement &routerNode, std::set< OSPF::AreaID > &areaList) const
Loads a list of OSPF Areas connected to this router from the config XML.
void loadAreaFromXML (const cXMLElement &asConfig, OSPF::AreaID areaID)
Loads basic configuration information for a given area from the config XML.
void loadAuthenticationConfig (OSPF::Interface *intf, const cXMLElement &ifConfig)
Loads authenticationType and authenticationKey attibutes for a router interface.
void loadInterfaceParameters (const cXMLElement &ifConfig)
Loads OSPF configuration information for a router interface.
void loadExternalRoute (const cXMLElement &externalRouteConfig)
Loads the configuration information of a route outside of the Autonomous System(external route).
void loadHostRoute (const cXMLElement &hostRouteConfig)
Loads the configuration of a host getRoute(a host directly connected to the router).
void loadVirtualLink (const cXMLElement &virtualLinkConfig)
Loads the configuration of an OSPf virtual link(virtual connection between two backbone routers).
bool loadConfigFromXML (cXMLElement *asConfig)
Loads the configuration of the OSPF data structure from the config XML.
void joinMulticastGroups (int interfaceId)
Private Attributes
IInterfaceTable * ift
Provides access to the interface table.
IRoutingTable * rt
Provides access to the IP routing table.
OSPF::Router * ospfRouter
Root object of the OSPF data structure.
Detailed Description
OMNeT++ module class acting as a facade for the OSPF data structure.
Handles the configuration loading and forwards the OMNeT++ messages (OSPF packets).
Constructor & Destructor Documentation
OSPFRouting::OSPFRouting ()
{
    ospfRouter = NULL;
}
OSPFRouting::~OSPFRouting () [virtual]
{
    delete ospfRouter;
}
Member Function Documentation
bool OSPFRouting::checkExternalRoute (const IPv4Address & route)
Return true if the route is in OSPF external LSA Table, false else.
Used by the BGPRouting module.
Referenced by BGPRouting::checkExternalRoute().
{
    for (unsigned long i=1; i < ospfRouter->getASExternalLSACount(); i++)
    {
        OSPF::ASExternalLSA* externalLSA = ospfRouter->getASExternalLSA(i);
        IPv4Address externalAddr = externalLSA->getHeader().getLinkStateID();
        if (externalAddr == route) //FIXME was this meant???
            return true;
    }
    return false;
}
void OSPFRouting::getAreaListFromXML (const cXMLElement & routerNode, std::set< OSPF::AreaID > & areaList) const [private]
Loads a list of OSPF Areas connected to this router from the config XML.
Parameters:
routerNode [in] XML node describing this router.
areaList [out] A set of OSPF Areas connected to this router.
Referenced by loadConfigFromXML().
{
    cXMLElementList routerConfig = routerNode.getChildren();
    for (cXMLElementList::iterator routerConfigIt = routerConfig.begin(); routerConfigIt != routerConfig.end(); routerConfigIt++) {
        std::string nodeName = (*routerConfigIt)->getTagName();
        if ((nodeName == "PointToPointInterface") ||
            (nodeName == "BroadcastInterface") ||
            (nodeName == "NBMAInterface") ||
            (nodeName == "PointToMultiPointInterface"))
        {
            OSPF::AreaID areaID = IPv4Address(getStrAttrOrPar(**routerConfigIt, "areaID"));
            if (areaList.find(areaID) == areaList.end())
                areaList.insert(areaID);
        }
    }
}
bool OSPFRouting::getBoolAttrOrPar (const cXMLElement & ifConfig, const char * name) const [private]
Referenced by loadConfigFromXML().
{
    const char* attrStr = ifConfig.getAttribute(name);
    if (attrStr && *attrStr)
    {
        if (strcmp(attrStr, "true") == 0 || strcmp(attrStr, "1") == 0)
            return true;
        if (strcmp(attrStr, "false") == 0 || strcmp(attrStr, "0") == 0)
            return false;
        throw cRuntimeError("Invalid boolean attribute %s = '%s' at %s", name, attrStr, ifConfig.getSourceLocation());
    }
    return par(name).boolValue();
}
int OSPFRouting::getIntAttrOrPar (const cXMLElement & ifConfig, const char * name) const [private]
Referenced by loadExternalRoute(), loadHostRoute(), loadInterfaceParameters(), and loadVirtualLink().
{
    const char* attrStr = ifConfig.getAttribute(name);
    if (attrStr && *attrStr)
        return atoi(attrStr);
    return par(name).longValue();
}
InterfaceEntry * OSPFRouting::getInterfaceByXMLAttributesOf (const cXMLElement & ifConfig) [private]
Search an InterfaceEntry in IInterfaceTable by interface name or toward module name an returns the InterfaceEntry pointer or throws an error.
Referenced by loadExternalRoute(), loadHostRoute(), and loadInterfaceParameters().
{
    const char *ifName = ifConfig.getAttribute("ifName");
    if (ifName && *ifName) {
        InterfaceEntry* ie = ift->getInterfaceByName(ifName);
        if (!ie)
            throw cRuntimeError("Error reading XML config: IInterfaceTable contains no interface named '%s' at %s", ifName, ifConfig.getSourceLocation());
        return ie;
    }
    const char *toward = getRequiredAttribute(ifConfig, "toward");
    cModule *destnode = simulation.getModuleByPath(toward);
    if (!destnode)
        error("toward module `%s' not found at %s", toward, ifConfig.getSourceLocation());
    cModule *host = ift->getHostModule();
    for (int i=0; i < ift->getNumInterfaces(); i++)
    {
        InterfaceEntry *ie = ift->getInterface(i);
        if (ie)
        {
            int gateId = ie->getNodeOutputGateId();
            if ((gateId != -1) && (host->gate(gateId)->pathContains(destnode)))
                return ie;
        }
    }
    throw cRuntimeError("Error reading XML config: IInterfaceTable contains no interface toward '%s' at %s", toward, ifConfig.getSourceLocation());
}
const char * OSPFRouting::getStrAttrOrPar (const cXMLElement & ifConfig, const char * name) const [private]
Referenced by getAreaListFromXML(), loadAuthenticationConfig(), loadExternalRoute(), loadHostRoute(), and loadInterfaceParameters().
{
    const char* attrStr = ifConfig.getAttribute(name);
    if (attrStr && *attrStr)
        return attrStr;
    return par(name).stringValue();
}
void OSPFRouting::handleMessage (cMessage * msg) [protected, virtual]
Forwards OSPF messages to the message handler object of the OSPF data structure.
Parameters:
msg [in] The OSPF message.
{
    ospfRouter->getMessageHandler()->messageReceived(msg);
}
void OSPFRouting::initialize (int stage) [protected, virtual]
OMNeT++ init method.
Runs at stage 4, after interfaces are registered(stage 0), the routing table is initialized(stage 1), and routerId gets assigned(stage 3). Loads OSPF configuration information from the config XML.
Parameters:
stage [in] The initialization stage.
{
    // we have to wait for stage 2 until interfaces get registered(stage 0)
    // and routerId gets assigned(stage 3)
    if (stage == 4)
    {
        rt = RoutingTableAccess().get();
        ift = InterfaceTableAccess().get();
        // Get routerId
        ospfRouter = new OSPF::Router(rt->getRouterId(), this);
        // read the OSPF AS configuration
        cXMLElement *ospfConfig = par("ospfConfig").xmlValue();
        if (!loadConfigFromXML(ospfConfig))
            error("Error reading AS configuration from %s", ospfConfig->getSourceLocation());
        ospfRouter->addWatches();
    }
}
void OSPFRouting::insertExternalRoute (int ifIndex, const OSPF::IPv4AddressRange & netAddr)
Insert a route learn by BGP in OSPF routingTable as an external route.
Used by the BGPRouting module. : interface ID
Referenced by BGPRouting::decisionProcess().
{
    simulation.setContext(this);
    OSPFASExternalLSAContents newExternalContents;
    newExternalContents.setRouteCost(OSPF_BGP_DEFAULT_COST);
    newExternalContents.setExternalRouteTag(OSPF_EXTERNAL_ROUTES_LEARNED_BY_BGP);
    const IPv4Address netmask = netAddr.mask;
    newExternalContents.setNetworkMask(netmask);
    ospfRouter->updateExternalRoute(netAddr.address, newExternalContents, ifIndex);
}
void OSPFRouting::joinMulticastGroups (int interfaceId) [private]
Referenced by loadExternalRoute(), loadHostRoute(), and loadInterfaceParameters().
{
    InterfaceEntry *ie = ift->getInterfaceById(interfaceId);
    if (!ie)
        error("Interface id=%d does not exist", interfaceId);
    IPv4InterfaceData *ipv4Data = ie->ipv4Data();
    if (!ipv4Data)
        error("Interface %s (id=%d) does not have IPv4 data", ie->getName(), interfaceId);
    ipv4Data->joinMulticastGroup(IPv4Address::ALL_OSPF_ROUTERS_MCAST);
    ipv4Data->joinMulticastGroup(IPv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST);
}
void OSPFRouting::loadAreaFromXML (const cXMLElement & asConfig, OSPF::AreaID areaID) [private]
Loads basic configuration information for a given area from the config XML.
Reads the configured address ranges, and whether this Area should be handled as a stub Area.
Parameters:
asConfig [in] XML node describing the configuration of the whole Autonomous System.
areaID [in] The Area to be added to the OSPF data structure.
Referenced by loadConfigFromXML().
{
    std::string areaXPath("Area[@id='");
    areaXPath += areaID.str(false);
    areaXPath += "']";
    cXMLElement* areaConfig = asConfig.getElementByPath(areaXPath.c_str());
    if (areaConfig == NULL) {
        error("No configuration for Area ID: %s at %s", areaID.str(false).c_str(), asConfig.getSourceLocation());
    }
    else {
        EV << "    loading info for Area id = " << areaID.str(false) << "\n";
    }
    OSPF::Area* area = new OSPF::Area(areaID);
    cXMLElementList areaDetails = areaConfig->getChildren();
    for (cXMLElementList::iterator arIt = areaDetails.begin(); arIt != areaDetails.end(); arIt++) {
        std::string nodeName = (*arIt)->getTagName();
        if (nodeName == "AddressRange") {
            OSPF::IPv4AddressRange addressRange;
            addressRange.address = ipv4AddressFromAddressString(getRequiredAttribute(**arIt, "address"));
            addressRange.mask = ipv4NetmaskFromAddressString(getRequiredAttribute(**arIt, "mask"));
            addressRange.address = addressRange.address & addressRange.mask;
            std::string status = getRequiredAttribute(**arIt, "status");
            area->addAddressRange(addressRange, status == "Advertise");
        }
        else if (nodeName == "Stub") {
            if (areaID == OSPF::BACKBONE_AREAID)
                error("The backbone cannot be configured as a stub at %s", (*arIt)->getSourceLocation());
            area->setExternalRoutingCapability(false);
            area->setStubDefaultCost(atoi(getRequiredAttribute(**arIt, "defaultCost")));
        }
        else
            error("Invalid node '%s' at %s", nodeName.c_str(), (*arIt)->getSourceLocation());
    }
    // Add the Area to the router
    ospfRouter->addArea(area);
}
void OSPFRouting::loadAuthenticationConfig (OSPF::Interface * intf, const cXMLElement & ifConfig) [private]
Loads authenticationType and authenticationKey attibutes for a router interface.
Referenced by loadInterfaceParameters(), and loadVirtualLink().
{
    std::string authenticationType = getStrAttrOrPar(ifConfig, "authenticationType");
    if (authenticationType == "SimplePasswordType") {
        intf->setAuthenticationType(OSPF::SIMPLE_PASSWORD_TYPE);
    } else if (authenticationType == "CrytographicType") {
        intf->setAuthenticationType(OSPF::CRYTOGRAPHIC_TYPE);
    } else if (authenticationType == "NullType") {
        intf->setAuthenticationType(OSPF::NULL_TYPE);
    } else {
        throw cRuntimeError("Invalid AuthenticationType '%s' at %s", authenticationType.c_str(), ifConfig.getSourceLocation());
    }
    std::string key = getStrAttrOrPar(ifConfig, "authenticationKey");
    OSPF::AuthenticationKeyType keyValue;
    memset(keyValue.bytes, 0, 8 * sizeof(char));
    int keyLength = key.length();
    if ((keyLength > 4) && (keyLength <= 18) && (keyLength % 2 == 0) && (key[0] == '0') && (key[1] == 'x')) {
        for (int i = keyLength; (i > 2); i -= 2) {
            keyValue.bytes[(i - 2) / 2] = hexPairToByte(key[i - 1], key[i]);
        }
    }
    intf->setAuthenticationKey(keyValue);
}
bool OSPFRouting::loadConfigFromXML (cXMLElement * asConfig) [private]
Loads the configuration of the OSPF data structure from the config XML.
Parameters:
filename [in] The path of the XML config file.
Returns:
True if the configuration was succesfully loaded.
Exceptions:
an getError() otherwise.
Referenced by initialize().
{
    if (strcmp(asConfig->getTagName(), "OSPFASConfig"))
        error("Cannot read OSPF configuration, unaccepted '%s' note at %s", asConfig->getTagName(), asConfig->getSourceLocation());
    cModule *myNode = findContainingNode(this);
    ASSERT(myNode);
    std::string nodeFullPath = myNode->getFullPath();
    std::string nodeShortenedFullPath = nodeFullPath.substr(nodeFullPath.find('.') + 1);
    // load information on this router
    cXMLElementList routers = asConfig->getElementsByTagName("Router");
    cXMLElement* routerNode = NULL;
    for (cXMLElementList::iterator routerIt = routers.begin(); routerIt != routers.end(); routerIt++) {
        const char* nodeName = getRequiredAttribute(*(*routerIt), "name");
        inet::PatternMatcher pattern(nodeName, true, true, true);
        if (pattern.matches(nodeFullPath.c_str()) || pattern.matches(nodeShortenedFullPath.c_str()))   // match Router@name and fullpath of my node
        {
            routerNode = *routerIt;
            break;
        }
    }
    if (routerNode == NULL) {
        error("No configuration for Router '%s' at '%s'", nodeFullPath.c_str(), asConfig->getSourceLocation());
    }
    EV << "OSPFRouting: Loading info for Router " << nodeFullPath << "\n";
    bool rfc1583Compatible = getBoolAttrOrPar(*routerNode, "RFC1583Compatible");
    ospfRouter->setRFC1583Compatibility(rfc1583Compatible);
    std::set<OSPF::AreaID> areaList;
    getAreaListFromXML(*routerNode, areaList);
    // if the router is an area border router then it MUST be part of the backbone(area 0)
    if ((areaList.size() > 1) && (areaList.find(OSPF::BACKBONE_AREAID) == areaList.end())) {
        areaList.insert(OSPF::BACKBONE_AREAID);
    }
    // load area information
    for (std::set<OSPF::AreaID>::iterator areaIt = areaList.begin(); areaIt != areaList.end(); areaIt++) {
        loadAreaFromXML(*asConfig, *areaIt);
    }
    // load interface information
    cXMLElementList routerConfig = routerNode->getChildren();
    for (cXMLElementList::iterator routerConfigIt = routerConfig.begin(); routerConfigIt != routerConfig.end(); routerConfigIt++) {
        std::string nodeName = (*routerConfigIt)->getTagName();
        if ((nodeName == "PointToPointInterface") ||
            (nodeName == "BroadcastInterface") ||
            (nodeName == "NBMAInterface") ||
            (nodeName == "PointToMultiPointInterface"))
        {
            loadInterfaceParameters(*(*routerConfigIt));
        }
        else if (nodeName == "ExternalInterface") {
            loadExternalRoute(*(*routerConfigIt));
        }
        else if (nodeName == "HostInterface") {
            loadHostRoute(*(*routerConfigIt));
        }
        else if (nodeName == "VirtualLink") {
            loadVirtualLink(*(*routerConfigIt));
        } else {
            throw cRuntimeError("Invalid '%s' node in Router '%s' at %s",
                    nodeName.c_str(), nodeFullPath.c_str(), (*routerConfigIt)->getSourceLocation());
        }
    }
    return true;
}
void OSPFRouting::loadExternalRoute (const cXMLElement & externalRouteConfig) [private]
Loads the configuration information of a route outside of the Autonomous System(external route).
Parameters:
externalRouteConfig [in] XML node describing the parameters of an external route.
Referenced by loadConfigFromXML().
{
    InterfaceEntry *ie = getInterfaceByXMLAttributesOf(externalRouteConfig);
    int ifIndex = ie->getInterfaceId();
    OSPFASExternalLSAContents asExternalRoute;
    OSPF::RoutingTableEntry externalRoutingEntry; // only used here to keep the path cost calculation in one place
    OSPF::IPv4AddressRange networkAddress;
    EV << "        loading ExternalInterface " << ie->getName() << " ifIndex[" << ifIndex << "]\n";
    joinMulticastGroups(ifIndex);
    networkAddress.address = ipv4AddressFromAddressString(getRequiredAttribute(externalRouteConfig, "advertisedExternalNetworkAddress"));
    networkAddress.mask = ipv4NetmaskFromAddressString(getRequiredAttribute(externalRouteConfig, "advertisedExternalNetworkMask"));
    networkAddress.address = networkAddress.address & networkAddress.mask;
    asExternalRoute.setNetworkMask(networkAddress.mask);
    int routeCost = getIntAttrOrPar(externalRouteConfig, "externalInterfaceOutputCost");
    asExternalRoute.setRouteCost(routeCost);
    std::string metricType = getStrAttrOrPar(externalRouteConfig, "externalInterfaceOutputType");
    if (metricType == "Type2") {
        asExternalRoute.setE_ExternalMetricType(true);
        externalRoutingEntry.setType2Cost(routeCost);
        externalRoutingEntry.setPathType(OSPF::RoutingTableEntry::TYPE2_EXTERNAL);
    } else if (metricType == "Type1") {
        asExternalRoute.setE_ExternalMetricType(false);
        externalRoutingEntry.setCost(routeCost);
        externalRoutingEntry.setPathType(OSPF::RoutingTableEntry::TYPE1_EXTERNAL);
    } else {
        throw cRuntimeError("Invalid 'externalInterfaceOutputType' at interface '%s' at ", ie->getName(), externalRouteConfig.getSourceLocation());
    }
    asExternalRoute.setForwardingAddress(ipv4AddressFromAddressString(getRequiredAttribute(externalRouteConfig, "forwardingAddress")));
    long externalRouteTagVal = 0;   // default value
    const char *externalRouteTag = externalRouteConfig.getAttribute("externalRouteTag");
    if (externalRouteTag && *externalRouteTag)
    {
        char *endp = NULL;
        externalRouteTagVal = strtol(externalRouteTag, &endp, 0);
        if(*endp)
            throw cRuntimeError("Invalid externalRouteTag='%s' at %s", externalRouteTag, externalRouteConfig.getSourceLocation());
    }
    asExternalRoute.setExternalRouteTag(externalRouteTagVal);
    // add the external route to the OSPF data structure
    ospfRouter->updateExternalRoute(networkAddress.address, asExternalRoute, ifIndex);
}
void OSPFRouting::loadHostRoute (const cXMLElement & hostRouteConfig) [private]
Loads the configuration of a host getRoute(a host directly connected to the router).
Parameters:
hostRouteConfig [in] XML node describing the parameters of a host route.
Referenced by loadConfigFromXML().
{
    OSPF::HostRouteParameters hostParameters;
    OSPF::AreaID hostArea;
    InterfaceEntry *ie = getInterfaceByXMLAttributesOf(hostRouteConfig);
    int ifIndex = ie->getInterfaceId();
    hostParameters.ifIndex = ifIndex;
    EV << "        loading HostInterface " << ie->getName() << " ifIndex[" << ifIndex << "]\n";
    joinMulticastGroups(hostParameters.ifIndex);
    hostArea = ipv4AddressFromAddressString(getStrAttrOrPar(hostRouteConfig, "areaID"));
    hostParameters.address = ipv4AddressFromAddressString(getRequiredAttribute(hostRouteConfig, "attachedHost"));
    hostParameters.linkCost = getIntAttrOrPar(hostRouteConfig, "linkCost");
    // add the host route to the OSPF data structure.
    OSPF::Area* area = ospfRouter->getAreaByID(hostArea);
    if (area != NULL) {
        area->addHostRoute(hostParameters);
    } else {
        error("Loading HostInterface '%s' aborted, unknown area %s at %s", ie->getName(), hostArea.str(false).c_str(), hostRouteConfig.getSourceLocation());
    }
}
void OSPFRouting::loadInterfaceParameters (const cXMLElement & ifConfig) [private]
Loads OSPF configuration information for a router interface.
Handles POINTTOPOINT, BROADCAST, NBMA and POINTTOMULTIPOINT interfaces.
Parameters:
ifConfig [in] XML node describing the configuration of an OSPF interface.
Referenced by loadConfigFromXML().
{
    OSPF::Interface* intf = new OSPF::Interface;
    InterfaceEntry *ie = getInterfaceByXMLAttributesOf(ifConfig);
    int ifIndex = ie->getInterfaceId();
    std::string interfaceType = ifConfig.getTagName();
    EV << "        loading " << interfaceType << " " << ie->getName() << " (ifIndex=" << ifIndex << ")\n";
    intf->setIfIndex(ifIndex);
    if (interfaceType == "PointToPointInterface") {
        intf->setType(OSPF::Interface::POINTTOPOINT);
    } else if (interfaceType == "BroadcastInterface") {
        intf->setType(OSPF::Interface::BROADCAST);
    } else if (interfaceType == "NBMAInterface") {
        intf->setType(OSPF::Interface::NBMA);
    } else if (interfaceType == "PointToMultiPointInterface") {
        intf->setType(OSPF::Interface::POINTTOMULTIPOINT);
    } else {
        delete intf;
        error("Unknown interface type '%s' for interface %s (ifIndex=%d) at %s",
                interfaceType.c_str(), ie->getName(), ifIndex, ifConfig.getSourceLocation());
    }
    joinMulticastGroups(ifIndex);
    OSPF::AreaID areaID = IPv4Address(getStrAttrOrPar(ifConfig, "areaID"));
    intf->setAreaID(areaID);
    intf->setOutputCost(getIntAttrOrPar(ifConfig, "interfaceOutputCost"));
    intf->setRetransmissionInterval(getIntAttrOrPar(ifConfig, "retransmissionInterval"));
    intf->setTransmissionDelay(getIntAttrOrPar(ifConfig, "interfaceTransmissionDelay"));
    if (interfaceType == "BroadcastInterface" || interfaceType == "NBMAInterface")
        intf->setRouterPriority(getIntAttrOrPar(ifConfig, "routerPriority"));
    intf->setHelloInterval(getIntAttrOrPar(ifConfig, "helloInterval"));
    intf->setRouterDeadInterval(getIntAttrOrPar(ifConfig, "routerDeadInterval"));
    loadAuthenticationConfig(intf, ifConfig);
    if (interfaceType == "NBMAInterface")
        intf->setPollInterval(getIntAttrOrPar(ifConfig, "pollInterval"));
    cXMLElementList ifDetails = ifConfig.getChildren();
    for (cXMLElementList::iterator ifElemIt = ifDetails.begin(); ifElemIt != ifDetails.end(); ifElemIt++) {
        std::string nodeName = (*ifElemIt)->getTagName();
        if ((interfaceType == "NBMAInterface") && (nodeName == "NBMANeighborList")) {
            cXMLElementList neighborList = (*ifElemIt)->getChildren();
            for (cXMLElementList::iterator neighborIt = neighborList.begin(); neighborIt != neighborList.end(); neighborIt++) {
                std::string neighborNodeName = (*neighborIt)->getTagName();
                if (neighborNodeName == "NBMANeighbor") {
                    OSPF::Neighbor* neighbor = new OSPF::Neighbor;
                    neighbor->setAddress(ipv4AddressFromAddressString(getRequiredAttribute(**neighborIt, "networkInterfaceAddress")));
                    neighbor->setPriority(atoi(getRequiredAttribute(**neighborIt, "neighborPriority")));
                    intf->addNeighbor(neighbor);
                }
            }
        }
        if ((interfaceType == "PointToMultiPointInterface") && (nodeName == "PointToMultiPointNeighborList")) {
            cXMLElementList neighborList = (*ifElemIt)->getChildren();
            for (cXMLElementList::iterator neighborIt = neighborList.begin(); neighborIt != neighborList.end(); neighborIt++) {
                std::string neighborNodeName = (*neighborIt)->getTagName();
                if (neighborNodeName == "PointToMultiPointNeighbor") {
                    OSPF::Neighbor* neighbor = new OSPF::Neighbor;
                    neighbor->setAddress(ipv4AddressFromAddressString((*neighborIt)->getNodeValue()));
                    intf->addNeighbor(neighbor);
                }
            }
        }
    }
    // add the interface to it's Area
    OSPF::Area* area = ospfRouter->getAreaByID(areaID);
    if (area != NULL) {
        area->addInterface(intf);
        intf->processEvent(OSPF::Interface::INTERFACE_UP); // notification should come from the blackboard...
    } else {
        delete intf;
        error("Loading %s ifIndex[%d] in Area %s aborted at %s", interfaceType.c_str(), ifIndex, areaID.str(false).c_str(), ifConfig.getSourceLocation());
    }
}
void OSPFRouting::loadVirtualLink (const cXMLElement & virtualLinkConfig) [private]
Loads the configuration of an OSPf virtual link(virtual connection between two backbone routers).
Parameters:
virtualLinkConfig [in] XML node describing the parameters of a virtual link.
Referenced by loadConfigFromXML().
{
    OSPF::Interface* intf = new OSPF::Interface;
    std::string endPoint = getRequiredAttribute(virtualLinkConfig, "endPointRouterID");
    OSPF::Neighbor* neighbor = new OSPF::Neighbor;
    EV << "        loading VirtualLink to " << endPoint << "\n";
    intf->setType(OSPF::Interface::VIRTUAL);
    neighbor->setNeighborID(ipv4AddressFromAddressString(endPoint.c_str()));
    intf->addNeighbor(neighbor);
    intf->setTransitAreaID(ipv4AddressFromAddressString(getRequiredAttribute(virtualLinkConfig, "transitAreaID")));
    intf->setRetransmissionInterval(getIntAttrOrPar(virtualLinkConfig, "retransmissionInterval"));
    intf->setTransmissionDelay(getIntAttrOrPar(virtualLinkConfig, "interfaceTransmissionDelay"));
    intf->setHelloInterval(getIntAttrOrPar(virtualLinkConfig, "helloInterval"));
    intf->setRouterDeadInterval(getIntAttrOrPar(virtualLinkConfig, "routerDeadInterval"));
    loadAuthenticationConfig(intf, virtualLinkConfig);
    // add the virtual link to the OSPF data structure.
    OSPF::Area* transitArea = ospfRouter->getAreaByID(intf->getAreaID());
    OSPF::Area* backbone = ospfRouter->getAreaByID(OSPF::BACKBONE_AREAID);
    if ((backbone != NULL) && (transitArea != NULL) && (transitArea->getExternalRoutingCapability())) {
        backbone->addInterface(intf);
    } else {
        error("Loading VirtualLink to %s through Area %s aborted at ", endPoint.c_str(), intf->getAreaID().str(false).c_str(), virtualLinkConfig.getSourceLocation());
        delete intf;
    }
}
virtual int OSPFRouting::numInitStages () const [inline, protected, virtual]
{return 5;}
int OSPFRouting::resolveInterfaceName (const std::string & name) const [private]
Looks up the interface name in IInterfaceTable, and returns interfaceId a.k.a ifIndex.
{
    InterfaceEntry* ie = ift->getInterfaceByName(name.c_str());
    if (!ie)
        throw cRuntimeError("Error reading XML config: IInterfaceTable contains no interface named '%s'", name.c_str());
    return ie->getInterfaceId();
}
Member Data Documentation
IInterfaceTable* OSPFRouting::ift [private]
Provides access to the interface table.
Referenced by getInterfaceByXMLAttributesOf(), initialize(), joinMulticastGroups(), and resolveInterfaceName().
OSPF::Router* OSPFRouting::ospfRouter [private]
Root object of the OSPF data structure.
Referenced by checkExternalRoute(), handleMessage(), initialize(), insertExternalRoute(), loadAreaFromXML(), loadConfigFromXML(), loadExternalRoute(), loadHostRoute(), loadInterfaceParameters(), loadVirtualLink(), OSPFRouting(), and ~OSPFRouting().
IRoutingTable* OSPFRouting::rt [private]
Provides access to the IP routing table.
Referenced by initialize().
The documentation for this class was generated from the following files:
OSPFRouting.h
OSPFRouting.cc