INET Framework for OMNeT++/OMNEST: Ieee80211Mac Class Reference
Ieee80211Mac Class Reference
IEEE 802.11g with e Media Access Control Layer.
#include <Ieee80211Mac.h>
Classes
struct Edca
struct EdcaOutVector
struct Ieee80211ASFTuple
This is used to populate fragments and identify duplicated messages.
Public Member Functions
Construction functions
Ieee80211Mac ()
virtual ~Ieee80211Mac ()
Protected Member Functions
virtual Ieee80211Frame * setBasicBitrate (Ieee80211Frame *frame)
Attaches a PhyControlInfo to the frame which will cause it to be sent at basicBitrate not bitrate (e.g.
virtual Ieee80211Frame * setBitrateFrame (Ieee80211Frame *frame)
int getTimeout (void)
Produce a readable name of the given MAC operation mode.
virtual int getMaxBitrate (void)
virtual int getMinBitrate (void)
virtual void reportDataOk (void)
virtual void reportDataFailed (void)
virtual int getMinTimerTimeout (void)
virtual int getMinSuccessThreshold (void)
virtual int getTimerTimeout (void)
virtual int getSuccessThreshold (void)
virtual void setTimerTimeout (int timer_timeout)
virtual void setSuccessThreshold (int success_threshold)
virtual void reportRecoveryFailure (void)
virtual void reportFailure (void)
virtual bool needRecoveryFallback (void)
virtual bool needNormalFallback (void)
virtual double getBitrate ()
virtual void setBitrate (double b_rate)
virtual void resetCurrentBackOff ()
virtual bool isBackoffPending ()
ModulationType getControlAnswerMode (ModulationType reqMode)
virtual void sendUp (cMessage *msg)
Sends a message to the upper layer.
virtual void removeOldTuplesFromDuplicateMap ()
virtual void promiscousFrame (cMessage *msg)
virtual bool isDuplicated (cMessage *msg)
Initialization functions
virtual int numInitStages () const
Initialization of the module and its variables.
virtual void initialize (int)
Initialization of the module and some variables.
virtual void registerInterface ()
virtual void initializeQueueModule ()
virtual void finish ()
virtual void configureAutoBitRate ()
virtual void initWatches ()
virtual const MACAddress & isInterfaceRegistered ()
Message handing functions
Functions called from other classes to notify about state changes and to handle messages.
virtual void receiveChangeNotification (int category, const cObject *details)
Called by the NotificationBoard whenever a change occurs we're interested in.
virtual void handleCommand (cMessage *msg)
Handle commands (msg kind+control info) coming from upper layers.
virtual void handleSelfMsg (cMessage *msg)
Handle timer self messages.
virtual void handleUpperMsg (cPacket *msg)
Handle messages from upper layer.
virtual void handleLowerMsg (cPacket *msg)
Handle messages from lower (physical) layer.
virtual void handleWithFSM (cMessage *msg)
Handle all kinds of messages and notifications with the state machine.
Timing functions
Calculate various timings based on transmission rate and physical layer charactersitics.
virtual simtime_t getSIFS ()
virtual simtime_t getSlotTime ()
virtual simtime_t getDIFS (int category=-1)
virtual simtime_t getAIFS (int AccessCategory)
virtual simtime_t getEIFS ()
virtual simtime_t getPIFS ()
virtual simtime_t computeBackoffPeriod (Ieee80211Frame *msg, int r)
virtual simtime_t getHeaderTime (double bitrate)
Timer functions
These functions have the side effect of starting the corresponding timers.
virtual void scheduleSIFSPeriod (Ieee80211Frame *frame)
virtual void scheduleDIFSPeriod ()
virtual void cancelDIFSPeriod ()
virtual void scheduleAIFSPeriod ()
virtual void rescheduleAIFSPeriod (int AccessCategory)
virtual void cancelAIFSPeriod ()
virtual void scheduleDataTimeoutPeriod (Ieee80211DataOrMgmtFrame *frame)
virtual void scheduleMulticastTimeoutPeriod (Ieee80211DataOrMgmtFrame *frame)
virtual void cancelTimeoutPeriod ()
virtual void scheduleCTSTimeoutPeriod ()
virtual void scheduleReservePeriod (Ieee80211Frame *frame)
Schedule network allocation period according to 9.2.5.4.
virtual void invalidateBackoffPeriod ()
Generates a new backoff period based on the contention window.
virtual bool isInvalidBackoffPeriod ()
virtual void generateBackoffPeriod ()
virtual void decreaseBackoffPeriod ()
virtual void scheduleBackoffPeriod ()
virtual void cancelBackoffPeriod ()
virtual void finishReception ()
Frame transmission functions
virtual void sendACKFrameOnEndSIFS ()
virtual void sendACKFrame (Ieee80211DataOrMgmtFrame *frame)
virtual void sendRTSFrame (Ieee80211DataOrMgmtFrame *frameToSend)
virtual void sendCTSFrameOnEndSIFS ()
virtual void sendCTSFrame (Ieee80211RTSFrame *rtsFrame)
virtual void sendDataFrameOnEndSIFS (Ieee80211DataOrMgmtFrame *frameToSend)
virtual void sendDataFrame (Ieee80211DataOrMgmtFrame *frameToSend)
virtual void sendMulticastFrame (Ieee80211DataOrMgmtFrame *frameToSend)
Frame builder functions
virtual Ieee80211DataOrMgmtFrame * buildDataFrame (Ieee80211DataOrMgmtFrame *frameToSend)
virtual Ieee80211ACKFrame * buildACKFrame (Ieee80211DataOrMgmtFrame *frameToACK)
virtual Ieee80211RTSFrame * buildRTSFrame (Ieee80211DataOrMgmtFrame *frameToSend)
virtual Ieee80211CTSFrame * buildCTSFrame (Ieee80211RTSFrame *rtsFrame)
virtual Ieee80211DataOrMgmtFrame * buildMulticastFrame (Ieee80211DataOrMgmtFrame *frameToSend)
Utility functions
virtual void finishCurrentTransmission ()
virtual void giveUpCurrentTransmission ()
virtual void retryCurrentTransmission ()
virtual bool transmissionQueueEmpty ()
virtual unsigned int transmissionQueueSize ()
virtual int mappingAccessCategory (Ieee80211DataOrMgmtFrame *frame)
Mapping to access categories.
virtual void sendDownPendingRadioConfigMsg ()
Send down the change channel message to the physical layer if there is any.
virtual void setMode (Mode mode)
Change the current MAC operation mode.
virtual Ieee80211DataOrMgmtFrame * getCurrentTransmission ()
Returns the current frame being transmitted.
virtual void resetStateVariables ()
Reset backoff, backoffPeriod and retryCounter for IDLE state.
virtual bool isMediumStateChange (cMessage *msg)
Used by the state machine to identify medium state change events.
virtual bool isMediumFree ()
Tells if the medium is free according to the physical and virtual carrier sense algorithm.
virtual bool isMulticast (Ieee80211Frame *msg)
Returns true if message is a multicast message.
virtual bool isForUs (Ieee80211Frame *msg)
Returns true if message destination address is ours.
virtual bool isSentByUs (Ieee80211Frame *msg)
Returns true if message source address is ours.
virtual bool isDataOrMgmtFrame (Ieee80211Frame *frame)
Checks if the frame is a data or management frame.
virtual bool isMsgAIFS (cMessage *msg)
Checks if the message is endAIFS and set currentAC.
virtual Ieee80211Frame * getFrameReceivedBeforeSIFS ()
Returns the last frame received before the SIFS period.
virtual void popTransmissionQueue ()
Deletes frame at the front of queue.
virtual double computeFrameDuration (Ieee80211Frame *msg)
Computes the duration (in seconds) of the transmission of a frame over the physical channel.
virtual double computeFrameDuration (int bits, double bitrate)
virtual void logState ()
Logs all state information.
Protected Attributes
Timer messages
cMessage * endSIFS
End of the Short Inter-Frame Time period.
cMessage * endDIFS
End of the Data Inter-Frame Time period.
cMessage * endTXOP
End of the Arbitration Inter-Frame Time period.
cMessage * endTimeout
End of the backoff period.
cMessage * endReserve
End of medium reserve period (NAV) when two other nodes were communicating on the channel.
cMessage * mediumStateChange
Radio state change self message.
Statistics
long numCollision
long numInternalCollision
long numBites
long numSentTXOP
long numReceived
long numSentMulticast
long numReceivedMulticast
long numReceivedOther
long numAckSend
cOutVector stateVector
simtime_t last
cOutVector radioStateVector
Private Types
enum { RATE_ARF, RATE_AARF, RATE_CR }
typedef std::list
< Ieee80211DataOrMgmtFrame * > Ieee80211DataOrMgmtFrameList
typedef std::map< MACAddress,
Ieee80211ASFTuple > Ieee80211ASFTupleList
Private Attributes
enum Ieee80211Mac:: { ... } rateControlMode
WifiPreamble wifiPreambleType
ModulationType recFrameModulationType
bool validRecMode
bool useModulationParameters
bool prioritizeMulticast
Configuration parameters
These are filled in during the initialization phase and not supposed to change afterwards.
MACAddress address
MAC address.
char opMode
double bitrate
The bitrate is used to send unicast data and mgmt frames; be sure to use a valid 802.11 bitrate.
double basicBitrate
The basic bitrate (1 or 2 Mbps) is used to transmit control frames and multicast/broadcast frames.
bool forceBitRate
unsigned int intrateIndex
int contI
int contJ
int samplingCoeff
double recvdThroughput
int autoBitrate
int rateIndex
int successCounter
int failedCounter
bool recovery
int timer
int successThreshold
int maxSuccessThreshold
int timerTimeout
int minSuccessThreshold
int minTimerTimeout
double successCoeff
double timerCoeff
double _snr
double snr
double lossRate
simtime_t timeStampLastMessageReceived
uint64_t recBytesOverPeriod
simtime_t throughputTimePeriod
cMessage * throughputTimer
double throughputLastPeriod
int maxQueueSize
Maximum number of frames in the queue; should be set in the omnetpp.ini.
int rtsThreshold
The minimum length of MPDU to use RTS/CTS mechanism.
int transmissionLimit
Maximum number of transmissions for a message.
int defaultAC
Default access catagory.
simtime_t ST
Slot time 9us(fast slot time 802.11g only) 20us(802.11b / 802.11g backward compatible)
double PHY_HEADER_LENGTH
int cwMinData
Minimum contention window.
int cwMaxData
Maximum contention window.
int cwMinMulticast
Contention window size for multicast messages.
static const int fragmentationThreshold = 2346
Messages longer than this threshold will be sent in multiple fragments.
Ieee80211Mac state variables
Various state information checked and modified according to the state machine.
enum State {
IDLE, DEFER, WAITAIFS, BACKOFF,
WAITACK, WAITMULTICAST, WAITCTS, WAITSIFS,
RECEIVE
}
the 80211 MAC state machine
enum Mode { DCF, PCF, EDCA }
80211 MAC operation modes
cFSM fsm
bool fixFSM
std::vector< Edca > edcCAF
std::vector< EdcaOutVector > edcCAFOutVector
IQoSClassifier * classifier
Arbitration interframe space number.
Mode mode
int sequenceNumber
Sequence number to be assigned to the next frame.
bool lastReceiveFailed
Indicates that the last frame received had bit errors in it or there was a collision during receiving the frame.
bool nav
True during network allocation period.
bool txop
True if we are in txop bursting packets.
int currentAC
Indicates which queue is acite.
int oldcurrentAC
Remember currentAC.
RadioState::State radioState
XXX Remember for which AC we wait for ACK.
int radioModule
Ieee80211DataOrMgmtFrame * fr
bool duplicateDetect
A list of last sender, sequence and fragment number tuples to identify duplicates, see spec 9.2.9.
bool purgeOldTuples
double duplicateTimeOut
simtime_t lastTimeDelete
Ieee80211ASFTupleList asfTuplesList
IPassiveQueue * queueModule
Passive queue module to request messages from.
cMessage * pendingRadioConfigMsg
The last change channel message received and not yet sent to the physical layer, or NULL.
virtual bool & backoff (int i=-1)
virtual simtime_t & TXOP (int i=-1)
virtual simtime_t & backoffPeriod (int i=-1)
virtual int & retryCounter (int i=-1)
virtual int & AIFSN (int i=-1)
virtual int & cwMax (int i=-1)
virtual int & cwMin (int i=-1)
virtual cMessage * endAIFS (int i=-1)
virtual cMessage * endBackoff (int i=-1)
virtual
Ieee80211DataOrMgmtFrameList * transmissionQueue (int i=-1)
virtual void setEndAIFS (int i, cMessage *msg)
virtual void setEndBackoff (int i, cMessage *msg)
virtual long & numRetry (int i=-1)
virtual long & numSentWithoutRetry (int i=-1)
virtual long & numGivenUp (int i=-1)
virtual long & numSent (int i=-1)
virtual long & numDropped (int i=-1)
virtual long & bites (int i=-1)
virtual simtime_t & minjitter (int i=-1)
virtual simtime_t & maxjitter (int i=-1)
virtual cOutVector * jitter (int i=-1)
virtual cOutVector * macDelay (int i=-1)
virtual cOutVector * throughput (int i=-1)
const int numCategories ()
virtual const bool isBakoffMsg (cMessage *msg)
const char * modeName (int mode)
int getRadioModuleId ()
Detailed Description
IEEE 802.11g with e Media Access Control Layer.
Various comments in the code refer to the Wireless LAN Medium Access Control (MAC) and Physical Layer(PHY) Specifications ANSI/IEEE Std 802.11, 1999 Edition (R2003) ANSI/IEEE Std 802.11, 2007 Edition
For more info, see the NED file.
TODO: support fragmentation TODO: PCF mode TODO: CF period TODO: pass radio power to upper layer TODO: transmission complete notification to upper layer TODO: STA TCF timer synchronization, see Chapter 11 pp 123
Parts of the implementation have been taken over from the Mobility Framework's Mac80211 module.
Member Typedef Documentation
typedef std::map<MACAddress, Ieee80211ASFTuple> Ieee80211Mac::Ieee80211ASFTupleList [private]
typedef std::list<Ieee80211DataOrMgmtFrame*> Ieee80211Mac::Ieee80211DataOrMgmtFrameList [private]
Member Enumeration Documentation
anonymous enum [private]
Enumerator:
RATE_ARF
RATE_AARF
RATE_CR
    {
        RATE_ARF,   // Auto Rate Fallback
        RATE_AARF,  // Adaptatice ARF
        RATE_CR,    // Constant Rate
    } rateControlMode;
enum Ieee80211Mac::Mode
80211 MAC operation modes
Enumerator:
DCF
Distributed Coordination Function.
PCF
Point Coordination Function.
EDCA
    {
        DCF,
        PCF,
        EDCA,
    };
enum Ieee80211Mac::State
the 80211 MAC state machine
Enumerator:
IDLE
DEFER
WAITAIFS
BACKOFF
WAITACK
WAITMULTICAST
WAITCTS
WAITSIFS
RECEIVE
    {
        IDLE,
        DEFER,
        WAITAIFS,
        BACKOFF,
        WAITACK,
        WAITMULTICAST,
        WAITCTS,
        WAITSIFS,
        RECEIVE,
    };
Constructor & Destructor Documentation
Ieee80211Mac::Ieee80211Mac ()
{
    endSIFS = NULL;
    endDIFS = NULL;
    endTimeout = NULL;
    endReserve = NULL;
    mediumStateChange = NULL;
    pendingRadioConfigMsg = NULL;
    classifier = NULL;
}
Ieee80211Mac::~Ieee80211Mac () [virtual]
{
    cancelAndDelete(endSIFS);
    cancelAndDelete(endDIFS);
    cancelAndDelete(endTimeout);
    cancelAndDelete(endReserve);
    cancelAndDelete(mediumStateChange);
    cancelAndDelete(endTXOP);
    for (unsigned int i = 0; i < edcCAF.size(); i++)
    {
        cancelAndDelete(endAIFS(i));
        cancelAndDelete(endBackoff(i));
        while (!transmissionQueue(i)->empty())
        {
            Ieee80211Frame *temp = dynamic_cast<Ieee80211Frame *> (transmissionQueue(i)->front());
            transmissionQueue(i)->pop_front();
            delete temp;
        }
    }
    edcCAF.clear();
    for (unsigned int i=0; i<edcCAFOutVector.size(); i++)
    {
        delete edcCAFOutVector[i].jitter;
        delete edcCAFOutVector[i].macDelay;
        delete edcCAFOutVector[i].throughput;
    }
    edcCAFOutVector.clear();
    if (pendingRadioConfigMsg)
        delete pendingRadioConfigMsg;
}
Member Function Documentation
int & Ieee80211Mac::AIFSN (int i = -1) [protected, virtual]
Referenced by getAIFS(), getDIFS(), and initialize().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].AIFSN;
}
bool & Ieee80211Mac::backoff (int i = -1) [protected, virtual]
Referenced by decreaseBackoffPeriod(), finishReception(), handleSelfMsg(), handleWithFSM(), initWatches(), logState(), resetStateVariables(), and retryCurrentTransmission().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
    return edcCAF[i].backoff;
}
simtime_t & Ieee80211Mac::backoffPeriod (int i = -1) [protected, virtual]
Referenced by decreaseBackoffPeriod(), generateBackoffPeriod(), handleWithFSM(), initWatches(), invalidateBackoffPeriod(), isInvalidBackoffPeriod(), logState(), resetStateVariables(), and scheduleBackoffPeriod().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].backoffPeriod;
}
long & Ieee80211Mac::bites (int i = -1) [protected, virtual]
Referenced by handleWithFSM(), and initialize().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].bites;
}
Ieee80211ACKFrame * Ieee80211Mac::buildACKFrame (Ieee80211DataOrMgmtFrame * frameToACK) [protected, virtual]
Referenced by sendACKFrame().
{
    Ieee80211ACKFrame *frame = new Ieee80211ACKFrame("wlan-ack");
    frame->setReceiverAddress(frameToACK->getTransmitterAddress());
    if (!frameToACK->getMoreFragments())
        frame->setDuration(0);
    else
        frame->setDuration(frameToACK->getDuration() - getSIFS() - computeFrameDuration(LENGTH_ACK, basicBitrate));
    return frame;
}
Ieee80211CTSFrame * Ieee80211Mac::buildCTSFrame (Ieee80211RTSFrame * rtsFrame) [protected, virtual]
Referenced by sendCTSFrame().
{
    Ieee80211CTSFrame *frame = new Ieee80211CTSFrame("wlan-cts");
    frame->setReceiverAddress(rtsFrame->getTransmitterAddress());
    frame->setDuration(rtsFrame->getDuration() - getSIFS() - computeFrameDuration(LENGTH_CTS, basicBitrate));
    return frame;
}
Ieee80211DataOrMgmtFrame * Ieee80211Mac::buildDataFrame (Ieee80211DataOrMgmtFrame * frameToSend) [protected, virtual]
Referenced by sendDataFrame(), and sendMulticastFrame().
{
    Ieee80211DataOrMgmtFrame *frame = (Ieee80211DataOrMgmtFrame *)frameToSend->dup();
    if (frameToSend->getControlInfo()!=NULL)
    {
        cObject * ctr = frameToSend->getControlInfo();
        PhyControlInfo *ctrl = dynamic_cast <PhyControlInfo*> (ctr);
        if (ctrl == NULL)
            opp_error("control info is not PhyControlInfo type %s");
        frame->setControlInfo(ctrl->dup());
    }
    if (isMulticast(frameToSend))
        frame->setDuration(0);
    else if (!frameToSend->getMoreFragments())
    {
        if (txop)
        {
            // ++ operation is safe because txop is true
            std::list<Ieee80211DataOrMgmtFrame*>::iterator nextframeToSend;
            nextframeToSend = transmissionQueue()->begin();
            nextframeToSend++;
            ASSERT(transmissionQueue()->end() != nextframeToSend);
            double bitRate = bitrate;
            int size = (*nextframeToSend)->getBitLength();
            if (transmissionQueue()->front()->getControlInfo() && dynamic_cast<PhyControlInfo*>(transmissionQueue()->front()->getControlInfo()))
            {
                bitRate = dynamic_cast<PhyControlInfo*>(transmissionQueue()->front()->getControlInfo())->getBitrate();
                if (bitRate == 0)
                    bitRate = bitrate;
            }
            frame->setDuration(3 * getSIFS() + 2 * computeFrameDuration(LENGTH_ACK, basicBitrate)
                               + computeFrameDuration(size,bitRate));
        }
        else
            frame->setDuration(getSIFS() + computeFrameDuration(LENGTH_ACK, basicBitrate));
    }
    else
        // FIXME: shouldn't we use the next frame to be sent?
        frame->setDuration(3 * getSIFS() + 2 * computeFrameDuration(LENGTH_ACK, basicBitrate) + computeFrameDuration(frameToSend));
    return frame;
}
Ieee80211DataOrMgmtFrame * Ieee80211Mac::buildMulticastFrame (Ieee80211DataOrMgmtFrame * frameToSend) [protected, virtual]
{
    Ieee80211DataOrMgmtFrame *frame = (Ieee80211DataOrMgmtFrame *)frameToSend->dup();
    PhyControlInfo *phyControlInfo_old = dynamic_cast<PhyControlInfo *>( frameToSend->getControlInfo() );
    if (phyControlInfo_old)
    {
        ev<<"Per frame1 params"<<endl;
        PhyControlInfo *phyControlInfo_new = new PhyControlInfo;
        *phyControlInfo_new = *phyControlInfo_old;
        //EV<<"PhyControlInfo bitrate "<<phyControlInfo->getBitrate()/1e6<<"Mbps txpower "<<phyControlInfo->txpower()<<"mW"<<endl;
        frame->setControlInfo(  phyControlInfo_new  );
    }
    frame->setDuration(0);
    return frame;
}
Ieee80211RTSFrame * Ieee80211Mac::buildRTSFrame (Ieee80211DataOrMgmtFrame * frameToSend) [protected, virtual]
Referenced by sendRTSFrame().
{
    Ieee80211RTSFrame *frame = new Ieee80211RTSFrame("wlan-rts");
    frame->setTransmitterAddress(address);
    frame->setReceiverAddress(frameToSend->getReceiverAddress());
    frame->setDuration(3 * getSIFS() + computeFrameDuration(LENGTH_CTS, basicBitrate) +
                       computeFrameDuration(frameToSend) +
                       computeFrameDuration(LENGTH_ACK, basicBitrate));
    return frame;
}
void Ieee80211Mac::cancelAIFSPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    EV << "canceling AIFS period\n";
    for (int i = 0; i<numCategories(); i++)
        cancelEvent(endAIFS(i));
    cancelEvent(endDIFS);
}
void Ieee80211Mac::cancelBackoffPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    EV << "cancelling Backoff period - only if some is scheduled\n";
    for (int i = 0; i<numCategories(); i++)
        cancelEvent(endBackoff(i));
}
void Ieee80211Mac::cancelDIFSPeriod () [protected, virtual]
{
    EV << "canceling DIFS period\n";
    cancelEvent(endDIFS);
}
void Ieee80211Mac::cancelTimeoutPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    EV << "canceling timeout period\n";
    cancelEvent(endTimeout);
}
simtime_t Ieee80211Mac::computeBackoffPeriod (Ieee80211Frame * msg, int r) [protected, virtual]
Referenced by generateBackoffPeriod().
{
    int cw;
    EV << "generating backoff slot number for retry: " << r << endl;
    if (msg && isMulticast(msg))
        cw = cwMinMulticast;
    else
    {
        ASSERT(0 <= r && r < transmissionLimit);
        cw = (cwMin() + 1) * (1 << r) - 1;
        if (cw > cwMax())
            cw = cwMax();
    }
    int c = intrand(cw + 1);
    EV << "generated backoff slot number: " << c << " , cw: " << cw << " ,cwMin:cwMax = " << cwMin() << ":" << cwMax() << endl;
    return ((double)c) * getSlotTime();
}
double Ieee80211Mac::computeFrameDuration (Ieee80211Frame * msg) [protected, virtual]
Computes the duration (in seconds) of the transmission of a frame over the physical channel.
'bits' should be the total length of the MAC frame in bits, but excluding the physical layer framing (preamble etc.)
Referenced by buildACKFrame(), buildCTSFrame(), buildDataFrame(), buildRTSFrame(), handleLowerMsg(), scheduleCTSTimeoutPeriod(), scheduleDataTimeoutPeriod(), scheduleMulticastTimeoutPeriod(), and sendDataFrame().
{
    PhyControlInfo *ctrl;
    double duration;
    ev<<*msg;
    ctrl = dynamic_cast<PhyControlInfo*> ( msg->removeControlInfo() );
    if ( ctrl )
    {
        ev<<"Per frame2 params bitrate "<<ctrl->getBitrate()/1e6<<endl;
        duration = computeFrameDuration(msg->getBitLength(), ctrl->getBitrate());
        delete ctrl;
        return duration;
    }
    else
        return computeFrameDuration(msg->getBitLength(), bitrate);
}
double Ieee80211Mac::computeFrameDuration (int bits, double bitrate) [protected, virtual]
{
    double duration;
    if (PHY_HEADER_LENGTH<0)
    {
        ModulationType modType;
        if (opMode=='g' || (opMode=='b'))
            modType = WifiModulationType::getMode80211g(bitrate);
        else if (opMode=='a')
            modType = WifiModulationType::getMode80211a(bitrate);
        else if (opMode=='p')
            modType = WifiModulationType::getMode80211p(bitrate);
        else
            opp_error("Opmode not supported");
        duration = SIMTIME_DBL(WifiModulationType::calculateTxDuration(bits, modType, wifiPreambleType));
    }
    else
    {
        if ((opMode=='g') || (opMode=='a') || (opMode=='p'))
            duration = 4*ceil((16+bits+6)/(bitrate/1e6*4))*1e-6 + PHY_HEADER_LENGTH;
        else if (opMode=='b')
            duration = bits / bitrate + PHY_HEADER_LENGTH / BITRATE_HEADER;
        else
            opp_error("Opmode not supported");
    }
    EV<<" duration="<<duration*1e6<<"us("<<bits<<"bits "<<bitrate/1e6<<"Mbps)"<<endl;
    return duration;
}
void Ieee80211Mac::configureAutoBitRate () [protected, virtual]
Referenced by initialize().
{
    forceBitRate = par("forceBitRate");
    minSuccessThreshold = par("minSuccessThreshold");
    minTimerTimeout = par("minTimerTimeout");
    timerTimeout = par("timerTimeout");
    successThreshold = par("successThreshold");
    autoBitrate = par("autoBitrate");
    switch (autoBitrate)
    {
    case 0:
        rateControlMode = RATE_CR;
        EV<<"MAC Transmission algorithm : Constant Rate"  <<endl;
        break;
    case 1:
        rateControlMode = RATE_ARF;
        EV<<"MAC Transmission algorithm : ARF Rate"  <<endl;
        break;
    case 2:
        rateControlMode = RATE_AARF;
        successCoeff = par("successCoeff");
        timerCoeff = par("timerCoeff");
        maxSuccessThreshold = par("maxSuccessThreshold");
        EV<<"MAC Transmission algorithm : AARF Rate"  <<endl;
        break;
    default:
        rateControlMode = RATE_CR;
        break;
    }
}
int & Ieee80211Mac::cwMax (int i = -1) [protected, virtual]
Referenced by computeBackoffPeriod(), and initialize().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].cwMax;
}
int & Ieee80211Mac::cwMin (int i = -1) [protected, virtual]
Referenced by computeBackoffPeriod(), and initialize().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].cwMin;
}
void Ieee80211Mac::decreaseBackoffPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    // see spec 9.9.1.5
    // decrase for every EDCAF
    // cancel event endBackoff after decrease or we don't know which endBackoff is scheduled
    for (int i = 0; i<numCategories(); i++)
    {
        if (backoff(i) && endBackoff(i)->isScheduled())
        {
            EV<< "old backoff[" << i << "] is " << backoffPeriod(i) << ", sim time is " << simTime()
            << ", endbackoff sending period is " << endBackoff(i)->getSendingTime() << endl;
            simtime_t elapsedBackoffTime = simTime() - endBackoff(i)->getSendingTime();
            backoffPeriod(i) -= ((int)(elapsedBackoffTime / getSlotTime())) * getSlotTime();
            EV << "actual backoff[" << i << "] is " <<backoffPeriod(i) << ", elapsed is " << elapsedBackoffTime << endl;
            ASSERT(backoffPeriod(i) >= 0);
            EV << "backoff[" << i << "] period decreased to " << backoffPeriod(i) << endl;
        }
    }
}
cMessage * Ieee80211Mac::endAIFS (int i = -1) [protected, virtual]
Referenced by cancelAIFSPeriod(), handleSelfMsg(), handleWithFSM(), isMsgAIFS(), logState(), rescheduleAIFSPeriod(), scheduleAIFSPeriod(), and ~Ieee80211Mac().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].endAIFS;
}
cMessage * Ieee80211Mac::endBackoff (int i = -1) [protected, virtual]
Referenced by cancelBackoffPeriod(), decreaseBackoffPeriod(), handleSelfMsg(), handleWithFSM(), isBakoffMsg(), logState(), scheduleBackoffPeriod(), and ~Ieee80211Mac().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].endBackoff;
}
void Ieee80211Mac::finish () [protected, virtual]
{
    recordScalar("number of received packets", numReceived);
    recordScalar("number of collisions", numCollision);
    recordScalar("number of internal collisions", numInternalCollision);
    for (int i=0; i<numCategories(); i++)
    {
        std::stringstream os;
        os<< i;
        std::string th = "number of retry for AC "+os.str();
        recordScalar(th.c_str(), numRetry(i));
    }
    recordScalar("sent and receive bites", numBites);
    for (int i=0; i<numCategories(); i++)
    {
        std::stringstream os;
        os<< i;
        std::string th = "sent packet within AC "+os.str();
        recordScalar(th.c_str(), numSent(i));
    }
    recordScalar("sent in TXOP ", numSentTXOP );
    for (int i=0; i<numCategories(); i++)
    {
        std::stringstream os;
        os<< i;
        std::string th = "sentWithoutRetry AC "+os.str();
        recordScalar(th.c_str(), numSentWithoutRetry(i));
    }
    for (int i=0; i<numCategories(); i++)
    {
        std::stringstream os;
        os<< i;
        std::string th = "numGivenUp AC "+os.str();
        recordScalar(th.c_str(), numGivenUp(i));
    }
    for (int i=0; i<numCategories(); i++)
    {
        std::stringstream os;
        os<< i;
        std::string th = "numDropped AC "+os.str();
        recordScalar(th.c_str(), numDropped(i));
    }
}
void Ieee80211Mac::finishCurrentTransmission () [protected, virtual]
Referenced by handleWithFSM().
{
    popTransmissionQueue();
    resetStateVariables();
}
void Ieee80211Mac::finishReception () [protected, virtual]
Referenced by handleWithFSM().
{
    if (getCurrentTransmission())
    {
        backoff() = true;
    }
    else
    {
        resetStateVariables();
    }
}
void Ieee80211Mac::generateBackoffPeriod () [protected, virtual]
Referenced by handleWithFSM(), and retryCurrentTransmission().
{
    backoffPeriod() = computeBackoffPeriod(getCurrentTransmission(), retryCounter());
    ASSERT(backoffPeriod() >= 0);
    EV << "backoff period set to " << backoffPeriod()<< endl;
}
simtime_t Ieee80211Mac::getAIFS (int AccessCategory) [protected, virtual]
Referenced by handleWithFSM(), rescheduleAIFSPeriod(), and scheduleAIFSPeriod().
{
    return AIFSN(AccessCategory) * getSlotTime() + getSIFS();
}
double Ieee80211Mac::getBitrate () [protected, virtual]
Referenced by buildDataFrame(), scheduleDataTimeoutPeriod(), and setBitrateFrame().
{
    return bitrate;
}
ModulationType Ieee80211Mac::getControlAnswerMode (ModulationType reqMode) [protected]
The standard has relatively unambiguous rules for selecting a control response rate (the below is quoted from IEEE 802.11-2007, Section 9.6):
To allow the transmitting STA to calculate the contents of the Duration/ID field, a STA responding to a received frame shall transmit its Control Response frame (either CTS or ACK), other than the BlockAck control frame, at the highest rate in the BSSBasicRateSet parameter that is less than or equal to the rate of the immediately previous frame in the frame exchange sequence (as defined in 9.12) and that is of the same modulation class (see 9.6.1) as the received frame...
If no suitable basic rate was found, we search the mandatory rates. The standard (IEEE 802.11-2007, Section 9.6) says:
...If no rate contained in the BSSBasicRateSet parameter meets these conditions, then the control frame sent in response to a received frame shall be transmitted at the highest mandatory rate of the PHY that is less than or equal to the rate of the received frame, and that is of the same modulation class as the received frame. In addition, the Control Response frame shall be sent using the same PHY options as the received frame, unless they conflict with the requirement to use the BSSBasicRateSet parameter.
TODO: Note that we're ignoring the last sentence for now, because there is not yet any manipulation here of PHY options.
If we still haven't found a suitable rate for the response then someone has messed up the simulation config. This probably means that the WifiPhyStandard is not set correctly, or that a rate that is not supported by the PHY has been explicitly requested in a WifiRemoteStationManager (or descendant) configuration.
Either way, it is serious - we can either disobey the standard or fail, and I have chosen to do the latter...
{
    bool found = false;
    ModulationType mode;
    for (uint32_t idx = 0; idx < (uint32_t)getMaxBitrate(); idx++)
    {
        ModulationType thismode;
        if (opMode=='b')
            thismode = WifiModulationType::getMode80211b(BITRATES_80211b[idx]);
        else if (opMode=='g')
            thismode = WifiModulationType::getMode80211g(BITRATES_80211g[idx]);
        else if (opMode=='a')
            thismode = WifiModulationType::getMode80211a(BITRATES_80211a[idx]);
        else if (opMode=='a')
            thismode = WifiModulationType::getMode80211p(BITRATES_80211p[idx]);
      /* If the rate:
       *
       *  - is a mandatory rate for the PHY, and
       *  - is equal to or faster than our current best choice, and
       *  - is less than or equal to the rate of the received frame, and
       *  - is of the same modulation class as the received frame
       *
       * ...then it's our best choice so far.
       */
      if (thismode.getIsMandatory()
          && (!found || thismode.getPhyRate() > mode.getPhyRate())
          && thismode.getPhyRate() <= reqMode.getPhyRate()
          && thismode.getModulationClass() == reqMode.getModulationClass())
        {
          mode = thismode;
          // As above; we've found a potentially-suitable transmit
          // rate, but we need to continue and consider all the
          // mandatory rates before we can be sure we've got the right
          // one.
          found = true;
        }
    }
  if (!found)
    {
      opp_error("Can't find response rate for reqMode. Check standard and selected rates match.");
    }
  return mode;
}
Ieee80211DataOrMgmtFrame * Ieee80211Mac::getCurrentTransmission () [protected, virtual]
Returns the current frame being transmitted.
Referenced by finishReception(), generateBackoffPeriod(), handleWithFSM(), logState(), resetStateVariables(), and retryCurrentTransmission().
{
    return transmissionQueue()->empty() ? NULL : (Ieee80211DataOrMgmtFrame *)transmissionQueue()->front();
}
simtime_t Ieee80211Mac::getDIFS (int category = -1) [protected, virtual]
Referenced by getEIFS(), handleWithFSM(), initialize(), scheduleAIFSPeriod(), and scheduleDIFSPeriod().
{
    if (category<0 || category>(numCategories()-1))
    {
        int index = numCategories()-1;
        if (index<0)
            index = 0;
        return getSIFS() + ((double)AIFSN(index) * getSlotTime());
    }
    else
    {
        return getSIFS() + ((double)AIFSN(category)) * getSlotTime();
    }
}
simtime_t Ieee80211Mac::getEIFS () [protected, virtual]
Referenced by scheduleAIFSPeriod(), and scheduleDIFSPeriod().
{
// FIXME:   return getSIFS() + getDIFS() + (8 * ACKSize + aPreambleLength + aPLCPHeaderLength) / lowestDatarate;
    if (PHY_HEADER_LENGTH<0)
    {
        if ((opMode=='b') || (opMode=='g'))
            return getSIFS() + getDIFS() + (8 * LENGTH_ACK) / 1E+6 + getHeaderTime(1E+6);
        else if (opMode=='a')
            return getSIFS() + getDIFS() + (8 * LENGTH_ACK) / 6E+6 + getHeaderTime(6E+6);
        else if (opMode=='p')
             return getSIFS() + getDIFS() + (8 * LENGTH_ACK) / 6E+6 + getHeaderTime(3E+6);
    }
    else
    {
        // FIXME: check how PHY_HEADER_LENGTH is handled. Is that given in bytes or secs ???
        // what is the rela unit? The use seems to be incosistent betwen b and g modes.
        if (opMode=='b')
            return getSIFS() + getDIFS() + (8 * LENGTH_ACK + PHY_HEADER_LENGTH) / 1E+6;
        else if (opMode=='g')
            return getSIFS() + getDIFS() + (8 * LENGTH_ACK) / 1E+6 + PHY_HEADER_LENGTH;
        else if (opMode=='a')
            return getSIFS() + getDIFS() + (8 * LENGTH_ACK) / 6E+6 + PHY_HEADER_LENGTH;
        else if (opMode=='p')
            return getSIFS() + getDIFS() + (8 * LENGTH_ACK) / 3E+6 + PHY_HEADER_LENGTH;
    }
    // if arrive here there is an error
    opp_error("mode not supported");
    return 0;
}
Ieee80211Frame * Ieee80211Mac::getFrameReceivedBeforeSIFS () [protected, virtual]
Returns the last frame received before the SIFS period.
Referenced by handleWithFSM().
{
    return (Ieee80211Frame *)endSIFS->getContextPointer();
}
simtime_t Ieee80211Mac::getHeaderTime (double bitrate) [protected, virtual]
Referenced by getEIFS().
{
    ModulationType modType;
    if ((opMode=='b') || (opMode=='g'))
        modType = WifiModulationType::getMode80211g(bitrate);
    else if (opMode=='a')
        modType = WifiModulationType::getMode80211a(bitrate);
    else if (opMode=='p')
        modType = WifiModulationType::getMode80211p(bitrate);
    else
        opp_error("mode not supported");
    return WifiModulationType::getPreambleAndHeader(modType, wifiPreambleType);
}
int Ieee80211Mac::getMaxBitrate (void) [protected, virtual]
Referenced by getControlAnswerMode(), initialize(), and reportDataOk().
{
    if (opMode=='b')
        return (NUM_BITERATES_80211b);
    else if (opMode=='g')
        return (NUM_BITERATES_80211g);
    else if (opMode=='a')
        return (NUM_BITERATES_80211a);
    else if (opMode=='p')
        return (NUM_BITERATES_80211p);
//
// If arrives here there is an error
    opp_error("Mode not supported");
    return 0;
}
int Ieee80211Mac::getMinBitrate (void) [protected, virtual]
Referenced by reportDataFailed().
{
    return 0;
}
int Ieee80211Mac::getMinSuccessThreshold (void) [protected, virtual]
Referenced by reportFailure().
{
    return minSuccessThreshold;
}
int Ieee80211Mac::getMinTimerTimeout (void) [protected, virtual]
Referenced by reportFailure(), and reportRecoveryFailure().
{
    return minTimerTimeout;
}
simtime_t Ieee80211Mac::getPIFS () [protected, virtual]
{
    return getSIFS() + getSlotTime();
}
int Ieee80211Mac::getRadioModuleId () [inline, protected]
Referenced by receiveChangeNotification().
{return radioModule;}
simtime_t Ieee80211Mac::getSIFS () [protected, virtual]
Referenced by buildACKFrame(), buildCTSFrame(), buildDataFrame(), buildRTSFrame(), getAIFS(), getDIFS(), getEIFS(), getPIFS(), scheduleCTSTimeoutPeriod(), scheduleDataTimeoutPeriod(), scheduleSIFSPeriod(), and sendDataFrame().
{
// TODO:   return aRxRFDelay() + aRxPLCPDelay() + aMACProcessingDelay() + aRxTxTurnaroundTime();
    if (useModulationParameters)
    {
        ModulationType modType;
        if ((opMode=='b') || (opMode=='g'))
            modType = WifiModulationType::getMode80211g(bitrate);
        else if (opMode=='a')
            modType = WifiModulationType::getMode80211a(bitrate);
        else if (opMode=='p')
            modType = WifiModulationType::getMode80211p(bitrate);
        else
            opp_error("mode not supported");
        return WifiModulationType::getSifsTime(modType,wifiPreambleType);
    }
    return SIFS;
}
simtime_t Ieee80211Mac::getSlotTime () [protected, virtual]
Referenced by computeBackoffPeriod(), decreaseBackoffPeriod(), getAIFS(), getDIFS(), and getPIFS().
{
// TODO:   return aCCATime() + aRxTxTurnaroundTime + aAirPropagationTime() + aMACProcessingDelay();
    if (useModulationParameters)
    {
        ModulationType modType;
        if ((opMode=='b') || (opMode=='g'))
            modType = WifiModulationType::getMode80211g(bitrate);
        else if (opMode=='a')
            modType = WifiModulationType::getMode80211a(bitrate);
        else if (opMode=='p')
            modType = WifiModulationType::getMode80211p(bitrate);
        else
            opp_error("mode not supported");
        return WifiModulationType::getSlotDuration(modType,wifiPreambleType);
    }
    return ST;
}
int Ieee80211Mac::getSuccessThreshold (void) [protected, virtual]
Referenced by reportDataOk(), and reportRecoveryFailure().
{
    return successThreshold;
}
int Ieee80211Mac::getTimeout (void) [protected]
Produce a readable name of the given MAC operation mode.
int Ieee80211Mac::getTimerTimeout (void) [protected, virtual]
Referenced by reportDataOk().
{
    return timerTimeout;
}
void Ieee80211Mac::giveUpCurrentTransmission () [protected, virtual]
Referenced by handleSelfMsg(), and handleWithFSM().
{
    Ieee80211DataOrMgmtFrame *temp = (Ieee80211DataOrMgmtFrame*) transmissionQueue()->front();
    nb->fireChangeNotification(NF_LINK_BREAK, temp);
    popTransmissionQueue();
    resetStateVariables();
    numGivenUp()++;
}
void Ieee80211Mac::handleCommand (cMessage * msg) [protected, virtual]
Handle commands (msg kind+control info) coming from upper layers.
Implements WirelessMacBase.
Referenced by handleUpperMsg().
{
    if (msg->getKind()==PHY_C_CONFIGURERADIO)
    {
        EV << "Passing on command " << msg->getName() << " to physical layer\n";
        if (pendingRadioConfigMsg != NULL)
        {
            // merge contents of the old command into the new one, then delete it
            PhyControlInfo *pOld = check_and_cast<PhyControlInfo *>(pendingRadioConfigMsg->getControlInfo());
            PhyControlInfo *pNew = check_and_cast<PhyControlInfo *>(msg->getControlInfo());
            if (pNew->getChannelNumber()==-1 && pOld->getChannelNumber()!=-1)
                pNew->setChannelNumber(pOld->getChannelNumber());
            if (pNew->getBitrate()==-1 && pOld->getBitrate()!=-1)
                pNew->setBitrate(pOld->getBitrate());
            delete pendingRadioConfigMsg;
            pendingRadioConfigMsg = NULL;
        }
        if (fsm.getState() == IDLE || fsm.getState() == DEFER || fsm.getState() == BACKOFF)
        {
            EV << "Sending it down immediately\n";
/*
// Dynamic power
            PhyControlInfo *phyControlInfo = dynamic_cast<PhyControlInfo *>(msg->getControlInfo());
            if (phyControlInfo)
                phyControlInfo->setAdaptiveSensitivity(true);
// end dynamic power
*/
            sendDown(msg);
        }
        else
        {
            EV << "Delaying " << msg->getName() << " until next IDLE or DEFER state\n";
            pendingRadioConfigMsg = msg;
        }
    }
    else
    {
        error("Unrecognized command from mgmt layer: (%s)%s msgkind=%d", msg->getClassName(), msg->getName(), msg->getKind());
    }
}
void Ieee80211Mac::handleLowerMsg (cPacket * msg) [protected, virtual]
Handle messages from lower (physical) layer.
Implements WirelessMacBase.
{
    EV<<"->Enter handleLowerMsg...\n";
    EV << "received message from lower layer: " << msg << endl;
    Radio80211aControlInfo * cinfo = dynamic_cast<Radio80211aControlInfo *>(msg->getControlInfo());
    if (cinfo && cinfo->getAirtimeMetric())
    {
        double rtsTime = 0;
        if (rtsThreshold*8<cinfo->getTestFrameSize())
             rtsTime=  computeFrameDuration(LENGTH_CTS, basicBitrate) +computeFrameDuration(LENGTH_RTS, basicBitrate);
        double frameDuration = cinfo->getTestFrameDuration() + computeFrameDuration(LENGTH_ACK, basicBitrate)+rtsTime;
        cinfo->setTestFrameDuration(frameDuration);
    }
    nb->fireChangeNotification(NF_LINK_FULL_PROMISCUOUS, msg);
    validRecMode = false;
    if (msg->getControlInfo() && dynamic_cast<Radio80211aControlInfo *>(msg->getControlInfo()))
    {
        Radio80211aControlInfo *cinfo = dynamic_cast<Radio80211aControlInfo *>(msg->getControlInfo());
        recFrameModulationType = cinfo->getModulationType();
        if (recFrameModulationType.getDataRate()>0)
            validRecMode = true;
    }
    if (rateControlMode == RATE_CR)
    {
        if (msg->getControlInfo())
            delete msg->removeControlInfo();
    }
    Ieee80211Frame *frame = dynamic_cast<Ieee80211Frame *>(msg);
    if (msg->getControlInfo() && dynamic_cast<Radio80211aControlInfo *>(msg->getControlInfo()))
    {
        Radio80211aControlInfo *cinfo = (Radio80211aControlInfo*) msg->removeControlInfo();
        if (contJ%10==0)
        {
            snr = _snr;
            contJ = 0;
            _snr = 0;
        }
        contJ++;
        _snr += cinfo->getSnr()/10;
        lossRate = cinfo->getLossRate();
        delete cinfo;
    }
    if (contI%samplingCoeff==0)
    {
        contI = 0;
        recvdThroughput = 0;
    }
    contI++;
    frame = dynamic_cast<Ieee80211Frame *>(msg);
    if (timeStampLastMessageReceived == 0)
        timeStampLastMessageReceived = simTime();
    else
    {
        if (frame)
            recvdThroughput += ((frame->getBitLength()/(simTime()-timeStampLastMessageReceived))/1000000)/samplingCoeff;
        timeStampLastMessageReceived = simTime();
    }
    if (frame && throughputTimer)
        recBytesOverPeriod += frame->getByteLength();
    if (!frame)
    {
        EV << "message from physical layer (%s)%s is not a subclass of Ieee80211Frame" << msg->getClassName() << " " << msg->getName() <<  endl;
        delete msg;
        return;
        // error("message from physical layer (%s)%s is not a subclass of Ieee80211Frame",msg->getClassName(), msg->getName());
    }
    EV << "Self address: " << address
    << ", receiver address: " << frame->getReceiverAddress()
    << ", received frame is for us: " << isForUs(frame)
    << ", received frame was sent by us: " << isSentByUs(frame)<<endl;
    Ieee80211TwoAddressFrame *twoAddressFrame = dynamic_cast<Ieee80211TwoAddressFrame *>(msg);
    ASSERT(!twoAddressFrame || twoAddressFrame->getTransmitterAddress() != address);
    handleWithFSM(msg);
    // if we are the owner then we did not send this message up
    if (msg->getOwner() == this)
        delete msg;
    EV<<"Leave handleLowerMsg...\n";
}
void Ieee80211Mac::handleSelfMsg (cMessage * msg) [protected, virtual]
Handle timer self messages.
Implements WirelessMacBase.
{
    if (msg==throughputTimer)
    {
        throughputLastPeriod = recBytesOverPeriod/SIMTIME_DBL(throughputTimePeriod);
        recBytesOverPeriod = 0;
        scheduleAt(simTime()+throughputTimePeriod, throughputTimer);
        return;
    }
    EV << "received self message: " << msg << "(kind: " << msg->getKind() << ")" << endl;
    if (msg == endReserve)
        nav = false;
    if (msg == endTXOP)
        txop = false;
    if ( !strcmp(msg->getName(), "AIFS") || !strcmp(msg->getName(), "Backoff") )
    {
        EV << "Changing currentAC to " << msg->getKind() << endl;
        currentAC = msg->getKind();
    }
    //check internal colision
    if ((strcmp(msg->getName(), "Backoff") == 0) || (strcmp(msg->getName(), "AIFS")==0))
    {
        int kind;
        kind = msg->getKind();
        if (kind<0)
            kind = 0;
        EV <<" kind is " << kind << ",name is " << msg->getName() <<endl;
        for (unsigned int i = numCategories()-1; (int)i > kind; i--)  //mozna prochaze jen 3..kind XXX
        {
            if (((endBackoff(i)->isScheduled() && endBackoff(i)->getArrivalTime() == simTime())
                    || (endAIFS(i)->isScheduled() && !backoff(i) && endAIFS(i)->getArrivalTime() == simTime()))
                    && !transmissionQueue(i)->empty())
            {
                EV << "Internal collision AC" << kind << " with AC" << i << endl;
                numInternalCollision++;
                EV << "Cancel backoff event and schedule new one for AC" << kind << endl;
                cancelEvent(endBackoff(kind));
                if (retryCounter() == transmissionLimit - 1)
                {
                    EV << "give up transmission for AC" << currentAC << endl;
                    giveUpCurrentTransmission();
                }
                else
                {
                    EV << "retry transmission for AC" << currentAC << endl;
                    retryCurrentTransmission();
                }
                return;
            }
        }
        currentAC = kind;
    }
    handleWithFSM(msg);
}
void Ieee80211Mac::handleUpperMsg (cPacket * msg) [protected, virtual]
Handle messages from upper layer.
Implements WirelessMacBase.
{
    if (queueModule && numCategories()>1 && (int)transmissionQueueSize() < maxQueueSize)
    {
        // the module are continuously asking for packets, except if the queue is full
        EV << "requesting another frame from queue module\n";
        queueModule->requestPacket();
    }
    // check if it's a command from the mgmt layer
    if (msg->getBitLength()==0 && msg->getKind()!=0)
    {
        handleCommand(msg);
        return;
    }
    // must be a Ieee80211DataOrMgmtFrame, within the max size because we don't support fragmentation
    Ieee80211DataOrMgmtFrame *frame = check_and_cast<Ieee80211DataOrMgmtFrame *>(msg);
    if (frame->getByteLength() > fragmentationThreshold)
        error("message from higher layer (%s)%s is too long for 802.11b, %d bytes (fragmentation is not supported yet)",
              msg->getClassName(), msg->getName(), (int)(msg->getByteLength()));
    EV << "frame " << frame << " received from higher layer, receiver = " << frame->getReceiverAddress() << endl;
    // if you get error from this assert check if is client associated to AP
    ASSERT(!frame->getReceiverAddress().isUnspecified());
    // fill in missing fields (receiver address, seq number), and insert into the queue
    frame->setTransmitterAddress(address);
    frame->setSequenceNumber(sequenceNumber);
    sequenceNumber = (sequenceNumber+1) % 4096;  //XXX seqNum must be checked upon reception of frames!
    if (mappingAccessCategory(frame) == 200)
    {
        // if function mappingAccessCategory() returns 200, it means transsmissionQueue is full
        return;
    }
    frame->setMACArrive(simTime());
    handleWithFSM(frame);
}
void Ieee80211Mac::handleWithFSM (cMessage * msg) [protected, virtual]
Handle all kinds of messages and notifications with the state machine.
Msg can be upper, lower, self or NULL (when radio state changes)
changed
Referenced by handleLowerMsg(), handleSelfMsg(), handleUpperMsg(), and receiveChangeNotification().
{
    removeOldTuplesFromDuplicateMap();
    // skip those cases where there's nothing to do, so the switch looks simpler
    if (isUpperMsg(msg) && fsm.getState() != IDLE)
    {
        if (fsm.getState() == WAITAIFS && endDIFS->isScheduled())
        {
            // a difs was schedule because all queues ware empty
            // change difs for aifs
            simtime_t remaint = getAIFS(currentAC)-getDIFS();
            scheduleAt(endDIFS->getArrivalTime()+remaint, endAIFS(currentAC));
            cancelEvent(endDIFS);
        }
        else if (fsm.getState() == BACKOFF && endBackoff(numCategories()-1)->isScheduled() &&  transmissionQueue(numCategories()-1)->empty())
        {
            // a backoff was schedule with all the queues empty
            // reschedule the backoff with the appropriate AC
            backoffPeriod(currentAC) = backoffPeriod(numCategories()-1);
            backoff(currentAC) = backoff(numCategories()-1);
            backoff(numCategories()-1) = false;
            scheduleAt(endBackoff(numCategories()-1)->getArrivalTime(), endBackoff(currentAC));
            cancelEvent(endBackoff(numCategories()-1));
        }
        EV << "deferring upper message transmission in " << fsm.getStateName() << " state\n";
        return;
    }
    Ieee80211Frame *frame = dynamic_cast<Ieee80211Frame*>(msg);
    int frameType = frame ? frame->getType() : -1;
    int msgKind = msg->getKind();
    logState();
    stateVector.record(fsm.getState());
    if (frame && isLowerMsg(frame))
    {
        lastReceiveFailed = (msgKind == COLLISION || msgKind == BITERROR);
        scheduleReservePeriod(frame);
    }
    // TODO: fix bug according to the message: [omnetpp] A possible bug in the Ieee80211's FSM.
    FSMA_Switch(fsm)
    {
        FSMA_State(IDLE)
        {
            FSMA_Enter(sendDownPendingRadioConfigMsg());
            /*
            if (fixFSM)
            {
            FSMA_Event_Transition(Data-Ready,
                                  // isUpperMsg(msg),
                                  isUpperMsg(msg) && backoffPeriod[currentAC] > 0,
                                  DEFER,
                //ASSERT(isInvalidBackoffPeriod() || backoffPeriod == 0);
                //invalidateBackoffPeriod();
               ASSERT(false);
            );
            FSMA_No_Event_Transition(Immediate-Data-Ready,
                !transmissionQueueEmpty(),
                                     DEFER,
              //  invalidateBackoffPeriod();
                ASSERT(backoff[currentAC]);
            );
            }
            */
            FSMA_Event_Transition(Data-Ready,
                                  isUpperMsg(msg),
                                  DEFER,
                                  ASSERT(isInvalidBackoffPeriod() || backoffPeriod() == 0);
                                  invalidateBackoffPeriod();
                                 );
            FSMA_No_Event_Transition(Immediate-Data-Ready,
                                     !transmissionQueueEmpty(),
                                     DEFER,
                                     if (retryCounter() == 0) //  jesjones patch.  TODO: check this particular case, I haven't been sure about this particular case
                                        invalidateBackoffPeriod();
                                    );
            FSMA_Event_Transition(Receive,
                                  isLowerMsg(msg),
                                  RECEIVE,
                                 );
        }
        FSMA_State(DEFER)
        {
            FSMA_Enter(sendDownPendingRadioConfigMsg());
            FSMA_Event_Transition(Wait-AIFS,
                                  isMediumStateChange(msg) && isMediumFree(),
                                  WAITAIFS,
                                  ;);
            FSMA_No_Event_Transition(Immediate-Wait-AIFS,
                                     isMediumFree() || (!isBackoffPending()),
                                     WAITAIFS,
                                     ;);
            FSMA_Event_Transition(Receive,
                                  isLowerMsg(msg),
                                  RECEIVE,
                                  ;);
        }
        FSMA_State(WAITAIFS)
        {
            FSMA_Enter(scheduleAIFSPeriod());
            FSMA_Event_Transition(EDCAF-Do-Nothing,
                                  isMsgAIFS(msg) && transmissionQueue()->empty(),
                                  WAITAIFS,
                                  ASSERT(0==1);
                                  ;);
            FSMA_Event_Transition(Immediate-Transmit-RTS,
                                  isMsgAIFS(msg) && !transmissionQueue()->empty() && !isMulticast(getCurrentTransmission())
                                  && getCurrentTransmission()->getByteLength() >= rtsThreshold && !backoff(),
                                  WAITCTS,
                                  sendRTSFrame(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                  cancelAIFSPeriod();
                                 );
            FSMA_Event_Transition(Immediate-Transmit-Multicast,
                                  isMsgAIFS(msg) && isMulticast(getCurrentTransmission()) && !backoff(),
                                  WAITMULTICAST,
                                  sendMulticastFrame(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                  cancelAIFSPeriod();
                                 );
            FSMA_Event_Transition(Immediate-Transmit-Data,
                                  isMsgAIFS(msg) && !isMulticast(getCurrentTransmission()) && !backoff(),
                                  WAITACK,
                                  sendDataFrame(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                  cancelAIFSPeriod();
                                 );
            /*FSMA_Event_Transition(AIFS-Over,
                                  isMsgAIFS(msg) && backoff[currentAC],
                                  BACKOFF,
                if (isInvalidBackoffPeriod())
                    generateBackoffPeriod();
            );*/
            FSMA_Event_Transition(AIFS-Over,
                                  isMsgAIFS(msg),
                                  BACKOFF,
                                  if (isInvalidBackoffPeriod())
                                  generateBackoffPeriod();
                                 );
            // end the difs and no other packet has been received
            FSMA_Event_Transition(DIFS-Over,
                                  msg == endDIFS && transmissionQueueEmpty(),
                                  BACKOFF,
                                  currentAC = numCategories()-1;
                                  if (isInvalidBackoffPeriod())
                                     generateBackoffPeriod();
                                   );
            FSMA_Event_Transition(DIFS-Over,
                                   msg == endDIFS,
                                   BACKOFF,
                                   for (int i=numCategories()-1; i>=0; i--)
{
                                       if (!transmissionQueue(i)->empty())
{
                                            currentAC = i;
                                       }
                                   }
                                   if (isInvalidBackoffPeriod())
                                      generateBackoffPeriod();
                                    );
            FSMA_Event_Transition(Busy,
                                  isMediumStateChange(msg) && !isMediumFree(),
                                  DEFER,
                                  for (int i=0; i<numCategories(); i++)
{
                                      if (endAIFS(i)->isScheduled())
                                          backoff(i) = true;
                                  }
                                  if (endDIFS->isScheduled()) backoff(numCategories()-1) = true;
                                  cancelAIFSPeriod();
                                  );
            FSMA_No_Event_Transition(Immediate-Busy,
                                     !isMediumFree(),
                                     DEFER,
                                     for (int i=0; i<numCategories(); i++)
{
                                         if (endAIFS(i)->isScheduled())
                                             backoff(i) = true;
                                     }
                                     if (endDIFS->isScheduled()) backoff(numCategories()-1) = true;
                                     cancelAIFSPeriod();
                                     );
            // radio state changes before we actually get the message, so this must be here
            FSMA_Event_Transition(Receive,
                                  isLowerMsg(msg),
                                  RECEIVE,
                                  cancelAIFSPeriod();
                                  ;);
        }
        FSMA_State(BACKOFF)
        {
            FSMA_Enter(scheduleBackoffPeriod());
            if (getCurrentTransmission())
            {
                FSMA_Event_Transition(Transmit-RTS,
                                      msg == endBackoff() && !isMulticast(getCurrentTransmission())
                                      && getCurrentTransmission()->getByteLength() >= rtsThreshold,
                                      WAITCTS,
                                      sendRTSFrame(getCurrentTransmission());
                                      oldcurrentAC = currentAC;
                                      cancelAIFSPeriod();
                                      decreaseBackoffPeriod();
                                      cancelBackoffPeriod();
                                     );
                FSMA_Event_Transition(Transmit-Multicast,
                                      msg == endBackoff() && isMulticast(getCurrentTransmission()),
                                      WAITMULTICAST,
                                      sendMulticastFrame(getCurrentTransmission());
                                      oldcurrentAC = currentAC;
                                      cancelAIFSPeriod();
                                      decreaseBackoffPeriod();
                                      cancelBackoffPeriod();
                                     );
                FSMA_Event_Transition(Transmit-Data,
                                      msg == endBackoff() && !isMulticast(getCurrentTransmission()),
                                      WAITACK,
                                      sendDataFrame(getCurrentTransmission());
                                      oldcurrentAC = currentAC;
                                      cancelAIFSPeriod();
                                      decreaseBackoffPeriod();
                                      cancelBackoffPeriod();
                                     );
            }
            FSMA_Event_Transition(AIFS-Over-backoff,
                                  isMsgAIFS(msg) && backoff(),
                                  BACKOFF,
                                  if (isInvalidBackoffPeriod())
                                  generateBackoffPeriod();
                                 );
            FSMA_Event_Transition(AIFS-Immediate-Transmit-RTS,
                                  isMsgAIFS(msg) && !transmissionQueue()->empty() && !isMulticast(getCurrentTransmission())
                                  && getCurrentTransmission()->getByteLength() >= rtsThreshold && !backoff(),
                                  WAITCTS,
                                  sendRTSFrame(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                  cancelAIFSPeriod();
                                  decreaseBackoffPeriod();
                                  cancelBackoffPeriod();
                                 );
            FSMA_Event_Transition(AIFS-Immediate-Transmit-Multicast,
                                  isMsgAIFS(msg) && isMulticast(getCurrentTransmission()) && !backoff(),
                                  WAITMULTICAST,
                                  sendMulticastFrame(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                  cancelAIFSPeriod();
                                  decreaseBackoffPeriod();
                                  cancelBackoffPeriod();
                                 );
            FSMA_Event_Transition(AIFS-Immediate-Transmit-Data,
                                  isMsgAIFS(msg) && !isMulticast(getCurrentTransmission()) && !backoff(),
                                  WAITACK,
                                  sendDataFrame(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                  cancelAIFSPeriod();
                                  decreaseBackoffPeriod();
                                  cancelBackoffPeriod();
                                 );
            FSMA_Event_Transition(Backoff-Idle,
                                  isBakoffMsg(msg) && transmissionQueueEmpty(),
                                  IDLE,
                                  resetStateVariables();
                                  );
            FSMA_Event_Transition(Backoff-Busy,
                                  isMediumStateChange(msg) && !isMediumFree(),
                                  DEFER,
                                  cancelAIFSPeriod();
                                  decreaseBackoffPeriod();
                                  cancelBackoffPeriod();
                                 );
        }
        FSMA_State(WAITACK)
        {
            FSMA_Enter(scheduleDataTimeoutPeriod(getCurrentTransmission()));
            FSMA_Event_Transition(Receive-ACK-TXOP,
                                  isLowerMsg(msg) && isForUs(frame) && frameType == ST_ACK && txop,
                                  WAITSIFS,
                                  currentAC = oldcurrentAC;
                                  if (retryCounter() == 0) numSentWithoutRetry()++;
                                  numSent()++;
                                  fr = getCurrentTransmission();
                                  numBites += fr->getBitLength();
                                  bites() += fr->getBitLength();
                                  macDelay()->record(simTime() - fr->getMACArrive());
                                  if (maxjitter() == 0 || maxjitter() < (simTime() - fr->getMACArrive()))
                                      maxjitter() = simTime() - fr->getMACArrive();
                                  if (minjitter() == 0 || minjitter() > (simTime() - fr->getMACArrive()))
                                      minjitter() = simTime() - fr->getMACArrive();
                                  EV << "record macDelay AC" << currentAC << " value " << simTime() - fr->getMACArrive() <<endl;
                                  numSentTXOP++;
                                  cancelTimeoutPeriod();
                                  finishCurrentTransmission();
                                  );
/*
            FSMA_Event_Transition(Receive-ACK,
                                  isLowerMsg(msg) && isForUs(frame) && frameType == ST_ACK,
                                  IDLE,
                                  currentAC=oldcurrentAC;
                                  if (retryCounter[currentAC] == 0) numSentWithoutRetry[currentAC]++;
                                  numSent[currentAC]++;
                                  fr=getCurrentTransmission();
                                  numBites += fr->getBitLength();
                                  bites[currentAC] += fr->getBitLength();
                                  macDelay[currentAC].record(simTime() - fr->getMACArrive());
                                  if (maxjitter[currentAC] == 0 || maxjitter[currentAC] < (simTime() - fr->getMACArrive())) maxjitter[currentAC]=simTime() - fr->getMACArrive();
                                      if (minjitter[currentAC] == 0 || minjitter[currentAC] > (simTime() - fr->getMACArrive())) minjitter[currentAC]=simTime() - fr->getMACArrive();
                                          EV << "record macDelay AC" << currentAC << " value " << simTime() - fr->getMACArrive() <<endl;
                                          cancelTimeoutPeriod();
                                          finishCurrentTransmission();
                                         );
             */
             /*Ieee 802.11 2007 9.9.1.2 EDCA TXOPs*/
             FSMA_Event_Transition(Receive-ACK,
                                  isLowerMsg(msg) && isForUs(frame) && frameType == ST_ACK,
                                  DEFER,
                                  currentAC = oldcurrentAC;
                                  if (retryCounter() == 0)
                                      numSentWithoutRetry()++;
                                  numSent()++;
                                  fr = getCurrentTransmission();
                                  numBites += fr->getBitLength();
                                  bites() += fr->getBitLength();
                                  macDelay()->record(simTime() - fr->getMACArrive());
                                  if (maxjitter() == 0 || maxjitter() < (simTime() - fr->getMACArrive()))
                                      maxjitter() = simTime() - fr->getMACArrive();
                                  if (minjitter() == 0 || minjitter() > (simTime() - fr->getMACArrive()))
                                      minjitter() = simTime() - fr->getMACArrive();
                                  EV << "record macDelay AC" << currentAC << " value " << simTime() - fr->getMACArrive() <<endl;
                                  cancelTimeoutPeriod();
                                  finishCurrentTransmission();
                                  resetCurrentBackOff();
                                  );
            FSMA_Event_Transition(Transmit-Data-Failed,
                                  msg == endTimeout && retryCounter(oldcurrentAC) == transmissionLimit - 1,
                                  IDLE,
                                  currentAC = oldcurrentAC;
                                  giveUpCurrentTransmission();
                                  txop = false;
                                  if (endTXOP->isScheduled()) cancelEvent(endTXOP);
                                 );
            FSMA_Event_Transition(Receive-ACK-Timeout,
                                  msg == endTimeout,
                                  DEFER,
                                  currentAC = oldcurrentAC;
                                  retryCurrentTransmission();
                                  txop = false;
                                  if (endTXOP->isScheduled()) cancelEvent(endTXOP);
                                 );
            FSMA_Event_Transition(Interrupted-ACK-Failure,
                                  isLowerMsg(msg) && retryCounter(oldcurrentAC) == transmissionLimit - 1,
                                  RECEIVE,
                                  currentAC=oldcurrentAC;
                                  giveUpCurrentTransmission();
                                  txop = false;
                                  if (endTXOP->isScheduled()) cancelEvent(endTXOP);
                                 );
            FSMA_Event_Transition(Retry-Interrupted-ACK,
                                 isLowerMsg(msg),
                                 RECEIVE,
                                 currentAC=oldcurrentAC;
                                 retryCurrentTransmission();
                                 txop = false;
                                 if (endTXOP->isScheduled()) cancelEvent(endTXOP);
                                 );
        }
        // wait until multicast is sent
        FSMA_State(WAITMULTICAST)
        {
            FSMA_Enter(scheduleMulticastTimeoutPeriod(getCurrentTransmission()));
            /*
                        FSMA_Event_Transition(Transmit-Multicast,
                                              msg == endTimeout,
                                              IDLE,
                            currentAC=oldcurrentAC;
                            finishCurrentTransmission();
                            numSentMulticast++;
                        );
            */
            FSMA_Event_Transition(Transmit-Multicast,
                                  msg == endTimeout,
                                  DEFER,
                                  currentAC = oldcurrentAC;
                                  fr = getCurrentTransmission();
                                  numBites += fr->getBitLength();
                                  bites() += fr->getBitLength();
                                  finishCurrentTransmission();
                                  numSentMulticast++;
                                  resetCurrentBackOff();
                                 );
        }
        // accoriding to 9.2.5.7 CTS procedure
        FSMA_State(WAITCTS)
        {
            FSMA_Enter(scheduleCTSTimeoutPeriod());
            FSMA_Event_Transition(Receive-CTS,
                                  isLowerMsg(msg) && isForUs(frame) && frameType == ST_CTS,
                                  WAITSIFS,
                                  cancelTimeoutPeriod();
                                 );
            FSMA_Event_Transition(Transmit-RTS-Failed,
                                  msg == endTimeout && retryCounter(oldcurrentAC) == transmissionLimit - 1,
                                  IDLE,
                                  currentAC = oldcurrentAC;
                                  giveUpCurrentTransmission();
                                 );
            FSMA_Event_Transition(Receive-CTS-Timeout,
                                  msg == endTimeout,
                                  DEFER,
                                  currentAC = oldcurrentAC;
                                  retryCurrentTransmission();
                                 );
        }
        FSMA_State(WAITSIFS)
        {
            FSMA_Enter(scheduleSIFSPeriod(frame));
            FSMA_Event_Transition(Transmit-Data-TXOP,
                                  msg == endSIFS && getFrameReceivedBeforeSIFS()->getType() == ST_ACK,
                                  WAITACK,
                                  sendDataFrame(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                 );
            FSMA_Event_Transition(Transmit-CTS,
                                  msg == endSIFS && getFrameReceivedBeforeSIFS()->getType() == ST_RTS,
                                  IDLE,
                                  sendCTSFrameOnEndSIFS();
                                  if (fixFSM)
                                      finishReception();
                                  else
                                      resetStateVariables();
                                  );
            FSMA_Event_Transition(Transmit-DATA,
                                  msg == endSIFS && getFrameReceivedBeforeSIFS()->getType() == ST_CTS,
                                  WAITACK,
                                  sendDataFrameOnEndSIFS(getCurrentTransmission());
                                  oldcurrentAC = currentAC;
                                 );
            FSMA_Event_Transition(Transmit-ACK,
                                  msg == endSIFS && isDataOrMgmtFrame(getFrameReceivedBeforeSIFS()),
                                  IDLE,
                                  sendACKFrameOnEndSIFS();
                                  if (fixFSM)
                                      finishReception();
                                  else
                                      resetStateVariables();
                                   );
        }
        // this is not a real state
        FSMA_State(RECEIVE)
        {
            FSMA_No_Event_Transition(Immediate-Receive-Error,
                                     isLowerMsg(msg) && (msgKind == COLLISION || msgKind == BITERROR),
                                     IDLE,
                                     EV << "received frame contains bit errors or collision, next wait period is EIFS\n";
                                     numCollision++;
                                     if (fixFSM)
                                         finishReception();
                                     else
                                         resetStateVariables();
                                     );
            FSMA_No_Event_Transition(Immediate-Receive-Multicast,
                                     isLowerMsg(msg) && isMulticast(frame) && !isSentByUs(frame) && isDataOrMgmtFrame(frame),
                                     IDLE,
                                     sendUp(frame);
                                     numReceivedMulticast++;
                                     if (fixFSM)
                                         finishReception();
                                     else
                                         resetStateVariables();
                                     );
            FSMA_No_Event_Transition(Immediate-Receive-Data,
                                     isLowerMsg(msg) && isForUs(frame) && isDataOrMgmtFrame(frame),
                                     WAITSIFS,
                                     sendUp(frame);
                                     numReceived++;
                                    );
            FSMA_No_Event_Transition(Immediate-Receive-RTS,
                                     isLowerMsg(msg) && isForUs(frame) && frameType == ST_RTS,
                                     WAITSIFS,
                                    );
            FSMA_No_Event_Transition(Immediate-Receive-Other-backtobackoff,
                                     isLowerMsg(msg) && isBackoffPending(), //(backoff[0] || backoff[1] || backoff[2] || backoff[3]),
                                     DEFER,
                                    );
            FSMA_No_Event_Transition(Immediate-Promiscuous-Data,
                                     isLowerMsg(msg) && !isForUs(frame) && isDataOrMgmtFrame(frame),
                                     IDLE,
                                     promiscousFrame(frame);
                                     if (fixFSM)
                                         finishReception();
                                     else
                                         resetStateVariables();
                                     numReceivedOther++;
                                     );
            FSMA_No_Event_Transition(Immediate-Receive-Other,
                                     isLowerMsg(msg),
                                     IDLE,
                                     if (fixFSM)
                                         finishReception();
                                     else
                                         resetStateVariables();
                                     numReceivedOther++;
                                     );
        }
    }
    EV<<"leaving handleWithFSM\n\t";
    logState();
    stateVector.record(fsm.getState());
    if (simTime() - last > 0.1)
    {
        for (int i = 0; i<numCategories(); i++)
        {
            throughput(i)->record(bites(i)/(simTime()-last));
            bites(i) = 0;
            if (maxjitter(i) > 0 && minjitter(i) > 0)
            {
                jitter(i)->record(maxjitter(i)-minjitter(i));
                maxjitter(i) = 0;
                minjitter(i) = 0;
            }
        }
        last = simTime();
    }
}
void Ieee80211Mac::initialize (int stage) [protected, virtual]
Initialization of the module and some variables.
Reimplemented from WirelessMacBase.
{
    WirelessMacBase::initialize(stage);
    if (stage == 0)
    {
        EV << "Initializing stage 0\n";
        int numQueues = 1;
        if (par("EDCA"))
        {
            const char *classifierClass = par("classifier");
            classifier = check_and_cast<IQoSClassifier*>(createOne(classifierClass));
            numQueues = classifier->getNumQueues();
        }
        for (int i=0; i<numQueues; i++)
        {
            Edca catEdca;
            catEdca.backoff = false;
            catEdca.backoffPeriod = -1;
            catEdca.retryCounter = 0;
            edcCAF.push_back(catEdca);
        }
        // initialize parameters
        // Variable to apply the fsm fix
        fixFSM = par("fixFSM");
        if (strcmp("b", par("opMode").stringValue())==0)
            opMode = 'b';
        else if (strcmp("g", par("opMode").stringValue())==0)
            opMode = 'g';
        else if (strcmp("a", par("opMode").stringValue())==0)
            opMode = 'a';
        else if (strcmp("p", par("opMode").stringValue())==0)
             opMode = 'p';
        else
            opMode = 'g';
        PHY_HEADER_LENGTH = par("phyHeaderLength"); //26us
        if (strcmp("SHORT", par("wifiPreambleMode").stringValue())==0)
            wifiPreambleType = WIFI_PREAMBLE_SHORT;
        else if (strcmp("LONG", par("wifiPreambleMode").stringValue())==0)
            wifiPreambleType = WIFI_PREAMBLE_LONG;
        else
            opp_error("Invalid wifiPreambleType. Must be SHORT or LONG");
        useModulationParameters = par("useModulationParameters");
        prioritizeMulticast = par("prioritizeMulticast");
        EV<<"Operating mode: 802.11"<<opMode;
        maxQueueSize = par("maxQueueSize");
        rtsThreshold = par("rtsThresholdBytes");
        // the variable is renamed due to a confusion in the standard
        // the name retry limit would be misleading, see the header file comment
        transmissionLimit = par("retryLimit");
        if (transmissionLimit == -1) transmissionLimit = 7;
        ASSERT(transmissionLimit >= 0);
        EV<<" retryLimit="<<transmissionLimit;
        cwMinData = par("cwMinData");
        if (cwMinData == -1) cwMinData = CW_MIN;
        ASSERT(cwMinData >= 0 && cwMinData <= 32767);
        cwMaxData = par("cwMaxData");
        if (cwMaxData == -1) cwMaxData = CW_MAX;
        ASSERT(cwMaxData >= 0 && cwMaxData <= 32767);
        cwMinMulticast = par("cwMinMulticast");
        if (cwMinMulticast == -1) cwMinMulticast = 31;
        ASSERT(cwMinMulticast >= 0);
        EV<<" cwMinMulticast="<<cwMinMulticast;
        defaultAC = par("defaultAC");
        if (classifier && dynamic_cast<Ieee80211eClassifier*>(classifier))
            dynamic_cast<Ieee80211eClassifier*>(classifier)->setDefaultClass(defaultAC);
        for (int i=0; i<numCategories(); i++)
        {
            std::stringstream os;
            os<< i;
            std::string strAifs = "AIFSN"+os.str();
            std::string strTxop = "TXOP"+os.str();
            if (hasPar(strAifs.c_str()) && hasPar(strTxop.c_str()))
            {
                AIFSN(i) = par(strAifs.c_str());
                TXOP(i) = par(strTxop.c_str());
            }
            else
                opp_error("parameters %s , %s don't exist", strAifs.c_str(), strTxop.c_str());
        }
        if (numCategories()==1)
            AIFSN(0) = par("AIFSN");
        for (int i = 0; i < numCategories(); i++)
        {
            ASSERT(AIFSN(i) >= 0 && AIFSN(i) < 16);
            if (i == 0 || i == 1)
            {
                cwMin(i) = cwMinData;
                cwMax(i) = cwMaxData;
            }
            if (i == 2)
            {
                cwMin(i) = (cwMinData + 1) / 2 - 1;
                cwMax(i) = cwMinData;
            }
            if (i == 3)
            {
                cwMin(i) = (cwMinData + 1) / 4 - 1;
                cwMax(i) = (cwMinData + 1) / 2 - 1;
            }
        }
        ST = par("slotTime"); //added by sorin
        if (ST==-1)
            ST = 20e-6; //20us
        EV<<" slotTime="<<ST*1e6<<"us DIFS="<< getDIFS()*1e6<<"us";
        basicBitrate = par("basicBitrate");
        if (basicBitrate==-1)
            basicBitrate = 1e6; //1Mbps
        EV<<" basicBitrate="<<basicBitrate/1e6<<"M";
        bitrate = par("bitrate");
        if (bitrate==-1)
            bitrate = 11e6; //11Mbps
        EV<<" bitrate="<<bitrate/1e6<<"M IDLE="<<IDLE<<" RECEIVE="<<RECEIVE<<endl;
        duplicateDetect = par("duplicateDetectionFilter");
        purgeOldTuples = par("purgeOldTuples");
        duplicateTimeOut = par("duplicateTimeOut");
        lastTimeDelete = 0;
        //FIXME refactor! copy-pasted code (4 times) with minimal changes
        // Auto rate code
        bool found = false;
        if (opMode == 'b')
        {
            rateIndex = 0;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (bitrate == BITRATES_80211b[i])
                {
                    found = true;
                    rateIndex = i;
                    break;
                }
            }
            if (!found)
            {
                bitrate = BITRATES_80211b[getMaxBitrate()-1];
                rateIndex = getMaxBitrate()-1;
            }
            found = false;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (basicBitrate == BITRATES_80211b[i])
                {
                    found = true;
                    break;
                }
            }
            if (!found)
                basicBitrate = BITRATES_80211b[0];
        }
        else if (opMode == 'g')
        {
            rateIndex = 0;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (bitrate == BITRATES_80211g[i])
                {
                    found = true;
                    rateIndex = i;
                    break;
                }
            }
            if (!found)
            {
                bitrate = BITRATES_80211g[getMaxBitrate()-1];
                rateIndex = getMaxBitrate()-1;
            }
            found = false;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (basicBitrate == BITRATES_80211g[i])
                {
                    found = true;
                    break;
                }
            }
            if (!found)
                basicBitrate = BITRATES_80211g[0];
        }
        else if (opMode == 'a')
        {
            rateIndex = 0;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (bitrate == BITRATES_80211a[i])
                {
                    found = true;
                    rateIndex = i;
                    break;
                }
            }
            if (!found)
            {
                bitrate = BITRATES_80211a[getMaxBitrate()-1];
                rateIndex = getMaxBitrate()-1;
            }
            found = false;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (basicBitrate == BITRATES_80211a[i])
                {
                    found = true;
                    break;
                }
            }
            if (!found)
                basicBitrate = BITRATES_80211a[0];
        }
        else if (opMode == 'p')
        {
            rateIndex = 0;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (bitrate == BITRATES_80211p[i])
                {
                    found = true;
                    rateIndex = i;
                    break;
                }
            }
            if (!found)
            {
                bitrate = BITRATES_80211p[getMaxBitrate()-1];
                rateIndex = getMaxBitrate()-1;
            }
            found = false;
            for (int i = 0; i < getMaxBitrate(); i++)
            {
                if (basicBitrate == BITRATES_80211p[i])
                {
                    found = true;
                    break;
                }
            }
            if (!found)
                basicBitrate = BITRATES_80211p[0];
        }
        // configure AutoBit Rate
        configureAutoBitRate();
//end auto rate code
        EV<<" bitrate="<<bitrate/1e6<<"M IDLE="<<IDLE<<" RECEIVE="<<RECEIVE<<endl;
        const char *addressString = par("address");
        address = isInterfaceRegistered();
        if (address.isUnspecified())
        {
            if (!strcmp(addressString, "auto"))
            {
                // assign automatic address
                address = MACAddress::generateAutoAddress();
                // change module parameter from "auto" to concrete address
                par("address").setStringValue(address.str().c_str());
            }
            else
                address.setAddress(addressString);
        }
        // subscribe for the information of the carrier sense
        nb->subscribe(this, NF_RADIOSTATE_CHANGED);
        // initialize self messages
        endSIFS = new cMessage("SIFS");
        endDIFS = new cMessage("DIFS");
        for (int i=0; i<numCategories(); i++)
        {
            setEndAIFS(i, new cMessage("AIFS", i));
            setEndBackoff(i, new cMessage("Backoff", i));
        }
        endTXOP = new cMessage("TXOP");
        endTimeout = new cMessage("Timeout");
        endReserve = new cMessage("Reserve");
        mediumStateChange = new cMessage("MediumStateChange");
        // interface
        if (isInterfaceRegistered().isUnspecified())
            registerInterface();
        // obtain pointer to external queue
        initializeQueueModule();
        // state variables
        fsm.setName("Ieee80211Mac State Machine");
        mode = DCF;
        sequenceNumber = 0;
        radioState = RadioState::IDLE;
        currentAC = 0;
        oldcurrentAC = 0;
        lastReceiveFailed = false;
        for (int i=0; i<numCategories(); i++)
            numDropped(i) = 0;
        nav = false;
        txop = false;
        last = 0;
        contI = 0;
        contJ = 0;
        recvdThroughput = 0;
        _snr = 0;
        samplingCoeff = 50;
        // statistics
        for (int i=0; i<numCategories(); i++)
        {
            numRetry(i) = 0;
            numSentWithoutRetry(i) = 0;
            numGivenUp(i) = 0;
            numSent(i) = 0;
            bites(i) = 0;
            maxjitter(i) = 0;
            minjitter(i) = 0;
        }
        numCollision = 0;
        numInternalCollision = 0;
        numReceived = 0;
        numSentMulticast = -1; //sorin
        numReceivedMulticast = 0;
        numBites = 0;
        numSentTXOP = 0;
        numReceivedOther = 0;
        numAckSend = 0;
        successCounter = 0;
        failedCounter = 0;
        recovery = 0;
        timer = 0;
        timeStampLastMessageReceived = 0;
        stateVector.setName("State");
        stateVector.setEnum("Ieee80211Mac");
        radioStateVector.setName("RadioState");
        radioStateVector.setEnum("RadioState");
        for (int i=0; i<numCategories(); i++)
        {
            EdcaOutVector outVectors;
            std::stringstream os;
            os<< i;
            std::string th = "throughput AC"+os.str();
            std::string delay = "Mac delay AC"+os.str();
            std::string jit = "jitter AC"+os.str();
            outVectors.jitter = new cOutVector(jit.c_str());
            outVectors.throughput = new cOutVector(th.c_str());
            outVectors.macDelay = new cOutVector(delay.c_str());
            edcCAFOutVector.push_back(outVectors);
        }
        // Code to compute the throughput over a period of time
        throughputTimePeriod = par("throughputTimePeriod");
        recBytesOverPeriod = 0;
        throughputLastPeriod = 0;
        throughputTimer = NULL;
        if (throughputTimePeriod>0)
            throughputTimer = new cMessage("throughput-timer");
        if (throughputTimer)
            scheduleAt(simTime()+throughputTimePeriod, throughputTimer);
        // end initialize variables throughput over a period of time
        // initialize watches
        validRecMode = false;
        initWatches();
        radioModule = gate("lowerLayerOut")->getNextGate()->getOwnerModule()->getId();
    }
}
void Ieee80211Mac::initializeQueueModule () [protected, virtual]
Referenced by initialize().
{
    // use of external queue module is optional -- find it if there's one specified
    if (par("queueModule").stringValue()[0])
    {
        cModule *module = getParentModule()->getSubmodule(par("queueModule").stringValue());
        queueModule = check_and_cast<IPassiveQueue *>(module);
        EV << "Requesting first two frames from queue module\n";
        queueModule->requestPacket();
        // needed for backoff: mandatory if next message is already present
        queueModule->requestPacket();
    }
}
void Ieee80211Mac::initWatches () [protected, virtual]
Referenced by initialize().
{
// initialize watches
     WATCH(fsm);
     WATCH(radioState);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].retryCounter);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].backoff);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].backoffPeriod);
     WATCH(currentAC);
     WATCH(oldcurrentAC);
     for (int i=0; i<numCategories(); i++)
         WATCH_LIST(edcCAF[i].transmissionQueue);
     WATCH(nav);
     WATCH(txop);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].numRetry);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].numSentWithoutRetry);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].numGivenUp);
     WATCH(numCollision);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].numSent);
     WATCH(numBites);
     WATCH(numSentTXOP);
     WATCH(numReceived);
     WATCH(numSentMulticast);
     WATCH(numReceivedMulticast);
     for (int i=0; i<numCategories(); i++)
         WATCH(edcCAF[i].numDropped);
     if (throughputTimer)
         WATCH(throughputLastPeriod);
}
void Ieee80211Mac::invalidateBackoffPeriod () [protected, virtual]
Generates a new backoff period based on the contention window.
Referenced by handleWithFSM().
{
    backoffPeriod() = -1;
}
virtual bool Ieee80211Mac::isBackoffPending () [inline, protected, virtual]
Referenced by handleWithFSM().
    {
        for (unsigned int i = 0; i<edcCAF.size(); i++)
        {
            if (edcCAF[i].backoff)
                return true;
        }
        return false;
    }
const bool Ieee80211Mac::isBakoffMsg (cMessage * msg) [protected, virtual]
Referenced by handleWithFSM().
{
    for (unsigned int i=0; i<edcCAF.size(); i++)
    {
        if (msg==edcCAF[i].endBackoff)
           return true;
    }
    return false;
}
bool Ieee80211Mac::isDataOrMgmtFrame (Ieee80211Frame * frame) [protected, virtual]
Checks if the frame is a data or management frame.
Referenced by handleWithFSM().
{
    return dynamic_cast<Ieee80211DataOrMgmtFrame*>(frame);
}
bool Ieee80211Mac::isDuplicated (cMessage * msg) [protected, virtual]
Referenced by promiscousFrame(), and sendUp().
{
    if (duplicateDetect) // duplicate detection filter
    {
        Ieee80211DataOrMgmtFrame *frame = dynamic_cast<Ieee80211DataOrMgmtFrame*>(msg);
        if (frame)
        {
            Ieee80211ASFTupleList::iterator it = asfTuplesList.find(frame->getTransmitterAddress());
            if (it == asfTuplesList.end())
            {
                Ieee80211ASFTuple tuple;
                tuple.receivedTime = simTime();
                tuple.sequenceNumber = frame->getSequenceNumber();
                tuple.fragmentNumber = frame->getFragmentNumber();
                asfTuplesList.insert(std::pair<MACAddress, Ieee80211ASFTuple>(frame->getTransmitterAddress(), tuple));
            }
            else
            {
                // check if duplicate
                if (it->second.sequenceNumber == frame->getSequenceNumber()
                        && it->second.fragmentNumber == frame->getFragmentNumber())
                {
                    return true;
                }
                else
                {
                    // actualize
                    it->second.sequenceNumber = frame->getSequenceNumber();
                    it->second.fragmentNumber = frame->getFragmentNumber();
                    it->second.receivedTime = simTime();
                }
            }
        }
    }
    return false;
}
bool Ieee80211Mac::isForUs (Ieee80211Frame * msg) [protected, virtual]
Returns true if message destination address is ours.
Referenced by handleLowerMsg(), handleWithFSM(), and scheduleReservePeriod().
{
    return frame && frame->getReceiverAddress() == address;
}
const MACAddress & Ieee80211Mac::isInterfaceRegistered () [protected, virtual]
Referenced by initialize().
{
    if (!par("multiMac").boolValue())
        return MACAddress::UNSPECIFIED_ADDRESS;
    IInterfaceTable *ift = InterfaceTableAccess().getIfExists();
    if (!ift)
        return MACAddress::UNSPECIFIED_ADDRESS;
    char *interfaceName = new char[strlen(getParentModule()->getFullName()) + 1];
    char *d = interfaceName;
    for (const char *s = getParentModule()->getFullName(); *s; s++)
        if (isalnum(*s))
            *d++ = *s;
    *d = '\0';
    InterfaceEntry * e = ift->getInterfaceByName(interfaceName);
    delete [] interfaceName;
    if (e)
        return e->getMacAddress();
    return MACAddress::UNSPECIFIED_ADDRESS;
}
bool Ieee80211Mac::isInvalidBackoffPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    return backoffPeriod() == -1;
}
bool Ieee80211Mac::isMediumFree () [protected, virtual]
Tells if the medium is free according to the physical and virtual carrier sense algorithm.
Referenced by handleWithFSM(), and logState().
{
    return radioState == RadioState::IDLE && !endReserve->isScheduled();
}
bool Ieee80211Mac::isMediumStateChange (cMessage * msg) [protected, virtual]
Used by the state machine to identify medium state change events.
This message is currently optimized away and not sent through the kernel.
Referenced by handleWithFSM().
{
    return msg == mediumStateChange || (msg == endReserve && radioState == RadioState::IDLE);
}
bool Ieee80211Mac::isMsgAIFS (cMessage * msg) [protected, virtual]
Checks if the message is endAIFS and set currentAC.
Referenced by handleWithFSM().
{
    for (int i = 0; i<numCategories(); i++)
        if (msg == endAIFS(i))
            return true;
    return false;
}
bool Ieee80211Mac::isMulticast (Ieee80211Frame * msg) [protected, virtual]
Returns true if message is a multicast message.
Referenced by buildDataFrame(), computeBackoffPeriod(), and handleWithFSM().
{
    return frame && frame->getReceiverAddress().isMulticast();
}
bool Ieee80211Mac::isSentByUs (Ieee80211Frame * msg) [protected, virtual]
Returns true if message source address is ours.
Referenced by handleLowerMsg(), and handleWithFSM().
{
    if (dynamic_cast<Ieee80211DataOrMgmtFrame *>(frame))
    {
        //EV<<"ad3 "<<((Ieee80211DataOrMgmtFrame *)frame)->getAddress3();
        //EV<<"myad "<<address<<endl;
        if ( ((Ieee80211DataOrMgmtFrame *)frame)->getAddress3() == address)//received frame sent by us
            return 1;
    }
    else
        EV<<"Cast failed"<<endl;
    return 0;
}
cOutVector * Ieee80211Mac::jitter (int i = -1) [protected, virtual]
Referenced by handleWithFSM().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAFOutVector[i].jitter;
}
void Ieee80211Mac::logState () [protected, virtual]
Logs all state information.
Referenced by handleWithFSM().
{
    std::string a[10];
    std::string b[10];
    std::string medium = "busy";
    for (int i=0; i<10; i++)
    {
        a[i] = "";
        b[i] = "";
    }
    if (isMediumFree())
        medium = "free";
    for (int i=0; i<numCategories(); i++)
    {
        if (endBackoff(i)->isScheduled())
            b[i] = "scheduled";
        if (endAIFS(i)->isScheduled())
            a[i] = "scheduled";
    }
    EV  << "# state information: mode = " << modeName(mode) << ", state = " << fsm.getStateName();
    EV << ", backoff 0.."<<numCategories()<<" = ";
    for (int i=0; i<numCategories(); i++)
         EV << backoff(i) << " ";
    EV <<  "\n# backoffPeriod 0.."<<numCategories()<<" = ";
    for (int i=0; i<numCategories(); i++)
         EV << backoffPeriod(i) << " ";
    EV << "\n# retryCounter 0.."<<numCategories()<<" = ";
    for (int i=0; i<numCategories(); i++)
         EV << retryCounter(i) << " ";
    EV << ", radioState = " << radioState << ", nav = " << nav <<  ",txop is "<< txop << "\n";
    EV << "#queue size 0.."<<numCategories()<<" = ";
    for (int i=0; i<numCategories(); i++)
        EV << transmissionQueue(i)->size() << " ";
    EV << ", medium is " << medium << ", scheduled AIFS are ";
    for (int i=0; i<numCategories(); i++)
        EV << i << "(" << a[i] << ")";
    EV << ", scheduled backoff are ";
    for (int i=0; i<numCategories(); i++)
        EV << i << "(" << b[i] << ")";
    EV << "\n# currentAC: " << currentAC << ", oldcurrentAC: " << oldcurrentAC;
    if (getCurrentTransmission() != NULL)
         EV << "\n# current transmission: " << getCurrentTransmission()->getId();
    else
        EV << "\n# current transmission: none";
    EV << endl;
}
cOutVector * Ieee80211Mac::macDelay (int i = -1) [protected, virtual]
Referenced by handleWithFSM().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAFOutVector[i].macDelay;
}
int Ieee80211Mac::mappingAccessCategory (Ieee80211DataOrMgmtFrame * frame) [protected, virtual]
Mapping to access categories.
Referenced by handleUpperMsg().
{
    bool isDataFrame = (dynamic_cast<Ieee80211DataFrame *>(frame) != NULL);
    currentAC = classifier ? classifier->classifyPacket(frame) : 0;
    // check for queue overflow
    if (isDataFrame && maxQueueSize && (int)transmissionQueueSize() >= maxQueueSize)
    {
        EV << "message " << frame << " received from higher layer but AC queue is full, dropping message\n";
        numDropped()++;
        delete frame;
        return 200;
    }
    if (isDataFrame)
    {
        if (!prioritizeMulticast  || !frame->getReceiverAddress().isMulticast() || transmissionQueue()->size() < 2)
            transmissionQueue()->push_back(frame);
        else
        {
            // if the last frame is management insert here
            Ieee80211DataFrame * frameAux = dynamic_cast<Ieee80211DataFrame *>(transmissionQueue()->back());
            if ((frameAux == NULL) || (frameAux && frameAux->getReceiverAddress().isMulticast()))
                transmissionQueue()->push_back(frame);
            else
            {
                // in other case search the possition
                std::list<Ieee80211DataOrMgmtFrame*>::iterator p = transmissionQueue()->end();
                while ((*p)->getReceiverAddress().isMulticast() && (p != transmissionQueue()->begin())) // search the first broadcast frame
                    {
                    if (dynamic_cast<Ieee80211DataFrame *>(*p) == NULL)
                        break;
                    p--;
                    }
                p++;
                transmissionQueue()->insert(p, frame);
            }
        }
    }
    else
    {
        if (transmissionQueue()->empty() || transmissionQueue()->size() == 1)
        {
            transmissionQueue()->push_back(frame);
        }
        else
        {
            std::list<Ieee80211DataOrMgmtFrame*>::iterator p;
            //we don't know if first frame in the queue is in middle of transmission
            //so for sure we placed it on second place
            p = transmissionQueue()->begin();
            p++;
            while ((dynamic_cast<Ieee80211DataFrame *> (*p) == NULL) && (p != transmissionQueue()->end())) // search the first not management frame
                p++;
            transmissionQueue()->insert(p, frame);
        }
    }
    EV << "frame classified as access category "<< currentAC <<" (0 background, 1 best effort, 2 video, 3 voice)\n";
    return true;
}
simtime_t & Ieee80211Mac::maxjitter (int i = -1) [protected, virtual]
Referenced by handleWithFSM(), and initialize().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].maxjitter;
}
simtime_t & Ieee80211Mac::minjitter (int i = -1) [protected, virtual]
Referenced by handleWithFSM(), and initialize().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].minjitter;
}
const char * Ieee80211Mac::modeName (int mode) [protected]
Referenced by logState().
{
#define CASE(x) case x: s=#x; break
    const char *s = "???";
    switch (mode)
    {
        CASE(DCF);
        CASE(PCF);
    }
    return s;
#undef CASE
}
bool Ieee80211Mac::needNormalFallback (void) [protected, virtual]
Referenced by reportDataFailed().
{
    int retryMod = (retryCounter() - 1) % 2;
    if (retryMod == 1)
    {
        return true;
    }
    else
    {
        return false;
    }
}
bool Ieee80211Mac::needRecoveryFallback (void) [protected, virtual]
{
    if (retryCounter() == 1)
    {
        return true;
    }
    else
    {
        return false;
    }
}
const int Ieee80211Mac::numCategories () [inline, protected]
Referenced by cancelAIFSPeriod(), cancelBackoffPeriod(), decreaseBackoffPeriod(), finish(), getDIFS(), handleSelfMsg(), handleUpperMsg(), handleWithFSM(), initialize(), initWatches(), isMsgAIFS(), logState(), numSentWithoutRetry(), popTransmissionQueue(), scheduleAIFSPeriod(), transmissionQueueEmpty(), and transmissionQueueSize().
{return edcCAF.size();}
long & Ieee80211Mac::numDropped (int i = -1) [protected, virtual]
Referenced by finish(), initialize(), initWatches(), and mappingAccessCategory().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].numDropped;
}
long & Ieee80211Mac::numGivenUp (int i = -1) [protected, virtual]
Referenced by finish(), giveUpCurrentTransmission(), initialize(), and initWatches().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].numGivenUp;
}
virtual int Ieee80211Mac::numInitStages () const [inline, protected, virtual]
Initialization of the module and its variables.
{return 2;}
long & Ieee80211Mac::numRetry (int i = -1) [protected, virtual]
Referenced by finish(), initialize(), initWatches(), and retryCurrentTransmission().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].numRetry;
}
long & Ieee80211Mac::numSent (int i = -1) [protected, virtual]
Referenced by finish(), handleWithFSM(), initialize(), and initWatches().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].numSent;
}
long & Ieee80211Mac::numSentWithoutRetry (int i = -1) [protected, virtual]
Referenced by finish(), handleWithFSM(), initialize(), and initWatches().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)numCategories())
         opp_error("AC doesn't exist");
     return edcCAF[i].numSentWithoutRetry;
}
void Ieee80211Mac::popTransmissionQueue () [protected, virtual]
Deletes frame at the front of queue.
Referenced by finishCurrentTransmission(), and giveUpCurrentTransmission().
{
    EV << "dropping frame from transmission queue\n";
    Ieee80211Frame *temp = dynamic_cast<Ieee80211Frame *>(transmissionQueue()->front());
    ASSERT(!transmissionQueue()->empty());
    transmissionQueue()->pop_front();
    if (queueModule)
    {
        if (numCategories()==1)
        {
        // the module are continuously asking for packets
            EV << "requesting another frame from queue module\n";
            queueModule->requestPacket();
         }
         else if (numCategories()>1 && (int)transmissionQueueSize()==maxQueueSize-1)
         {
         // Now exist a empty frame space
         // the module are continuously asking for packets
            EV << "requesting another frame from queue module\n";
            queueModule->requestPacket();
         }
    }
    delete temp;
}
void Ieee80211Mac::promiscousFrame (cMessage * msg) [protected, virtual]
Referenced by handleWithFSM().
{
    if (!isDuplicated(msg)) // duplicate detection filter
        nb->fireChangeNotification(NF_LINK_PROMISCUOUS, msg);
}
void Ieee80211Mac::receiveChangeNotification (int category, const cObject * details) [protected, virtual]
Called by the NotificationBoard whenever a change occurs we're interested in.
Implements INotifiable.
{
    Enter_Method_Silent();
    printNotificationBanner(category, details);
    if (category == NF_RADIOSTATE_CHANGED)
    {
        RadioState * rstate = check_and_cast<RadioState *>(details);
        if (rstate->getRadioId()!=getRadioModuleId())
            return;
        RadioState::State newRadioState = rstate->getState();
        // FIXME: double recording, because there's no sample hold in the gui
        radioStateVector.record(radioState);
        radioStateVector.record(newRadioState);
        radioState = newRadioState;
        handleWithFSM(mediumStateChange);
    }
}
void Ieee80211Mac::registerInterface () [protected, virtual]
Referenced by initialize().
{
    IInterfaceTable *ift = InterfaceTableAccess().getIfExists();
    if (!ift)
        return;
    InterfaceEntry *e = new InterfaceEntry(this);
    // interface name: NetworkInterface module's name without special characters ([])
    char *interfaceName = new char[strlen(getParentModule()->getFullName()) + 1];
    char *d = interfaceName;
    for (const char *s = getParentModule()->getFullName(); *s; s++)
        if (isalnum(*s))
            *d++ = *s;
    *d = '\0';
    e->setName(interfaceName);
    delete [] interfaceName;
    // address
    e->setMACAddress(address);
    e->setInterfaceToken(address.formInterfaceIdentifier());
    // FIXME: MTU on 802.11 = ?
    e->setMtu(par("mtu").longValue());
    // capabilities
    e->setBroadcast(true);
    e->setMulticast(true);
    e->setPointToPoint(false);
    // add
    ift->addInterface(e);
}
void Ieee80211Mac::removeOldTuplesFromDuplicateMap () [protected, virtual]
Referenced by handleWithFSM().
{
    if (duplicateDetect && lastTimeDelete+duplicateTimeOut>=simTime())
    {
        lastTimeDelete=simTime();
        for (Ieee80211ASFTupleList::iterator it = asfTuplesList.begin();it!=asfTuplesList.begin();)
        {
            if (it->second.receivedTime+duplicateTimeOut<simTime())
            {
                Ieee80211ASFTupleList::iterator itAux=it;
                it++;
                asfTuplesList.erase(itAux);
            }
            else
                it++;
        }
    }
}
void Ieee80211Mac::reportDataFailed (void) [protected, virtual]
Referenced by retryCurrentTransmission().
{
    retryCounter()++;
    if (rateControlMode==RATE_CR)
       return;
    timer++;
    failedCounter++;
    successCounter = 0;
    if (recovery)
    {
        if (retryCounter() == 1)
        {
            reportRecoveryFailure();
            if (rateIndex != getMinBitrate() && rateControlMode != RATE_CR)
            {
                rateIndex--;
                if (opMode=='b') setBitrate(BITRATES_80211b[rateIndex]);
                else if (opMode=='g') setBitrate(BITRATES_80211g[rateIndex]);
                else if (opMode=='a') setBitrate(BITRATES_80211a[rateIndex]);
                else if (opMode=='p') setBitrate(BITRATES_80211p[rateIndex]);
                else opp_error("mode not supported");
            }
        }
        timer = 0;
    }
    else
    {
        if (needNormalFallback())
        {
            reportFailure();
            if (rateIndex != getMinBitrate() && rateControlMode != RATE_CR)
            {
                rateIndex--;
                if (opMode=='b') setBitrate(BITRATES_80211b[rateIndex]);
                else if (opMode=='g') setBitrate(BITRATES_80211g[rateIndex]);
                else if (opMode=='a') setBitrate(BITRATES_80211a[rateIndex]);
                else if (opMode=='p') setBitrate(BITRATES_80211p[rateIndex]);
                else opp_error("mode not supported");
            }
        }
        if (retryCounter() >= 2)
        {
            timer = 0;
        }
    }
}
void Ieee80211Mac::reportDataOk (void) [protected, virtual]
Referenced by resetStateVariables().
{
    retryCounter() = 0;
    if (rateControlMode==RATE_CR)
       return;
    successCounter ++;
    failedCounter = 0;
    recovery = false;
    if ((successCounter == getSuccessThreshold() || timer == getTimerTimeout())
            && (rateIndex+1 < (getMaxBitrate())))
    {
        if (rateControlMode != RATE_CR)
        {
            rateIndex++;
            if (opMode=='b') setBitrate(BITRATES_80211b[rateIndex]);
            else if (opMode=='g') setBitrate(BITRATES_80211g[rateIndex]);
            else if (opMode=='a') setBitrate(BITRATES_80211a[rateIndex]);
            else if (opMode=='p') setBitrate(BITRATES_80211p[rateIndex]);
            else opp_error("mode not supported");
        }
        timer = 0;
        successCounter = 0;
        recovery = true;
    }
}
void Ieee80211Mac::reportFailure (void) [protected, virtual]
Referenced by reportDataFailed().
{
    if (rateControlMode == RATE_AARF)
    {
        setTimerTimeout(getMinTimerTimeout());
        setSuccessThreshold(getMinSuccessThreshold());
    }
}
void Ieee80211Mac::reportRecoveryFailure (void) [protected, virtual]
Referenced by reportDataFailed().
{
    if (rateControlMode == RATE_AARF)
    {
        setSuccessThreshold((int)(std::min((double)getSuccessThreshold() * successCoeff, (double) maxSuccessThreshold)));
        setTimerTimeout((int)(std::max((double)getMinTimerTimeout(), (double)(getSuccessThreshold() * timerCoeff))));
    }
}
void Ieee80211Mac::rescheduleAIFSPeriod (int AccessCategory) [protected, virtual]
{
    ASSERT(1);
    EV << "rescheduling AIFS[" << AccessCategory << "]\n";
    cancelEvent(endAIFS(AccessCategory));
    scheduleAt(simTime() + getAIFS(AccessCategory), endAIFS(AccessCategory));
}
virtual void Ieee80211Mac::resetCurrentBackOff () [inline, protected, virtual]
Referenced by handleWithFSM().
    {
        backoff() = true;
        backoffPeriod() = -1;
    }
void Ieee80211Mac::resetStateVariables () [protected, virtual]
Reset backoff, backoffPeriod and retryCounter for IDLE state.
Referenced by finishCurrentTransmission(), finishReception(), giveUpCurrentTransmission(), and handleWithFSM().
{
    backoffPeriod() = 0;
    if (rateControlMode == RATE_AARF || rateControlMode == RATE_ARF)
        reportDataOk();
    else
        retryCounter() = 0;
    if (!transmissionQueue()->empty())
    {
        backoff() = true;
        getCurrentTransmission()->setRetry(false);
    }
    else
    {
        backoff() = false;
    }
}
int & Ieee80211Mac::retryCounter (int i = -1) [protected, virtual]
Referenced by generateBackoffPeriod(), handleSelfMsg(), handleWithFSM(), initWatches(), logState(), needNormalFallback(), needRecoveryFallback(), reportDataFailed(), reportDataOk(), resetStateVariables(), and retryCurrentTransmission().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].retryCounter;
}
void Ieee80211Mac::retryCurrentTransmission () [protected, virtual]
Referenced by handleSelfMsg(), and handleWithFSM().
{
    ASSERT(retryCounter() < transmissionLimit - 1);
    getCurrentTransmission()->setRetry(true);
    if (rateControlMode == RATE_AARF || rateControlMode == RATE_ARF)
        reportDataFailed();
    else
        retryCounter() ++;
    numRetry()++;
    backoff() = true;
    generateBackoffPeriod();
}
void Ieee80211Mac::scheduleAIFSPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    bool schedule = false;
    for (int i = 0; i<numCategories(); i++)
    {
        if (!endAIFS(i)->isScheduled() && !transmissionQueue(i)->empty())
        {
            if (lastReceiveFailed)
            {
                EV << "reception of last frame failed, scheduling EIFS-DIFS+AIFS period (" << i << ")\n";
                scheduleAt(simTime() + getEIFS() - getDIFS() + getAIFS(i), endAIFS(i));
            }
            else
            {
                EV << "scheduling AIFS period (" << i << ")\n";
                scheduleAt(simTime() + getAIFS(i), endAIFS(i));
            }
        }
        if (endAIFS(i)->isScheduled())
            schedule = true;
    }
    if (!schedule && !endDIFS->isScheduled())
    {
        // schedule default DIFS
        currentAC = numCategories()-1;
        scheduleDIFSPeriod();
    }
}
void Ieee80211Mac::scheduleBackoffPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    EV << "scheduling backoff period\n";
    scheduleAt(simTime() + backoffPeriod(), endBackoff());
}
void Ieee80211Mac::scheduleCTSTimeoutPeriod () [protected, virtual]
Referenced by handleWithFSM().
{
    if (!endTimeout->isScheduled())
    {
        EV << "scheduling CTS timeout period\n";
        scheduleAt(simTime() + computeFrameDuration(LENGTH_RTS, basicBitrate) + getSIFS()
                   + computeFrameDuration(LENGTH_CTS, basicBitrate) + MAX_PROPAGATION_DELAY * 2, endTimeout);
    }
}
void Ieee80211Mac::scheduleDataTimeoutPeriod (Ieee80211DataOrMgmtFrame * frame) [protected, virtual]
Referenced by handleWithFSM().
{
    double tim;
    double bitRate = bitrate;
    if (dynamic_cast<PhyControlInfo*> (frameToSend->getControlInfo()))
    {
        bitRate = dynamic_cast<PhyControlInfo*> (frameToSend->getControlInfo())->getBitrate();
        if (bitRate == 0)
            bitRate = bitrate;
    }
    if (!endTimeout->isScheduled())
    {
        EV << "scheduling data timeout period\n";
        if (useModulationParameters)
        {
            ModulationType modType;
            if ((opMode=='b') || (opMode=='g'))
                modType = WifiModulationType::getMode80211g(bitRate);
            else if (opMode=='a')
                modType = WifiModulationType::getMode80211a(bitRate);
            else if (opMode=='p')
                modType = WifiModulationType::getMode80211p(bitRate);
            else
                opp_error("mode not supported");
            WifiModulationType::getSlotDuration(modType,wifiPreambleType);
            tim = computeFrameDuration(frameToSend) +SIMTIME_DBL(
                 WifiModulationType::getSlotDuration(modType,wifiPreambleType) +
                 WifiModulationType::getSifsTime(modType,wifiPreambleType) +
                 WifiModulationType::get_aPHY_RX_START_Delay (modType,wifiPreambleType));
        }
        else
            tim = computeFrameDuration(frameToSend) +SIMTIME_DBL( getSIFS()) + computeFrameDuration(LENGTH_ACK, basicBitrate) + MAX_PROPAGATION_DELAY * 2;
        EV<<" time out="<<tim*1e6<<"us"<<endl;
        scheduleAt(simTime() + tim, endTimeout);
    }
}
void Ieee80211Mac::scheduleDIFSPeriod () [protected, virtual]
Referenced by scheduleAIFSPeriod().
{
    if (lastReceiveFailed)
    {
        EV << "reception of last frame failed, scheduling EIFS period\n";
        scheduleAt(simTime() + getEIFS(), endDIFS);
    }
    else
    {
        EV << "scheduling DIFS period\n";
        scheduleAt(simTime() + getDIFS(), endDIFS);
    }
}
void Ieee80211Mac::scheduleMulticastTimeoutPeriod (Ieee80211DataOrMgmtFrame * frame) [protected, virtual]
Referenced by handleWithFSM().
{
    if (!endTimeout->isScheduled())
    {
        EV << "scheduling multicast timeout period\n";
        scheduleAt(simTime() + computeFrameDuration(frameToSend), endTimeout);
    }
}
void Ieee80211Mac::scheduleReservePeriod (Ieee80211Frame * frame) [protected, virtual]
Schedule network allocation period according to 9.2.5.4.
Referenced by handleWithFSM().
{
    simtime_t reserve = frame->getDuration();
    // see spec. 7.1.3.2
    if (!isForUs(frame) && reserve != 0 && reserve < 32768)
    {
        if (endReserve->isScheduled())
        {
            simtime_t oldReserve = endReserve->getArrivalTime() - simTime();
            if (oldReserve > reserve)
                return;
            reserve = std::max(reserve, oldReserve);
            cancelEvent(endReserve);
        }
        else if (radioState == RadioState::IDLE)
        {
            // NAV: the channel just became virtually busy according to the spec
            scheduleAt(simTime(), mediumStateChange);
        }
        EV << "scheduling reserve period for: " << reserve << endl;
        ASSERT(reserve > 0);
        nav = true;
        scheduleAt(simTime() + reserve, endReserve);
    }
}
void Ieee80211Mac::scheduleSIFSPeriod (Ieee80211Frame * frame) [protected, virtual]
Referenced by handleWithFSM().
{
    EV << "scheduling SIFS period\n";
    endSIFS->setContextPointer(frame->dup());
    scheduleAt(simTime() + getSIFS(), endSIFS);
}
void Ieee80211Mac::sendACKFrame (Ieee80211DataOrMgmtFrame * frame) [protected, virtual]
Referenced by sendACKFrameOnEndSIFS().
{
    EV << "sending ACK frame\n";
    numAckSend++;
    sendDown(setBasicBitrate(buildACKFrame(frameToACK)));
}
void Ieee80211Mac::sendACKFrameOnEndSIFS () [protected, virtual]
Referenced by handleWithFSM().
{
    Ieee80211Frame *frameToACK = (Ieee80211Frame *)endSIFS->getContextPointer();
    endSIFS->setContextPointer(NULL);
    sendACKFrame(check_and_cast<Ieee80211DataOrMgmtFrame*>(frameToACK));
    delete frameToACK;
}
void Ieee80211Mac::sendCTSFrame (Ieee80211RTSFrame * rtsFrame) [protected, virtual]
Referenced by sendCTSFrameOnEndSIFS().
{
    EV << "sending CTS frame\n";
    sendDown(setBasicBitrate(buildCTSFrame(rtsFrame)));
}
void Ieee80211Mac::sendCTSFrameOnEndSIFS () [protected, virtual]
Referenced by handleWithFSM().
{
    Ieee80211Frame *rtsFrame = (Ieee80211Frame *)endSIFS->getContextPointer();
    endSIFS->setContextPointer(NULL);
    sendCTSFrame(check_and_cast<Ieee80211RTSFrame*>(rtsFrame));
    delete rtsFrame;
}
void Ieee80211Mac::sendDataFrame (Ieee80211DataOrMgmtFrame * frameToSend) [protected, virtual]
Referenced by handleWithFSM(), and sendDataFrameOnEndSIFS().
{
    simtime_t t = 0, time = 0;
    int count = 0;
    std::list<Ieee80211DataOrMgmtFrame*>::iterator frame;
    frame = transmissionQueue()->begin();
    ASSERT(*frame==frameToSend);
    if (!txop && TXOP() > 0 && transmissionQueue()->size() >= 2 )
    {
        //we start packet burst within TXOP time period
        txop = true;
        for (frame=transmissionQueue()->begin(); frame != transmissionQueue()->end(); ++frame)
        {
            count++;
            t = computeFrameDuration(*frame) + 2 * getSIFS() + computeFrameDuration(LENGTH_ACK, basicBitrate);
            EV << "t is " << t << endl;
            if (TXOP()>time+t)
            {
                time += t;
                EV << "adding t \n";
            }
            else
            {
                break;
            }
        }
        //to be sure we get endTXOP earlier then receive ACK and we have to minus SIFS time from first packet
        time -= getSIFS()/2 + getSIFS();
        EV << "scheduling TXOP for AC" << currentAC << ", duration is " << time << ",count is " << count << endl;
        scheduleAt(simTime() + time, endTXOP);
    }
    EV << "sending Data frame\n";
    sendDown(buildDataFrame(dynamic_cast<Ieee80211DataOrMgmtFrame*>(setBitrateFrame(frameToSend))));
}
void Ieee80211Mac::sendDataFrameOnEndSIFS (Ieee80211DataOrMgmtFrame * frameToSend) [protected, virtual]
Referenced by handleWithFSM().
{
    Ieee80211Frame *ctsFrame = (Ieee80211Frame *)endSIFS->getContextPointer();
    endSIFS->setContextPointer(NULL);
    sendDataFrame(frameToSend);
    delete ctsFrame;
}
void Ieee80211Mac::sendDownPendingRadioConfigMsg () [protected, virtual]
Send down the change channel message to the physical layer if there is any.
Referenced by handleWithFSM().
{
    if (pendingRadioConfigMsg != NULL)
    {
        sendDown(pendingRadioConfigMsg);
        pendingRadioConfigMsg = NULL;
    }
}
void Ieee80211Mac::sendMulticastFrame (Ieee80211DataOrMgmtFrame * frameToSend) [protected, virtual]
Referenced by handleWithFSM().
{
    EV << "sending Multicast frame\n";
    if (frameToSend->getControlInfo())
        delete frameToSend->removeControlInfo();
    sendDown(buildDataFrame(dynamic_cast<Ieee80211DataOrMgmtFrame*>(setBasicBitrate(frameToSend))));
}
void Ieee80211Mac::sendRTSFrame (Ieee80211DataOrMgmtFrame * frameToSend) [protected, virtual]
Referenced by handleWithFSM().
{
    EV << "sending RTS frame\n";
    sendDown(setBasicBitrate(buildRTSFrame(frameToSend)));
}
void Ieee80211Mac::sendUp (cMessage * msg) [protected, virtual]
Sends a message to the upper layer.
Reimplemented from WirelessMacBase.
Referenced by handleWithFSM().
{
    EV << "sending up " << msg << "\n";
    if (!isDuplicated(msg)) // duplicate detection filter
    {
        if (msg->isPacket())
            emit(packetSentToUpperSignal, msg);
        send(msg, upperLayerOut);
    }
}
Ieee80211Frame * Ieee80211Mac::setBasicBitrate (Ieee80211Frame * frame) [protected, virtual]
Attaches a PhyControlInfo to the frame which will cause it to be sent at basicBitrate not bitrate (e.g.
2Mbps instead of 11Mbps). Used with ACK, CTS, RTS.
Referenced by sendACKFrame(), sendCTSFrame(), sendMulticastFrame(), and sendRTSFrame().
{
    ASSERT(frame->getControlInfo()==NULL);
    PhyControlInfo *ctrl = new PhyControlInfo();
    ctrl->setBitrate(basicBitrate);
    frame->setControlInfo(ctrl);
    return frame;
}
void Ieee80211Mac::setBitrate (double b_rate) [protected, virtual]
Referenced by reportDataFailed(), and reportDataOk().
{
    bitrate = rate;
}
Ieee80211Frame * Ieee80211Mac::setBitrateFrame (Ieee80211Frame * frame) [protected, virtual]
Referenced by sendDataFrame().
{
    if (rateControlMode == RATE_CR && forceBitRate == false)
    {
        if (frame->getControlInfo())
            delete  frame->removeControlInfo();
        return frame;
    }
    PhyControlInfo *ctrl = NULL;
    if (frame->getControlInfo()==NULL)
    {
        ctrl = new PhyControlInfo();
        frame->setControlInfo(ctrl);
    }
    else
        ctrl = dynamic_cast<PhyControlInfo*>(frame->getControlInfo());
    if (ctrl)
        ctrl->setBitrate(getBitrate());
    return frame;
}
virtual void Ieee80211Mac::setEndAIFS (int i, cMessage * msg) [inline, protected, virtual]
Referenced by initialize().
{edcCAF[i].endAIFS = msg;}
virtual void Ieee80211Mac::setEndBackoff (int i, cMessage * msg) [inline, protected, virtual]
Referenced by initialize().
{edcCAF[i].endBackoff = msg;}
void Ieee80211Mac::setMode (Mode mode) [protected, virtual]
Change the current MAC operation mode.
{
    if (mode == PCF)
        error("PCF mode not yet supported");
    this->mode = mode;
}
void Ieee80211Mac::setSuccessThreshold (int success_threshold) [protected, virtual]
Referenced by reportFailure(), and reportRecoveryFailure().
{
    if (success_threshold >= minSuccessThreshold)
        successThreshold = success_threshold;
    else
        error("success_threshold is less than minSuccessThreshold");
}
void Ieee80211Mac::setTimerTimeout (int timer_timeout) [protected, virtual]
Referenced by reportFailure(), and reportRecoveryFailure().
{
    if (timer_timeout >= minTimerTimeout)
        timerTimeout = timer_timeout;
    else
        error("timer_timeout is less than minTimerTimeout");
}
cOutVector * Ieee80211Mac::throughput (int i = -1) [protected, virtual]
Referenced by handleWithFSM().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAFOutVector[i].throughput;
}
Ieee80211Mac::Ieee80211DataOrMgmtFrameList * Ieee80211Mac::transmissionQueue (int i = -1) [protected, virtual]
Referenced by buildDataFrame(), getCurrentTransmission(), giveUpCurrentTransmission(), handleSelfMsg(), handleWithFSM(), initWatches(), logState(), mappingAccessCategory(), popTransmissionQueue(), resetStateVariables(), scheduleAIFSPeriod(), sendDataFrame(), transmissionQueueEmpty(), transmissionQueueSize(), and ~Ieee80211Mac().
{
    if (i==-1)
        i = currentAC;
    if (i>=(int)edcCAF.size())
        opp_error("AC doesn't exist");
    return &(edcCAF[i].transmissionQueue);
}
bool Ieee80211Mac::transmissionQueueEmpty () [protected, virtual]
Referenced by handleWithFSM().
{
    for (int i=0; i<numCategories(); i++)
       if (!transmissionQueue(i)->empty()) return false;
    return true;
}
unsigned int Ieee80211Mac::transmissionQueueSize () [protected, virtual]
Referenced by handleUpperMsg(), mappingAccessCategory(), and popTransmissionQueue().
{
    unsigned int totalSize=0;
        for (int i=0; i<numCategories(); i++)
            totalSize+=transmissionQueue(i)->size();
    return totalSize;
}
simtime_t & Ieee80211Mac::TXOP (int i = -1) [protected, virtual]
Referenced by handleWithFSM(), initialize(), and sendDataFrame().
{
    if (i==-1)
         i = currentAC;
    if (i>=(int)edcCAF.size())
         opp_error("AC doesn't exist");
     return edcCAF[i].TXOP;
}
Member Data Documentation
double Ieee80211Mac::_snr [protected]
Referenced by handleLowerMsg(), and initialize().
MACAddress Ieee80211Mac::address [protected]
MAC address.
Referenced by buildRTSFrame(), handleLowerMsg(), handleUpperMsg(), initialize(), isForUs(), isSentByUs(), and registerInterface().
Ieee80211ASFTupleList Ieee80211Mac::asfTuplesList [protected]
Referenced by isDuplicated(), and removeOldTuplesFromDuplicateMap().
int Ieee80211Mac::autoBitrate [protected]
Referenced by configureAutoBitRate().
double Ieee80211Mac::basicBitrate [protected]
The basic bitrate (1 or 2 Mbps) is used to transmit control frames and multicast/broadcast frames.
Referenced by buildACKFrame(), buildCTSFrame(), buildDataFrame(), buildRTSFrame(), handleLowerMsg(), initialize(), scheduleCTSTimeoutPeriod(), scheduleDataTimeoutPeriod(), sendDataFrame(), and setBasicBitrate().
double Ieee80211Mac::bitrate [protected]
The bitrate is used to send unicast data and mgmt frames; be sure to use a valid 802.11 bitrate.
Referenced by buildDataFrame(), computeFrameDuration(), getBitrate(), getSIFS(), getSlotTime(), initialize(), scheduleDataTimeoutPeriod(), and setBitrate().
IQoSClassifier* Ieee80211Mac::classifier [protected]
Arbitration interframe space number.
The duration AIFS[AC] is a duration derived from the value AIFSN[AC] by the relation AIFS[AC] = AIFSN[AC] aSlotTime + aSIFSTime. See spec 7.3.2.29 Remaining backoff period in seconds True if backoff is enabled TXOP parametr Number of frame retransmission attempts, this is a simpification of SLRC and SSRC, see 9.2.4 in the spec
Referenced by Ieee80211Mac(), initialize(), and mappingAccessCategory().
int Ieee80211Mac::contI [protected]
Referenced by handleLowerMsg(), and initialize().
int Ieee80211Mac::contJ [protected]
Referenced by handleLowerMsg(), and initialize().
int Ieee80211Mac::currentAC [protected]
Indicates which queue is acite.
Depends on access category.
Referenced by AIFSN(), backoff(), backoffPeriod(), bites(), cwMax(), cwMin(), endAIFS(), endBackoff(), handleSelfMsg(), handleWithFSM(), initialize(), initWatches(), jitter(), logState(), macDelay(), mappingAccessCategory(), maxjitter(), minjitter(), numDropped(), numGivenUp(), numRetry(), numSent(), numSentWithoutRetry(), retryCounter(), scheduleAIFSPeriod(), sendDataFrame(), throughput(), transmissionQueue(), and TXOP().
int Ieee80211Mac::cwMaxData [protected]
Maximum contention window.
Referenced by initialize().
int Ieee80211Mac::cwMinData [protected]
Minimum contention window.
Referenced by initialize().
int Ieee80211Mac::cwMinMulticast [protected]
Contention window size for multicast messages.
Referenced by computeBackoffPeriod(), and initialize().
int Ieee80211Mac::defaultAC [protected]
Default access catagory.
Referenced by initialize().
bool Ieee80211Mac::duplicateDetect [protected]
A list of last sender, sequence and fragment number tuples to identify duplicates, see spec 9.2.9.
Referenced by initialize(), isDuplicated(), and removeOldTuplesFromDuplicateMap().
double Ieee80211Mac::duplicateTimeOut [protected]
Referenced by initialize(), and removeOldTuplesFromDuplicateMap().
std::vector<Edca> Ieee80211Mac::edcCAF [protected]
Referenced by AIFSN(), backoff(), backoffPeriod(), bites(), cwMax(), cwMin(), endAIFS(), endBackoff(), initialize(), initWatches(), isBakoffMsg(), jitter(), macDelay(), maxjitter(), minjitter(), numDropped(), numGivenUp(), numRetry(), numSent(), numSentWithoutRetry(), retryCounter(), throughput(), transmissionQueue(), TXOP(), and ~Ieee80211Mac().
std::vector<EdcaOutVector> Ieee80211Mac::edcCAFOutVector [protected]
Referenced by initialize(), jitter(), macDelay(), throughput(), and ~Ieee80211Mac().
cMessage* Ieee80211Mac::endDIFS [protected]
End of the Data Inter-Frame Time period.
Referenced by cancelAIFSPeriod(), cancelDIFSPeriod(), handleWithFSM(), Ieee80211Mac(), initialize(), scheduleAIFSPeriod(), scheduleDIFSPeriod(), and ~Ieee80211Mac().
cMessage* Ieee80211Mac::endReserve [protected]
End of medium reserve period (NAV) when two other nodes were communicating on the channel.
Referenced by handleSelfMsg(), Ieee80211Mac(), initialize(), isMediumFree(), isMediumStateChange(), scheduleReservePeriod(), and ~Ieee80211Mac().
cMessage* Ieee80211Mac::endSIFS [protected]
End of the Short Inter-Frame Time period.
Referenced by getFrameReceivedBeforeSIFS(), handleWithFSM(), Ieee80211Mac(), initialize(), scheduleSIFSPeriod(), sendACKFrameOnEndSIFS(), sendCTSFrameOnEndSIFS(), sendDataFrameOnEndSIFS(), and ~Ieee80211Mac().
cMessage* Ieee80211Mac::endTimeout [protected]
End of the backoff period.
Timeout after the transmission of an RTS, a CTS, or a DATA frame
Referenced by cancelTimeoutPeriod(), handleWithFSM(), Ieee80211Mac(), initialize(), scheduleCTSTimeoutPeriod(), scheduleDataTimeoutPeriod(), scheduleMulticastTimeoutPeriod(), and ~Ieee80211Mac().
cMessage* Ieee80211Mac::endTXOP [protected]
End of the Arbitration Inter-Frame Time period.
End of the TXOP time limit period
Referenced by handleSelfMsg(), handleWithFSM(), initialize(), sendDataFrame(), and ~Ieee80211Mac().
int Ieee80211Mac::failedCounter [protected]
Referenced by initialize(), reportDataFailed(), and reportDataOk().
bool Ieee80211Mac::fixFSM [protected]
Referenced by handleWithFSM(), and initialize().
bool Ieee80211Mac::forceBitRate [protected]
Referenced by configureAutoBitRate(), and setBitrateFrame().
Ieee80211DataOrMgmtFrame* Ieee80211Mac::fr [protected]
Referenced by handleWithFSM().
const int Ieee80211Mac::fragmentationThreshold = 2346 [static, protected]
Messages longer than this threshold will be sent in multiple fragments.
see spec 361
Referenced by handleUpperMsg().
cFSM Ieee80211Mac::fsm [protected]
Referenced by handleCommand(), handleWithFSM(), initialize(), initWatches(), and logState().
unsigned int Ieee80211Mac::intrateIndex [protected]
simtime_t Ieee80211Mac::last [protected]
Referenced by handleWithFSM(), and initialize().
bool Ieee80211Mac::lastReceiveFailed [protected]
Indicates that the last frame received had bit errors in it or there was a collision during receiving the frame.
If this flag is set, then the MAC will wait EIFS - DIFS + AIFS instead of AIFS period of time in WAITAIFS state.
Referenced by handleWithFSM(), initialize(), scheduleAIFSPeriod(), and scheduleDIFSPeriod().
simtime_t Ieee80211Mac::lastTimeDelete [protected]
Referenced by initialize(), and removeOldTuplesFromDuplicateMap().
double Ieee80211Mac::lossRate [protected]
Referenced by handleLowerMsg().
int Ieee80211Mac::maxQueueSize [protected]
Maximum number of frames in the queue; should be set in the omnetpp.ini.
Referenced by handleUpperMsg(), initialize(), mappingAccessCategory(), and popTransmissionQueue().
int Ieee80211Mac::maxSuccessThreshold [protected]
Referenced by configureAutoBitRate(), and reportRecoveryFailure().
cMessage* Ieee80211Mac::mediumStateChange [protected]
Radio state change self message.
Currently this is optimized away and sent directly
Referenced by Ieee80211Mac(), initialize(), isMediumStateChange(), receiveChangeNotification(), scheduleReservePeriod(), and ~Ieee80211Mac().
int Ieee80211Mac::minSuccessThreshold [protected]
Referenced by configureAutoBitRate(), getMinSuccessThreshold(), and setSuccessThreshold().
int Ieee80211Mac::minTimerTimeout [protected]
Referenced by configureAutoBitRate(), getMinTimerTimeout(), and setTimerTimeout().
Mode Ieee80211Mac::mode [protected]
Referenced by getControlAnswerMode(), initialize(), logState(), and setMode().
bool Ieee80211Mac::nav [protected]
True during network allocation period.
This flag is present to be able to watch this state.
Referenced by handleSelfMsg(), initialize(), initWatches(), logState(), and scheduleReservePeriod().
long Ieee80211Mac::numAckSend [protected]
Referenced by initialize(), and sendACKFrame().
long Ieee80211Mac::numBites [protected]
Referenced by finish(), handleWithFSM(), initialize(), and initWatches().
long Ieee80211Mac::numCollision [protected]
Referenced by finish(), handleWithFSM(), initialize(), and initWatches().
long Ieee80211Mac::numInternalCollision [protected]
Referenced by finish(), handleSelfMsg(), and initialize().
long Ieee80211Mac::numReceived [protected]
Referenced by finish(), handleWithFSM(), initialize(), and initWatches().
long Ieee80211Mac::numReceivedMulticast [protected]
Referenced by handleWithFSM(), initialize(), and initWatches().
long Ieee80211Mac::numReceivedOther [protected]
Referenced by handleWithFSM(), and initialize().
long Ieee80211Mac::numSentMulticast [protected]
Referenced by handleWithFSM(), initialize(), and initWatches().
long Ieee80211Mac::numSentTXOP [protected]
Referenced by finish(), handleWithFSM(), initialize(), and initWatches().
int Ieee80211Mac::oldcurrentAC [protected]
Remember currentAC.
We need this to figure out internal colision.
Referenced by handleWithFSM(), initialize(), initWatches(), and logState().
char Ieee80211Mac::opMode [protected]
Referenced by computeFrameDuration(), getControlAnswerMode(), getEIFS(), getHeaderTime(), getMaxBitrate(), getSIFS(), getSlotTime(), initialize(), reportDataFailed(), reportDataOk(), and scheduleDataTimeoutPeriod().
cMessage* Ieee80211Mac::pendingRadioConfigMsg [protected]
The last change channel message received and not yet sent to the physical layer, or NULL.
The message will be sent down when the state goes to IDLE or DEFER next time.
Referenced by handleCommand(), Ieee80211Mac(), sendDownPendingRadioConfigMsg(), and ~Ieee80211Mac().
double Ieee80211Mac::PHY_HEADER_LENGTH [protected]
Referenced by computeFrameDuration(), getEIFS(), and initialize().
bool Ieee80211Mac::prioritizeMulticast [private]
Referenced by initialize(), and mappingAccessCategory().
bool Ieee80211Mac::purgeOldTuples [protected]
Referenced by initialize().
IPassiveQueue* Ieee80211Mac::queueModule [protected]
Passive queue module to request messages from.
Referenced by handleUpperMsg(), initializeQueueModule(), and popTransmissionQueue().
int Ieee80211Mac::radioModule [protected]
Referenced by initialize().
RadioState::State Ieee80211Mac::radioState [protected]
XXX Remember for which AC we wait for ACK.
Physical radio (medium) state copied from physical layer
Referenced by initialize(), initWatches(), isMediumFree(), isMediumStateChange(), logState(), receiveChangeNotification(), and scheduleReservePeriod().
cOutVector Ieee80211Mac::radioStateVector [protected]
Referenced by initialize(), and receiveChangeNotification().
enum { ... } Ieee80211Mac::rateControlMode [private]
Referenced by configureAutoBitRate(), handleLowerMsg(), reportDataFailed(), reportDataOk(), reportFailure(), reportRecoveryFailure(), resetStateVariables(), retryCurrentTransmission(), and setBitrateFrame().
int Ieee80211Mac::rateIndex [protected]
Referenced by initialize(), reportDataFailed(), and reportDataOk().
uint64_t Ieee80211Mac::recBytesOverPeriod [protected]
Referenced by handleLowerMsg(), handleSelfMsg(), and initialize().
ModulationType Ieee80211Mac::recFrameModulationType [private]
Referenced by handleLowerMsg().
bool Ieee80211Mac::recovery [protected]
Referenced by initialize(), reportDataFailed(), and reportDataOk().
double Ieee80211Mac::recvdThroughput [protected]
Referenced by handleLowerMsg(), and initialize().
int Ieee80211Mac::rtsThreshold [protected]
The minimum length of MPDU to use RTS/CTS mechanism.
0 means always, extremely large value means never. See spec 9.2.6 and 361.
Referenced by handleLowerMsg(), handleWithFSM(), and initialize().
int Ieee80211Mac::samplingCoeff [protected]
Referenced by handleLowerMsg(), and initialize().
int Ieee80211Mac::sequenceNumber [protected]
Sequence number to be assigned to the next frame.
Referenced by handleUpperMsg(), and initialize().
double Ieee80211Mac::snr [protected]
Referenced by handleLowerMsg().
simtime_t Ieee80211Mac::ST [protected]
Slot time 9us(fast slot time 802.11g only) 20us(802.11b / 802.11g backward compatible)
Referenced by getSlotTime(), and initialize().
cOutVector Ieee80211Mac::stateVector [protected]
Referenced by handleWithFSM(), and initialize().
double Ieee80211Mac::successCoeff [protected]
Referenced by configureAutoBitRate(), and reportRecoveryFailure().
int Ieee80211Mac::successCounter [protected]
Referenced by initialize(), reportDataFailed(), and reportDataOk().
int Ieee80211Mac::successThreshold [protected]
Referenced by configureAutoBitRate(), getSuccessThreshold(), and setSuccessThreshold().
double Ieee80211Mac::throughputLastPeriod [protected]
Referenced by handleSelfMsg(), initialize(), and initWatches().
simtime_t Ieee80211Mac::throughputTimePeriod [protected]
Referenced by handleSelfMsg(), and initialize().
cMessage* Ieee80211Mac::throughputTimer [protected]
Referenced by handleLowerMsg(), handleSelfMsg(), initialize(), and initWatches().
int Ieee80211Mac::timer [protected]
double Ieee80211Mac::timerCoeff [protected]
Referenced by configureAutoBitRate(), and reportRecoveryFailure().
int Ieee80211Mac::timerTimeout [protected]
Referenced by configureAutoBitRate(), getTimerTimeout(), and setTimerTimeout().
simtime_t Ieee80211Mac::timeStampLastMessageReceived [protected]
Referenced by handleLowerMsg(), and initialize().
int Ieee80211Mac::transmissionLimit [protected]
Maximum number of transmissions for a message.
This includes the initial transmission and all subsequent retransmissions. Thus a value 0 is invalid and a value 1 means no retransmissions. See: dot11ShortRetryLimit on page 484. 'This attribute shall indicate the maximum number of transmission attempts of a frame, the length of which is less than or equal to dot11RTSThreshold, that shall be made before a failure condition is indicated. The default value of this attribute shall be 7'
Referenced by computeBackoffPeriod(), handleSelfMsg(), handleWithFSM(), initialize(), and retryCurrentTransmission().
bool Ieee80211Mac::txop [protected]
True if we are in txop bursting packets.
Referenced by buildDataFrame(), handleSelfMsg(), handleWithFSM(), initialize(), initWatches(), logState(), and sendDataFrame().
bool Ieee80211Mac::useModulationParameters [private]
Referenced by getSIFS(), getSlotTime(), initialize(), and scheduleDataTimeoutPeriod().
bool Ieee80211Mac::validRecMode [private]
Referenced by handleLowerMsg(), and initialize().
WifiPreamble Ieee80211Mac::wifiPreambleType [private]
Referenced by computeFrameDuration(), getHeaderTime(), getSIFS(), getSlotTime(), initialize(), and scheduleDataTimeoutPeriod().
The documentation for this class was generated from the following files:
Ieee80211Mac.h
Ieee80211Mac.cc