INET Framework for OMNeT++/OMNEST: RTCP Class Reference
RTCP Class Reference
The class RTCP is responsible for creating, receiving and processing of rtcp packets.
#include <RTCP.h>
Public Member Functions
RTCP ()
virtual ~RTCP ()
Protected Member Functions
virtual void initialize ()
Initializes variables.
virtual void handleMessage (cMessage *msg)
Message handling.
virtual void handleMessageFromRTP (cMessage *msg)
Handles messages from the RTP module.
virtual void handleMessageFromUDP (cMessage *msg)
Handles messages coming from the socket layer.
virtual void handleSelfMessage (cMessage *msg)
Handles self messages.
virtual void handleInitializeRTCP (RTPInnerPacket *rinp)
Initializes the rtcp module when the session is started.
virtual void handleSenderModuleInitialized (RTPInnerPacket *rinp)
Stores information about the new transmission.
virtual void handleDataOut (RTPInnerPacket *packet)
Stores information about an outgoing RTP data packet.
virtual void handleDataIn (RTPInnerPacket *rinp)
Stores information about an outgoing RTP data packet.
virtual void handleLeaveSession (RTPInnerPacket *rinp)
Makes the rtcp module send an RTCPByePacket in the next RTCPCompoundPacket to tell other participants in the RTP session that this end system leaves.
virtual void connectRet ()
Called when the socket layer has finished a connect.
virtual void readRet (cPacket *sifpIn)
Called when this rtcp module receives data from the socket layer.
virtual void createSocket ()
Request a server socket from the socket layer.
virtual void chooseSSRC ()
Chooses the ssrc identifier for this end system.
virtual void scheduleInterval ()
Calculates the length of the next rtcp interval an issues a self message to remind itself.
virtual void createPacket ()
Creates and sends an RTCPCompoundPacket.
virtual void processOutgoingRTPPacket (RTPPacket *packet)
Extracts information of a sent RTPPacket.
virtual void processIncomingRTPPacket (RTPPacket *packet, IPv4Address address, int port)
Extracts information of a received RTPPacket.
virtual void processIncomingRTCPPacket (RTCPCompoundPacket *packet, IPv4Address address, int port)
Extracts information of a received RTCPCompoundPacket.
void processIncomingRTCPSenderReportPacket (RTCPSenderReportPacket *rtcpSenderReportPacket, IPv4Address address, int port)
void processIncomingRTCPReceiverReportPacket (RTCPReceiverReportPacket *rtcpReceiverReportPacket, IPv4Address address, int port)
void processIncomingRTCPSDESPacket (RTCPSDESPacket *rtcpSDESPacket, IPv4Address address, int port, simtime_t arrivalTime)
void processIncomingRTCPByePacket (RTCPByePacket *rtcpByePacket, IPv4Address address, int port)
virtual RTPParticipantInfo * findParticipantInfo (uint32 ssrc)
Returns the RTPParticipantInfo object used for storing information about the RTP end system with this ssrc identifier.
virtual void calculateAveragePacketSize (int size)
Recalculates the average size of an RTCPCompoundPacket when one of this size has been sent or received.
Protected Attributes
int _mtu
The maximum size an RTCPCompundPacket can have.
int _bandwidth
The bandwidth for this RTP session.
int _rtcpPercentage
The percentage of bandwidth for rtcp.
IPv4Address _destinationAddress
The destination address.
int _port
The rtcp port.
bool _ssrcChosen
True when this end system has chosen its ssrc identifier.
bool _leaveSession
True when this end system is about to leave the session.
RTPSenderInfo * _senderInfo
The RTPSenderInfo about this end system.
cArray _participantInfos
Information about all known RTP end system participating in this RTP session.
UDPSocket _udpSocket
The UDP socket for sending/receiving rtcp packets.
int _packetsCalculated
The number of packets this rtcp module has calculated.
double _averagePacketSize
The average size of an RTCPCompoundPacket.
Static Protected Attributes
static simsignal_t rcvdPkSignal = SIMSIGNAL_NULL
The output vector for statistical data about the behaviour of rtcp.
Detailed Description
The class RTCP is responsible for creating, receiving and processing of rtcp packets.
It also keeps track of this and other RTP end systems.
Constructor & Destructor Documentation
RTCP::RTCP ()
{
    _senderInfo = NULL;
}
RTCP::~RTCP () [virtual]
{
    if (!_ssrcChosen)
        delete _senderInfo;
}
Member Function Documentation
void RTCP::calculateAveragePacketSize (int size) [protected, virtual]
Recalculates the average size of an RTCPCompoundPacket when one of this size has been sent or received.
Referenced by createPacket(), and processIncomingRTCPPacket().
{
    // add size of ip and udp header to given size before calculating
#if 1
    double sumPacketSize = (double)(_packetsCalculated) * _averagePacketSize  + (double)(size + 20 + 8);
    _averagePacketSize = sumPacketSize / (double)(++_packetsCalculated);
#else
    _averagePacketSize += ((double)(size + 20 + 8) - _averagePacketSize) / (double)(++_packetsCalculated);
#endif
}
void RTCP::chooseSSRC () [protected, virtual]
Chooses the ssrc identifier for this end system.
Referenced by handleSelfMessage().
{
    uint32 ssrc = 0;
    bool ssrcConflict = false;
    do
    {
        ssrc = intrand(0x7fffffff);
        ssrcConflict = findParticipantInfo(ssrc) != NULL;
    } while (ssrcConflict);
    ev << "chooseSSRC" << ssrc;
    _senderInfo->setSsrc(ssrc);
    _participantInfos.add(_senderInfo);
    _ssrcChosen = true;
}
void RTCP::connectRet () [protected, virtual]
Called when the socket layer has finished a connect.
Referenced by createSocket().
{
    // schedule first rtcp packet
    double intervalLength = 2.5 * (dblrand() + 0.5);
    cMessage *reminderMessage = new cMessage("Interval");
    scheduleAt(simTime() + intervalLength, reminderMessage);
}
void RTCP::createPacket () [protected, virtual]
Creates and sends an RTCPCompoundPacket.
Referenced by handleSelfMessage().
{
    // first packet in an rtcp compound packet must
    // be a sender or receiver report
    RTCPReceiverReportPacket *reportPacket;
    // if this rtcp end system is a sender (see SenderInformation::isSender() for
    // details) insert a sender report
    if (_senderInfo->isSender())
    {
        RTCPSenderReportPacket *senderReportPacket = new RTCPSenderReportPacket("SenderReportPacket");
        SenderReport *senderReport = _senderInfo->senderReport(simTime());
        senderReportPacket->setSenderReport(*senderReport);
        delete senderReport;
        reportPacket = senderReportPacket;
    }
    else
        reportPacket = new RTCPReceiverReportPacket("ReceiverReportPacket");
    reportPacket->setSsrc(_senderInfo->getSsrc());
    // insert receiver reports for packets from other sources
    for (int i = 0; i < _participantInfos.size(); i++)
    {
        if (_participantInfos.exist(i))
        {
            RTPParticipantInfo *participantInfo = (RTPParticipantInfo *)(_participantInfos.get(i));
            if (participantInfo->getSsrc() != _senderInfo->getSsrc())
            {
                ReceptionReport *report = ((RTPReceiverInfo *)participantInfo)->receptionReport(simTime());
                if (report != NULL)
                {
                    reportPacket->addReceptionReport(report);
                }
            }
            participantInfo->nextInterval(simTime());
            if (participantInfo->toBeDeleted(simTime()))
            {
                _participantInfos.remove(participantInfo);
                delete participantInfo;
                // perhaps inform the profile
            }
        }
    }
    // insert source description items (at least common name)
    RTCPSDESPacket *sdesPacket = new RTCPSDESPacket("SDESPacket");
    SDESChunk *chunk = _senderInfo->getSDESChunk();
    sdesPacket->addSDESChunk(chunk);
    RTCPCompoundPacket *compoundPacket = new RTCPCompoundPacket("RTCPCompoundPacket");
    compoundPacket->addRTCPPacket(reportPacket);
    compoundPacket->addRTCPPacket(sdesPacket);
    // create rtcp app/bye packets if needed
    if (_leaveSession)
    {
        RTCPByePacket *byePacket = new RTCPByePacket("ByePacket");
        byePacket->setSsrc(_senderInfo->getSsrc());
        compoundPacket->addRTCPPacket(byePacket);
    }
    calculateAveragePacketSize(compoundPacket->getByteLength());
    cPacket *msg = new cPacket("RTCPCompoundPacket");
    msg->encapsulate(compoundPacket);
    _udpSocket.sendTo(msg, _destinationAddress, _port);
    if (_leaveSession)
    {
        RTPInnerPacket *rinp = new RTPInnerPacket("sessionLeft()");
        rinp->setSessionLeftPkt();
        send(rinp, "rtpOut");
    }
}
void RTCP::createSocket () [protected, virtual]
Request a server socket from the socket layer.
Referenced by handleInitializeRTCP().
{
    _udpSocket.bind(_port);  //XXX this will fail if this function is invoked multiple times; not sure that may (or is expected to) happen
    _udpSocket.joinLocalMulticastGroups(); //TODO make it parameter-dependent
    connectRet();
}
RTPParticipantInfo * RTCP::findParticipantInfo (uint32 ssrc) [protected, virtual]
Returns the RTPParticipantInfo object used for storing information about the RTP end system with this ssrc identifier.
Returns NULL if this end system is unknown.
Referenced by chooseSSRC(), processIncomingRTCPByePacket(), processIncomingRTCPReceiverReportPacket(), processIncomingRTCPSDESPacket(), processIncomingRTCPSenderReportPacket(), and processIncomingRTPPacket().
{
    char *ssrcString = RTPParticipantInfo::ssrcToName(ssrc);
    return (RTPParticipantInfo *)(_participantInfos.get(ssrcString));
}
void RTCP::handleDataIn (RTPInnerPacket * rinp) [protected, virtual]
Stores information about an outgoing RTP data packet.
Referenced by handleMessageFromRTP().
{
    RTPPacket *rtpPacket = check_and_cast<RTPPacket *>(rinp->decapsulate());
    //rtpPacket->dump();
    processIncomingRTPPacket(rtpPacket, rinp->getAddress(), rinp->getPort());
}
void RTCP::handleDataOut (RTPInnerPacket * packet) [protected, virtual]
Stores information about an outgoing RTP data packet.
Referenced by handleMessageFromRTP().
{
    RTPPacket *rtpPacket = check_and_cast<RTPPacket *>(packet->decapsulate());
    processOutgoingRTPPacket(rtpPacket);
}
void RTCP::handleInitializeRTCP (RTPInnerPacket * rinp) [protected, virtual]
Initializes the rtcp module when the session is started.
Referenced by handleMessageFromRTP().
{
    _mtu = rinp->getMTU();
    _bandwidth = rinp->getBandwidth();
    _rtcpPercentage = rinp->getRtcpPercentage();
    _destinationAddress = rinp->getAddress();
    _port = rinp->getPort();
    _senderInfo = new RTPSenderInfo();
    SDESItem *sdesItem = new SDESItem(SDESItem::SDES_CNAME, rinp->getCommonName());
    _senderInfo->addSDESItem(sdesItem);
    // create server socket for receiving rtcp packets
    createSocket();
}
void RTCP::handleLeaveSession (RTPInnerPacket * rinp) [protected, virtual]
Makes the rtcp module send an RTCPByePacket in the next RTCPCompoundPacket to tell other participants in the RTP session that this end system leaves.
Referenced by handleMessageFromRTP().
{
    _leaveSession = true;
}
void RTCP::handleMessage (cMessage * msg) [protected, virtual]
Message handling.
Dispatches messages by arrival gate.
{
    // first distinguish incoming messages by arrival gate
    if (msg->isSelfMessage())
    {
        handleSelfMessage(msg);
    }
    else if (msg->getArrivalGateId() == findGate("rtpIn"))
    {
        handleMessageFromRTP(msg);
    }
    else if (msg->getArrivalGateId() == findGate("udpIn"))
    {
        handleMessageFromUDP(msg);
    }
    else
    {
        error("Message from unknown gate");
    }
    delete msg;
}
void RTCP::handleMessageFromRTP (cMessage * msg) [protected, virtual]
Handles messages from the RTP module.
Referenced by handleMessage().
{
    // from the rtp module all messages are of type RTPInnerPacket
    RTPInnerPacket *rinp = check_and_cast<RTPInnerPacket *>(msg);
    // distinguish by type
    switch (rinp->getType())
    {
    case RTP_INP_INITIALIZE_RTCP:
        handleInitializeRTCP(rinp);
        break;
    case RTP_INP_SENDER_MODULE_INITIALIZED:
        handleSenderModuleInitialized(rinp);
        break;
    case RTP_INP_DATA_OUT:
        handleDataOut(rinp);
        break;
    case RTP_INP_DATA_IN:
        handleDataIn(rinp);
        break;
    case RTP_INP_LEAVE_SESSION:
        handleLeaveSession(rinp);
        break;
    default:
        throw cRuntimeError("Unknown RTPInnerPacket type");
    }
}
void RTCP::handleMessageFromUDP (cMessage * msg) [protected, virtual]
Handles messages coming from the socket layer.
Referenced by handleMessage().
{
    // from SocketLayer all message are of type cMessage
    readRet(PK(msg));
}
void RTCP::handleSelfMessage (cMessage * msg) [protected, virtual]
Handles self messages.
Referenced by handleMessage().
{
    // it's time to create an rtcp packet
    if (!_ssrcChosen)
    {
        chooseSSRC();
        RTPInnerPacket *rinp1 = new RTPInnerPacket("rtcpInitialized()");
        rinp1->setRtcpInitializedPkt(_senderInfo->getSsrc());
        send(rinp1, "rtpOut");
    }
    createPacket();
    if (!_leaveSession)
    {
        scheduleInterval();
    }
}
void RTCP::handleSenderModuleInitialized (RTPInnerPacket * rinp) [protected, virtual]
Stores information about the new transmission.
Referenced by handleMessageFromRTP().
{
    _senderInfo->setStartTime(simTime());
    _senderInfo->setClockRate(rinp->getClockRate());
    _senderInfo->setTimeStampBase(rinp->getTimeStampBase());
    _senderInfo->setSequenceNumberBase(rinp->getSequenceNumberBase());
}
void RTCP::initialize () [protected, virtual]
Initializes variables.
{
    // initialize variables
    _ssrcChosen = false;
    _leaveSession = false;
    _udpSocket.setOutputGate(gate("udpOut"));
    _packetsCalculated = 0;
    _averagePacketSize = 0.0;
    _participantInfos.setName("ParticipantInfos");
    rcvdPkSignal = registerSignal("rcvdPk");
}
void RTCP::processIncomingRTCPByePacket (RTCPByePacket * rtcpByePacket, IPv4Address address, int port) [protected]
Referenced by processIncomingRTCPPacket().
{
    uint32 ssrc = rtcpByePacket->getSsrc();
    RTPParticipantInfo *participantInfo = findParticipantInfo(ssrc);
    if (participantInfo != NULL && participantInfo != _senderInfo)
    {
        _participantInfos.remove(participantInfo);
        delete participantInfo;
        // perhaps it would be useful to inform
        // the profile to remove the corresponding
        // receiver module
    }
}
void RTCP::processIncomingRTCPPacket (RTCPCompoundPacket * packet, IPv4Address address, int port) [protected, virtual]
Extracts information of a received RTCPCompoundPacket.
Referenced by readRet().
{
    calculateAveragePacketSize(packet->getByteLength());
    cArray &rtcpPackets = packet->getRtcpPackets();
    simtime_t arrivalTime = packet->getArrivalTime();
    for (int i = 0; i < rtcpPackets.size(); i++)
    {
        RTCPPacket *rtcpPacket = (RTCPPacket *)(rtcpPackets.remove(i));
        if (rtcpPacket)
        {
            // remove the rtcp packet from the rtcp compound packet
            switch (rtcpPacket->getPacketType())
            {
            case RTCP_PT_SR:
                processIncomingRTCPSenderReportPacket(
                        (RTCPSenderReportPacket *)rtcpPacket, address, port);
                break;
            case RTCP_PT_RR:
                processIncomingRTCPReceiverReportPacket(
                        (RTCPReceiverReportPacket *)rtcpPacket, address, port);
                break;
            case RTCP_PT_SDES:
                processIncomingRTCPSDESPacket(
                        (RTCPSDESPacket *)rtcpPacket, address, port, arrivalTime);
                break;
            case RTCP_PT_BYE:
                processIncomingRTCPByePacket(
                        (RTCPByePacket *)rtcpPacket, address, port);
                break;
            default:
                // app rtcp packets
                break;
            }
            delete rtcpPacket;
        }
    }
    delete packet;
}
void RTCP::processIncomingRTCPReceiverReportPacket (RTCPReceiverReportPacket * rtcpReceiverReportPacket, IPv4Address address, int port) [protected]
Referenced by processIncomingRTCPPacket().
{
    uint32 ssrc = rtcpReceiverReportPacket->getSsrc();
    RTPParticipantInfo *participantInfo = findParticipantInfo(ssrc);
    if (participantInfo == NULL)
    {
        participantInfo = new RTPReceiverInfo(ssrc);
        participantInfo->setAddress(address);
        participantInfo->setRTCPPort(port);
        _participantInfos.add(participantInfo);
    }
    else
    {
        if ((participantInfo->getAddress() == address) &&
                (participantInfo->getRTCPPort() == PORT_UNDEF))
        {
            participantInfo->setRTCPPort(port);
        }
        else
        {
            // check for ssrc conflict
        }
    }
    cArray &receptionReports = rtcpReceiverReportPacket->getReceptionReports();
    for (int j = 0; j < receptionReports.size(); j++)
    {
        if (receptionReports.exist(j))
        {
            ReceptionReport *receptionReport = (ReceptionReport *)(receptionReports.remove(j));
            if (_senderInfo && (receptionReport->getSsrc() == _senderInfo->getSsrc()))
            {
                _senderInfo->processReceptionReport(receptionReport, simTime());
            }
            else
                //cancelAndDelete(receptionReport);
                delete receptionReport;
        }
    }
}
void RTCP::processIncomingRTCPSDESPacket (RTCPSDESPacket * rtcpSDESPacket, IPv4Address address, int port, simtime_t arrivalTime) [protected]
Referenced by processIncomingRTCPPacket().
{
    cArray &sdesChunks = rtcpSDESPacket->getSdesChunks();
    for (int j = 0; j < sdesChunks.size(); j++)
    {
        if (sdesChunks.exist(j))
        {
            // remove the sdes chunk from the cArray of sdes chunks
            SDESChunk *sdesChunk = (SDESChunk *)(sdesChunks.remove(j));
            // this is needed to avoid seg faults
            //sdesChunk->setOwner(this);
            uint32 ssrc = sdesChunk->getSsrc();
            RTPParticipantInfo *participantInfo = findParticipantInfo(ssrc);
            if (participantInfo == NULL)
            {
                participantInfo = new RTPReceiverInfo(ssrc);
                participantInfo->setAddress(address);
                participantInfo->setRTCPPort(port);
                _participantInfos.add(participantInfo);
            }
            else
            {
                // check for ssrc conflict
            }
            participantInfo->processSDESChunk(sdesChunk, arrivalTime);
        }
    }
}
void RTCP::processIncomingRTCPSenderReportPacket (RTCPSenderReportPacket * rtcpSenderReportPacket, IPv4Address address, int port) [protected]
Referenced by processIncomingRTCPPacket().
{
    uint32 ssrc = rtcpSenderReportPacket->getSsrc();
    RTPParticipantInfo *participantInfo = findParticipantInfo(ssrc);
    if (participantInfo == NULL)
    {
        participantInfo = new RTPReceiverInfo(ssrc);
        participantInfo->setAddress(address);
        participantInfo->setRTCPPort(port);
        _participantInfos.add(participantInfo);
    }
    else
    {
        if ((participantInfo->getAddress() == address) &&
                (participantInfo->getRTCPPort() == PORT_UNDEF))
        {
            participantInfo->setRTCPPort(port);
        }
        else
        {
            // check for ssrc conflict
        }
    }
    participantInfo->processSenderReport(rtcpSenderReportPacket->getSenderReport(), simTime());
    cArray &receptionReports = rtcpSenderReportPacket->getReceptionReports();
    for (int j = 0; j < receptionReports.size(); j++)
    {
        if (receptionReports.exist(j))
        {
            ReceptionReport *receptionReport = (ReceptionReport *)(receptionReports.remove(j));
            if (_senderInfo && (receptionReport->getSsrc() == _senderInfo->getSsrc()))
            {
                _senderInfo->processReceptionReport(receptionReport, simTime());
            }
            else
                //cancelAndDelete(receptionReport);
                delete receptionReport;
        }
    }
}
void RTCP::processIncomingRTPPacket (RTPPacket * packet, IPv4Address address, int port) [protected, virtual]
Extracts information of a received RTPPacket.
Referenced by handleDataIn().
{
    bool good = false;
    uint32 ssrc = packet->getSsrc();
    RTPParticipantInfo *participantInfo = findParticipantInfo(ssrc);
    if (participantInfo == NULL)
    {
        participantInfo = new RTPParticipantInfo(ssrc);
        participantInfo->setAddress(address);
        participantInfo->setRTPPort(port);
        _participantInfos.add(participantInfo);
        good = true;
    }
    else
    {
        // check for ssrc conflict
        if (participantInfo->getAddress() == address)
        {
            if (participantInfo->getRTPPort() == port)
            {
                good = true;
            }
            else if (participantInfo->getRTPPort() == PORT_UNDEF)
            {
                participantInfo->setRTPPort(port);
                good = true;
            }
        }
    }
    if (good)
    {
        participantInfo->processRTPPacket(packet, getId(),  packet->getArrivalTime());
    }
    else
    {
        ev << "Incoming packet address/port conflict, packet dropped.\n";
        delete packet;
    }
}
void RTCP::processOutgoingRTPPacket (RTPPacket * packet) [protected, virtual]
Extracts information of a sent RTPPacket.
Referenced by handleDataOut().
{
    _senderInfo->processRTPPacket(packet, getId(), simTime());
}
void RTCP::readRet (cPacket * sifpIn) [protected, virtual]
Called when this rtcp module receives data from the socket layer.
Referenced by handleMessageFromUDP().
{
    emit(rcvdPkSignal, sifpIn);
    RTCPCompoundPacket *packet = check_and_cast<RTCPCompoundPacket *>(sifpIn->decapsulate());
    processIncomingRTCPPacket(packet, IPv4Address(_destinationAddress), _port);
}
void RTCP::scheduleInterval () [protected, virtual]
Calculates the length of the next rtcp interval an issues a self message to remind itself.
Referenced by handleSelfMessage().
{
    simtime_t intervalLength = _averagePacketSize * (simtime_t)(_participantInfos.size()) /
            (simtime_t)(_bandwidth * _rtcpPercentage * (_senderInfo->isSender() ? 1.0 : 0.75) / 100.0);
    // interval length must be at least 5 seconds
    if (intervalLength < 5.0)
        intervalLength = 5.0;
    // to avoid rtcp packet bursts multiply calculated interval length
    // with a random number between 0.5 and 1.5
    intervalLength = intervalLength * (0.5 + dblrand());
    intervalLength /= (double) (2.71828-1.5); // [RFC 3550] , by Ahmed ayadi
    cMessage *reminderMessage = new cMessage("Interval");
    scheduleAt(simTime() + intervalLength, reminderMessage);
}
Member Data Documentation
double RTCP::_averagePacketSize [protected]
The average size of an RTCPCompoundPacket.
Referenced by calculateAveragePacketSize(), initialize(), and scheduleInterval().
int RTCP::_bandwidth [protected]
The bandwidth for this RTP session.
Referenced by handleInitializeRTCP(), and scheduleInterval().
IPv4Address RTCP::_destinationAddress [protected]
The destination address.
Referenced by createPacket(), handleInitializeRTCP(), and readRet().
bool RTCP::_leaveSession [protected]
True when this end system is about to leave the session.
Referenced by createPacket(), handleLeaveSession(), handleSelfMessage(), and initialize().
int RTCP::_mtu [protected]
The maximum size an RTCPCompundPacket can have.
Referenced by handleInitializeRTCP().
int RTCP::_packetsCalculated [protected]
The number of packets this rtcp module has calculated.
Referenced by calculateAveragePacketSize(), and initialize().
cArray RTCP::_participantInfos [protected]
Information about all known RTP end system participating in this RTP session.
Referenced by chooseSSRC(), createPacket(), findParticipantInfo(), initialize(), processIncomingRTCPByePacket(), processIncomingRTCPReceiverReportPacket(), processIncomingRTCPSDESPacket(), processIncomingRTCPSenderReportPacket(), processIncomingRTPPacket(), and scheduleInterval().
int RTCP::_port [protected]
The rtcp port.
Referenced by createPacket(), createSocket(), handleInitializeRTCP(), and readRet().
int RTCP::_rtcpPercentage [protected]
The percentage of bandwidth for rtcp.
Referenced by handleInitializeRTCP(), and scheduleInterval().
RTPSenderInfo* RTCP::_senderInfo [protected]
The RTPSenderInfo about this end system.
Referenced by chooseSSRC(), createPacket(), handleInitializeRTCP(), handleSelfMessage(), handleSenderModuleInitialized(), processIncomingRTCPByePacket(), processIncomingRTCPReceiverReportPacket(), processIncomingRTCPSenderReportPacket(), processOutgoingRTPPacket(), RTCP(), scheduleInterval(), and ~RTCP().
bool RTCP::_ssrcChosen [protected]
True when this end system has chosen its ssrc identifier.
Referenced by chooseSSRC(), handleSelfMessage(), initialize(), and ~RTCP().
UDPSocket RTCP::_udpSocket [protected]
The UDP socket for sending/receiving rtcp packets.
Referenced by createPacket(), createSocket(), and initialize().
simsignal_t RTCP::rcvdPkSignal = SIMSIGNAL_NULL [static, protected]
The output vector for statistical data about the behaviour of rtcp.
Every participant's rtcp module writes its calculated rtcp interval (without variation
Referenced by initialize(), and readRet().
The documentation for this class was generated from the following files:
RTCP.h
RTCP.cc