INET Framework for OMNeT++/OMNEST: IPv6Datagram Class Reference
IPv6Datagram Class Reference
Represents an IPv6 datagram.
#include <IPv6Datagram.h>
Public Member Functions
IPv6Datagram (const char *name=NULL, int kind=0)
IPv6Datagram (const IPv6Datagram &other)
IPv6Datagram & operator= (const IPv6Datagram &other)
~IPv6Datagram ()
virtual IPv6Datagram * dup () const
virtual int getDiffServCodePoint () const
Returns bits 0-5 of the Traffic Class field, a value in the 0..63 range.
virtual void setDiffServCodePoint (int dscp)
Sets bits 0-5 of the Traffic Class field; expects a value in the 0..63 range.
virtual int getExplicitCongestionNotification () const
Returns bits 6-7 of the Traffic Class field, a value in the range 0..3.
virtual void setExplicitCongestionNotification (int ecn)
Sets bits 6-7 of the Traffic Class field; expects a value in the 0..3 range.
virtual void setExtensionHeaderArraySize (unsigned int size)
Generated but unused method, should not be called.
virtual void setExtensionHeader (unsigned int k, const IPv6ExtensionHeaderPtr &extensionHeader_var)
Generated but unused method, should not be called.
virtual unsigned int getExtensionHeaderArraySize () const
Returns the number of extension headers in this datagram.
virtual IPv6ExtensionHeaderPtr & getExtensionHeader (unsigned int k)
Returns the kth extension header in this datagram.
virtual IPv6ExtensionHeader * findExtensionHeaderByType (IPProtocolId extensionType, int index=0) const
Returns the extension header of the specified type, or NULL.
virtual void addExtensionHeader (IPv6ExtensionHeader *eh, int atPos=-1)
Adds an extension header to the datagram.
virtual int calculateHeaderByteLength () const
Calculates the length of the IPv6 header plus the extension headers.
virtual int calculateUnfragmentableHeaderByteLength () const
Calculates the length of the unfragmentable part of IPv6 header plus the extension headers.
virtual int calculateFragmentLength () const
Calculates the length of the payload and extension headers after the Fragment Header.
virtual IPv6ExtensionHeader * removeFirstExtensionHeader ()
Removes and returns the first extension header of this datagram.
virtual IPv6ExtensionHeader * removeExtensionHeader (IPProtocolId extensionType)
Removes and returns the first extension header with the given type.
Protected Types
typedef std::vector
< IPv6ExtensionHeader * > ExtensionHeaders
Protected Attributes
ExtensionHeaders extensionHeaders
Private Member Functions
void copy (const IPv6Datagram &other)
void clean ()
int getExtensionHeaderOrder (IPv6ExtensionHeader *eh)
Detailed Description
Represents an IPv6 datagram.
More info in the IPv6Datagram.msg file (and the documentation generated from it).
Member Typedef Documentation
typedef std::vector<IPv6ExtensionHeader*> IPv6Datagram::ExtensionHeaders [protected]
Constructor & Destructor Documentation
IPv6Datagram::IPv6Datagram (const char * name = NULL, int kind = 0) [inline]
: IPv6Datagram_Base(name, kind) {}
IPv6Datagram::IPv6Datagram (const IPv6Datagram & other) [inline]
: IPv6Datagram_Base(other) { copy(other); }
IPv6Datagram::~IPv6Datagram ()
{
    clean();
}
Member Function Documentation
void IPv6Datagram::addExtensionHeader (IPv6ExtensionHeader * eh, int atPos = -1) [virtual]
Adds an extension header to the datagram.
The atPos parameter should not be used, the extension headers are stored in the order specified in RFC 2460 4.1.
Referenced by copy(), IPv6::encapsulate(), and IPv6::fragmentAndSend().
{
        if (atPos != -1)
                throw cRuntimeError(this, "addExtensionHeader() does not support atPos parameter.");
        int thisOrder = getExtensionHeaderOrder(eh);
    unsigned int i;
        for (i=0; i<extensionHeaders.size(); i++)
    {
        int thatOrder = getExtensionHeaderOrder(extensionHeaders[i]);
        if (thisOrder != -1 && thatOrder > thisOrder)
            break;
        else if (thisOrder == thatOrder)
        {
            if (thisOrder == 1)
                thisOrder=6;
            else if (thisOrder != -1)
                throw cRuntimeError(this, "addExtensionHeader() duplicate extension header: %d",
                                        eh->getExtensionType());
        }
    }
        // insert at position atPos, shift up the rest of the array
    extensionHeaders.insert(extensionHeaders.begin()+i, eh);
}
int IPv6Datagram::calculateFragmentLength () const [virtual]
Calculates the length of the payload and extension headers after the Fragment Header.
Note: it is assumed that headers are ordered as described in RFC 2460 4.1.
Referenced by IPv6FragBuf::addFragment().
{
        int len = getByteLength() - IPv6_HEADER_BYTES;
        unsigned int i;
        for (i=0; i<extensionHeaders.size(); i++)
        {
                len -= extensionHeaders[i]->getByteLength();
        if (extensionHeaders[i]->getExtensionType() == IP_PROT_IPv6EXT_FRAGMENT)
            break;
        }
        ASSERT2(i<extensionHeaders.size(), "IPv6Datagram::calculateFragmentLength() called on non-fragment datagram");
        return len;
}
int IPv6Datagram::calculateHeaderByteLength () const [virtual]
Calculates the length of the IPv6 header plus the extension headers.
Referenced by IPv6::encapsulate().
{
    int len = 40;
    for (unsigned int i=0; i<extensionHeaders.size(); i++)
        len += extensionHeaders[i]->getByteLength();
    return len;
}
int IPv6Datagram::calculateUnfragmentableHeaderByteLength () const [virtual]
Calculates the length of the unfragmentable part of IPv6 header plus the extension headers.
Note: it is assumed that headers are ordered as described in RFC 2460 4.1.
Referenced by IPv6FragBuf::addFragment(), and IPv6::fragmentAndSend().
{
        int lastUnfragmentableExtensionIndex = -1;
        for (int i=((int)extensionHeaders.size())-1; i>=0; i--)
        {
                int type = extensionHeaders[i]->getExtensionType();
                if (type == IP_PROT_IPv6EXT_ROUTING || type == IP_PROT_IPv6EXT_HOP)
                {
                        lastUnfragmentableExtensionIndex = i;
                        break;
                }
        }
        int len = 40;
        for (int i=0; i<=lastUnfragmentableExtensionIndex; i++)
                len += extensionHeaders[i]->getByteLength();
        return len;
}
void IPv6Datagram::clean () [private]
Referenced by operator=(), and ~IPv6Datagram().
{
    IPv6ExtensionHeaderPtr eh;
    while ( ! extensionHeaders.empty() )
    {
        eh = extensionHeaders.back();
        extensionHeaders.pop_back(); // remove pointer element from container
        delete eh; // delete the header
    }
}
void IPv6Datagram::copy (const IPv6Datagram & other) [private]
Referenced by operator=().
{
    for (ExtensionHeaders::const_iterator i=other.extensionHeaders.begin(); i!=other.extensionHeaders.end(); ++i)
        addExtensionHeader((*i)->dup());
}
virtual IPv6Datagram* IPv6Datagram::dup () const [inline, virtual]
Reimplemented from IPv6Datagram_Base.
Referenced by IPv6ControlInfo::copy(), IPv6::fragmentAndSend(), and IPv6::routeMulticastPacket().
{return new IPv6Datagram(*this);}
IPv6ExtensionHeader * IPv6Datagram::findExtensionHeaderByType (IPProtocolId extensionType, int index = 0) const [virtual]
Returns the extension header of the specified type, or NULL.
If index is 0, then the first, if 1 then the second extension is returned. (The datagram might contain two Destination Options extension.)
Referenced by IPv6::localDeliver().
{
        for (ExtensionHeaders::const_iterator it=extensionHeaders.begin(); it != extensionHeaders.end(); ++it)
                if ((*it)->getExtensionType() == extensionType)
                {
                        if (index == 0)
                                return *it;
                        else
                                index--;
                }
        return NULL;
}
virtual int IPv6Datagram::getDiffServCodePoint () const [inline, virtual]
Returns bits 0-5 of the Traffic Class field, a value in the 0..63 range.
Implements IPv6Datagram_Base.
Referenced by BehaviorAggregateClassifier::getDscpFromPacket().
{ return getTrafficClass() & 0x3f; }
virtual int IPv6Datagram::getExplicitCongestionNotification () const [inline, virtual]
Returns bits 6-7 of the Traffic Class field, a value in the range 0..3.
Implements IPv6Datagram_Base.
{ return (getTrafficClass() >> 6) & 0x03; }
IPv6ExtensionHeaderPtr & IPv6Datagram::getExtensionHeader (unsigned int k) [virtual]
Returns the kth extension header in this datagram.
Implements IPv6Datagram_Base.
{
    static IPv6ExtensionHeaderPtr null;
    if (k>=extensionHeaders.size())
        return (null = NULL);
    return extensionHeaders[k];
}
unsigned int IPv6Datagram::getExtensionHeaderArraySize () const [virtual]
Returns the number of extension headers in this datagram.
Implements IPv6Datagram_Base.
Referenced by IPv6::routePacket().
{
    return extensionHeaders.size();
}
int IPv6Datagram::getExtensionHeaderOrder (IPv6ExtensionHeader * eh) [private]
Referenced by addExtensionHeader().
{
        switch (eh->getExtensionType())
        {
        case IP_PROT_IPv6EXT_HOP: return 0;
        case IP_PROT_IPv6EXT_DEST: return 1;
        case IP_PROT_IPv6EXT_ROUTING: return 2;
        case IP_PROT_IPv6EXT_FRAGMENT: return 3;
        case IP_PROT_IPv6EXT_AUTH: return 4;
        case IP_PROT_IPv6EXT_ESP: return 5;
        // second IP_PROT_IPv6EXT_DEST has order 6
        case IP_PROT_IPv6EXT_MOB: return 7;
        default: return -1;
        }
}
IPv6Datagram & IPv6Datagram::operator= (const IPv6Datagram & other)
{
    if (this==&other) return *this;
    clean();
    IPv6Datagram_Base::operator=(other);
    copy(other);
    return *this;
}
IPv6ExtensionHeader * IPv6Datagram::removeExtensionHeader (IPProtocolId extensionType) [virtual]
Removes and returns the first extension header with the given type.
Referenced by IPv6FragBuf::addFragment().
{
        for (unsigned int i=0; i<extensionHeaders.size(); i++)
        {
                if (extensionHeaders[i]->getExtensionType() == extensionType)
                {
                        IPv6ExtensionHeader* eh = extensionHeaders[i];
                        extensionHeaders.erase(extensionHeaders.begin()+i);
                        return eh;
                }
        }
        return NULL;
}
IPv6ExtensionHeader * IPv6Datagram::removeFirstExtensionHeader () [virtual]
Removes and returns the first extension header of this datagram.
{
    if (extensionHeaders.empty())
        return NULL;
    IPv6ExtensionHeader* eh = extensionHeaders.front();
    extensionHeaders.erase( extensionHeaders.begin() );
    return eh;
}
virtual void IPv6Datagram::setDiffServCodePoint (int dscp) [inline, virtual]
Sets bits 0-5 of the Traffic Class field; expects a value in the 0..63 range.
Implements IPv6Datagram_Base.
Referenced by DSCPMarker::markPacket().
{ setTrafficClass((getTrafficClass() & 0xc0) | (dscp & 0x3f)); }
virtual void IPv6Datagram::setExplicitCongestionNotification (int ecn) [inline, virtual]
Sets bits 6-7 of the Traffic Class field; expects a value in the 0..3 range.
Implements IPv6Datagram_Base.
{ setTrafficClass((getTrafficClass() & 0x3f) | ((ecn & 0x3) << 6)); }
void IPv6Datagram::setExtensionHeader (unsigned int k, const IPv6ExtensionHeaderPtr & extensionHeader_var) [virtual]
Generated but unused method, should not be called.
Implements IPv6Datagram_Base.
{
    throw cRuntimeError(this, "setExtensionHeader() not supported, use addExtensionHeader()");
}
void IPv6Datagram::setExtensionHeaderArraySize (unsigned int size) [virtual]
Generated but unused method, should not be called.
Implements IPv6Datagram_Base.
{
    throw cRuntimeError(this, "setExtensionHeaderArraySize() not supported, use addExtensionHeader()");
}
Member Data Documentation
ExtensionHeaders IPv6Datagram::extensionHeaders [protected]
Referenced by addExtensionHeader(), calculateFragmentLength(), calculateHeaderByteLength(), calculateUnfragmentableHeaderByteLength(), clean(), copy(), findExtensionHeaderByType(), getExtensionHeader(), getExtensionHeaderArraySize(), removeExtensionHeader(), and removeFirstExtensionHeader().
The documentation for this class was generated from the following files:
IPv6Datagram.h
IPv6Datagram.cc