INET Framework for OMNeT++/OMNEST: WirelessMacBase Class Reference
WirelessMacBase Class Reference
Base class for wireless MAC protocols that use MF's physical layer.
#include <WirelessMacBase.h>
Protected Member Functions
virtual void initialize (int)
Initialization of the module and some variables.
virtual void handleMessage (cMessage *msg)
Called every time a message arrives.
Handle Messages
Functions to redefine by the programmer
virtual void handleSelfMsg (cMessage *msg)=0
Handle self messages such as timers.
virtual void handleUpperMsg (cPacket *msg)=0
Handle packets from upper layer.
virtual void handleCommand (cMessage *msg)=0
Handle commands from upper layer.
virtual void handleLowerMsg (cPacket *msg)=0
Handle packets from lower layer.
virtual bool isUpperMsg (cMessage *msg)
virtual bool isLowerMsg (cMessage *msg)
Convenience Functions
virtual void sendDown (cMessage *msg)
Sends a message to the lower layer.
virtual void sendUp (cMessage *msg)
Sends a message to the upper layer.
Protected Attributes
NotificationBoard * nb
Cached pointer to the NotificationBoard module.
int upperLayerIn
gate id
int upperLayerOut
int lowerLayerIn
int lowerLayerOut
Static Protected Attributes
static simsignal_t packetSentToLowerSignal = SIMSIGNAL_NULL
static simsignal_t packetReceivedFromLowerSignal = SIMSIGNAL_NULL
static simsignal_t packetSentToUpperSignal = SIMSIGNAL_NULL
static simsignal_t packetReceivedFromUpperSignal = SIMSIGNAL_NULL
Detailed Description
Base class for wireless MAC protocols that use MF's physical layer.
Author:
Daniel Willkomm, Andras Varga
Member Function Documentation
virtual void WirelessMacBase::handleCommand (cMessage * msg) [protected, pure virtual]
Handle commands from upper layer.
Implemented in Ieee80211Mac.
Referenced by handleMessage().
virtual void WirelessMacBase::handleLowerMsg (cPacket * msg) [protected, pure virtual]
Handle packets from lower layer.
Implemented in Ieee80211Mac.
Referenced by handleMessage().
void WirelessMacBase::handleMessage (cMessage * msg) [protected, virtual]
Called every time a message arrives.
{
    if (msg->isSelfMessage())
        handleSelfMsg(msg);
    else if (!msg->isPacket())
        handleCommand(msg);
    else if (msg->getArrivalGateId()==upperLayerIn)
    {
        emit(packetReceivedFromUpperSignal, msg);
        handleUpperMsg(PK(msg));
    }
    else
    {
        emit(packetReceivedFromLowerSignal, msg);
        handleLowerMsg(PK(msg));
    }
}
virtual void WirelessMacBase::handleSelfMsg (cMessage * msg) [protected, pure virtual]
Handle self messages such as timers.
Implemented in Ieee80211Mac.
Referenced by handleMessage().
virtual void WirelessMacBase::handleUpperMsg (cPacket * msg) [protected, pure virtual]
Handle packets from upper layer.
Implemented in Ieee80211Mac.
Referenced by handleMessage().
void WirelessMacBase::initialize (int stage) [protected, virtual]
Initialization of the module and some variables.
Reimplemented in Ieee80211Mac.
{
    if (stage==0)
    {
        upperLayerIn = findGate("upperLayerIn");
        upperLayerOut = findGate("upperLayerOut");
        lowerLayerIn = findGate("lowerLayerIn");
        lowerLayerOut = findGate("lowerLayerOut");
        // get a pointer to the NotificationBoard module
        nb = NotificationBoardAccess().get();
        packetSentToLowerSignal = registerSignal("packetSentToLower");
        packetReceivedFromLowerSignal = registerSignal("packetReceivedFromLower");
        packetSentToUpperSignal = registerSignal("packetSentToUpper");
        packetReceivedFromUpperSignal = registerSignal("packetReceivedFromUpper");
    }
}
bool WirelessMacBase::isLowerMsg (cMessage * msg) [protected, virtual]
Referenced by Ieee80211Mac::handleWithFSM().
{
    return msg->getArrivalGateId()==lowerLayerIn;
}
bool WirelessMacBase::isUpperMsg (cMessage * msg) [protected, virtual]
Referenced by Ieee80211Mac::handleWithFSM().
{
    return msg->getArrivalGateId()==upperLayerIn;
}
void WirelessMacBase::sendDown (cMessage * msg) [protected, virtual]
Sends a message to the lower layer.
Referenced by Ieee80211Mac::handleCommand(), Ieee80211Mac::sendACKFrame(), Ieee80211Mac::sendCTSFrame(), Ieee80211Mac::sendDataFrame(), Ieee80211Mac::sendDownPendingRadioConfigMsg(), Ieee80211Mac::sendMulticastFrame(), and Ieee80211Mac::sendRTSFrame().
{
    EV << "sending down " << msg << "\n";
    if (msg->isPacket())
        emit(packetSentToLowerSignal, msg);
    send(msg, lowerLayerOut);
}
void WirelessMacBase::sendUp (cMessage * msg) [protected, virtual]
Sends a message to the upper layer.
Reimplemented in Ieee80211Mac.
{
    EV << "sending up " << msg << "\n";
    if (msg->isPacket())
        emit(packetSentToUpperSignal, msg);
    send(msg, upperLayerOut);
}
Member Data Documentation
int WirelessMacBase::lowerLayerIn [protected]
Referenced by initialize(), and isLowerMsg().
int WirelessMacBase::lowerLayerOut [protected]
Referenced by initialize(), and sendDown().
NotificationBoard* WirelessMacBase::nb [protected]
Cached pointer to the NotificationBoard module.
simsignal_t WirelessMacBase::packetReceivedFromLowerSignal = SIMSIGNAL_NULL [static, protected]
Referenced by handleMessage(), and initialize().
simsignal_t WirelessMacBase::packetReceivedFromUpperSignal = SIMSIGNAL_NULL [static, protected]
Referenced by handleMessage(), and initialize().
simsignal_t WirelessMacBase::packetSentToLowerSignal = SIMSIGNAL_NULL [static, protected]
Referenced by initialize(), and sendDown().
simsignal_t WirelessMacBase::packetSentToUpperSignal = SIMSIGNAL_NULL [static, protected]
Referenced by initialize(), sendUp(), and Ieee80211Mac::sendUp().
int WirelessMacBase::upperLayerIn [protected]
gate id
Referenced by handleMessage(), initialize(), and isUpperMsg().
int WirelessMacBase::upperLayerOut [protected]
Referenced by initialize(), sendUp(), and Ieee80211Mac::sendUp().
The documentation for this class was generated from the following files:
WirelessMacBase.h
WirelessMacBase.cc