INET Framework for OMNeT++/OMNEST: IPassiveQueue Class Reference
IPassiveQueue Class Reference
Abstract interface for passive queues.
#include <IPassiveQueue.h>
Public Member Functions
virtual ~IPassiveQueue ()
virtual void requestPacket ()=0
The queue should send a packet whenever this method is invoked.
virtual int getNumPendingRequests ()=0
Returns number of pending requests.
virtual bool isEmpty ()=0
Return true when queue is empty, otherwise return false.
virtual void clear ()=0
Clear all queued packets and stored requests.
virtual void addListener (IPassiveQueueListener *listener)=0
Adds a new listener to the listener list.
virtual void removeListener (IPassiveQueueListener *listener)=0
Removes a listener from the listener list.
Detailed Description
Abstract interface for passive queues.
Constructor & Destructor Documentation
virtual IPassiveQueue::~IPassiveQueue () [inline, virtual]
{}
Member Function Documentation
virtual void IPassiveQueue::addListener (IPassiveQueueListener * listener) [pure virtual]
Adds a new listener to the listener list.
It does nothing, if the listener list already contains the listener (by pointer equality).
Implemented in PassiveQueueBase, and SchedulerBase.
Referenced by SchedulerBase::initialize().
virtual void IPassiveQueue::clear () [pure virtual]
Clear all queued packets and stored requests.
Implemented in PassiveQueueBase, and SchedulerBase.
virtual int IPassiveQueue::getNumPendingRequests () [pure virtual]
Returns number of pending requests.
Implemented in PassiveQueueBase, and SchedulerBase.
Referenced by EtherMACBase::getNextFrameFromQueue(), PPP::handleMessage(), PPP::initialize(), EtherMACBase::initializeQueueModule(), EtherMACBase::processConnectDisconnect(), PPP::refreshOutGateConnection(), and EtherMACBase::requestNextFrameFromExtQueue().
virtual bool IPassiveQueue::isEmpty () [pure virtual]
Return true when queue is empty, otherwise return false.
Implemented in Ieee80211MgmtBase, DropTailQueue, SchedulerBase, and FIFOQueue.
Referenced by PriorityScheduler::schedulePacket().
virtual void IPassiveQueue::removeListener (IPassiveQueueListener * listener) [pure virtual]
Removes a listener from the listener list.
It does nothing if the listener was not found on the listener list.
Implemented in PassiveQueueBase, and SchedulerBase.
virtual void IPassiveQueue::requestPacket () [pure virtual]
The queue should send a packet whenever this method is invoked.
If the queue is currently empty, it should send a packet when when one becomes available.
Implemented in PassiveQueueBase, and SchedulerBase.
Referenced by EtherMACBase::getNextFrameFromQueue(), PPP::handleMessage(), Ieee80211Mac::handleUpperMsg(), PPP::initialize(), EtherMACBase::initializeQueueModule(), Ieee80211Mac::initializeQueueModule(), Ieee80211Mac::popTransmissionQueue(), EtherMACBase::processConnectDisconnect(), PPP::refreshOutGateConnection(), EtherMACBase::requestNextFrameFromExtQueue(), and PriorityScheduler::schedulePacket().
The documentation for this class was generated from the following file:
IPassiveQueue.h