INET Framework for OMNeT++/OMNEST: OSPF::SummaryLSA Class Reference
OSPF::SummaryLSA Class Reference
#include <LSA.h>
Public Member Functions
SummaryLSA ()
SummaryLSA (const OSPFSummaryLSA &lsa)
SummaryLSA (const SummaryLSA &lsa)
virtual ~SummaryLSA ()
bool getPurgeable () const
void setPurgeable (bool purge=true)
bool validateLSChecksum () const
bool update (const OSPFSummaryLSA *lsa)
bool differsFrom (const OSPFSummaryLSA *summaryLSA) const
Protected Attributes
bool purgeable
Constructor & Destructor Documentation
OSPF::SummaryLSA::SummaryLSA () [inline]
: OSPFSummaryLSA(), RoutingInfo(), LSATrackingInfo(), purgeable(false) {}
OSPF::SummaryLSA::SummaryLSA (const OSPFSummaryLSA & lsa) [inline]
: OSPFSummaryLSA(lsa), RoutingInfo(), LSATrackingInfo(), purgeable(false) {}
OSPF::SummaryLSA::SummaryLSA (const SummaryLSA & lsa) [inline]
: OSPFSummaryLSA(lsa), RoutingInfo(lsa), LSATrackingInfo(lsa), purgeable(lsa.purgeable) {}
virtual OSPF::SummaryLSA::~SummaryLSA () [inline, virtual]
{}
Member Function Documentation
bool OSPF::SummaryLSA::differsFrom (const OSPFSummaryLSA * summaryLSA) const
Referenced by update().
{
    const OSPFLSAHeader& lsaHeader = summaryLSA->getHeader();
    bool differentHeader = ((header_var.getLsOptions() != lsaHeader.getLsOptions()) ||
                            ((header_var.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                            ((header_var.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                            (header_var.getLsaLength() != lsaHeader.getLsaLength()));
    bool differentBody = false;
    if (!differentHeader) {
        differentBody = ((networkMask_var != summaryLSA->getNetworkMask()) ||
                         (routeCost_var != summaryLSA->getRouteCost()) ||
                         (tosData_arraysize != summaryLSA->getTosDataArraySize()));
        if (!differentBody) {
            unsigned int tosCount = tosData_arraysize;
            for (unsigned int i = 0; i < tosCount; i++) {
                if ((tosData_var[i].tos != summaryLSA->getTosData(i).tos) ||
                    (tosData_var[i].tosMetric[0] != summaryLSA->getTosData(i).tosMetric[0]) ||
                    (tosData_var[i].tosMetric[1] != summaryLSA->getTosData(i).tosMetric[1]) ||
                    (tosData_var[i].tosMetric[2] != summaryLSA->getTosData(i).tosMetric[2]))
                {
                    differentBody = true;
                    break;
                }
            }
        }
    }
    return (differentHeader || differentBody);
}
bool OSPF::SummaryLSA::getPurgeable () const [inline]
{ return purgeable; }
void OSPF::SummaryLSA::setPurgeable (bool purge = true) [inline]
{ purgeable = purge; }
bool OSPF::SummaryLSA::update (const OSPFSummaryLSA * lsa)
Referenced by OSPF::Area::ageDatabase().
{
    bool different = differsFrom(lsa);
    (*this) = (*lsa);
    resetInstallTime();
    if (different) {
        clearNextHops();
        return true;
    } else {
        return false;
    }
}
bool OSPF::SummaryLSA::validateLSChecksum () const [inline]
Referenced by OSPF::Area::ageDatabase().
{ return true; } // not implemented
Member Data Documentation
bool OSPF::SummaryLSA::purgeable [protected]
Referenced by getPurgeable(), and setPurgeable().
The documentation for this class was generated from the following files:
LSA.h
SummaryLSA.cc