INET Framework for OMNeT++/OMNEST: ANSimMobility Class Reference
ANSimMobility Class Reference
Uses the <position_change> elements of the ANSim tool's trace file.
#include <ANSimMobility.h>
Public Member Functions
ANSimMobility ()
Protected Member Functions
virtual void initialize (int stage)
Initializes mobility model parameters.
virtual void initializePosition ()
Initializes the position according to the mobility model.
virtual void setTargetPosition ()
Overridden from LineSegmentsMobilityBase.
virtual void move ()
Overridden from LineSegmentsMobilityBase.
virtual cXMLElement * findNextPositionChange (cXMLElement *positionChange)
Finds the next <position_change> element.
virtual void extractDataFrom (cXMLElement *node)
Utility: extract data from given <position_update> element.
Protected Attributes
int nodeId
we'll have to compare this to the <node_id> elements
cXMLElement * nextPositionChange
points to the next <position_change> element
Detailed Description
Uses the <position_change> elements of the ANSim tool's trace file.
See NED file for more info.
Author:
Andras Varga
Constructor & Destructor Documentation
ANSimMobility::ANSimMobility ()
{
    nodeId = -1;
    nextPositionChange = NULL;
}
Member Function Documentation
void ANSimMobility::extractDataFrom (cXMLElement * node) [protected, virtual]
Utility: extract data from given <position_update> element.
Referenced by initializePosition(), and setTargetPosition().
{
    // extract data from <position_change> element
    // FIXME start_time has to be taken into account too! as pause from prev element's end_time
    const char *startTimeStr = firstChildWithTag(node, "start_time")->getNodeValue();
    const char *endTimeStr = firstChildWithTag(node, "end_time")->getNodeValue();
    cXMLElement *destElem = firstChildWithTag(node, "destination");
    const char *xStr = firstChildWithTag(destElem, "xpos")->getNodeValue();
    const char *yStr = firstChildWithTag(destElem, "ypos")->getNodeValue();
    if (!endTimeStr || !xStr || !yStr)
        throw cRuntimeError("No content in <end_time>, <destination>/<xpos> or <ypos> element at %s", node->getSourceLocation());
    nextChange = atof(endTimeStr);
    targetPosition.x = atof(xStr);
    targetPosition.y = atof(yStr);
}
cXMLElement * ANSimMobility::findNextPositionChange (cXMLElement * positionChange) [protected, virtual]
Finds the next <position_change> element.
Referenced by initializePosition(), and setTargetPosition().
{
    // find next <position_change> element with matching <node_id> tag (current one also OK)
    while(positionChange){
        const char *nodeIdStr = firstChildWithTag(positionChange, "node_id")->getNodeValue();
        if(nodeIdStr && atoi(nodeIdStr) == nodeId)
            break;
        positionChange = positionChange->getNextSibling();
    }
    return positionChange;
}
void ANSimMobility::initialize (int stage) [protected, virtual]
Initializes mobility model parameters.
Reimplemented from LineSegmentsMobilityBase.
{
    LineSegmentsMobilityBase::initialize(stage);
    EV << "initializing ANSimMobility stage " << stage << endl;
    if (stage == 0)
    {
        nodeId = par("nodeId");
        if (nodeId == -1)
            nodeId = getParentModule()->getIndex();
        // get script: param should point to <simulation> element
        cXMLElement *rootElem = par("ansimTrace");
        if (strcmp(rootElem->getTagName(), "simulation")!=0)
            throw cRuntimeError("<simulation> is expected as root element not <%s> at %s",
                  rootElem->getTagName(), rootElem->getSourceLocation());
        nextPositionChange = rootElem->getElementByPath("mobility/position_change");
        if (!nextPositionChange)
            throw cRuntimeError("Element doesn't have <mobility> child or <position_change> grandchild at %s",
                  rootElem->getSourceLocation());
    }
}
void ANSimMobility::initializePosition () [protected, virtual]
Initializes the position according to the mobility model.
Reimplemented from MobilityBase.
{
    cXMLElement *firstPositionChange = findNextPositionChange(nextPositionChange);
    if (firstPositionChange)
        extractDataFrom(firstPositionChange);
    lastPosition = targetPosition;
}
void ANSimMobility::move () [protected, virtual]
Overridden from LineSegmentsMobilityBase.
Reimplemented from LineSegmentsMobilityBase.
{
    LineSegmentsMobilityBase::move();
    raiseErrorIfOutside();
}
void ANSimMobility::setTargetPosition () [protected, virtual]
Overridden from LineSegmentsMobilityBase.
Implements LineSegmentsMobilityBase.
{
    nextPositionChange = findNextPositionChange(nextPositionChange);
    if (!nextPositionChange)
    {
        nextChange = -1;
        stationary = true;
        targetPosition = lastPosition;
        return;
    }
    // extract data from it
    extractDataFrom(nextPositionChange);
    // skip this one
    nextPositionChange = nextPositionChange->getNextSibling();
}
Member Data Documentation
cXMLElement* ANSimMobility::nextPositionChange [protected]
points to the next <position_change> element
Referenced by ANSimMobility(), initialize(), initializePosition(), and setTargetPosition().
int ANSimMobility::nodeId [protected]
we'll have to compare this to the <node_id> elements
Referenced by ANSimMobility(), findNextPositionChange(), and initialize().
The documentation for this class was generated from the following files:
ANSimMobility.h
ANSimMobility.cc