INET Framework for OMNeT++/OMNEST: RTPPacket Class Reference
RTPPacket Class Reference
This class represents an RTP data packet.
#include <RTPPacket.h>
Public Member Functions
RTPPacket (const char *name=NULL, int kind=0)
RTPPacket (const RTPPacket &other)
RTPPacket & operator= (const RTPPacket &other)
virtual RTPPacket * dup () const
virtual std::string info () const
Writes a one line info about this RTPPacket into the given string.
virtual void dump () const
Writes a longer description about this RTPPacket into the given stream.
virtual int getHeaderLength () const
Returns the length of the header (fixed plus variable part) of this RTPPacket.
virtual void setHeaderLength (int x)
virtual int getPayloadLength () const
Returns the size of the payload stored in this RTPPacket.
virtual void setPayloadLength (int x)
Detailed Description
This class represents an RTP data packet.
Real data can either be encapsulated or simulated by adding length. Following RTP header fields exist but aren't used: padding, extension, csrcCount. The csrcList can't be used because csrcCount is always 0.
Constructor & Destructor Documentation
RTPPacket::RTPPacket (const char * name = NULL, int kind = 0) [inline]
Referenced by dup().
: RTPPacket_Base(name, kind) {}
RTPPacket::RTPPacket (const RTPPacket & other) [inline]
: RTPPacket_Base(other) {}
Member Function Documentation
void RTPPacket::dump () const [virtual]
Writes a longer description about this RTPPacket into the given stream.
Referenced by RTP::readRet().
{
    ev << "RTPPacket:" << endl;
    ev << "  payloadType = " << payloadType_var << endl;
    ev << "  sequenceNumber = " << sequenceNumber_var << endl;
    ev << "  timeStamp = " << timeStamp_var << endl;
    ev << "  payloadLength = " << getPayloadLength() << endl;
}
virtual RTPPacket* RTPPacket::dup () const [inline, virtual]
Reimplemented from RTPPacket_Base.
{return new RTPPacket(*this);}
int RTPPacket::getHeaderLength () const [virtual]
Returns the length of the header (fixed plus variable part) of this RTPPacket.
Implements RTPPacket_Base.
Referenced by getPayloadLength().
{
    // fixed header is 12 bytes long,
    // add 4 bytes for every csrc identifier
    return (RTPPACKET_FIX_HEADERLENGTH + 4 * getCsrcArraySize());
}
int RTPPacket::getPayloadLength () const [virtual]
Returns the size of the payload stored in this RTPPacket.
Implements RTPPacket_Base.
Referenced by dump(), info(), and RTPSenderInfo::processRTPPacket().
{
    return (getByteLength() - getHeaderLength());
}
std::string RTPPacket::info () const [virtual]
Writes a one line info about this RTPPacket into the given string.
{
    std::stringstream out;
    out << "RTPPacket: payloadType=" << payloadType_var
        << " payloadLength=" << getPayloadLength();
    return out.str();
}
RTPPacket& RTPPacket::operator= (const RTPPacket & other) [inline]
{RTPPacket_Base::operator=(other); return *this;}
virtual void RTPPacket::setHeaderLength (int x) [inline, virtual]
Implements RTPPacket_Base.
{ throw cRuntimeError("Don't use SetHeaderLength()"); }
virtual void RTPPacket::setPayloadLength (int x) [inline, virtual]
Implements RTPPacket_Base.
{ throw cRuntimeError("Don't use SetPayloadLength()"); }
The documentation for this class was generated from the following files:
RTPPacket.h
RTPPacket.cc