INET Framework for OMNeT++/OMNEST: OSPF::NetworkLSA Class Reference
OSPF::NetworkLSA Class Reference
#include <LSA.h>
Public Member Functions
NetworkLSA ()
NetworkLSA (const OSPFNetworkLSA &lsa)
NetworkLSA (const NetworkLSA &lsa)
virtual ~NetworkLSA ()
bool validateLSChecksum () const
bool update (const OSPFNetworkLSA *lsa)
bool differsFrom (const OSPFNetworkLSA *networkLSA) const
Constructor & Destructor Documentation
OSPF::NetworkLSA::NetworkLSA () [inline]
: OSPFNetworkLSA(), RoutingInfo(), LSATrackingInfo() {}
OSPF::NetworkLSA::NetworkLSA (const OSPFNetworkLSA & lsa) [inline]
: OSPFNetworkLSA(lsa), RoutingInfo(), LSATrackingInfo() {}
OSPF::NetworkLSA::NetworkLSA (const NetworkLSA & lsa) [inline]
: OSPFNetworkLSA(lsa), RoutingInfo(lsa), LSATrackingInfo(lsa) {}
virtual OSPF::NetworkLSA::~NetworkLSA () [inline, virtual]
{}
Member Function Documentation
bool OSPF::NetworkLSA::differsFrom (const OSPFNetworkLSA * networkLSA) const
Referenced by update().
{
    const OSPFLSAHeader& lsaHeader = networkLSA->getHeader();
    bool differentHeader = ((header_var.getLsOptions() != lsaHeader.getLsOptions()) ||
                            ((header_var.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                            ((header_var.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                            (header_var.getLsaLength() != lsaHeader.getLsaLength()));
    bool differentBody = false;
    if (!differentHeader) {
        differentBody = ((networkMask_var != networkLSA->getNetworkMask()) ||
                         (attachedRouters_arraysize != networkLSA->getAttachedRoutersArraySize()));
        if (!differentBody) {
            unsigned int routerCount = attachedRouters_arraysize;
            for (unsigned int i = 0; i < routerCount; i++) {
                if (attachedRouters_var[i] != networkLSA->getAttachedRouters(i)) {
                    differentBody = true;
                    break;
                }
            }
        }
    }
    return (differentHeader || differentBody);
}
bool OSPF::NetworkLSA::update (const OSPFNetworkLSA * lsa)
Referenced by OSPF::Area::ageDatabase(), and OSPF::NeighborState::changeState().
{
    bool different = differsFrom(lsa);
    (*this) = (*lsa);
    resetInstallTime();
    if (different) {
        clearNextHops();
        return true;
    } else {
        return false;
    }
}
bool OSPF::NetworkLSA::validateLSChecksum () const [inline]
Referenced by OSPF::Area::ageDatabase().
{ return true; } // not implemented
The documentation for this class was generated from the following files:
LSA.h
NetworkLSA.cc