INET Framework for OMNeT++/OMNEST: IRoutingTable Class Reference
IRoutingTable Class Reference
A C++ interface to abstract the functionality of IRoutingTable.
#include <IRoutingTable.h>
Public Member Functions
virtual ~IRoutingTable ()
virtual void printRoutingTable () const =0
For debugging.
virtual void printMulticastRoutingTable () const =0
For debugging.
virtual cModule * getHostModule ()=0
Returns the host or router this routing table lives in.
virtual bool isIPForwardingEnabled ()=0
IPv4 forwarding on/off.
virtual bool isMulticastForwardingEnabled ()=0
IPv4 multicast forwarding on/off.
virtual IPv4Address getRouterId ()=0
Returns routerId.
virtual void setRouterId (IPv4Address a)=0
Sets routerId.
Interfaces
virtual void configureInterfaceForIPv4 (InterfaceEntry *ie)=0
virtual InterfaceEntry * getInterfaceByAddress (const IPv4Address &address) const =0
Returns an interface given by its address.
Routing functions (query the route table)
virtual bool isLocalAddress (const IPv4Address &dest) const =0
Checks if the address is a local one, i.e.
virtual bool isLocalBroadcastAddress (const IPv4Address &dest) const =0
Checks if the address is a local network broadcast address, i.e.
virtual InterfaceEntry * findInterfaceByLocalBroadcastAddress (const IPv4Address &dest) const =0
Returns the interface entry having the specified address as its local broadcast address.
virtual IPv4Route * findBestMatchingRoute (const IPv4Address &dest) const =0
The routing function.
virtual InterfaceEntry * getInterfaceForDestAddr (const IPv4Address &dest) const =0
Convenience function based on findBestMatchingRoute().
virtual IPv4Address getGatewayForDestAddr (const IPv4Address &dest) const =0
Convenience function based on findBestMatchingRoute().
Multicast routing functions
virtual bool isLocalMulticastAddress (const IPv4Address &dest) const =0
Checks if the address is in one of the local multicast group address list.
virtual const IPv4MulticastRoute * findBestMatchingMulticastRoute (const IPv4Address &origin, const IPv4Address &group) const =0
Returns route for a multicast origin and group.
Route table manipulation
virtual int getNumRoutes () const =0
Returns the total number of unicast routes.
virtual IPv4Route * getRoute (int k) const =0
Returns the kth route.
virtual IPv4Route * getDefaultRoute () const =0
Finds and returns the default route, or NULL if it doesn't exist.
virtual void addRoute (IPv4Route *entry)=0
Adds a route to the routing table.
virtual IPv4Route * removeRoute (IPv4Route *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteRoute (IPv4Route *entry)=0
Deletes the given route from the routing table.
virtual int getNumMulticastRoutes () const =0
Returns the total number of multicast routes.
virtual IPv4MulticastRoute * getMulticastRoute (int k) const =0
Returns the kth multicast route.
virtual void addMulticastRoute (IPv4MulticastRoute *entry)=0
Adds a multicast route to the routing table.
virtual IPv4MulticastRoute * removeMulticastRoute (IPv4MulticastRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteMulticastRoute (IPv4MulticastRoute *entry)=0
Deletes the given multicast route from the routing table.
virtual void purge ()=0
Deletes invalid routes from the routing table.
virtual std::vector< IPv4Address > gatherAddresses () const =0
Utility function: Returns a vector of all addresses of the node.
virtual void routeChanged (IPv4Route *entry, int fieldCode)=0
To be called from route objects whenever a field changes.
virtual void multicastRouteChanged (IPv4MulticastRoute *entry, int fieldCode)=0
To be called from multicast route objects whenever a field changes.
Detailed Description
A C++ interface to abstract the functionality of IRoutingTable.
Referring to IRoutingTable via this interface makes it possible to transparently replace IRoutingTable with a different implementation, without any change to the base INET.
See also:
IRoutingTable, IPv4Route
Constructor & Destructor Documentation
virtual IRoutingTable::~IRoutingTable () [inline, virtual]
{};
Member Function Documentation
virtual void IRoutingTable::addMulticastRoute (IPv4MulticastRoute * entry) [pure virtual]
Adds a multicast route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implemented in RoutingTable.
Referenced by IPv4NetworkConfigurator::addManualMulticastRoutes().
virtual void IRoutingTable::addRoute (IPv4Route * entry) [pure virtual]
Adds a route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implemented in RoutingTable.
Referenced by FlatNetworkConfigurator::addDefaultRoutes(), OSPF::Router::addExternalRouteInIPTable(), IPv4NetworkConfigurator::addManualRoutes(), IPv4NetworkConfigurator::addStaticRoutes(), DHCPClient::changeFSMState(), BGPRouting::decisionProcess(), FlatNetworkConfigurator::fillRoutingTables(), DSDV_2::handleMessage(), ManetRoutingBase::omnet_chg_rte(), RoutingTableParser::parseRouting(), TED::rebuildRoutingTable(), OSPF::Router::rebuildRoutingTable(), ManetRoutingBase::setRoute(), and OSPF::Router::updateExternalRoute().
virtual void IRoutingTable::configureInterfaceForIPv4 (InterfaceEntry * ie) [pure virtual]
Implemented in RoutingTable.
virtual bool IRoutingTable::deleteMulticastRoute (IPv4MulticastRoute * entry) [pure virtual]
Deletes the given multicast route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implemented in RoutingTable.
virtual bool IRoutingTable::deleteRoute (IPv4Route * entry) [pure virtual]
Deletes the given route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implemented in RoutingTable.
Referenced by BGPRouting::decisionProcess(), BGPRouting::deleteBGPRoutingEntry(), DSDV_2::handleMessage(), DSDV_2::initialize(), DSRUU::initialize(), ManetRoutingBase::omnet_chg_rte(), ManetRoutingBase::omnet_clean_rte(), TED::rebuildRoutingTable(), OSPF::Router::rebuildRoutingTable(), ManetRoutingBase::registerRoutingModule(), and ManetRoutingBase::setRoute().
virtual const IPv4MulticastRoute* IRoutingTable::findBestMatchingMulticastRoute (const IPv4Address & origin, const IPv4Address & group) const [pure virtual]
Returns route for a multicast origin and group.
Implemented in RoutingTable.
Referenced by IPv4::forwardMulticastPacket().
virtual IPv4Route* IRoutingTable::findBestMatchingRoute (const IPv4Address & dest) const [pure virtual]
The routing function.
Performs longest prefix match for the given destination address, and returns the resulting route. Returns NULL if there is no matching route.
Implemented in RoutingTable.
Referenced by IPv4::determineOutgoingInterfaceForMulticastDatagram(), DSDV_2::handleMessage(), ManetRoutingBase::omnet_chg_rte(), IPv4::routeUnicastPacket(), and ManetRoutingBase::setRoute().
virtual InterfaceEntry* IRoutingTable::findInterfaceByLocalBroadcastAddress (const IPv4Address & dest) const [pure virtual]
Returns the interface entry having the specified address as its local broadcast address.
Implemented in RoutingTable.
Referenced by IPv4::handlePacketFromNetwork().
virtual std::vector<IPv4Address> IRoutingTable::gatherAddresses () const [pure virtual]
Utility function: Returns a vector of all addresses of the node.
Implemented in RoutingTable.
virtual IPv4Route* IRoutingTable::getDefaultRoute () const [pure virtual]
Finds and returns the default route, or NULL if it doesn't exist.
Implemented in RoutingTable.
virtual IPv4Address IRoutingTable::getGatewayForDestAddr (const IPv4Address & dest) const [pure virtual]
Convenience function based on findBestMatchingRoute().
Returns the gateway for the destination address. Returns the unspecified address if the destination is not in routing table or the gateway field is not filled in in the route.
Implemented in RoutingTable.
virtual cModule* IRoutingTable::getHostModule () [pure virtual]
Returns the host or router this routing table lives in.
Implemented in RoutingTable.
virtual InterfaceEntry* IRoutingTable::getInterfaceByAddress (const IPv4Address & address) const [pure virtual]
Returns an interface given by its address.
Returns NULL if not found.
Implemented in RoutingTable.
Referenced by RSVP::commitResv(), IPv4::determineOutgoingInterfaceForMulticastDatagram(), IPv4::encapsulate(), TED::initialize(), and TED::rebuildRoutingTable().
virtual InterfaceEntry* IRoutingTable::getInterfaceForDestAddr (const IPv4Address & dest) const [pure virtual]
Convenience function based on findBestMatchingRoute().
Returns the output interface for the packets with dest as destination address, or NULL if the destination is not in routing table.
Implemented in RoutingTable.
Referenced by ARP::addressRecognized(), RSVP::commitResv(), BGPRouting::createSession(), RSVP::evalNextHopInterface(), LDP::findInterfaceFromPeerAddr(), BGPRouting::findNextSession(), IPv4::getShortestPathInterfaceToSource(), LDP::locateNextHop(), SCTPAssociation::pmStartPathManagement(), RTP::resolveMTU(), and SCTPPathVariables::SCTPPathVariables().
virtual IPv4MulticastRoute* IRoutingTable::getMulticastRoute (int k) const [pure virtual]
Returns the kth multicast route.
Implemented in RoutingTable.
Referenced by IPv4NetworkConfigurator::dumpConfig().
virtual int IRoutingTable::getNumMulticastRoutes () const [pure virtual]
Returns the total number of multicast routes.
Implemented in RoutingTable.
Referenced by IPv4NetworkConfigurator::dumpConfig(), and IPv4NetworkConfigurator::dumpRoutes().
virtual int IRoutingTable::getNumRoutes () const [pure virtual]
Returns the total number of unicast routes.
Implemented in RoutingTable.
Referenced by OSPF::Router::addExternalRouteInIPTable(), DHCPClient::changeFSMState(), IPv4NetworkConfigurator::dumpConfig(), NetworkInfo::dumpRoutingInfo(), LDP::findPeerAddrFromInterface(), DSDV_2::initialize(), DSRUU::initialize(), BGPRouting::isInRoutingTable(), ManetRoutingBase::omnet_chg_rte(), ManetRoutingBase::omnet_clean_rte(), ManetRoutingBase::omnet_exist_rte(), BGPRouting::ospfExist(), LDP::rebuildFecList(), TED::rebuildRoutingTable(), OSPF::Router::rebuildRoutingTable(), ManetRoutingBase::registerRoutingModule(), ManetRoutingBase::setRoute(), and OSPF::Router::updateExternalRoute().
virtual IPv4Route* IRoutingTable::getRoute (int k) const [pure virtual]
Returns the kth route.
Implemented in RoutingTable.
Referenced by OSPF::Router::addExternalRouteInIPTable(), DHCPClient::changeFSMState(), BGPRouting::decisionProcess(), IPv4NetworkConfigurator::dumpConfig(), NetworkInfo::dumpRoutingInfo(), LDP::findPeerAddrFromInterface(), DSDV_2::initialize(), DSRUU::initialize(), BGPRouting::isInRoutingTable(), ManetRoutingBase::omnet_chg_rte(), ManetRoutingBase::omnet_clean_rte(), ManetRoutingBase::omnet_exist_rte(), BGPRouting::ospfExist(), LDP::rebuildFecList(), TED::rebuildRoutingTable(), OSPF::Router::rebuildRoutingTable(), ManetRoutingBase::registerRoutingModule(), ManetRoutingBase::setRoute(), and OSPF::Router::updateExternalRoute().
virtual IPv4Address IRoutingTable::getRouterId () [pure virtual]
Returns routerId.
Implemented in RoutingTable.
Referenced by BGPRouting::createSession(), SimpleClassifier::initialize(), LIBTable::initialize(), TED::initialize(), LinkStateRouting::initialize(), OSPFRouting::initialize(), RSVP::initialize(), BGPRouting::loadConfigFromXML(), LDP::openTCPConnectionToPeer(), LDP::processHelloTimeout(), LDP::processLDPHello(), RoutingTableRecorder::recordRouteChange(), ManetRoutingBase::registerRoutingModule(), IPvXAddressResolver::routerIdOf(), LDP::sendHelloTo(), LDP::sendMapping(), LDP::sendMappingRequest(), and LDP::sendNotify().
virtual bool IRoutingTable::isIPForwardingEnabled () [pure virtual]
IPv4 forwarding on/off.
Implemented in RoutingTable.
Referenced by IPv4NetworkConfigurator::determineGatewayForLink(), IPv4NetworkConfigurator::extractWiredTopology(), and IPv4::handlePacketFromNetwork().
virtual bool IRoutingTable::isLocalAddress (const IPv4Address & dest) const [pure virtual]
Checks if the address is a local one, i.e.
one of the host's.
Implemented in RoutingTable.
Referenced by ARP::addressRecognized(), LDP::findInterfaceFromPeerAddr(), IPv4::handleMessageFromHL(), IPv4::handlePacketFromNetwork(), ManetRoutingBase::isIpLocalAddress(), and ManetRoutingBase::isLocalAddress().
virtual bool IRoutingTable::isLocalBroadcastAddress (const IPv4Address & dest) const [pure virtual]
Checks if the address is a local network broadcast address, i.e.
one of the broadcast addresses derived from the interface addresses and netmasks.
Implemented in RoutingTable.
Referenced by IPv4::handleMessageFromHL().
virtual bool IRoutingTable::isLocalMulticastAddress (const IPv4Address & dest) const [pure virtual]
Checks if the address is in one of the local multicast group address list.
Implemented in RoutingTable.
virtual bool IRoutingTable::isMulticastForwardingEnabled () [pure virtual]
IPv4 multicast forwarding on/off.
Implemented in RoutingTable.
Referenced by IPv4NetworkConfigurator::addManualMulticastRoutes(), IGMPv2::configureInterface(), IPv4::handlePacketFromNetwork(), IGMPv2::processLeave(), IGMPv2::processQuery(), and IGMPv2::processV2Report().
virtual void IRoutingTable::multicastRouteChanged (IPv4MulticastRoute * entry, int fieldCode) [pure virtual]
To be called from multicast route objects whenever a field changes.
Used for maintaining internal data structures and firing "routing table changed" notifications.
Implemented in RoutingTable.
Referenced by IPv4MulticastRoute::changed().
virtual void IRoutingTable::printMulticastRoutingTable () const [pure virtual]
For debugging.
Implemented in RoutingTable.
Referenced by IPv4NetworkConfigurator::dumpRoutes().
virtual void IRoutingTable::printRoutingTable () const [pure virtual]
For debugging.
Implemented in RoutingTable.
Referenced by IPv4NetworkConfigurator::dumpRoutes().
virtual void IRoutingTable::purge () [pure virtual]
Deletes invalid routes from the routing table.
Invalid routes are those where the isValid() method returns false.
Implemented in RoutingTable.
Referenced by DSDV_2::handleMessage().
virtual IPv4MulticastRoute* IRoutingTable::removeMulticastRoute (IPv4MulticastRoute * entry) [pure virtual]
Removes the given route from the routing table, and returns it.
NULL is returned of the route was not in the routing table.
Implemented in RoutingTable.
virtual IPv4Route* IRoutingTable::removeRoute (IPv4Route * entry) [pure virtual]
Removes the given route from the routing table, and returns it.
NULL is returned of the route was not in the routing table.
Implemented in RoutingTable.
virtual void IRoutingTable::routeChanged (IPv4Route * entry, int fieldCode) [pure virtual]
To be called from route objects whenever a field changes.
Used for maintaining internal data structures and firing "routing table changed" notifications.
Implemented in RoutingTable.
Referenced by IPv4Route::changed().
virtual void IRoutingTable::setRouterId (IPv4Address a) [pure virtual]
Sets routerId.
Implemented in RoutingTable.
The documentation for this class was generated from the following file:
IRoutingTable.h