INET Framework for OMNeT++/OMNEST: MACAddress Class Reference
MACAddress Class Reference
Stores an IEEE 802 MAC address (6 octets = 48 bits).
#include <MACAddress.h>
Public Member Functions
MACAddress ()
Default constructor initializes address bytes to zero.
MACAddress (uint64 bits)
Initializes the address from the lower 48 bits of the 64-bit argument.
MACAddress (const char *hexstr)
Constructor which accepts a hex string (12 hex digits, may also contain spaces, hyphens and colons)
MACAddress (const MACAddress &other)
Copy constructor.
MACAddress & operator= (const MACAddress &other)
Assignment.
unsigned int getAddressSize () const
Returns the address size in bytes, that is, 6.
unsigned char getAddressByte (unsigned int k) const
Returns the kth byte of the address.
void setAddressByte (unsigned int k, unsigned char addrbyte)
Sets the kth byte of the address.
bool tryParse (const char *hexstr)
Sets the address and returns true if the syntax of the string is correct.
void setAddress (const char *hexstr)
Converts address value from hex string (12 hex digits, may also contain spaces, hyphens and colons)
void getAddressBytes (unsigned char *addrbytes) const
Copies the address to the given pointer (array of 6 unsigned chars).
void getAddressBytes (char *addrbytes) const
void setAddressBytes (unsigned char *addrbytes)
Sets address bytes.
void setAddressBytes (char *addrbytes)
void setBroadcast ()
Sets the address to the broadcast address (hex ff:ff:ff:ff:ff:ff).
bool isBroadcast () const
Returns true if this is the broadcast address (hex ff:ff:ff:ff:ff:ff).
bool isMulticast () const
Returns true if this is a multicast logical address (first byte's lsb is 1).
bool isUnspecified () const
Returns true if all address bytes are zero.
std::string str () const
Converts address to a hex string.
uint64 getInt () const
Converts address to 48 bits integer.
bool equals (const MACAddress &other) const
Returns true if the two addresses are equal.
bool operator== (const MACAddress &other) const
Returns true if the two addresses are equal.
bool operator!= (const MACAddress &other) const
Returns true if the two addresses are not equal.
int compareTo (const MACAddress &other) const
Returns -1, 0 or 1 as result of comparison of 2 addresses.
InterfaceToken formInterfaceIdentifier () const
Create interface identifier (IEEE EUI-64) which can be used by IPv6 stateless address autoconfiguration.
bool operator< (const MACAddress &other) const
bool operator> (const MACAddress &other) const
Static Public Member Functions
static MACAddress generateAutoAddress ()
Generates a unique address which begins with 0a:aa and ends in a unique suffix.
Static Public Attributes
static const MACAddress UNSPECIFIED_ADDRESS
The unspecified MAC address, 00:00:00:00:00:00.
static const MACAddress BROADCAST_ADDRESS
The broadcast MAC address, ff:ff:ff:ff:ff:ff.
static const MACAddress MULTICAST_PAUSE_ADDRESS
The special multicast PAUSE MAC address, 01:80:C2:00:00:01.
Private Attributes
uint64 address
Static Private Attributes
static unsigned int autoAddressCtr
Detailed Description
Stores an IEEE 802 MAC address (6 octets = 48 bits).
Constructor & Destructor Documentation
MACAddress::MACAddress () [inline]
Default constructor initializes address bytes to zero.
{ address = 0; }
MACAddress::MACAddress (uint64 bits) [inline]
Initializes the address from the lower 48 bits of the 64-bit argument.
{ address = bits & MAC_ADDRESS_MASK; }
MACAddress::MACAddress (const char * hexstr) [inline, explicit]
Constructor which accepts a hex string (12 hex digits, may also contain spaces, hyphens and colons)
{ setAddress(hexstr); }
MACAddress::MACAddress (const MACAddress & other) [inline]
Copy constructor.
{ address = other.address; }
Member Function Documentation
int MACAddress::compareTo (const MACAddress & other) const
Returns -1, 0 or 1 as result of comparison of 2 addresses.
Referenced by MACRelayUnitBase::MAC_compare::operator()(), and Ieee80211MgmtAP::MAC_compare::operator()().
{
    return (address < other.address) ? -1 : (address == other.address) ? 0 : 1;  // note: "return address-other.address" is not OK because 64-bit result does not fit into the return type
}
bool MACAddress::equals (const MACAddress & other) const [inline]
Returns true if the two addresses are equal.
Referenced by EtherMACBase::dropFrameNotForUs(), EtherMACFullDuplex::processFrameFromUpperLayer(), EtherMAC::processFrameFromUpperLayer(), IPv6NeighbourDiscovery::processNAForOtherNCEStates(), IPv6NeighbourDiscovery::processNSWithSpecifiedSrcAddr(), and IPv6NeighbourDiscovery::processRAForRouterUpdates().
{ return address == other.address; }
InterfaceToken MACAddress::formInterfaceIdentifier () const
Create interface identifier (IEEE EUI-64) which can be used by IPv6 stateless address autoconfiguration.
Referenced by EtherMACBase::registerInterface(), and Ieee80211Mac::registerInterface().
{
    uint32 high = ((address>>16)|0xff)^0x02000000;
    uint32 low = (0xfe<<24)|(address&0xffffff);
    return InterfaceToken(low, high, 64);
}
MACAddress MACAddress::generateAutoAddress () [static]
Generates a unique address which begins with 0a:aa and ends in a unique suffix.
Referenced by Ieee80211Mac::initialize(), and EtherMACBase::initializeMACAddress().
{
    ++autoAddressCtr;
    uint64 intAddr = 0x0AAA00000000L + (autoAddressCtr & 0xffffffffL);
    MACAddress addr(intAddr);
    return addr;
}
unsigned char MACAddress::getAddressByte (unsigned int k) const
Returns the kth byte of the address.
Referenced by getAddressBytes(), and str().
{
    if (k>=MAC_ADDRESS_SIZE) throw cRuntimeError("Array of size 6 indexed with %d", k);
    int offset = (MAC_ADDRESS_SIZE-k-1)*8;
    return 0xff&(address>>offset);
}
void MACAddress::getAddressBytes (unsigned char * addrbytes) const
Copies the address to the given pointer (array of 6 unsigned chars).
Referenced by dsr_pkt_alloc(), and dsr_pkt_alloc2().
{
    for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
        addrbytes[i] = getAddressByte(i);
}
void MACAddress::getAddressBytes (char * addrbytes) const [inline]
Referenced by getAddressBytes().
{ getAddressBytes((unsigned char *)addrbytes); }
unsigned int MACAddress::getAddressSize () const [inline]
Returns the address size in bytes, that is, 6.
{ return MAC_ADDRESS_SIZE; }
uint64 MACAddress::getInt () const [inline]
Converts address to 48 bits integer.
Referenced by OLSR::check_packet(), ManetRoutingBase::getAp(), OLSR::getIfaceAddressFromIndex(), DYMOUM::handleMessage(), handleMessage(), initialize(), Batman::initialize(), DYMOUM::initialize(), ManetRoutingBase::isLocalAddress(), ManetRoutingBase::isMulticastAddress(), DYMOUM::packetFailedMac(), packetFailedMac(), DYMOUM::processFullPromiscuous(), ManetRoutingBase::receiveChangeNotification(), recvAODVUUPacket(), DYMOUM::recvDYMOUMPacket(), rreq_proactive(), and DYMOUM::rreq_proactive().
{ return address; }
bool MACAddress::isBroadcast () const [inline]
Returns true if this is the broadcast address (hex ff:ff:ff:ff:ff:ff).
Referenced by EtherMACBase::dropFrameNotForUs(), MACRelayUnitBase::handleAndDispatchFrame(), DYMOUM::packetFailedMac(), and packetFailedMac().
{ return address == MAC_ADDRESS_MASK; }
bool MACAddress::isMulticast () const [inline]
Returns true if this is a multicast logical address (first byte's lsb is 1).
Referenced by EtherMACBase::dropFrameNotForUs(), Ieee80211MgmtAP::handleDataFrame(), Ieee80211MgmtAP::handleUpperMessage(), Ieee80211Mac::isMulticast(), and Ieee80211Mac::mappingAccessCategory().
{ return getAddressByte(0) & 0x01; };
bool MACAddress::isUnspecified () const [inline]
Returns true if all address bytes are zero.
Referenced by Ieee80211MgmtAPBase::distributeReceivedDataFrame(), Ieee80211MgmtSTASimplified::encapsulate(), ManetRoutingBase::getAp(), ManetRoutingBase::getApList(), EtherEncap::handleSendPause(), EtherLLC::handleSendPause(), Ieee80211MgmtSTASimplified::handleUpperMessage(), Ieee80211MgmtSTA::handleUpperMessage(), Ieee80211Mac::handleUpperMsg(), EtherTrafGen::initialize(), EtherAppCli::initialize(), Ieee80211Mac::initialize(), ARP::processARPPacket(), Ieee80211AgentSTA::processAssociateConfirm(), EtherMACFullDuplex::processFrameFromUpperLayer(), EtherMAC::processFrameFromUpperLayer(), IPv6NeighbourDiscovery::processNAForIncompleteNCEState(), IPv6NeighbourDiscovery::processNAForOtherNCEStates(), IPv6NeighbourDiscovery::processNSWithSpecifiedSrcAddr(), IPv6NeighbourDiscovery::processRAForRouterUpdates(), Ieee80211MgmtSTA::processScanCommand(), IPv6::routePacket(), ARP::sendARPRequest(), IPv6::sendDatagramToOutput(), IPv6NeighbourDiscovery::sendSolicitedNA(), EtherMACFullDuplex::startFrameTransmission(), EtherMAC::startFrameTransmission(), IPv6NeighbourDiscovery::validateNSPacket(), and IPv6NeighbourDiscovery::validateRSPacket().
{ return address == 0; }
bool MACAddress::operator!= (const MACAddress & other) const [inline]
Returns true if the two addresses are not equal.
{ return address != other.address; }
bool MACAddress::operator< (const MACAddress & other) const [inline]
{ return address < other.address; }
MACAddress& MACAddress::operator= (const MACAddress & other) [inline]
Assignment.
{ address = other.address; return *this; }
bool MACAddress::operator== (const MACAddress & other) const [inline]
Returns true if the two addresses are equal.
{ return address == other.address; }
bool MACAddress::operator> (const MACAddress & other) const [inline]
{ return address > other.address; }
void MACAddress::setAddress (const char * hexstr)
Converts address value from hex string (12 hex digits, may also contain spaces, hyphens and colons)
Referenced by Ieee80211MgmtSTASimplified::initialize(), Ieee80211MgmtBase::initialize(), Ieee80211Mac::initialize(), EtherMACBase::initializeMACAddress(), EtherTrafGen::resolveDestMACAddress(), and EtherAppCli::resolveDestMACAddress().
{
    if (!tryParse(hexstr))
        throw cRuntimeError("MACAddress: wrong address syntax '%s': 12 hex digits expected, with optional embedded spaces, hyphens or colons", hexstr);
}
void MACAddress::setAddressByte (unsigned int k, unsigned char addrbyte)
Sets the kth byte of the address.
Referenced by ARP::mapMulticastAddress(), setAddressBytes(), and tryParse().
{
    if (k>=MAC_ADDRESS_SIZE) throw cRuntimeError("Array of size 6 indexed with %d", k);
    int offset = (MAC_ADDRESS_SIZE-k-1)*8;
    address = (address&(~(((uint64)0xff)<<offset)))|(((uint64)addrbyte)<<offset);
}
void MACAddress::setAddressBytes (unsigned char * addrbytes)
Sets address bytes.
The argument should point to an array of 6 unsigned chars.
{
    address = 0; // clear top 16 bits too that setAddressByte() calls skip
    for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
        setAddressByte(i, addrbytes[i]);
}
void MACAddress::setAddressBytes (char * addrbytes) [inline]
Referenced by setAddressBytes().
{ setAddressBytes((unsigned char *)addrbytes); }
void MACAddress::setBroadcast () [inline]
Sets the address to the broadcast address (hex ff:ff:ff:ff:ff:ff).
{ address = MAC_ADDRESS_MASK; }
std::string MACAddress::str () const
Converts address to a hex string.
Referenced by Ieee80211MgmtSTA::handleAssociationResponseFrame(), Ieee80211Mac::initialize(), EtherMACBase::initializeMACAddress(), operator<<(), Ieee80211MgmtSTA::processAssociateCommand(), Ieee80211MgmtSTA::processAuthenticateCommand(), Ieee80211MgmtSTA::processDeauthenticateCommand(), EtherMACFullDuplex::processFrameFromUpperLayer(), EtherMAC::processFrameFromUpperLayer(), IPv6NeighbourDiscovery::processNUDTimeout(), DHCPClient::sendDiscover(), DHCPClient::sendRequest(), Ieee80211MgmtSTA::startAssociation(), and Ieee80211MgmtSTA::startAuthentication().
{
    char buf[20];
    char *s = buf;
    for (int i=0; i<MAC_ADDRESS_SIZE; i++, s += 3)
        sprintf(s, "%2.2X-", getAddressByte(i));
    *(s-1) = '\0';
    return std::string(buf);
}
bool MACAddress::tryParse (const char * hexstr)
Sets the address and returns true if the syntax of the string is correct.
(See setAddress() for the syntax.)
Referenced by EtherTrafGen::resolveDestMACAddress(), EtherAppCli::resolveDestMACAddress(), and setAddress().
{
    if (!hexstr)
        return false;
    // check syntax
    int numHexDigits = 0;
    for (const char *s = hexstr; *s; s++) {
        if (isxdigit(*s))
            numHexDigits++;
        else if (*s!=' ' && *s!=':' && *s!='-')
            return false; // wrong syntax
    }
    if (numHexDigits != 2*MAC_ADDRESS_SIZE)
        return false;
    // Converts hex string into the address
    // if hext string is shorter, address is filled with zeros;
    // Non-hex characters are discarded before conversion.
    address = 0; // clear top 16 bits too that setAddressByte() calls skip
    int k = 0;
    const char *s = hexstr;
    for (int pos=0; pos<MAC_ADDRESS_SIZE; pos++)
    {
        if (!s || !*s)
        {
            setAddressByte(pos, 0);
        }
        else
        {
            while (*s && !isxdigit(*s)) s++;
            if (!*s) {setAddressByte(pos, 0); continue;}
            unsigned char d = isdigit(*s) ? (*s-'0') : islower(*s) ? (*s-'a'+10) : (*s-'A'+10);
            d = d<<4;
            s++;
            while (*s && !isxdigit(*s)) s++;
            if (!*s) {setAddressByte(pos, 0); continue;}
            d += isdigit(*s) ? (*s-'0') : islower(*s) ? (*s-'a'+10) : (*s-'A'+10);
            s++;
            setAddressByte(pos, d);
            k++;
        }
    }
    return true;
}
Member Data Documentation
uint64 MACAddress::address [private]
Referenced by compareTo(), equals(), formInterfaceIdentifier(), getAddressByte(), MACAddress(), operator!=(), operator<(), operator=(), operator==(), operator>(), setAddressByte(), setAddressBytes(), and tryParse().
unsigned int MACAddress::autoAddressCtr [static, private]
Referenced by generateAutoAddress().
const MACAddress MACAddress::BROADCAST_ADDRESS [static]
The broadcast MAC address, ff:ff:ff:ff:ff:ff.
Referenced by IPv6::handleMessageFromHL(), Ieee80211Etx::handleTimer(), initialize(), Batman::initialize(), AODVUU::isBroadcast(), DYMOUM::isBroadcast(), ManetRoutingBase::isMulticastAddress(), ARP::processOutboundPacket(), Ieee80211MgmtSTA::processScanCommand(), IPv6::routeMulticastPacket(), rreq_proactive(), DYMOUM::rreq_proactive(), Ieee80211MgmtAP::sendBeacon(), and ManetRoutingBase::sendToIp().
const MACAddress MACAddress::MULTICAST_PAUSE_ADDRESS [static]
The special multicast PAUSE MAC address, 01:80:C2:00:00:01.
Referenced by EtherMACBase::dropFrameNotForUs(), EtherEncap::handleSendPause(), EtherLLC::handleSendPause(), and MACRelayUnitBase::sendPauseFrame().
const MACAddress MACAddress::UNSPECIFIED_ADDRESS [static]
The unspecified MAC address, 00:00:00:00:00:00.
Referenced by ARP::getDirectAddressResolution(), Ieee80211Etx::handleBwMessage(), Ieee80211Mac::isInterfaceRegistered(), IPv6NeighbourDiscovery::processIPv6Datagram(), and IPv6NeighbourDiscovery::resolveNeighbour().
The documentation for this class was generated from the following files:
MACAddress.h
MACAddress.cc