INET Framework for OMNeT++/OMNEST: IPv6FragBuf Class Reference
IPv6FragBuf Class Reference
Reassembly buffer for fragmented IPv6 datagrams.
#include <IPv6FragBuf.h>
Classes
struct DatagramBuffer
struct Key
Public Member Functions
IPv6FragBuf ()
Ctor.
~IPv6FragBuf ()
Dtor.
void init (ICMPv6 *icmp)
Initialize fragmentation buffer.
IPv6Datagram * addFragment (IPv6Datagram *datagram, IPv6FragmentHeader *fh, simtime_t now)
Takes a fragment and inserts it into the reassembly buffer.
void purgeStaleFragments (simtime_t lastupdate)
Throws out all fragments which are incomplete and their last update (last fragment arrival) was before "lastupdate", and sends ICMP TIME EXCEEDED message about them.
Protected Types
typedef std::map< Key,
DatagramBuffer > Buffers
Protected Attributes
Buffers bufs
ICMPv6 * icmpModule
Detailed Description
Reassembly buffer for fragmented IPv6 datagrams.
Member Typedef Documentation
typedef std::map<Key,DatagramBuffer> IPv6FragBuf::Buffers [protected]
Constructor & Destructor Documentation
IPv6FragBuf::IPv6FragBuf ()
Ctor.
{
    icmpModule = NULL;
}
IPv6FragBuf::~IPv6FragBuf ()
Dtor.
{
}
Member Function Documentation
IPv6Datagram * IPv6FragBuf::addFragment (IPv6Datagram * datagram, IPv6FragmentHeader * fh, simtime_t now)
Takes a fragment and inserts it into the reassembly buffer.
If this fragment completes a datagram, the full reassembled datagram is returned, otherwise NULL.
Referenced by IPv6::localDeliver().
{
    // find datagram buffer
    Key key;
    key.id = fh->getIdentification();
    key.src = datagram->getSrcAddress();
    key.dest = datagram->getDestAddress();
    Buffers::iterator i = bufs.find(key);
    DatagramBuffer *buf = NULL;
    if (i==bufs.end())
    {
        // this is the first fragment of that datagram, create reassembly buffer for it
        buf = &bufs[key];
        buf->datagram = NULL;
        buf->createdAt = now;
    }
    else
    {
        // use existing buffer
        buf = &(i->second);
    }
    int fragmentLength = datagram->calculateFragmentLength();
    unsigned short offset = fh->getFragmentOffset();
    bool moreFragments = fh->getMoreFragments();
    // RFC 2460 4.5:
        // If the length of a fragment, as derived from the fragment packet's
        // Payload Length field, is not a multiple of 8 octets and the M flag
        // of that fragment is 1, then that fragment must be discarded and an
        // ICMP Parameter Problem, Code 0, message should be sent to the
        // source of the fragment, pointing to the Payload Length field of
        // the fragment packet.
    if (moreFragments && (fragmentLength % 8) != 0)
    {
        icmpModule->sendErrorMessage(datagram, ICMPv6_PARAMETER_PROBLEM, ERROREOUS_HDR_FIELD); // TODO set pointer
        return NULL;
    }
    // RFC 2460 4.5:
        // If the length and offset of a fragment are such that the Payload
        // Length of the packet reassembled from that fragment would exceed
        // 65,535 octets, then that fragment must be discarded and an ICMP
        // Parameter Problem, Code 0, message should be sent to the source of
        // the fragment, pointing to the Fragment Offset field of the
        // fragment packet.
    if (offset + fragmentLength > 65535)
    {
        icmpModule->sendErrorMessage(datagram, ICMPv6_PARAMETER_PROBLEM, ERROREOUS_HDR_FIELD); // TODO set pointer
        return NULL;
    }
    // add fragment to buffer
    bool isComplete = buf->buf.addFragment(offset,
                                           offset+fragmentLength,
                                           !moreFragments);
    // Store the first fragment. The first fragment contains the whole
    // encapsulated payload, and extension headers of the
    // original datagram.
    if (offset == 0)
    {
        delete buf->datagram;
        buf->datagram = datagram;
    }
    else
    {
        delete datagram;
    }
    // do we have the complete datagram?
    if (isComplete)
    {
        // datagram complete: deallocate buffer and return complete datagram
        IPv6Datagram *ret = buf->datagram;
        ASSERT(ret);
        ret->removeExtensionHeader(IP_PROT_IPv6EXT_FRAGMENT);
        ret->setByteLength(ret->calculateUnfragmentableHeaderByteLength()+buf->buf.getTotalLength());
        bufs.erase(i);
        return ret;
    }
    else
    {
        // there are still missing fragments
        return NULL;
    }
}
void IPv6FragBuf::init (ICMPv6 * icmp)
Initialize fragmentation buffer.
ICMP module is needed for sending TIME_EXCEEDED ICMP message in purgeStaleFragments().
Referenced by IPv6::initialize().
{
    icmpModule = icmp;
}
void IPv6FragBuf::purgeStaleFragments (simtime_t lastupdate)
Throws out all fragments which are incomplete and their last update (last fragment arrival) was before "lastupdate", and sends ICMP TIME EXCEEDED message about them.
Timeout should be between 60 seconds and 120 seconds (RFC1122). This method should be called more frequently, maybe every 10..30 seconds or so.
Referenced by IPv6::localDeliver().
{
    // this method shouldn't be called too often because iteration on
    // an std::map is *very* slow...
    ASSERT(icmpModule);
    for (Buffers::iterator i=bufs.begin(); i!=bufs.end(); )
    {
        // if too old, remove it
        DatagramBuffer& buf = i->second;
        if (buf.createdAt < lastupdate)
        {
            if (buf.datagram)
            {
                                // send ICMP error
                                EV << "datagram fragment timed out in reassembly buffer, sending ICMP_TIME_EXCEEDED\n";
                                icmpModule->sendErrorMessage(buf.datagram, ICMPv6_TIME_EXCEEDED, 0);
            }
            // delete
            Buffers::iterator oldi = i++;
            bufs.erase(oldi);
        }
        else
        {
            ++i;
        }
    }
}
Member Data Documentation
Buffers IPv6FragBuf::bufs [protected]
Referenced by addFragment(), and purgeStaleFragments().
ICMPv6* IPv6FragBuf::icmpModule [protected]
Referenced by addFragment(), init(), IPv6FragBuf(), and purgeStaleFragments().
The documentation for this class was generated from the following files:
IPv6FragBuf.h
IPv6FragBuf.cc