INET Framework for OMNeT++/OMNEST: BasicModule Class Reference
BasicModule Class Reference
Base class for all simple modules of a host that want to have access to the NotificationBoard module.
#include <BasicModule.h>
Protected Member Functions
virtual cModule * findHost (bool errorIfNotFound=true) const
Function to get a pointer to the host module.
const char * getLogName (int)
Function to get the logging name of id.
virtual void initialize (int)
Basic initialization for all modules.
virtual int numInitStages () const
Divide initialization into two stages.
const char * logName (void) const
Function to get the logging name of the host.
virtual void receiveChangeNotification (int category, const cObject *details)
Called by the NotificationBoard whenever a change of a category occurs to which we have subscribed.
Protected Attributes
bool coreDebug
Debug switch for the core modules.
bool debug
Debug switch for all other modules.
std::string loggingName
Log name of the host module.
Detailed Description
Base class for all simple modules of a host that want to have access to the NotificationBoard module.
The basic module additionally provides a function findHost() which returns a pointer to the host module.
There is no Define_Module() for this class because we use BasicModule only as a base class to derive all other module. There will never be a stand-alone BasicModule module (and that is why there is no Define_Module() and no .ned file for BasicModule).
See also:
NotificationBoard
Author:
Steffen Sroka
Andreas Koepke
Member Function Documentation
cModule * BasicModule::findHost (bool errorIfNotFound = true) const [protected, virtual]
Function to get a pointer to the host module.
Referenced by Radio::changeChannel(), Radio::connectReceiver(), MobilityBase::findVisualRepresentation(), initialize(), and ChannelAccess::initialize().
{
    cModule *mod;
    for (mod = getParentModule(); mod != 0; mod = mod->getParentModule()) {
        cProperties *properties = mod->getProperties();
        if (properties && properties->getAsBool("node"))
            break;
    }
    if (errorIfNotFound && !mod)
        error("findHost(): host module not found (it should have a property named node)");
    return mod;
}
const char * BasicModule::getLogName (int id) [protected]
Function to get the logging name of id.
This function returns the logging name of the module with the specified id.
It can be used for logging messages to simplify debugging in TKEnv.
Only supports ids from simple module derived from the BasicModule or the nic compound module id.
Parameters:
id Id of the module for the desired logging name
Returns:
logging name of module id or NULL if not found
See also:
logName
{
    BasicModule *mod;
    mod = (BasicModule *) simulation.getModule(id);
    if (mod->isSimple())
        return mod->logName();
    else if (mod->getSubmodule("snrEval"))
        return ((BasicModule *) mod->getSubmodule("snrEval"))->logName();
    else if (mod->getSubmodule("phy"))
        return ((BasicModule *) mod->getSubmodule("phy"))->logName();
    else
        return NULL;
};
void BasicModule::initialize (int stage) [protected, virtual]
Basic initialization for all modules.
Subscription to NotificationBoard should be in stage==0, and firing notifications in stage==1 or later.
NOTE: You have to call this in the initialize() function of the inherited class!
Reimplemented in MoBANCoordinator, MobilityBase, ChannelAccess, MoBANLocal, Radio, MovingMobilityBase, Ns2MotionMobility, TurtleMobility, CircleMobility, MassMobility, RectangleMobility, LinearNodeDistributionMobility, GaussMarkovMobility, LineSegmentsMobilityBase, ANSimMobility, ConstSpeedMobility, StaticGridMobility, TractorMobility, BonnMotionMobility, LinearMobility, ChiangMobility, and RandomWPMobility.
{
    cModule *host = findHost(false);
    if (stage == 0)
    {
        if (hasPar("coreDebug"))
            coreDebug = par("coreDebug").boolValue();
        else
            coreDebug = false;
        if (hasPar("debug"))
            debug = par("debug").boolValue();
        else
            debug = false;
        if (host) {
            // get the logging name of the host
            if (host->hasPar("logName"))
                loggingName = host->par("logName").stringValue();
            else
                loggingName = host->getName();
            char tmp[8];
            sprintf(&tmp[0], "[%d]", host->getIndex());
            loggingName += tmp;
        }
    }
}
const char* BasicModule::logName (void) const [inline, protected]
Function to get the logging name of the host.
The logging name is the ned module name of the host (unless the host ned variable loggingName is specified). It can be used for logging messages to simplify debugging in TKEnv.
Referenced by getLogName().
    {
      return loggingName.c_str();
    };
virtual int BasicModule::numInitStages () const [inline, protected, virtual]
Divide initialization into two stages.
In the first stage (stage==0), modules subscribe to notification categories at NotificationBoard. The first notifications (e.g. about the initial values of some variables such as RadioState) should take place earliest in the second stage (stage==1), when everyone interested in them has already subscribed.
Reimplemented in ChannelAccess, MobilityBase, and MovingMobilityBase.
{return 2;}
virtual void BasicModule::receiveChangeNotification (int category, const cObject * details) [inline, protected, virtual]
Called by the NotificationBoard whenever a change of a category occurs to which we have subscribed.
Redefined from INotifiable.
Implements INotifiable.
{}
Member Data Documentation
bool BasicModule::coreDebug [protected]
Debug switch for the core modules.
Referenced by initialize().
bool BasicModule::debug [protected]
Debug switch for all other modules.
Referenced by initialize().
std::string BasicModule::loggingName [protected]
Log name of the host module.
Referenced by initialize().
The documentation for this class was generated from the following files:
BasicModule.h
BasicModule.cc