INET Framework for OMNeT++/OMNEST: TCPSpoof Class Reference
TCPSpoof Class Reference
Sends fabricated TCP packets.
#include <TCPSpoof.h>
Protected Member Functions
virtual void sendToIP (TCPSegment *tcpseg, IPvXAddress src, IPvXAddress dest)
virtual unsigned long chooseInitialSeqNum ()
virtual void sendSpoofPacket ()
virtual void initialize ()
virtual void handleMessage (cMessage *msg)
Static Protected Attributes
static simsignal_t sentPkSignal = SIMSIGNAL_NULL
Detailed Description
Sends fabricated TCP packets.
Member Function Documentation
unsigned long TCPSpoof::chooseInitialSeqNum () [protected, virtual]
Referenced by sendSpoofPacket().
{
    // choose an initial send sequence number in the same way as TCP does
    return (unsigned long)SIMTIME_DBL(fmod(simTime()*250000.0, 1.0+(double)(unsigned)0xffffffffUL)) & 0xffffffffUL;
}
void TCPSpoof::handleMessage (cMessage * msg) [protected, virtual]
{
    if (!msg->isSelfMessage())
        error("Does not process incoming messages");
    sendSpoofPacket();
    delete msg;
}
void TCPSpoof::initialize () [protected, virtual]
{
    sentPkSignal = registerSignal("sentPk");
    simtime_t t = par("t").doubleValue();
    scheduleAt(t, new cMessage("timer"));
}
void TCPSpoof::sendSpoofPacket () [protected, virtual]
Referenced by handleMessage().
{
    TCPSegment *tcpseg = new TCPSegment("spoof");
    IPvXAddress srcAddr = IPvXAddressResolver().resolve(par("srcAddress"));
    IPvXAddress destAddr = IPvXAddressResolver().resolve(par("destAddress"));
    int srcPort = par("srcPort");
    int destPort = par("destPort");
    bool isSYN = par("isSYN");
    unsigned long seq = par("seqNo").longValue()==-1 ? chooseInitialSeqNum() : par("seqNo").longValue();
    // one can customize the following according to concrete needs
    tcpseg->setSrcPort(srcPort);
    tcpseg->setDestPort(destPort);
    tcpseg->setByteLength(TCP_HEADER_OCTETS);
    tcpseg->setSequenceNo(seq);
    //tcpseg->setAckNo(...);
    tcpseg->setSynBit(isSYN);
    tcpseg->setWindow(16384);
    sendToIP(tcpseg, srcAddr, destAddr);
}
void TCPSpoof::sendToIP (TCPSegment * tcpseg, IPvXAddress src, IPvXAddress dest) [protected, virtual]
Referenced by sendSpoofPacket().
{
    EV << "Sending: ";
    //printSegmentBrief(tcpseg);
    if (!dest.isIPv6())
    {
        // send over IPv4
        IPv4ControlInfo *controlInfo = new IPv4ControlInfo();
        controlInfo->setProtocol(IP_PROT_TCP);
        controlInfo->setSrcAddr(src.get4());
        controlInfo->setDestAddr(dest.get4());
        tcpseg->setControlInfo(controlInfo);
        emit(sentPkSignal, tcpseg);
        send(tcpseg, "ipv4Out");
    }
    else
    {
        // send over IPv6
        IPv6ControlInfo *controlInfo = new IPv6ControlInfo();
        controlInfo->setProtocol(IP_PROT_TCP);
        controlInfo->setSrcAddr(src.get6());
        controlInfo->setDestAddr(dest.get6());
        tcpseg->setControlInfo(controlInfo);
        emit(sentPkSignal, tcpseg);
        send(tcpseg, "ipv6Out");
    }
}
Member Data Documentation
simsignal_t TCPSpoof::sentPkSignal = SIMSIGNAL_NULL [static, protected]
Referenced by initialize(), and sendToIP().
The documentation for this class was generated from the following files:
TCPSpoof.h
TCPSpoof.cc