INET Framework for OMNeT++/OMNEST: RSVPPathMsg Class Reference
RSVPPathMsg Class Reference
RSVP PATH message.
#include <RSVPPathMsg.h>
Public Member Functions
RSVPPathMsg (const char *name=NULL, int kind=PATH_MESSAGE)
RSVPPathMsg (const RSVPPathMsg &other)
RSVPPathMsg & operator= (const RSVPPathMsg &other)
virtual RSVPPathMsg * dup () const
IPv4Address getSrcAddress ()
int getLspId ()
IPv4Address getNHOP ()
IPv4Address getLIH ()
double getBW ()
SenderTemplateObj_t & getSenderTemplate ()
void setSenderTemplate (const SenderTemplateObj_t &s)
SenderTspecObj_t & getSenderTspec ()
void setSenderTspec (const SenderTspecObj_t &s)
Detailed Description
RSVP PATH message.
This class adds convenience get() and set() methods to the generated base class, but no extra data.
Constructor & Destructor Documentation
RSVPPathMsg::RSVPPathMsg (const char * name = NULL, int kind = PATH_MESSAGE) [inline]
Referenced by dup().
: RSVPPathMsg_Base(name, kind) {}
RSVPPathMsg::RSVPPathMsg (const RSVPPathMsg & other) [inline]
: RSVPPathMsg_Base(other) {}
Member Function Documentation
virtual RSVPPathMsg* RSVPPathMsg::dup () const [inline, virtual]
Reimplemented from RSVPPathMsg_Base.
{return new RSVPPathMsg(*this);}
double RSVPPathMsg::getBW () [inline]
{return getSender_descriptor().Sender_Tspec_Object.req_bandwidth;}
IPv4Address RSVPPathMsg::getLIH () [inline]
{return getHop().Logical_Interface_Handle;}
int RSVPPathMsg::getLspId () [inline]
Referenced by RSVP::print().
{return getSender_descriptor().Sender_Template_Object.Lsp_Id;}
IPv4Address RSVPPathMsg::getNHOP () [inline]
Referenced by RSVP::createPSB(), and RSVP::processPathMsg().
{return getHop().Next_Hop_Address;}
SenderTemplateObj_t& RSVPPathMsg::getSenderTemplate () [inline]
Referenced by RSVP::createPSB(), and RSVP::processPathMsg().
{return getSender_descriptor().Sender_Template_Object;}
SenderTspecObj_t& RSVPPathMsg::getSenderTspec () [inline]
Referenced by RSVP::createPSB(), and RSVP::processPathMsg().
{return getSender_descriptor().Sender_Tspec_Object;}
IPv4Address RSVPPathMsg::getSrcAddress () [inline]
{return getSender_descriptor().Sender_Template_Object.SrcAddress;}
RSVPPathMsg& RSVPPathMsg::operator= (const RSVPPathMsg & other) [inline]
{RSVPPathMsg_Base::operator=(other); return *this;}
void RSVPPathMsg::setSenderTemplate (const SenderTemplateObj_t & s) [inline]
{getSender_descriptor().Sender_Template_Object = s;}
void RSVPPathMsg::setSenderTspec (const SenderTspecObj_t & s) [inline]
{getSender_descriptor().Sender_Tspec_Object = s;}
The documentation for this class was generated from the following file:
RSVPPathMsg.h