INET Framework for OMNeT++/OMNEST: OSPF::RoutingInfo Class Reference
OSPF::RoutingInfo Class Reference
#include <LSA.h>
Public Member Functions
RoutingInfo ()
RoutingInfo (const RoutingInfo &routingInfo)
virtual ~RoutingInfo ()
void addNextHop (NextHop nextHop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
void setDistance (unsigned long d)
unsigned long getDistance () const
void setParent (OSPFLSA *p)
OSPFLSA * getParent () const
Private Attributes
std::vector< NextHop > nextHops
unsigned long distance
OSPFLSA * parent
Constructor & Destructor Documentation
OSPF::RoutingInfo::RoutingInfo () [inline]
: distance(0), parent(NULL) {}
OSPF::RoutingInfo::RoutingInfo (const RoutingInfo & routingInfo) [inline]
: nextHops(routingInfo.nextHops), distance(routingInfo.distance), parent(routingInfo.parent) {}
virtual OSPF::RoutingInfo::~RoutingInfo () [inline, virtual]
{}
Member Function Documentation
void OSPF::RoutingInfo::addNextHop (NextHop nextHop) [inline]
Referenced by OSPF::Area::calculateShortestPathTree().
{ nextHops.push_back(nextHop); }
void OSPF::RoutingInfo::clearNextHops () [inline]
Referenced by OSPF::Area::calculateShortestPathTree(), OSPF::RouterLSA::update(), OSPF::NetworkLSA::update(), OSPF::SummaryLSA::update(), and OSPF::ASExternalLSA::update().
{ nextHops.clear(); }
unsigned long OSPF::RoutingInfo::getDistance () const [inline]
Referenced by OSPF::Area::calculateShortestPathTree().
{ return distance; }
NextHop OSPF::RoutingInfo::getNextHop (unsigned int index) const [inline]
Referenced by OSPF::Area::calculateNextHops(), and OSPF::Area::calculateShortestPathTree().
{ return nextHops[index]; }
unsigned int OSPF::RoutingInfo::getNextHopCount () const [inline]
Referenced by OSPF::Area::calculateNextHops(), and OSPF::Area::calculateShortestPathTree().
{ return nextHops.size(); }
OSPFLSA* OSPF::RoutingInfo::getParent () const [inline]
Referenced by OSPF::Area::calculateNextHops(), and OSPF::Router::isDestinationUnreachable().
{ return parent; }
void OSPF::RoutingInfo::setDistance (unsigned long d) [inline]
Referenced by OSPF::Area::calculateShortestPathTree().
{ distance = d; }
void OSPF::RoutingInfo::setParent (OSPFLSA * p) [inline]
Referenced by OSPF::Area::calculateShortestPathTree().
{ parent = p; }
Member Data Documentation
unsigned long OSPF::RoutingInfo::distance [private]
Referenced by getDistance(), and setDistance().
std::vector<NextHop> OSPF::RoutingInfo::nextHops [private]
Referenced by addNextHop(), clearNextHops(), getNextHop(), and getNextHopCount().
OSPFLSA* OSPF::RoutingInfo::parent [private]
Referenced by getParent(), and setParent().
The documentation for this class was generated from the following file:
LSA.h