INET Framework for OMNeT++/OMNEST: IInterfaceTable Class Reference
IInterfaceTable Class Reference
A C++ interface to abstract the functionality of InterfaceTable.
#include <IInterfaceTable.h>
Public Member Functions
virtual ~IInterfaceTable ()
virtual std::string getFullPath () const =0
Module path name.
virtual cModule * getHostModule ()=0
Returns the host or router this interface table lives in.
virtual void addInterface (InterfaceEntry *entry)=0
Adds an interface.
virtual void deleteInterface (InterfaceEntry *entry)=0
Deletes the given interface from the table.
virtual int getNumInterfaces ()=0
Returns the number of interfaces.
virtual InterfaceEntry * getInterface (int pos)=0
Returns the InterfaceEntry specified by an index 0..numInterfaces-1.
virtual InterfaceEntry * getInterfaceById (int id)=0
Returns an interface by its Id.
virtual InterfaceEntry * getInterfaceByNodeOutputGateId (int id)=0
Returns an interface given by its getNodeOutputGateId().
virtual InterfaceEntry * getInterfaceByNodeInputGateId (int id)=0
Returns an interface given by its getNodeInputGateId().
virtual InterfaceEntry * getInterfaceByNetworkLayerGateIndex (int index)=0
Returns an interface given by its getNetworkLayerGateIndex().
virtual InterfaceEntry * getInterfaceByInterfaceModule (cModule *ifmod)=0
Returns an interface by one of its component module (e.g.
virtual InterfaceEntry * getInterfaceByName (const char *name)=0
Returns an interface given by its name.
virtual InterfaceEntry * getFirstLoopbackInterface ()=0
Returns the first interface with the isLoopback flag set.
virtual InterfaceEntry * getFirstMulticastInterface ()=0
Returns the first multicast capable interface.
Protected Member Functions
virtual void interfaceChanged (InterfaceEntry *entry, int category)=0
Friends
class InterfaceEntry
Detailed Description
A C++ interface to abstract the functionality of InterfaceTable.
Referring to InterfaceTable via this interface makes it possible to transparently replace InterfaceTable with a different implementation, without any change to the base INET.
See also:
InterfaceTable, InterfaceEntry
Constructor & Destructor Documentation
virtual IInterfaceTable::~IInterfaceTable () [inline, virtual]
{}
Member Function Documentation
virtual void IInterfaceTable::addInterface (InterfaceEntry * entry) [pure virtual]
Adds an interface.
The entry->getInterfaceModule() will be used to discover and fill in getNetworkLayerGateIndex(), getNodeOutputGateId(), and getNodeInputGateId() in InterfaceEntry. It should be NULL if this is a virtual interface (e.g. loopback).
Implemented in InterfaceTable.
Referenced by ExtInterface::registerInterface(), PPP::registerInterface(), EtherMACBase::registerInterface(), and Ieee80211Mac::registerInterface().
virtual void IInterfaceTable::deleteInterface (InterfaceEntry * entry) [pure virtual]
Deletes the given interface from the table.
Indices of existing interfaces (see getInterface(int)) may change. It is an error if the given interface is not in the table.
Implemented in InterfaceTable.
virtual InterfaceEntry* IInterfaceTable::getFirstLoopbackInterface () [pure virtual]
Returns the first interface with the isLoopback flag set.
(If there's no loopback, it returns NULL -- but this should never happen because InterfaceTable itself registers a loopback interface on startup.)
Implemented in InterfaceTable.
Referenced by RoutingTable::configureLoopbackForIPv4(), RoutingTable::configureRouterId(), and IPv4::handleMessageFromHL().
virtual InterfaceEntry* IInterfaceTable::getFirstMulticastInterface () [pure virtual]
Returns the first multicast capable interface.
If there is no such interface, then returns NULL.
Implemented in InterfaceTable.
Referenced by IPv4::determineOutgoingInterfaceForMulticastDatagram().
virtual std::string IInterfaceTable::getFullPath () const [pure virtual]
Module path name.
Implemented in InterfaceTable.
Referenced by FlatNetworkConfigurator::fillRoutingTables(), IPvXAddressResolver::getIPv4AddressFrom(), and IPvXAddressResolver::getIPv6AddressFrom().
virtual cModule* IInterfaceTable::getHostModule () [pure virtual]
Returns the host or router this interface table lives in.
Implemented in InterfaceTable.
Referenced by IPv4NetworkConfigurator::addMulticastGroups(), IPv4NetworkConfigurator::findInterfaceOnLinkByNode(), InterfaceEntry::getFullPath(), OSPFRouting::getInterfaceByXMLAttributesOf(), IPv4NetworkConfigurator::getWirelessId(), IPv4NetworkConfigurator::linkContainsMatchingHostExcept(), IPv4NetworkConfigurator::InterfaceMatcher::matches(), and IPv4NetworkConfigurator::readAddressConfiguration().
virtual InterfaceEntry* IInterfaceTable::getInterface (int pos) [pure virtual]
Returns the InterfaceEntry specified by an index 0..numInterfaces-1.
Throws an error if index is out of range.
Note that this index is NOT the same as interfaceId! Indices are not guaranteed to stay the same after interface addition/deletion, so cannot be used to reliably identify the interface. Use interfaceId to refer to interfaces from other modules or from messages/packets.
Implemented in InterfaceTable.
Referenced by FlatNetworkConfigurator::addDefaultRoutes(), FlatNetworkConfigurator6::addOwnAdvPrefixRoutes(), IPvXAddressResolver::addressOf(), FlatNetworkConfigurator6::addStaticRoutes(), IPv4NetworkConfigurator::addStaticRoutes(), FlatNetworkConfigurator::assignAddresses(), IPv6NeighbourDiscovery::assignLinkLocalAddress(), FlatNetworkConfigurator6::configureAdvPrefixes(), RoutingTable::configureRouterId(), IPv4NetworkConfigurator::determineGatewayForLink(), IPv4NetworkConfigurator::extractWiredTopology(), IPv4NetworkConfigurator::extractWirelessTopology(), RoutingTable::findInterfaceByLocalBroadcastAddress(), IPv4NetworkConfigurator::findInterfaceOnLinkByNodeAddress(), BGPRouting::findMyAS(), RoutingTable::gatherAddresses(), PingTestApp::getAllAddresses(), RoutingTable::getInterfaceByAddress(), RoutingTable6::getInterfaceByAddress(), OSPFRouting::getInterfaceByXMLAttributesOf(), IPvXAddressResolver::getIPv4AddressFrom(), IPvXAddressResolver::getIPv6AddressFrom(), TED::initialize(), DSDV_2::initialize(), ARP::initialize(), Ieee80211Etx::initialize(), RoutingTable::initialize(), RoutingTable6::initialize(), IPv6NeighbourDiscovery::initialize(), IGMPv2::initialize(), LDP::initialize(), DSRUU::initialize(), BGPRouting::isInInterfaceTable(), RoutingTable::isLocalAddress(), RoutingTable6::isLocalAddress(), ManetRoutingBase::isLocalAddress(), RoutingTable::isLocalBroadcastAddress(), RoutingTable::isLocalMulticastAddress(), UDPSocket::joinLocalMulticastGroups(), UDP::joinMulticastGroups(), UDPSocket::leaveLocalMulticastGroups(), SCTPAssociation::processInitArrived(), LDP::rebuildFecList(), ManetRoutingBase::registerRoutingModule(), IPv4::routeLocalBroadcastPacket(), IPv6::routeMulticastPacket(), ManetRoutingBase::sendICMP(), SCTPAssociation::sendInit(), and RoutingTable::updateNetmaskRoutes().
virtual InterfaceEntry* IInterfaceTable::getInterfaceById (int id) [pure virtual]
Returns an interface by its Id.
Ids are guaranteed to be invariant to interface deletions/additions. Returns NULL if there is no such interface (This allows detecting stale IDs without raising an error.)
Implemented in InterfaceTable.
Referenced by OSPF::Router::addExternalRouteInIPTable(), OSPF::RoutingTableEntry::addNextHop(), xMIPv6::cancelEntries(), IPv6Tunneling::decapsulateDatagram(), IPv6::handleMessageFromHL(), IPv4::handleMessageFromHL(), IPv6NeighbourDiscovery::initiateAddressResolution(), IPv6NeighbourDiscovery::initiateNeighbourUnreachabilityDetection(), UDP::joinMulticastGroups(), OSPFRouting::joinMulticastGroups(), ARP::processARPPacket(), IPv6NeighbourDiscovery::processARTimeout(), xMIPv6::processBAMessage(), xMIPv6::processBRRMessage(), xMIPv6::processBUMessage(), xMIPv6::processCoTMessage(), IPv6NeighbourDiscovery::processDADTimeout(), ICMPv6::processEchoRequest(), xMIPv6::processHoTMessage(), IGMPv2::processIgmpMessage(), IPv6NeighbourDiscovery::processIPv6Datagram(), LDP::processLDPHello(), IPv6NeighbourDiscovery::processNAForIncompleteNCEState(), IPv6NeighbourDiscovery::processNAForOtherNCEStates(), IPv6NeighbourDiscovery::processNAPacket(), IPv6NeighbourDiscovery::processNSPacket(), IPv6NeighbourDiscovery::processNUDTimeout(), ARP::processOutboundPacket(), IPv6NeighbourDiscovery::processRAForRouterUpdates(), IPv6NeighbourDiscovery::processRAPacket(), IPv6NeighbourDiscovery::processRSPacket(), IPv6::routePacket(), OSPF::Interface::setIfIndex(), xMIPv6::validateBAck(), and xMIPv6::validateCoTMessage().
virtual InterfaceEntry* IInterfaceTable::getInterfaceByInterfaceModule (cModule * ifmod) [pure virtual]
Returns an interface by one of its component module (e.g.
PPP). Returns NULL if not found.
Implemented in InterfaceTable.
Referenced by DiffservUtil::getInterfaceDatarate().
virtual InterfaceEntry* IInterfaceTable::getInterfaceByName (const char * name) [pure virtual]
Returns an interface given by its name.
Returns NULL if not found.
Implemented in InterfaceTable.
Referenced by IPv4NetworkConfigurator::addManualMulticastRoutes(), IPvXAddressResolver::addressOf(), LDP::findPeerAddrFromInterface(), OSPFRouting::getInterfaceByXMLAttributesOf(), DHCPServer::initialize(), LinkStateRouting::initialize(), DHCPClient::initialize(), Ieee80211Mac::isInterfaceRegistered(), RoutingTableParser::parseInterfaces(), RoutingTableParser::parseRouting(), RoutingTable6::parseXMLConfigFile(), MPLS::processMPLSPacketFromL2(), IPv4NetworkConfigurator::resolveInterfaceAndGateway(), OSPFRouting::resolveInterfaceName(), UDPBasicApp::setSocketOptions(), RSVP::setupHello(), HostAutoConfigurator::setupNetworkLayer(), and MPLS::tryLabelAndForwardIPv4Datagram().
virtual InterfaceEntry* IInterfaceTable::getInterfaceByNetworkLayerGateIndex (int index) [pure virtual]
Returns an interface given by its getNetworkLayerGateIndex().
Returns NULL if not found.
Implemented in InterfaceTable.
Referenced by IPv4::getSourceInterfaceFrom(), IPv6::getSourceInterfaceFrom(), and MPLS::processMPLSPacketFromL2().
virtual InterfaceEntry* IInterfaceTable::getInterfaceByNodeInputGateId (int id) [pure virtual]
Returns an interface given by its getNodeInputGateId().
Returns NULL if not found.
Implemented in InterfaceTable.
Referenced by FlatNetworkConfigurator6::addStaticRoutes(), IPv4NetworkConfigurator::extractWiredNeighbors(), IPv4NetworkConfigurator::extractWiredTopology(), and TED::initialize().
virtual InterfaceEntry* IInterfaceTable::getInterfaceByNodeOutputGateId (int id) [pure virtual]
Returns an interface given by its getNodeOutputGateId().
Returns NULL if not found.
Implemented in InterfaceTable.
Referenced by FlatNetworkConfigurator6::addStaticRoutes(), IPv4NetworkConfigurator::extractWiredTopology(), and FlatNetworkConfigurator::fillRoutingTables().
virtual int IInterfaceTable::getNumInterfaces () [pure virtual]
Returns the number of interfaces.
Implemented in InterfaceTable.
Referenced by FlatNetworkConfigurator::addDefaultRoutes(), FlatNetworkConfigurator6::addOwnAdvPrefixRoutes(), IPvXAddressResolver::addressOf(), FlatNetworkConfigurator6::addStaticRoutes(), IPv4NetworkConfigurator::addStaticRoutes(), FlatNetworkConfigurator::assignAddresses(), IPv6NeighbourDiscovery::assignLinkLocalAddress(), FlatNetworkConfigurator6::configureAdvPrefixes(), RoutingTable::configureRouterId(), IPv6Tunneling::createTunnel(), IPv4NetworkConfigurator::determineGatewayForLink(), IPv4NetworkConfigurator::extractWiredTopology(), IPv4NetworkConfigurator::extractWirelessTopology(), RoutingTable::findInterfaceByLocalBroadcastAddress(), IPv4NetworkConfigurator::findInterfaceOnLinkByNodeAddress(), BGPRouting::findMyAS(), RoutingTable::gatherAddresses(), PingTestApp::getAllAddresses(), RoutingTable::getInterfaceByAddress(), RoutingTable6::getInterfaceByAddress(), OSPFRouting::getInterfaceByXMLAttributesOf(), IPvXAddressResolver::getIPv4AddressFrom(), IPvXAddressResolver::getIPv6AddressFrom(), IPv6::handleMessageFromHL(), IPv4::handleMessageFromHL(), TED::initialize(), DSDV_2::initialize(), ARP::initialize(), Ieee80211Etx::initialize(), RoutingTable::initialize(), RoutingTable6::initialize(), IPv6NeighbourDiscovery::initialize(), IGMPv2::initialize(), LDP::initialize(), DSRUU::initialize(), BGPRouting::isInInterfaceTable(), RoutingTable::isLocalAddress(), RoutingTable6::isLocalAddress(), ManetRoutingBase::isLocalAddress(), RoutingTable::isLocalBroadcastAddress(), RoutingTable::isLocalMulticastAddress(), UDPSocket::joinLocalMulticastGroups(), UDP::joinMulticastGroups(), UDPSocket::leaveLocalMulticastGroups(), SCTPAssociation::processInitArrived(), LDP::rebuildFecList(), ManetRoutingBase::registerRoutingModule(), IPv4::routeLocalBroadcastPacket(), IPv6::routeMulticastPacket(), IPv6::routePacket(), SCTPAssociation::sendInit(), xMIPv6::triggerRouteOptimization(), and RoutingTable::updateNetmaskRoutes().
virtual void IInterfaceTable::interfaceChanged (InterfaceEntry * entry, int category) [protected, pure virtual]
Implemented in InterfaceTable.
Referenced by InterfaceEntry::changed().
Friends And Related Function Documentation
friend class InterfaceEntry [friend]
Referenced by InterfaceTable::initialize().
The documentation for this class was generated from the following file:
IInterfaceTable.h