INET Framework for OMNeT++/OMNEST: Ieee80211MgmtAPBase Class Reference
Ieee80211MgmtAPBase Class Reference
Used in 802.11 infrastructure mode: abstract base class for management frame handling for access points (APs).
#include <Ieee80211MgmtAPBase.h>
Public Types
enum EncapDecap { ENCAP_DECAP_TRUE = 1, ENCAP_DECAP_FALSE, ENCAP_DECAP_ETH }
Protected Member Functions
virtual int numInitStages () const
virtual void initialize (int)
virtual void distributeReceivedDataFrame (Ieee80211DataFrame *frame)
Utility function for APs: sends back a data frame we received from a STA to the wireless LAN, after tweaking fromDS/toDS bits and shuffling addresses as needed.
virtual Ieee80211DataFrame * encapsulate (cPacket *msg)
Utility function for handleUpperMessage()
virtual Ieee80211DataFrame * convertFromEtherFrame (EtherFrame *ethframe)
Utility function: converts EtherFrame to Ieee80211Frame.
virtual EtherFrame * convertToEtherFrame (Ieee80211DataFrame *frame)
Utility function: converts Ieee80211Frame to EtherFrame.
virtual void sendToUpperLayer (Ieee80211DataFrame *frame)
Utility function: send a frame to upperLayerOut.
Protected Attributes
bool isConnectedToHL
EncapDecap encapDecap
Detailed Description
Used in 802.11 infrastructure mode: abstract base class for management frame handling for access points (APs).
This class extends Ieee80211MgmtBase with utility functions that are useful for implementing AP functionality.
Author:
Andras Varga
Member Enumeration Documentation
enum Ieee80211MgmtAPBase::EncapDecap
Enumerator:
ENCAP_DECAP_TRUE
ENCAP_DECAP_FALSE
ENCAP_DECAP_ETH
{ ENCAP_DECAP_TRUE = 1, ENCAP_DECAP_FALSE, ENCAP_DECAP_ETH} EncapDecap;
Member Function Documentation
Ieee80211DataFrame * Ieee80211MgmtAPBase::convertFromEtherFrame (EtherFrame * ethframe) [protected, virtual]
Utility function: converts EtherFrame to Ieee80211Frame.
This is needed because MACRelayUnit which we use for LAN bridging functionality deals with EtherFrames.
Referenced by encapsulate().
{
#ifdef WITH_ETHERNET
    // create new frame
    Ieee80211DataFrameWithSNAP *frame = new Ieee80211DataFrameWithSNAP(ethframe->getName());
    frame->setFromDS(true);
    // copy addresses from ethernet frame (transmitter addr will be set to our addr by MAC)
    frame->setReceiverAddress(ethframe->getDest());
    frame->setAddress3(ethframe->getSrc());
    // copy EtherType from original frame
    if (dynamic_cast<EthernetIIFrame *>(ethframe))
        frame->setEtherType(((EthernetIIFrame *) ethframe)->getEtherType());
    else if (dynamic_cast<EtherFrameWithSNAP *>(ethframe))
        frame->setEtherType(((EtherFrameWithSNAP *) ethframe)->getLocalcode());
    else
        error("Unaccepted EtherFrame type: %s, contains no EtherType", ethframe->getClassName());
    // encapsulate payload
    cPacket *payload = ethframe->decapsulate();
    if (!payload)
        error("received empty EtherFrame from upper layer");
    frame->encapsulate(payload);
    delete ethframe;
    // done
    return frame;
#else
    throw cRuntimeError("INET compiled without ETHERNET feature!");
#endif
}
EtherFrame * Ieee80211MgmtAPBase::convertToEtherFrame (Ieee80211DataFrame * frame) [protected, virtual]
Utility function: converts Ieee80211Frame to EtherFrame.
This is needed because MACRelayUnit which we use for LAN bridging functionality deals with EtherFrames.
Referenced by sendToUpperLayer().
{
#ifdef WITH_ETHERNET
    Ieee80211DataFrameWithSNAP *frame = check_and_cast<Ieee80211DataFrameWithSNAP *>(frame_);
    // create a matching ethernet frame
    EthernetIIFrame *ethframe = new EthernetIIFrame(frame->getName()); //TODO option to use EtherFrameWithSNAP instead
    ethframe->setDest(frame->getAddress3());
    ethframe->setSrc(frame->getTransmitterAddress());
    ethframe->setEtherType(frame->getEtherType());
    // encapsulate the payload in there
    cPacket *payload = frame->decapsulate();
    delete frame;
    ASSERT(payload!=NULL);
    ethframe->encapsulate(payload);
    if (ethframe->getByteLength() < MIN_ETHERNET_FRAME_BYTES)
        ethframe->setByteLength(MIN_ETHERNET_FRAME_BYTES);
    // done
    return ethframe;
#else
    throw cRuntimeError("INET compiled without ETHERNET feature!");
#endif
}
void Ieee80211MgmtAPBase::distributeReceivedDataFrame (Ieee80211DataFrame * frame) [protected, virtual]
Utility function for APs: sends back a data frame we received from a STA to the wireless LAN, after tweaking fromDS/toDS bits and shuffling addresses as needed.
Referenced by Ieee80211MgmtAPSimplified::handleDataFrame(), and Ieee80211MgmtAP::handleDataFrame().
{
    // adjust toDS/fromDS bits, and shuffle addresses
    frame->setToDS(false);
    frame->setFromDS(true);
    // move destination address to address1 (receiver address),
    // and fill address3 with original source address;
    // sender address (address2) will be filled in by MAC
    ASSERT(!frame->getAddress3().isUnspecified());
    frame->setReceiverAddress(frame->getAddress3());
    frame->setAddress3(frame->getTransmitterAddress());
    sendOrEnqueue(frame);
}
Ieee80211DataFrame * Ieee80211MgmtAPBase::encapsulate (cPacket * msg) [protected, virtual]
Utility function for handleUpperMessage()
Referenced by Ieee80211MgmtAPSimplified::handleUpperMessage(), and Ieee80211MgmtAP::handleUpperMessage().
{
    switch (encapDecap)
    {
        case ENCAP_DECAP_ETH:
#ifdef WITH_ETHERNET
            return convertFromEtherFrame(check_and_cast<EtherFrame *>(msg));
#else
            throw cRuntimeError("INET compiled without ETHERNET feature, but the 'encapDecap' parameter is set to 'eth'!");
#endif
            break;
        case ENCAP_DECAP_TRUE:
            {
                Ieee802Ctrl* ctrl = check_and_cast<Ieee802Ctrl*>(msg->removeControlInfo());
                Ieee80211DataFrameWithSNAP *frame = new Ieee80211DataFrameWithSNAP(msg->getName());
                frame->setFromDS(true);
                // copy addresses from ethernet frame (transmitter addr will be set to our addr by MAC)
                frame->setAddress3(ctrl->getSrc());
                frame->setReceiverAddress(ctrl->getDest());
                frame->setEtherType(ctrl->getEtherType());
                delete ctrl;
                // encapsulate payload
                frame->encapsulate(msg);
                return frame;
            }
            break;
        case ENCAP_DECAP_FALSE:
            return check_and_cast<Ieee80211DataFrame *>(msg);
            break;
        default:
            throw cRuntimeError("Unknown encapDecap value: %d", encapDecap);
            break;
    }
    return NULL;
}
void Ieee80211MgmtAPBase::initialize (int stage) [protected, virtual]
Reimplemented from Ieee80211MgmtBase.
Reimplemented in Ieee80211MgmtAP, and Ieee80211MgmtAPSimplified.
{
    Ieee80211MgmtBase::initialize(stage);
    if (stage == 0)
    {
        isConnectedToHL = gate("upperLayerOut")->getPathEndGate()->isConnected();
        const char * encDec = par("encapDecap").stringValue();
        if (!strcmp(encDec, "true"))
            encapDecap = ENCAP_DECAP_TRUE;
        else if (!strcmp(encDec, "false"))
            encapDecap = ENCAP_DECAP_FALSE;
        else if (!strcmp(encDec, "eth"))
            encapDecap = ENCAP_DECAP_ETH;
        else
            throw cRuntimeError("Unknown encapDecap parameter value: '%s'! Must be 'true','false' or 'eth'.", encDec);
        WATCH(isConnectedToHL);
    }
}
virtual int Ieee80211MgmtAPBase::numInitStages () const [inline, protected, virtual]
Reimplemented from Ieee80211MgmtBase.
Reimplemented in Ieee80211MgmtAP, and Ieee80211MgmtAPSimplified.
{return 2;}
void Ieee80211MgmtAPBase::sendToUpperLayer (Ieee80211DataFrame * frame) [protected, virtual]
Utility function: send a frame to upperLayerOut.
If convertToEtherFrameFlag is true, converts the given frame to EtherFrame, deleting the original frame, and send the converted frame. This function is needed for LAN bridging functionality: MACRelayUnit deals with EtherFrames.
Referenced by Ieee80211MgmtAPSimplified::handleDataFrame(), and Ieee80211MgmtAP::handleDataFrame().
{
    if (!isConnectedToHL)
    {
        delete frame;
        return;
    }
    cPacket *outFrame = NULL;
    switch (encapDecap)
    {
        case ENCAP_DECAP_ETH:
#ifdef WITH_ETHERNET
            outFrame = convertToEtherFrame(frame);
#else
            throw cRuntimeError("INET compiled without ETHERNET feature, but the 'encapDecap' parameter is set to 'eth'!");
#endif
            break;
        case ENCAP_DECAP_TRUE:
            {
                cPacket* payload = frame->decapsulate();
                Ieee802Ctrl *ctrl = new Ieee802Ctrl();
                ctrl->setSrc(frame->getTransmitterAddress());
                ctrl->setDest(frame->getAddress3());
                Ieee80211DataFrameWithSNAP *frameWithSNAP = dynamic_cast<Ieee80211DataFrameWithSNAP *>(frame);
                if (frameWithSNAP)
                    ctrl->setEtherType(frameWithSNAP->getEtherType());
                payload->setControlInfo(ctrl);
                delete frame;
                outFrame = payload;
            }
            break;
        case ENCAP_DECAP_FALSE:
            outFrame = frame;
            break;
        default:
            throw cRuntimeError("Unknown encapDecap value: %d", encapDecap);
            break;
    }
    send(outFrame, "upperLayerOut");
}
Member Data Documentation
EncapDecap Ieee80211MgmtAPBase::encapDecap [protected]
Referenced by encapsulate(), initialize(), and sendToUpperLayer().
bool Ieee80211MgmtAPBase::isConnectedToHL [protected]
Referenced by Ieee80211MgmtAPSimplified::handleDataFrame(), Ieee80211MgmtAP::handleDataFrame(), initialize(), and sendToUpperLayer().
The documentation for this class was generated from the following files:
Ieee80211MgmtAPBase.h
Ieee80211MgmtAPBase.cc