INET Framework for OMNeT++/OMNEST: SDESChunk Class Reference
SDESChunk Class Reference
The class SDESChunk is used for storing SDESItem objects for one rtp end system.
#include <sdes.h>
Public Member Functions
SDESChunk (const char *name=NULL, uint32 ssrc=0)
Default constructor.
SDESChunk (const SDESChunk &sdesChunk)
Copy constructor.
virtual ~SDESChunk ()
Destructor.
SDESChunk & operator= (const SDESChunk &sdesChunk)
Operator equal.
virtual SDESChunk * dup () const
Duplicates this SDESChunk by calling the copy constructor.
virtual std::string info () const
Writes a short info about this SDESChunk into the given string.
virtual void dump (std::ostream &os) const
Writes a longer info about this SDESChunk into the given stream.
virtual void addSDESItem (SDESItem *item)
Adds an SDESItem to this SDESChunk.
virtual uint32 getSsrc () const
Returns the ssrc identifier this SDESChunk is for.
virtual void setSsrc (uint32 ssrc)
Sets the ssrc identifier this SDESChunk is for.
virtual int getLength () const
Returns the length in bytes of this SDESChunk.
Protected Attributes
uint32 _ssrc
The ssrc identifier this SDESChunk is for.
int _length
The length in bytes of this SDESChunk.
Private Member Functions
void copy (const SDESChunk &other)
Detailed Description
The class SDESChunk is used for storing SDESItem objects for one rtp end system.
Constructor & Destructor Documentation
SDESChunk::SDESChunk (const char * name = NULL, uint32 ssrc = 0)
Default constructor.
Referenced by dup().
                                                  : cArray(name)
{
    _ssrc = ssrc;
    _length = 4;
}
SDESChunk::SDESChunk (const SDESChunk & sdesChunk)
Copy constructor.
                                               : cArray(sdesChunk)
{
    copy(sdesChunk);
}
SDESChunk::~SDESChunk () [virtual]
Destructor.
{
}
Member Function Documentation
void SDESChunk::addSDESItem (SDESItem * item) [virtual]
Adds an SDESItem to this SDESChunk.
If there is already an SDESItem of the same type in this SDESChunk it is replaced by the new one.
Referenced by RTPParticipantInfo::addSDESItem().
{
    for (int i = 0; i < size(); i++)
    {
        if (exist(i))
        {
            SDESItem *compareItem = (SDESItem *)(get(i));
            if (compareItem->getType() == sdesItem->getType())
            {
                remove(compareItem);
                _length = _length - compareItem->getLength();
                delete compareItem;
            }
        }
    }
    //sdesItem->setOwner(this);
    add(sdesItem);
    _length += sdesItem->getLength();
}
void SDESChunk::copy (const SDESChunk & other) [inline, private]
Referenced by operator=(), and SDESChunk().
{
    _ssrc = sdesChunk._ssrc;
    _length = sdesChunk._length;
}
void SDESChunk::dump (std::ostream & os) const [virtual]
Writes a longer info about this SDESChunk into the given stream.
{
    os << "SDESChunk:" << endl;
    os << "  ssrc = " << _ssrc << endl;
    for (int i = 0; i < size(); i++)
    {
        if (exist(i))
        {
            ((const SDESItem *)(get(i)))->dump(os);
        }
    }
}
SDESChunk * SDESChunk::dup () const [virtual]
Duplicates this SDESChunk by calling the copy constructor.
{
    return new SDESChunk(*this);
}
int SDESChunk::getLength () const [virtual]
Returns the length in bytes of this SDESChunk.
Referenced by RTCPSDESPacket::addSDESChunk().
{
    return _length;
}
uint32 SDESChunk::getSsrc () const [virtual]
Returns the ssrc identifier this SDESChunk is for.
Referenced by RTPParticipantInfo::getSsrc(), and RTCP::processIncomingRTCPSDESPacket().
{
    return _ssrc;
}
std::string SDESChunk::info () const [virtual]
Writes a short info about this SDESChunk into the given string.
{
    std::stringstream out;
    out << "SDESChunk.ssrc=" << _ssrc << " items=" << size();
    return out.str();
}
SDESChunk & SDESChunk::operator= (const SDESChunk & sdesChunk)
Operator equal.
{
    if (this == &sdesChunk) return *this;
    cArray::operator=(sdesChunk);
    copy(sdesChunk);
    return *this;
}
void SDESChunk::setSsrc (uint32 ssrc) [virtual]
Sets the ssrc identifier this SDESChunk is for.
Referenced by RTPParticipantInfo::setSsrc().
{
    _ssrc = ssrc;
}
Member Data Documentation
int SDESChunk::_length [protected]
The length in bytes of this SDESChunk.
Referenced by addSDESItem(), copy(), getLength(), and SDESChunk().
uint32 SDESChunk::_ssrc [protected]
The ssrc identifier this SDESChunk is for.
Referenced by copy(), dump(), getSsrc(), info(), SDESChunk(), and setSsrc().
The documentation for this class was generated from the following files:
sdes.h
sdes.cc