INET Framework for OMNeT++/OMNEST: IPv4InterfaceData Class Reference
IPv4InterfaceData Class Reference
IPv4-specific data in an InterfaceEntry.
#include <IPv4InterfaceData.h>
Classes
struct HostMulticastData
struct RouterMulticastData
Public Types
typedef std::vector< IPv4Address > IPv4AddressVector
Public Member Functions
IPv4InterfaceData ()
virtual ~IPv4InterfaceData ()
virtual std::string info () const
virtual std::string detailedInfo () const
Getters
IPv4Address getIPAddress () const
IPv4Address getNetmask () const
int getMetric () const
int getMulticastTtlThreshold () const
const IPv4AddressVector & getJoinedMulticastGroups () const
const IPv4AddressVector & getReportedMulticastGroups () const
bool isMemberOfMulticastGroup (const IPv4Address &multicastAddress) const
bool hasMulticastListener (const IPv4Address &multicastAddress) const
Setters
virtual void setIPAddress (IPv4Address a)
virtual void setNetmask (IPv4Address m)
virtual void setMetric (int m)
virtual void setMulticastTtlThreshold (int threshold)
virtual void joinMulticastGroup (const IPv4Address &multicastAddress)
virtual void leaveMulticastGroup (const IPv4Address &multicastAddress)
virtual void addMulticastListener (const IPv4Address &multicastAddress)
virtual void removeMulticastListener (const IPv4Address &multicastAddress)
Protected Member Functions
void changed1 ()
HostMulticastData * getHostData ()
const HostMulticastData * getHostData () const
RouterMulticastData * getRouterData ()
const RouterMulticastData * getRouterData () const
Protected Attributes
IPv4Address inetAddr
IPv4 address of interface.
IPv4Address netmask
netmask
int metric
link "cost"; see e.g. MS KB article Q299540
HostMulticastData * hostData
RouterMulticastData * routerData
NotificationBoard * nb
Private Member Functions
IPv4InterfaceData (const IPv4InterfaceData &obj)
IPv4InterfaceData & operator= (const IPv4InterfaceData &obj)
Detailed Description
IPv4-specific data in an InterfaceEntry.
Stores interface IPv4 address, netmask, metric, etc.
See also:
InterfaceEntry
Member Typedef Documentation
typedef std::vector<IPv4Address> IPv4InterfaceData::IPv4AddressVector
Constructor & Destructor Documentation
IPv4InterfaceData::IPv4InterfaceData (const IPv4InterfaceData & obj) [private]
IPv4InterfaceData::IPv4InterfaceData ()
{
    netmask = IPv4Address::ALLONES_ADDRESS;
    metric = 0;
    hostData = NULL;
    routerData = NULL;
    nb = NULL;
}
IPv4InterfaceData::~IPv4InterfaceData () [virtual]
{
    delete hostData;
    delete routerData;
}
Member Function Documentation
void IPv4InterfaceData::addMulticastListener (const IPv4Address & multicastAddress) [virtual]
Referenced by IGMPv2::processV2Report().
{
    if(!multicastAddress.isMulticast())
        throw cRuntimeError("IPv4InterfaceData::addMulticastListener(): multicast address expected, received %s.", multicastAddress.str().c_str());
    if (!hasMulticastListener(multicastAddress))
    {
        getRouterData()->reportedMulticastGroups.push_back(multicastAddress);
        changed1();
    }
}
void IPv4InterfaceData::changed1 () [inline, protected]
Referenced by addMulticastListener(), joinMulticastGroup(), leaveMulticastGroup(), and removeMulticastListener().
{changed(NF_INTERFACE_IPv4CONFIG_CHANGED);}
std::string IPv4InterfaceData::detailedInfo () const [virtual]
{
    std::stringstream out;
    out << "inet addr:" << getIPAddress() << "\tMask: " << getNetmask() << "\n";
    out << "Metric: " << getMetric() << "\n";
    if (hostData)
        out << hostData->detailedInfo();
    if (routerData)
        out << routerData->detailedInfo();
    return out.str();
}
HostMulticastData* IPv4InterfaceData::getHostData () [inline, protected]
Referenced by joinMulticastGroup(), and leaveMulticastGroup().
{ if (!hostData) hostData = new HostMulticastData(); return hostData; }
const HostMulticastData* IPv4InterfaceData::getHostData () const [inline, protected]
Referenced by getHostData().
{ return const_cast<IPv4InterfaceData*>(this)->getHostData(); }
IPv4Address IPv4InterfaceData::getIPAddress () const [inline]
Referenced by Batman::add_del_interface_rules(), IPv4NetworkConfigurator::addStaticRoutes(), RoutingTable::configureRouterId(), IPv4NetworkConfigurator::createInterfaceInfo(), BGPRouting::createSession(), detailedInfo(), IPv4NetworkConfigurator::dumpConfig(), RSVP::evalNextHopInterface(), RoutingTable::findInterfaceByLocalBroadcastAddress(), IPv4NetworkConfigurator::findInterfaceOnLinkByNodeAddress(), BGPRouting::findMyAS(), IPv4::fragmentAndSend(), RoutingTable::gatherAddresses(), PingTestApp::getAllAddresses(), OLSR::getIfaceAddressFromIndex(), RoutingTable::getInterfaceByAddress(), IPvXAddressResolver::getInterfaceIPv4Address(), DSDV_2::handleMessage(), Batman::handleMessage(), DSRUU::handleMessage(), IPv4::handlePacketFromNetwork(), IPv4Route::info(), info(), TED::initialize(), LinkStateRouting::initialize(), ARP::initialize(), Batman::initialize(), DYMOUM::initialize(), DSRUU::initialize(), BGPRouting::isInInterfaceTable(), RoutingTable::isLocalAddress(), RoutingTable::isLocalBroadcastAddress(), locality(), BGPRouting::openTCPConnectionToPeer(), RoutingTable::printRoutingTable(), SCTPAssociation::processInitArrived(), ARP::processOutboundPacket(), DHCPServer::processPacket(), LDP::rebuildFecList(), RoutingTableRecorder::recordInterfaceChange(), recvAODVUUPacket(), ManetRoutingBase::registerRoutingModule(), IPv4NetworkConfigurator::resolveInterfaceAndGateway(), Batman::send_udp_packet(), DHCPServer::sendACK(), ARP::sendARPRequest(), ManetRoutingBase::sendICMP(), SCTPAssociation::sendInit(), DHCPServer::sendOffer(), ManetRoutingBase::sendToIp(), ARP::setChangeAddress(), OSPF::Interface::setIfIndex(), RSVP::setupHello(), InterfaceTable::updateLinkDisplayString(), RoutingTable::updateNetmaskRoutes(), and BGPRouting::updateSendProcess().
{return inetAddr;}
const IPv4AddressVector& IPv4InterfaceData::getJoinedMulticastGroups () const [inline]
Referenced by IPv4NetworkConfigurator::dumpConfig(), isMemberOfMulticastGroup(), UDPSocket::joinLocalMulticastGroups(), and UDPSocket::leaveLocalMulticastGroups().
{return getHostData()->joinedMulticastGroups;}
int IPv4InterfaceData::getMetric () const [inline]
Referenced by detailedInfo(), IPv4NetworkConfigurator::dumpConfig(), TED::initialize(), and RoutingTable::updateNetmaskRoutes().
{return metric;}
int IPv4InterfaceData::getMulticastTtlThreshold () const [inline]
Referenced by IPv4::forwardMulticastPacket().
{return getRouterData()->multicastTtlThreshold;}
IPv4Address IPv4InterfaceData::getNetmask () const [inline]
Referenced by Batman::add_del_interface_rules(), IPv4NetworkConfigurator::addStaticRoutes(), IPv4NetworkConfigurator::createInterfaceInfo(), detailedInfo(), IPv4NetworkConfigurator::dumpConfig(), RoutingTable::findInterfaceByLocalBroadcastAddress(), IPvXAddressResolver::getInterfaceIPv4Address(), info(), RoutingTable::isLocalBroadcastAddress(), locality(), ARP::processOutboundPacket(), OSPF::Interface::setIfIndex(), InterfaceTable::updateLinkDisplayString(), and RoutingTable::updateNetmaskRoutes().
{return netmask;}
const IPv4AddressVector& IPv4InterfaceData::getReportedMulticastGroups () const [inline]
{return getRouterData()->reportedMulticastGroups;}
RouterMulticastData* IPv4InterfaceData::getRouterData () [inline, protected]
Referenced by addMulticastListener(), hasMulticastListener(), and removeMulticastListener().
{ if (!routerData) routerData = new RouterMulticastData(); return routerData; }
const RouterMulticastData* IPv4InterfaceData::getRouterData () const [inline, protected]
Referenced by getRouterData().
{ return const_cast<IPv4InterfaceData*>(this)->getRouterData(); }
bool IPv4InterfaceData::hasMulticastListener (const IPv4Address & multicastAddress) const
Referenced by addMulticastListener(), and IPv4::forwardMulticastPacket().
{
    const IPv4AddressVector &multicastGroups = getRouterData()->reportedMulticastGroups;
    return find(multicastGroups.begin(),  multicastGroups.end(), multicastAddress) != multicastGroups.end();
}
std::string IPv4InterfaceData::info () const [virtual]
Referenced by joinMulticastGroup(), and leaveMulticastGroup().
{
    std::stringstream out;
    out << "IPv4:{inet_addr:" << getIPAddress() << "/" << getNetmask().getNetmaskLength();
    if (hostData)
        out << hostData->info();
    if (routerData)
        out << routerData->info();
    out << "}";
    return out.str();
}
bool IPv4InterfaceData::isMemberOfMulticastGroup (const IPv4Address & multicastAddress) const
Referenced by IPv4::handlePacketFromNetwork(), RoutingTable::isLocalMulticastAddress(), DYMOUM::processPacket(), and processPacket().
{
    const IPv4AddressVector &multicastGroups = getJoinedMulticastGroups();
    return find(multicastGroups.begin(), multicastGroups.end(), multicastAddress) != multicastGroups.end();
}
void IPv4InterfaceData::joinMulticastGroup (const IPv4Address & multicastAddress) [virtual]
Referenced by UDP::addMulticastAddressToInterface(), IPv4NetworkConfigurator::addMulticastGroups(), RoutingTable::configureInterfaceForIPv4(), DSDV_2::initialize(), DSRUU::initialize(), OSPFRouting::joinMulticastGroups(), RoutingTableParser::parseMulticastGroups(), and HostAutoConfigurator::setupNetworkLayer().
{
    if(!multicastAddress.isMulticast())
        throw cRuntimeError("IPv4InterfaceData::joinMulticastGroup(): multicast address expected, received %s.", multicastAddress.str().c_str());
    IPv4AddressVector &multicastGroups = getHostData()->joinedMulticastGroups;
    std::vector<int> &refCounts = getHostData()->refCounts;
    for (int i = 0; i < (int)multicastGroups.size(); ++i)
    {
        if (multicastGroups[i] == multicastAddress)
        {
            refCounts[i]++;
            return;
        }
    }
    multicastGroups.push_back(multicastAddress);
    refCounts.push_back(1);
    changed1();
    if (!nb)
        nb = NotificationBoardAccess().get();
    IPv4MulticastGroupInfo info(ownerp, multicastAddress);
    nb->fireChangeNotification(NF_IPv4_MCAST_JOIN, &info);
}
void IPv4InterfaceData::leaveMulticastGroup (const IPv4Address & multicastAddress) [virtual]
{
    if(!multicastAddress.isMulticast())
        throw cRuntimeError("IPv4InterfaceData::leaveMulticastGroup(): multicast address expected, received %s.", multicastAddress.str().c_str());
    IPv4AddressVector &multicastGroups = getHostData()->joinedMulticastGroups;
    std::vector<int> &refCounts = getHostData()->refCounts;
    for (int i = 0; i < (int)multicastGroups.size(); ++i)
    {
        if (multicastGroups[i] == multicastAddress)
        {
            if (--refCounts[i] == 0)
            {
                multicastGroups.erase(multicastGroups.begin()+i);
                refCounts.erase(refCounts.begin()+i);
                changed1();
                if (!nb)
                    nb = NotificationBoardAccess().get();
                IPv4MulticastGroupInfo info(ownerp, multicastAddress);
                nb->fireChangeNotification(NF_IPv4_MCAST_LEAVE, &info);
            }
        }
    }
}
IPv4InterfaceData& IPv4InterfaceData::operator= (const IPv4InterfaceData & obj) [private]
void IPv4InterfaceData::removeMulticastListener (const IPv4Address & multicastAddress) [virtual]
Referenced by IGMPv2::processLeaveTimer().
{
    IPv4AddressVector &multicastGroups = getRouterData()->reportedMulticastGroups;
    int n = multicastGroups.size();
    int i;
    for (i = 0; i < n; i++)
        if (multicastGroups[i] == multicastAddress)
            break;
    if (i != n)
    {
        multicastGroups.erase(multicastGroups.begin() + i);
        changed1();
    }
}
virtual void IPv4InterfaceData::setIPAddress (IPv4Address a) [inline, virtual]
Referenced by FlatNetworkConfigurator::assignAddresses(), IPv4NetworkConfigurator::assignAddresses(), DHCPClient::changeFSMState(), RoutingTable::configureLoopbackForIPv4(), RoutingTable::configureRouterId(), RoutingTableParser::parseInterfaces(), ManetRoutingBase::registerRoutingModule(), and HostAutoConfigurator::setupNetworkLayer().
{inetAddr = a; changed1();}
virtual void IPv4InterfaceData::setMetric (int m) [inline, virtual]
Referenced by RoutingTable::configureInterfaceForIPv4(), RoutingTable::configureLoopbackForIPv4(), RoutingTableParser::parseInterfaces(), and IPv4NetworkConfigurator::readAddressConfiguration().
{metric = m; changed1();}
virtual void IPv4InterfaceData::setMulticastTtlThreshold (int threshold) [inline, virtual]
{getRouterData()->multicastTtlThreshold=threshold; changed1();}
virtual void IPv4InterfaceData::setNetmask (IPv4Address m) [inline, virtual]
Referenced by FlatNetworkConfigurator::assignAddresses(), IPv4NetworkConfigurator::assignAddresses(), DHCPClient::changeFSMState(), RoutingTable::configureLoopbackForIPv4(), RoutingTable::configureRouterId(), RoutingTableParser::parseInterfaces(), ManetRoutingBase::registerRoutingModule(), and HostAutoConfigurator::setupNetworkLayer().
{netmask = m; changed1();}
Member Data Documentation
HostMulticastData* IPv4InterfaceData::hostData [protected]
Referenced by detailedInfo(), info(), IPv4InterfaceData(), and ~IPv4InterfaceData().
IPv4Address IPv4InterfaceData::inetAddr [protected]
IPv4 address of interface.
int IPv4InterfaceData::metric [protected]
link "cost"; see e.g. MS KB article Q299540
Referenced by IPv4InterfaceData().
NotificationBoard* IPv4InterfaceData::nb [protected]
IPv4Address IPv4InterfaceData::netmask [protected]
netmask
Referenced by IPv4InterfaceData().
RouterMulticastData* IPv4InterfaceData::routerData [protected]
Referenced by detailedInfo(), info(), IPv4InterfaceData(), and ~IPv4InterfaceData().
The documentation for this class was generated from the following files:
IPv4InterfaceData.h
IPv4InterfaceData.cc