INET Framework for OMNeT++/OMNEST: RTPProfile Class Reference
RTPProfile Class Reference
The class RTPProfile is a module which handles RTPPayloadSender and RTPPayloadReceiver modules.
#include <RTPProfile.h>
Classes
class SSRCGate
Public Member Functions
RTPProfile ()
Protected Types
typedef std::map< uint32,
SSRCGate * > SSRCGateMap
Stores information to which gate rtp data packets from a ssrc must be forwarded.
Protected Member Functions
virtual void initialize ()
Initializes variables.
virtual ~RTPProfile ()
virtual void handleMessage (cMessage *msg)
Creates and removes payload sender and receiver modules on demand.
virtual void handleMessageFromRTP (cMessage *msg)
Handles messages received from the rtp module.
virtual void handleMessageFromPayloadSender (cMessage *msg)
Handles messages coming from the sender module.
virtual void handleMessageFromPayloadReceiver (cMessage *msg)
Handles messages coming from a receiver module.
virtual void initializeProfile (RTPInnerPacket *rinp)
Initialization message received from rtp module.
virtual void createSenderModule (RTPInnerPacket *rinp)
This method is called when the application issued the creation of an rtp payload sender module to transmit data.
virtual void deleteSenderModule (RTPInnerPacket *rinp)
When a sender module is no longer needed it can be deleted by the profile module.
virtual void senderModuleControl (RTPInnerPacket *rinp)
The profile module forwards sender control messages to the sender module.
virtual void dataIn (RTPInnerPacket *rinp)
Handles incoming data packets: If there isn't a receiver module for this sender it creates one.
virtual void senderModuleInitialized (RTPInnerPacket *rinp)
The sender module returns a senderModuleInitialized message after being initialized.
virtual void senderModuleStatus (RTPInnerPacket *rinp)
After having received a sender module control message the sender module returns a sender status message to inform the application what it's doing at the moment.
virtual void dataOut (RTPInnerPacket *rinp)
Handles outgoing data packets: Calls processOutgoingPacket and forwards the packet to the rtp module.
virtual void processIncomingPacket (RTPInnerPacket *rinp)
Every time a rtp packet is received it it pre-processed by this method to remove profile specific extension which are not handled by the payload receiver module.
virtual void processOutgoingPacket (RTPInnerPacket *rinp)
Simular to the procedure for incoming packets, this adds profile specific extensions to outgoing rtp packets.
virtual SSRCGate * findSSRCGate (uint32 ssrc)
Finds the gate of the receiver module for rtp data packets from this ssrc.
virtual SSRCGate * newSSRCGate (uint32 ssrc)
Creates a new association ssrc/gateId for this ssrc.
Protected Attributes
const char * _profileName
The name of this profile.
int _maxReceivers
The maximum number of incoming data streams this profile module can handle.
SSRCGateMap _ssrcGates
int _rtcpPercentage
The percentage of the available bandwidth to be used for rtcp.
int _preferredPort
The rtp port this profile uses if no port is given.
int _mtu
The maximum size an RTPPacket can have.
bool _autoOutputFileNames
If this is set true the RTPProfile automatically sets the output file name for payload receiver modules so the user is not bothered to set them manually during simulation runtime.
Detailed Description
The class RTPProfile is a module which handles RTPPayloadSender and RTPPayloadReceiver modules.
It creates them dynamically on demand. This class offers all functionality for the above tasks, subclasses just need to set variables like profile name, rtcp percentage and preferred port in their initialize() method. The dynamically created sender and receiver modules must have have following class names: RTP<profileName>Payload<payloadType>Sender RTP<profileName>Payload<payloadType>Receiver
Member Typedef Documentation
typedef std::map<uint32, SSRCGate *> RTPProfile::SSRCGateMap [protected]
Stores information to which gate rtp data packets from a ssrc must be forwarded.
Constructor & Destructor Documentation
RTPProfile::RTPProfile ()
{
}
RTPProfile::~RTPProfile () [protected, virtual]
{
    SSRCGateMap::iterator i;
    for (i = _ssrcGates.begin(); i != _ssrcGates.end(); i++)
        delete i->second;
}
Member Function Documentation
void RTPProfile::createSenderModule (RTPInnerPacket * rinp) [protected, virtual]
This method is called when the application issued the creation of an rtp payload sender module to transmit data.
It creates a new sender module and connects it. The profile module informs the rtp module of having finished this task. Then it initializes the newly create sender module with a inititalizeSenderModule message.
Referenced by handleMessageFromRTP().
{
    ev << "createSenderModule Enter"<<endl;
    int ssrc = rinp->getSsrc();
    int payloadType = rinp->getPayloadType();
    char moduleName[100];
    ev << "ProfileName: " << _profileName << " payloadType: " << payloadType<<endl;
    const char *pkgPrefix = "inet.transport.rtp."; //FIXME hardcoded string
    sprintf(moduleName, "%sRTP%sPayload%iSender", pkgPrefix, _profileName, payloadType);
    cModuleType *moduleType = cModuleType::find(moduleName);
    if (moduleType == NULL)
        throw cRuntimeError("RTPProfile: payload sender module '%s' not found", moduleName);
    RTPPayloadSender *rtpPayloadSender = (RTPPayloadSender *)(moduleType->create(moduleName, this));
    rtpPayloadSender->finalizeParameters();
    gate("payloadSenderOut")->connectTo(rtpPayloadSender->gate("profileIn"));
    rtpPayloadSender->gate("profileOut")->connectTo(gate("payloadSenderIn"));
    rtpPayloadSender->callInitialize();
    rtpPayloadSender->scheduleStart(simTime());
    RTPInnerPacket *rinpOut1 = new RTPInnerPacket("senderModuleCreated()");
    rinpOut1->setSenderModuleCreatedPkt(ssrc);
    send(rinpOut1, "rtpOut");
    RTPInnerPacket *rinpOut2 = new RTPInnerPacket("initializeSenderModule()");
    rinpOut2->setInitializeSenderModulePkt(ssrc, rinp->getFileName(), _mtu);
    send(rinpOut2, "payloadSenderOut");
    delete rinp;
    ev << "createSenderModule Exit"<<endl;
}
void RTPProfile::dataIn (RTPInnerPacket * rinp) [protected, virtual]
Handles incoming data packets: If there isn't a receiver module for this sender it creates one.
The data packet is forwarded to the receiver module after calling processIncomingPacket.
Referenced by handleMessageFromRTP().
{
    ev << "dataIn(RTPInnerPacket *rinp) Enter"<<endl;
    processIncomingPacket(rinp);
    RTPPacket *packet = check_and_cast<RTPPacket *>(rinp->getEncapsulatedPacket());
    uint32 ssrc = packet->getSsrc();
    SSRCGate *ssrcGate = findSSRCGate(ssrc);
    if (!ssrcGate)
    {
        ssrcGate = newSSRCGate(ssrc);
        char payloadReceiverName[100];
        const char *pkgPrefix = "inet.transport.rtp."; //FIXME hardcoded string
        sprintf(payloadReceiverName, "%sRTP%sPayload%iReceiver",
                pkgPrefix, _profileName, packet->getPayloadType());
        cModuleType *moduleType = cModuleType::find(payloadReceiverName);
        if (moduleType == NULL)
            throw cRuntimeError("Receiver module type %s not found", payloadReceiverName);
        else
        {
            RTPPayloadReceiver *receiverModule =
                    (RTPPayloadReceiver *)(moduleType->create(payloadReceiverName, this));
            if (_autoOutputFileNames)
            {
                char outputFileName[100];
                sprintf(outputFileName, "id%i.sim", receiverModule->getId());
                receiverModule->par("outputFileName") = outputFileName;
            }
            receiverModule->finalizeParameters();
            this->gate(ssrcGate->getGateId())->connectTo(receiverModule->gate("profileIn"));
            receiverModule->gate("profileOut")->connectTo(this->gate(ssrcGate->getGateId() -
                    findGate("payloadReceiverOut", 0) + findGate("payloadReceiverIn", 0)));
            for (int i=0; receiverModule->callInitialize(i); i++)
                ;
            receiverModule->scheduleStart(simTime());
        }
    }
    send(rinp, ssrcGate->getGateId());
    ev << "dataIn(RTPInnerPacket *rinp) Exit"<<endl;
}
void RTPProfile::dataOut (RTPInnerPacket * rinp) [protected, virtual]
Handles outgoing data packets: Calls processOutgoingPacket and forwards the packet to the rtp module.
Referenced by handleMessageFromPayloadSender().
{
    processOutgoingPacket(rinp);
    send(rinp, "rtpOut");
}
void RTPProfile::deleteSenderModule (RTPInnerPacket * rinp) [protected, virtual]
When a sender module is no longer needed it can be deleted by the profile module.
Referenced by handleMessageFromRTP().
{
    cModule *senderModule = gate("payloadSenderOut")->getNextGate()->getOwnerModule();
    senderModule->deleteModule();
    RTPInnerPacket *rinpOut = new RTPInnerPacket("senderModuleDeleted()");
    rinpOut->setSenderModuleDeletedPkt(rinpIn->getSsrc());
    delete rinpIn;
    send(rinpOut, "rtpOut");
}
RTPProfile::SSRCGate * RTPProfile::findSSRCGate (uint32 ssrc) [protected, virtual]
Finds the gate of the receiver module for rtp data packets from this ssrc.
Referenced by dataIn().
{
    SSRCGateMap::iterator objectIndex = _ssrcGates.find(ssrc);
    if (objectIndex == _ssrcGates.end())
        return NULL;
    return objectIndex->second;
}
void RTPProfile::handleMessage (cMessage * msg) [protected, virtual]
Creates and removes payload sender and receiver modules on demand.
{
    if (msg->getArrivalGateId() == findGate("rtpIn"))
    {
        handleMessageFromRTP(msg);
    }
    else if (msg->getArrivalGateId() == findGate("payloadSenderIn"))
    {
        handleMessageFromPayloadSender(msg);
    }
    else if (msg->getArrivalGateId() >= findGate("payloadReceiverIn")
            && msg->getArrivalGateId() < findGate("payloadReceiverIn") + _maxReceivers)
    {
        handleMessageFromPayloadReceiver(msg);
    }
    else
    {
        error("message coming from unknown gate");
    }
}
void RTPProfile::handleMessageFromPayloadReceiver (cMessage * msg) [protected, virtual]
Handles messages coming from a receiver module.
Referenced by handleMessage().
{
    // currently payload receiver modules don't send messages
    delete msg;
}
void RTPProfile::handleMessageFromPayloadSender (cMessage * msg) [protected, virtual]
Handles messages coming from the sender module.
Referenced by handleMessage().
{
    RTPInnerPacket *rinpIn = check_and_cast<RTPInnerPacket *>(msg);
    switch (rinpIn->getType())
    {
    case RTP_INP_DATA_OUT:
        dataOut(rinpIn);
        break;
    case RTP_INP_SENDER_MODULE_INITIALIZED:
        senderModuleInitialized(rinpIn);
        break;
    case RTP_INP_SENDER_MODULE_STATUS:
        senderModuleStatus(rinpIn);
        break;
    default:
        error("Profile received RTPInnerPacket from sender module with wrong type: %d", rinpIn->getType());
        break;
    }
}
void RTPProfile::handleMessageFromRTP (cMessage * msg) [protected, virtual]
Handles messages received from the rtp module.
Referenced by handleMessage().
{
    ev << "handleMessageFromRTP Enter "<<endl;
    RTPInnerPacket *rinpIn = check_and_cast<RTPInnerPacket *>(msg);
    switch (rinpIn->getType())
    {
    case RTP_INP_INITIALIZE_PROFILE:
        initializeProfile(rinpIn);
        break;
    case RTP_INP_CREATE_SENDER_MODULE:
        createSenderModule(rinpIn);
        break;
    case RTP_INP_DELETE_SENDER_MODULE:
        deleteSenderModule(rinpIn);
        break;
    case RTP_INP_SENDER_MODULE_CONTROL:
        senderModuleControl(rinpIn);
        break;
    case RTP_INP_DATA_IN:
        dataIn(rinpIn);
        break;
   default:
        error("RTPInnerPacket from RTPModule has wrong type: %d", rinpIn->getType());
        break;
    }
    ev << "handleMessageFromRTP Exit "<<endl;
}
void RTPProfile::initialize () [protected, virtual]
Initializes variables.
Must be overwritten by subclasses.
Reimplemented in RTPAVProfile.
{
    ev << "initialize() Enter"<<endl;
    _profileName = "Profile";
    _rtcpPercentage = 5;
    _preferredPort = PORT_UNDEF;
    // how many gates to payload receivers do we have
    _maxReceivers = gateSize("payloadReceiverOut");
    _ssrcGates.clear();
    _autoOutputFileNames = par("autoOutputFileNames").boolValue();
    ev << "initialize() Exit"<<endl;
}
void RTPProfile::initializeProfile (RTPInnerPacket * rinp) [protected, virtual]
Initialization message received from rtp module.
Referenced by handleMessageFromRTP().
{
    ev << "initializeProfile Enter"<<endl;
    _mtu = rinp->getMTU();
    delete rinp;
    RTPInnerPacket *rinpOut = new RTPInnerPacket("profileInitialized()");
    rinpOut->setProfileInitializedPkt(_rtcpPercentage, _preferredPort);
    send(rinpOut, "rtpOut");
    ev << "initializeProfile Exit"<<endl;
}
RTPProfile::SSRCGate * RTPProfile::newSSRCGate (uint32 ssrc) [protected, virtual]
Creates a new association ssrc/gateId for this ssrc.
Referenced by dataIn().
{
    SSRCGate *ssrcGate = new SSRCGate(ssrc);
    bool assigned = false;
    int receiverGateId = findGate("payloadReceiverOut", 0);
    for (int i = receiverGateId; i < receiverGateId + _maxReceivers && !assigned; i++)
    {
        if (!gate(i)->isConnected())
        {
            ssrcGate->setGateId(i);
            assigned = true;
        }
    }
    if (!assigned)
        throw cRuntimeError("Can't manage more senders");
    _ssrcGates[ssrc] = ssrcGate;
    return ssrcGate;
}
void RTPProfile::processIncomingPacket (RTPInnerPacket * rinp) [protected, virtual]
Every time a rtp packet is received it it pre-processed by this method to remove profile specific extension which are not handled by the payload receiver module.
In this implementation the packet isn't changed. Important: This method works with RTPInnerPacket. So the rtp packet must be decapsulated, changed and encapsulated again.
Referenced by dataIn().
{
    // do nothing with the packet
}
void RTPProfile::processOutgoingPacket (RTPInnerPacket * rinp) [protected, virtual]
Simular to the procedure for incoming packets, this adds profile specific extensions to outgoing rtp packets.
Referenced by dataOut().
{
    // do nothing with the packet
}
void RTPProfile::senderModuleControl (RTPInnerPacket * rinp) [protected, virtual]
The profile module forwards sender control messages to the sender module.
Referenced by handleMessageFromRTP().
{
    send(rinp, "payloadSenderOut");
}
void RTPProfile::senderModuleInitialized (RTPInnerPacket * rinp) [protected, virtual]
The sender module returns a senderModuleInitialized message after being initialized.
The profile module forwards this message to the rtp module which delivers it to its destination, the rtcp module.
Referenced by handleMessageFromPayloadSender().
{
    ev << "senderModuleInitialized"<<endl;
    send(rinp, "rtpOut");
}
void RTPProfile::senderModuleStatus (RTPInnerPacket * rinp) [protected, virtual]
After having received a sender module control message the sender module returns a sender status message to inform the application what it's doing at the moment.
Referenced by handleMessageFromPayloadSender().
{
    ev << "senderModuleStatus"<<endl;
    send(rinp, "rtpOut");
}
Member Data Documentation
bool RTPProfile::_autoOutputFileNames [protected]
If this is set true the RTPProfile automatically sets the output file name for payload receiver modules so the user is not bothered to set them manually during simulation runtime.
Referenced by dataIn(), and initialize().
int RTPProfile::_maxReceivers [protected]
The maximum number of incoming data streams this profile module can handle.
It is set to the gate size of "payloadReceiverOut", "payloadReceiverIn".
Referenced by handleMessage(), initialize(), and newSSRCGate().
int RTPProfile::_mtu [protected]
The maximum size an RTPPacket can have.
Referenced by createSenderModule(), and initializeProfile().
int RTPProfile::_preferredPort [protected]
The rtp port this profile uses if no port is given.
Referenced by RTPAVProfile::initialize(), initialize(), and initializeProfile().
const char* RTPProfile::_profileName [protected]
The name of this profile.
Needed for dynamic creating of sender and receiver modules.
Referenced by createSenderModule(), dataIn(), RTPAVProfile::initialize(), and initialize().
int RTPProfile::_rtcpPercentage [protected]
The percentage of the available bandwidth to be used for rtcp.
Referenced by RTPAVProfile::initialize(), initialize(), and initializeProfile().
SSRCGateMap RTPProfile::_ssrcGates [protected]
Referenced by findSSRCGate(), initialize(), newSSRCGate(), and ~RTPProfile().
The documentation for this class was generated from the following files:
RTPProfile.h
RTPProfile.cc