INET Framework for OMNeT++/OMNEST: RTPInnerPacket Class Reference
RTPInnerPacket Class Reference
This class is used for communication between submodules of the RTP layer module.
#include <RTPInnerPacket.h>
Public Member Functions
RTPInnerPacket (const char *name=NULL, int kind=0)
RTPInnerPacket (const RTPInnerPacket &other)
RTPInnerPacket & operator= (const RTPInnerPacket &other)
virtual RTPInnerPacket * dup () const
virtual std::string info () const
Writes a short info about this RTPInnerPacket into the given string.
virtual void dump (std::ostream &os) const
Writes a longer info about this RTPInnerPacket into the given output stream.
virtual void setInitializeProfilePkt (int mtu)
Called by the rtp module after creating the profile module.
virtual void setProfileInitializedPkt (int rtcpPercentage, int port)
Called by the profile module after it has received the initializeProfile() message.
virtual void setInitializeRTCPPkt (const char *commonName, int mtu, int bandwidth, int rtcpPercentage, IPv4Address address, int port)
Called by the rtp module to inform the rtcp module about mandatory information for starting the rtp session.
virtual void setRtcpInitializedPkt (uint32 ssrc)
Called by the rtcp module after it has waited for half an rtcp interval for incoming messages from other session participants.
virtual void setCreateSenderModulePkt (uint32 ssrc, int payloadType, const char *fileName)
virtual void setSenderModuleCreatedPkt (uint32 ssrc)
virtual void setDeleteSenderModulePkt (uint32 ssrc)
virtual void setSenderModuleDeletedPkt (uint32 ssrc)
virtual void setInitializeSenderModulePkt (uint32 ssrc, const char *fileName, int mtu)
virtual void setSenderModuleInitializedPkt (uint32 ssrc, int payloadType, int clockRate, int timeStampBase, int sequenceNumberBase)
virtual void setSenderModuleControlPkt (uint32 ssrc, RTPSenderControlMessage *msg)
virtual void setSenderModuleStatusPkt (uint32 ssrc, RTPSenderStatusMessage *msg)
virtual void setLeaveSessionPkt ()
Called by the rtp module to inform the rtcp module that the session should be left.
virtual void setSessionLeftPkt ()
Called by the rtcp module when the rtcp bye packet has been sent to the network.
virtual void setDataOutPkt (RTPPacket *packet)
Capsulates the outgoing RTPPacket into this RTPInnerPacket to transport it within the rtp layer.
virtual void setDataInPkt (RTPPacket *packet, IPv4Address address, int port)
Capsultes the incoming RTPPacket into this RTPInnerPacket to transport it within the rtp layer.
virtual int getMTU () const
Returns the maximum transmission unit stored in this RTPInnerPacket.
Detailed Description
This class is used for communication between submodules of the RTP layer module.
Constructor & Destructor Documentation
RTPInnerPacket::RTPInnerPacket (const char * name = NULL, int kind = 0) [inline]
Referenced by dup().
: RTPInnerPacket_Base(name, kind) {}
RTPInnerPacket::RTPInnerPacket (const RTPInnerPacket & other) [inline]
: RTPInnerPacket_Base(other) {}
Member Function Documentation
void RTPInnerPacket::dump (std::ostream & os) const [virtual]
Writes a longer info about this RTPInnerPacket into the given output stream.
{
    os << "RTPInnerPacket:" << endl;
    os << "  type = " << type_var << endl;
    os << "  commonName = " << commonName_var << endl;
    os << "  mtu = " << mtu_var << endl;
    os << "  bandwidth = " << bandwidth_var << endl;
    os << "  rtcpPercentage = " << rtcpPercentage_var << endl;
    os << "  address = " << address_var << endl;
    os << "  port = " << port_var << endl;
    os << "  ssrc = " << ssrc_var << endl;
    os << "  payloadType = " << payloadType_var << endl;
    os << "  fileName = " << fileName_var << endl;
    os << "  clockRate = " << clockRate_var << endl;
    os << "  timeStampBase = " << timeStampBase_var << endl;
    os << "  sequenceNumberBase = " << sequenceNumberBase_var << endl;
}
virtual RTPInnerPacket* RTPInnerPacket::dup () const [inline, virtual]
Reimplemented from RTPInnerPacket_Base.
Referenced by RTP::dataOut().
{return new RTPInnerPacket(*this);}
virtual int RTPInnerPacket::getMTU () const [inline, virtual]
Returns the maximum transmission unit stored in this RTPInnerPacket.
Referenced by RTCP::handleInitializeRTCP(), RTPProfile::initializeProfile(), and RTPPayloadSender::initializeSenderModule().
{ return getMtu(); }
std::string RTPInnerPacket::info () const [virtual]
Writes a short info about this RTPInnerPacket into the given string.
{
    std::stringstream out;
    out << "RTPInnerPacket: type=" << type_var;
    return out.str();
}
RTPInnerPacket& RTPInnerPacket::operator= (const RTPInnerPacket & other) [inline]
{RTPInnerPacket_Base::operator=(other); return *this;}
void RTPInnerPacket::setCreateSenderModulePkt (uint32 ssrc, int payloadType, const char * fileName) [virtual]
Referenced by RTP::createSenderModule().
{
    type_var = RTP_INP_CREATE_SENDER_MODULE;
    ssrc_var = ssrc;
    payloadType_var = payloadType;
    fileName_var = fileName;
}
void RTPInnerPacket::setDataInPkt (RTPPacket * packet, IPv4Address address, int port) [virtual]
Capsultes the incoming RTPPacket into this RTPInnerPacket to transport it within the rtp layer.
Referenced by RTP::readRet().
{
    type_var = RTP_INP_DATA_IN;
    address_var = address;
    port_var = port;
    encapsulate(packet);
}
void RTPInnerPacket::setDataOutPkt (RTPPacket * packet) [virtual]
Capsulates the outgoing RTPPacket into this RTPInnerPacket to transport it within the rtp layer.
Referenced by RTPAVProfilePayload32Sender::sendPacket().
{
    type_var = RTP_INP_DATA_OUT;
    encapsulate(packet);
}
void RTPInnerPacket::setDeleteSenderModulePkt (uint32 ssrc) [virtual]
Referenced by RTP::deleteSenderModule().
{
    type_var = RTP_INP_DELETE_SENDER_MODULE;
    ssrc_var = ssrc;
}
void RTPInnerPacket::setInitializeProfilePkt (int mtu) [virtual]
Called by the rtp module after creating the profile module.
It informes the profile about the maximum size an rtp packet can have.
Referenced by RTP::initializeProfile().
{
    type_var = RTP_INP_INITIALIZE_PROFILE;
    mtu_var = mtu;
}
void RTPInnerPacket::setInitializeRTCPPkt (const char * commonName, int mtu, int bandwidth, int rtcpPercentage, IPv4Address address, int port) [virtual]
Called by the rtp module to inform the rtcp module about mandatory information for starting the rtp session.
Referenced by RTP::initializeRTCP().
{
    type_var = RTP_INP_INITIALIZE_RTCP;
    commonName_var = commonName;
    mtu_var = mtu;
    bandwidth_var = bandwidth;
    rtcpPercentage_var = rtcpPercentage;
    address_var = address;
    port_var = port;
}
void RTPInnerPacket::setInitializeSenderModulePkt (uint32 ssrc, const char * fileName, int mtu) [virtual]
Referenced by RTPProfile::createSenderModule().
{
    type_var = RTP_INP_INITIALIZE_SENDER_MODULE;
    ssrc_var = ssrc;
    fileName_var = fileName;
    mtu_var = mtu;
}
void RTPInnerPacket::setLeaveSessionPkt () [virtual]
Called by the rtp module to inform the rtcp module that the session should be left.
Referenced by RTP::leaveSession().
{
    type_var = RTP_INP_LEAVE_SESSION;
}
void RTPInnerPacket::setProfileInitializedPkt (int rtcpPercentage, int port) [virtual]
Called by the profile module after it has received the initializeProfile() message.
It informs the rtp module about the percentage of the available bandwidth to be used by rtcp and the preferred port for this profile.
Referenced by RTPProfile::initializeProfile().
{
    type_var = RTP_INP_PROFILE_INITIALIZED;
    rtcpPercentage_var = rtcpPercentage;
    port_var = port;
}
void RTPInnerPacket::setRtcpInitializedPkt (uint32 ssrc) [virtual]
Called by the rtcp module after it has waited for half an rtcp interval for incoming messages from other session participants.
It informs the rtp module which later informs the rtp application about the ssrc identifier
Referenced by RTCP::handleSelfMessage().
{
    type_var = RTP_INP_RTCP_INITIALIZED;
    ssrc_var = ssrc;
}
void RTPInnerPacket::setSenderModuleControlPkt (uint32 ssrc, RTPSenderControlMessage * msg) [virtual]
Referenced by RTP::senderModuleControl().
{
    type_var = RTP_INP_SENDER_MODULE_CONTROL;
    ssrc_var = ssrc;
    encapsulate(msg);
}
void RTPInnerPacket::setSenderModuleCreatedPkt (uint32 ssrc) [virtual]
Referenced by RTPProfile::createSenderModule().
{
    type_var = RTP_INP_SENDER_MODULE_CREATED;
    ssrc_var = ssrc;
}
void RTPInnerPacket::setSenderModuleDeletedPkt (uint32 ssrc) [virtual]
Referenced by RTPProfile::deleteSenderModule().
{
    type_var = RTP_INP_SENDER_MODULE_DELETED;
    ssrc_var = ssrc;
}
void RTPInnerPacket::setSenderModuleInitializedPkt (uint32 ssrc, int payloadType, int clockRate, int timeStampBase, int sequenceNumberBase) [virtual]
Referenced by RTPPayloadSender::initializeSenderModule().
{
    type_var = RTP_INP_SENDER_MODULE_INITIALIZED;
    ssrc_var = ssrc;
    payloadType_var = payloadType;
    clockRate_var = clockRate;
    timeStampBase_var = timeStampBase;
    sequenceNumberBase_var = sequenceNumberBase;
}
void RTPInnerPacket::setSenderModuleStatusPkt (uint32 ssrc, RTPSenderStatusMessage * msg) [virtual]
Referenced by RTPPayloadSender::endOfFile(), RTPPayloadSender::pause(), RTPPayloadSender::play(), and RTPPayloadSender::stop().
{
    type_var = RTP_INP_SENDER_MODULE_STATUS;
    ssrc_var = ssrc;
    encapsulate(msg);
}
void RTPInnerPacket::setSessionLeftPkt () [virtual]
Called by the rtcp module when the rtcp bye packet has been sent to the network.
Referenced by RTCP::createPacket().
{
    type_var = RTP_INP_SESSION_LEFT;
}
The documentation for this class was generated from the following files:
RTPInnerPacket.h
RTPInnerPacket.cc