INET Framework for OMNeT++/OMNEST: RTPParticipantInfo Class Reference
RTPParticipantInfo Class Reference
This class is a super class for classes intended for storing information about RTP end systems.
#include <RTPParticipantInfo.h>
Public Member Functions
RTPParticipantInfo (uint32 ssrc=0)
Default constructor.
RTPParticipantInfo (const RTPParticipantInfo &participantInfo)
Copy constructor.
virtual ~RTPParticipantInfo ()
Destructor.
RTPParticipantInfo & operator= (const RTPParticipantInfo &participantInfo)
Assignment operator.
virtual RTPParticipantInfo * dup () const
Duplicates this RTPParticipantInfo by calling the copy constructor.
virtual void processRTPPacket (RTPPacket *packet, int id, simtime_t arrivalTime)
This method should be extended by a subclass for extracting information about the originating endsystem of an RTP packet.
virtual void processSenderReport (SenderReport &report, simtime_t arrivalTime)
This method extracts information about an RTP endsystem as provided by the given SenderReport.
virtual void processReceptionReport (ReceptionReport &report, simtime_t arrivalTime)
This method extracts information of the given ReceptionReport.
virtual void processSDESChunk (SDESChunk *sdesChunk, simtime_t arrivalTime)
This method extracts sdes information of the given sdes chunk.and stores it.
virtual SDESChunk * getSDESChunk () const
Returns a copy of the sdes chunk used for storing source description items about this system.
virtual void addSDESItem (SDESItem *sdesItem)
Adds this sdes item to the sdes chunk of this participant.
virtual ReceptionReport * receptionReport (simtime_t now)
This method is intended to be overwritten by subclasses.
virtual SenderReport * senderReport (simtime_t now)
This method is intended to be overwritten by subclasses which are used for storing information about itself.
virtual void nextInterval (simtime_t now)
This method should be called by the rtcp module which uses this class for storing information every time an rtcp packet is sent.
virtual bool toBeDeleted (simtime_t now)
Returns true if the end system does no longer participate in the RTP session.
virtual bool isSender () const
Returns true if this endsystem has sent at least one RTP data packet during the last two rtcp intervals (including the current one).
virtual uint32 getSsrc () const
Returns the ssrc identifier of the RTP endsystem.
virtual void setSsrc (uint32 ssrc)
Sets the ssrc identifier.
virtual void addSDESItem (SDESItem::SDES_ITEM_TYPE type, const char *content)
Creates a new SDESItem and adds it to the SDESChunk stored in this RTPParticipantInfo.
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Static Public Member Functions
static char * ssrcToName (uint32 ssrc)
This method returns the given 32 bit ssrc identifier as an 8 character hexadecimal number which is used as name of an RTPParticipantInfo object.
Protected Attributes
SDESChunk _sdesChunk
Used for storing sdes information about this RTP endsystem.
int _silentIntervals
Stores the number of rtcp intervals (including the current one) during which this RTP endsystem hasn't sent any RTP data packets.
Private Member Functions
void copy (const RTPParticipantInfo &other)
Detailed Description
This class is a super class for classes intended for storing information about RTP end systems.
It has two subclasses: RTPReceiverInformation which is used for storing information about other system participating in an RTP session. RTPSenderInformation is used by an RTP endsystem for storing information about itself.
See also:
RTPReceiverInformation
RTPSenderInformation
Constructor & Destructor Documentation
RTPParticipantInfo::RTPParticipantInfo (uint32 ssrc = 0)
Default constructor.
Referenced by dup().
                                                  :
    RTPParticipantInfo_Base(),
    _sdesChunk("SDESChunk", ssrc)
{
    setName(ssrcToName(ssrc));
    // because there haven't been sent any RTP packets
    // by this endsystem at all, the number of silent
    // intervals would be undefined; to calculate with
    // it but not to regard this endsystem as a sender
    // it is set to 3; see isSender() for details
    _silentIntervals = 3;
}
RTPParticipantInfo::RTPParticipantInfo (const RTPParticipantInfo & participantInfo)
Copy constructor.
                                                                      : RTPParticipantInfo_Base(other)
{
    copy(other);
}
RTPParticipantInfo::~RTPParticipantInfo () [virtual]
Destructor.
{
}
Member Function Documentation
void RTPParticipantInfo::addSDESItem (SDESItem * sdesItem) [virtual]
Adds this sdes item to the sdes chunk of this participant.
Referenced by RTCP::handleInitializeRTCP(), and processSDESChunk().
{
    _sdesChunk.addSDESItem(sdesItem);
}
void RTPParticipantInfo::addSDESItem (SDESItem::SDES_ITEM_TYPE type, const char * content) [virtual]
Creates a new SDESItem and adds it to the SDESChunk stored in this RTPParticipantInfo.
{
    _sdesChunk.addSDESItem(new SDESItem(type, content));
}
void RTPParticipantInfo::copy (const RTPParticipantInfo & other) [inline, private]
Referenced by operator=(), and RTPParticipantInfo().
{
    _sdesChunk = other._sdesChunk;
    _silentIntervals = other._silentIntervals;
}
RTPParticipantInfo * RTPParticipantInfo::dup () const [virtual]
Duplicates this RTPParticipantInfo by calling the copy constructor.
Reimplemented from RTPParticipantInfo_Base.
Reimplemented in RTPReceiverInfo, and RTPSenderInfo.
{
    return new RTPParticipantInfo(*this);
}
SDESChunk * RTPParticipantInfo::getSDESChunk () const [virtual]
Returns a copy of the sdes chunk used for storing source description items about this system.
Referenced by RTCP::createPacket().
{
    return new SDESChunk(_sdesChunk);
}
uint32 RTPParticipantInfo::getSsrc () const [virtual]
Returns the ssrc identifier of the RTP endsystem.
Implements RTPParticipantInfo_Base.
Referenced by RTCP::createPacket(), RTCP::handleSelfMessage(), RTCP::processIncomingRTCPReceiverReportPacket(), RTCP::processIncomingRTCPSenderReportPacket(), and RTPReceiverInfo::receptionReport().
{
    return _sdesChunk.getSsrc();
}
bool RTPParticipantInfo::isSender () const [virtual]
Returns true if this endsystem has sent at least one RTP data packet during the last two rtcp intervals (including the current one).
Referenced by RTCP::createPacket(), RTPReceiverInfo::receptionReport(), RTCP::scheduleInterval(), and RTPSenderInfo::senderReport().
{
    return (_silentIntervals <= 1);
}
void RTPParticipantInfo::nextInterval (simtime_t now) [virtual]
This method should be called by the rtcp module which uses this class for storing information every time an rtcp packet is sent.
Some behaviour of RTP and rtcp (and this class) depend on how many rtcp intervals have passed, for example an RTP end system is marked as inactive if there haven't been received packets from it for a certain number of rtpc intervals. Call getSenderReport() and createReceptionReport() before calling this method.
See also:
getSenderReport()
createReceptionReport()
Reimplemented in RTPReceiverInfo.
Referenced by RTCP::createPacket().
{
    _silentIntervals++;
}
RTPParticipantInfo & RTPParticipantInfo::operator= (const RTPParticipantInfo & participantInfo)
Assignment operator.
{
    if (this == &other) return *this;
    RTPParticipantInfo_Base::operator=(other);
    copy(other);
    return *this;
}
virtual void RTPParticipantInfo::parsimPack (cCommBuffer * b) [inline, virtual]
Reimplemented from RTPParticipantInfo_Base.
{ throw cRuntimeError("The parsimPack() not implemented."); }
virtual void RTPParticipantInfo::parsimUnpack (cCommBuffer * b) [inline, virtual]
Reimplemented from RTPParticipantInfo_Base.
{ throw cRuntimeError("The parsimUnpack() not implemented."); }
void RTPParticipantInfo::processReceptionReport (ReceptionReport & report, simtime_t arrivalTime) [virtual]
This method extracts information of the given ReceptionReport.
{
    // useful code can be found in subclasses
}
void RTPParticipantInfo::processRTPPacket (RTPPacket * packet, int id, simtime_t arrivalTime) [virtual]
This method should be extended by a subclass for extracting information about the originating endsystem of an RTP packet.
This method sets _silentInterval to 0 so that the sender of this RTP packet is regarded as an active sender.
Reimplemented in RTPReceiverInfo, and RTPSenderInfo.
Referenced by RTCP::processIncomingRTPPacket().
{
    _silentIntervals = 0;
    delete packet;
}
void RTPParticipantInfo::processSDESChunk (SDESChunk * sdesChunk, simtime_t arrivalTime) [virtual]
This method extracts sdes information of the given sdes chunk.and stores it.
Reimplemented in RTPReceiverInfo.
Referenced by RTCP::processIncomingRTCPSDESPacket().
{
    for (int i = 0; i < sdesChunk->size(); i++)
    {
        if (sdesChunk->exist(i))
        {
            SDESItem *sdesItem = (SDESItem *)(sdesChunk->remove(i));
            addSDESItem(sdesItem);
        }
    }
    delete sdesChunk;
}
void RTPParticipantInfo::processSenderReport (SenderReport & report, simtime_t arrivalTime) [virtual]
This method extracts information about an RTP endsystem as provided by the given SenderReport.
Referenced by RTCP::processIncomingRTCPSenderReportPacket().
{
    // useful code can be found in subclasses
}
ReceptionReport * RTPParticipantInfo::receptionReport (simtime_t now) [virtual]
This method is intended to be overwritten by subclasses.
It should return a receiver report if there have been received RTP packets from that endsystem and NULL otherwise.
Reimplemented in RTPReceiverInfo.
{
    return NULL;
}
SenderReport * RTPParticipantInfo::senderReport (simtime_t now) [virtual]
This method is intended to be overwritten by subclasses which are used for storing information about itself.
It should return a sender report if there have been sent RTP packets recently or NULL otherwise. The implementation for this class always returns NULL.
Reimplemented in RTPSenderInfo.
{
    return NULL;
}
void RTPParticipantInfo::setSsrc (uint32 ssrc) [virtual]
Sets the ssrc identifier.
Implements RTPParticipantInfo_Base.
Referenced by RTCP::chooseSSRC().
{
    _sdesChunk.setSsrc(ssrc);
}
char * RTPParticipantInfo::ssrcToName (uint32 ssrc) [static]
This method returns the given 32 bit ssrc identifier as an 8 character hexadecimal number which is used as name of an RTPParticipantInfo object.
Referenced by RTCP::findParticipantInfo(), and RTPParticipantInfo().
{
    char name[9];
    sprintf(name, "%08x", ssrc);
    return opp_strdup(name);
}
bool RTPParticipantInfo::toBeDeleted (simtime_t now) [virtual]
Returns true if the end system does no longer participate in the RTP session.
The implementation in this class always returns false.
Reimplemented in RTPReceiverInfo.
Referenced by RTCP::createPacket().
{
    return false;
}
Member Data Documentation
SDESChunk RTPParticipantInfo::_sdesChunk [protected]
Used for storing sdes information about this RTP endsystem.
The ssrc identifier is also stored here.
Referenced by addSDESItem(), copy(), getSDESChunk(), getSsrc(), and setSsrc().
int RTPParticipantInfo::_silentIntervals [protected]
Stores the number of rtcp intervals (including the current one) during which this RTP endsystem hasn't sent any RTP data packets.
When an RTP data packet is received it is reset to 0.
Referenced by copy(), isSender(), nextInterval(), processRTPPacket(), and RTPParticipantInfo().
The documentation for this class was generated from the following files:
RTPParticipantInfo.h
RTPParticipantInfo.cc