INET Framework for OMNeT++/OMNEST: OSPF::RoutingTableEntry Class Reference
OSPF::RoutingTableEntry Class Reference
#include <OSPFRoutingTableEntry.h>
Public Types
enum RoutingPathType { INTRAAREA = 0, INTERAREA = 1, TYPE1_EXTERNAL = 2, TYPE2_EXTERNAL = 3 }
typedef unsigned char RoutingDestinationType
Public Member Functions
RoutingTableEntry ()
RoutingTableEntry (const RoutingTableEntry &entry)
virtual ~RoutingTableEntry ()
bool operator== (const RoutingTableEntry &entry) const
bool operator!= (const RoutingTableEntry &entry) const
void setDestinationType (RoutingDestinationType type)
RoutingDestinationType getDestinationType () const
void setOptionalCapabilities (OSPFOptions options)
OSPFOptions getOptionalCapabilities () const
void setArea (AreaID source)
AreaID getArea () const
void setPathType (RoutingPathType type)
RoutingPathType getPathType () const
void setCost (Metric pathCost)
Metric getCost () const
void setType2Cost (Metric pathCost)
Metric getType2Cost () const
void setLinkStateOrigin (const OSPFLSA *lsa)
const OSPFLSA * getLinkStateOrigin () const
void addNextHop (NextHop hop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
Static Public Attributes
static const unsigned char NETWORK_DESTINATION = 0
static const unsigned char AREA_BORDER_ROUTER_DESTINATION = 1
static const unsigned char AS_BOUNDARY_ROUTER_DESTINATION = 2
Private Attributes
RoutingDestinationType destinationType
OSPFOptions optionalCapabilities
AreaID area
RoutingPathType pathType
Metric cost
Metric type2Cost
const OSPFLSA * linkStateOrigin
std::vector< NextHop > nextHops
Member Typedef Documentation
typedef unsigned char OSPF::RoutingTableEntry::RoutingDestinationType
Member Enumeration Documentation
enum OSPF::RoutingTableEntry::RoutingPathType
Enumerator:
INTRAAREA
INTERAREA
TYPE1_EXTERNAL
TYPE2_EXTERNAL
{
        INTRAAREA = 0,
        INTERAREA = 1,
        TYPE1_EXTERNAL = 2,
        TYPE2_EXTERNAL = 3
    };
Constructor & Destructor Documentation
OSPF::RoutingTableEntry::RoutingTableEntry (void)
                                         :
    IPv4Route(),
    destinationType(OSPF::RoutingTableEntry::NETWORK_DESTINATION),
    area(OSPF::BACKBONE_AREAID),
    pathType(OSPF::RoutingTableEntry::INTRAAREA),
    type2Cost(0),
    linkStateOrigin(NULL)
{
    setNetmask(IPv4Address::ALLONES_ADDRESS);
    setSource(IPv4Route::OSPF);
    memset(&optionalCapabilities, 0, sizeof(OSPFOptions));
}
OSPF::RoutingTableEntry::RoutingTableEntry (const RoutingTableEntry & entry)
                                                                       :
    destinationType(entry.destinationType),
    optionalCapabilities(entry.optionalCapabilities),
    area(entry.area),
    pathType(entry.pathType),
    cost(entry.cost),
    type2Cost(entry.type2Cost),
    linkStateOrigin(entry.linkStateOrigin),
    nextHops(entry.nextHops)
{
    setDestination(entry.getDestination());
    setNetmask(entry.getNetmask());
    setGateway(entry.getGateway());
    setInterface(entry.getInterface());
    setSource(entry.getSource());
    setMetric(entry.getMetric());
}
virtual OSPF::RoutingTableEntry::~RoutingTableEntry () [inline, virtual]
{}
Member Function Documentation
void OSPF::RoutingTableEntry::addNextHop (OSPF::NextHop hop)
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), and OSPF::Area::recheckSummaryLSAs().
{
    if (nextHops.size() == 0) {
        InterfaceEntry*    routingInterface = InterfaceTableAccess().get()->getInterfaceById(hop.ifIndex);
        setInterface(routingInterface);
        // TODO: this used to be commented out, but it seems we need it
        // otherwise gateways will never be filled in and gateway is needed for broadcast networks
        setGateway(hop.hopAddress);
    }
    nextHops.push_back(hop);
}
void OSPF::RoutingTableEntry::clearNextHops () [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), and OSPF::Area::recheckSummaryLSAs().
{ nextHops.clear(); }
AreaID OSPF::RoutingTableEntry::getArea () const [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateInterAreaRoutes(), operator<<(), OSPF::Router::pruneASBoundaryRouterEntries(), OSPF::Area::recheckSummaryLSAs(), and OSPF::Router::selectLeastCostRoutingEntry().
{ return area; }
Metric OSPF::RoutingTableEntry::getCost () const [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::findSameOrWorseCostRoute(), operator<<(), OSPF::Area::recheckSummaryLSAs(), and OSPF::Router::selectLeastCostRoutingEntry().
{ return cost; }
RoutingDestinationType OSPF::RoutingTableEntry::getDestinationType () const [inline]
Referenced by OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::findSameOrWorseCostRoute(), OSPF::Router::getRoutesToASBoundaryRouter(), OSPF::Router::hasRouteToASBoundaryRouter(), OSPF::Router::lookup(), operator<<(), OSPF::Area::originateSummaryLSA(), and OSPF::Area::recheckSummaryLSAs().
{ return destinationType; }
const OSPFLSA* OSPF::RoutingTableEntry::getLinkStateOrigin () const [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), and operator<<().
{ return linkStateOrigin; }
NextHop OSPF::RoutingTableEntry::getNextHop (unsigned int index) const [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), operator<<(), and OSPF::Area::recheckSummaryLSAs().
{ return nextHops[index]; }
unsigned int OSPF::RoutingTableEntry::getNextHopCount () const [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), operator<<(), and OSPF::Area::recheckSummaryLSAs().
{ return nextHops.size(); }
OSPFOptions OSPF::RoutingTableEntry::getOptionalCapabilities () const [inline]
{ return optionalCapabilities; }
RoutingPathType OSPF::RoutingTableEntry::getPathType (void) const [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::findSameOrWorseCostRoute(), OSPF::Router::getPreferredEntry(), OSPF::Router::lookup(), operator<<(), OSPF::Router::pruneASBoundaryRouterEntries(), and OSPF::Area::recheckSummaryLSAs().
{ return pathType; }
Metric OSPF::RoutingTableEntry::getType2Cost () const [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), and operator<<().
{ return type2Cost; }
bool OSPF::RoutingTableEntry::operator!= (const RoutingTableEntry & entry) const [inline]
{ return (!((*this) == entry)); }
bool OSPF::RoutingTableEntry::operator== (const RoutingTableEntry & entry) const
{
    unsigned int hopCount = nextHops.size();
    unsigned int i = 0;
    if (hopCount != entry.nextHops.size()) {
        return false;
    }
    for (i = 0; i < hopCount; i++) {
        if ((nextHops[i] != entry.nextHops[i]))
        {
            return false;
        }
    }
    return ((destinationType == entry.destinationType) &&
            (getDestination() == entry.getDestination()) &&
            (getNetmask() == entry.getNetmask()) &&
            (optionalCapabilities == entry.optionalCapabilities) &&
            (area == entry.area) &&
            (pathType == entry.pathType) &&
            (cost == entry.cost) &&
            (type2Cost == entry.type2Cost) &&
            (linkStateOrigin == entry.linkStateOrigin));
}
void OSPF::RoutingTableEntry::setArea (AreaID source) [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), and OSPF::Router::lookup().
{ area = source; }
void OSPF::RoutingTableEntry::setCost (Metric pathCost)
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), and OSPFRouting::loadExternalRoute().
{
    cost = pathCost;
    // FIXME: this is a hack. But the correct way to do it is to implement a separate IRoutingTable module for OSPF...
    if (pathType == OSPF::RoutingTableEntry::TYPE2_EXTERNAL) {
        setMetric(cost + type2Cost * 1000);
    } else {
        setMetric(cost);
    }
}
void OSPF::RoutingTableEntry::setDestinationType (RoutingDestinationType type) [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), and OSPF::Router::lookup().
{ destinationType = type; }
void OSPF::RoutingTableEntry::setLinkStateOrigin (const OSPFLSA * lsa) [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), and OSPF::Area::createRoutingTableEntryFromSummaryLSA().
{ linkStateOrigin = lsa; }
void OSPF::RoutingTableEntry::setOptionalCapabilities (OSPFOptions options) [inline]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), and OSPF::Area::createRoutingTableEntryFromSummaryLSA().
{ optionalCapabilities = options; }
void OSPF::RoutingTableEntry::setPathType (RoutingPathType type)
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), OSPFRouting::loadExternalRoute(), and OSPF::Router::lookup().
{
    pathType = type;
    // FIXME: this is a hack. But the correct way to do it is to implement a separate IRoutingTable module for OSPF...
    if (pathType == OSPF::RoutingTableEntry::TYPE2_EXTERNAL) {
        setMetric(cost + type2Cost * 1000);
    } else {
        setMetric(cost);
    }
}
void OSPF::RoutingTableEntry::setType2Cost (Metric pathCost)
Referenced by OSPF::Router::calculateASExternalRoutes(), and OSPFRouting::loadExternalRoute().
{
    type2Cost = pathCost;
    // FIXME: this is a hack. But the correct way to do it is to implement a separate IRoutingTable module for OSPF...
    if (pathType == OSPF::RoutingTableEntry::TYPE2_EXTERNAL) {
        setMetric(cost + type2Cost * 1000);
    } else {
        setMetric(cost);
    }
}
Member Data Documentation
AreaID OSPF::RoutingTableEntry::area [private]
Referenced by getArea(), operator==(), and setArea().
const unsigned char OSPF::RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION = 1 [static]
Referenced by OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::findSameOrWorseCostRoute(), OSPF::Router::installASExternalLSA(), operator<<(), OSPF::Area::originateSummaryLSA(), and OSPF::Area::recheckSummaryLSAs().
const unsigned char OSPF::RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION = 2 [static]
Referenced by OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), OSPF::Area::findSameOrWorseCostRoute(), OSPF::Router::getRoutesToASBoundaryRouter(), OSPF::Router::hasRouteToASBoundaryRouter(), OSPF::Router::installASExternalLSA(), operator<<(), OSPF::Area::originateSummaryLSA(), and OSPF::Area::recheckSummaryLSAs().
Metric OSPF::RoutingTableEntry::cost [private]
Referenced by getCost(), and operator==().
RoutingDestinationType OSPF::RoutingTableEntry::destinationType [private]
Referenced by getDestinationType(), operator==(), and setDestinationType().
const OSPFLSA* OSPF::RoutingTableEntry::linkStateOrigin [private]
Referenced by getLinkStateOrigin(), operator==(), and setLinkStateOrigin().
const unsigned char OSPF::RoutingTableEntry::NETWORK_DESTINATION = 0 [static]
Referenced by OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateInterAreaRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Area::createRoutingTableEntryFromSummaryLSA(), OSPF::Area::findSameOrWorseCostRoute(), OSPF::Router::lookup(), OSPF::Router::notifyAboutRoutingTableChanges(), operator<<(), OSPF::Area::originateSummaryLSA(), OSPF::Router::rebuildRoutingTable(), and OSPF::Area::recheckSummaryLSAs().
std::vector<NextHop> OSPF::RoutingTableEntry::nextHops [private]
Referenced by clearNextHops(), getNextHop(), getNextHopCount(), and operator==().
OSPFOptions OSPF::RoutingTableEntry::optionalCapabilities [private]
Referenced by getOptionalCapabilities(), operator==(), RoutingTableEntry(), and setOptionalCapabilities().
RoutingPathType OSPF::RoutingTableEntry::pathType [private]
Referenced by getPathType(), and operator==().
Metric OSPF::RoutingTableEntry::type2Cost [private]
Referenced by getType2Cost(), and operator==().
The documentation for this class was generated from the following files:
OSPFRoutingTableEntry.h
OSPFRoutingTableEntry.cc