INET Framework for OMNeT++/OMNEST: OSPF Namespace Reference
OSPF Namespace Reference
All OSPF classes are in this namespace.
Classes
class Interface
class InterfaceState
class InterfaceStateBackup
class InterfaceStateDesignatedRouter
class InterfaceStateDown
class InterfaceStateLoopback
class InterfaceStateNotDesignatedRouter
class InterfaceStatePointToPoint
class InterfaceStateWaiting
class DatabaseDescriptionHandler
class HelloHandler
class IMessageHandler
class LinkStateAcknowledgementHandler
class LinkStateRequestHandler
class LinkStateUpdateHandler
class MessageHandler
class Neighbor
class NeighborState
class NeighborStateAttempt
class NeighborStateDown
class NeighborStateExchange
class NeighborStateExchangeStart
class NeighborStateFull
class NeighborStateInit
class NeighborStateLoading
class NeighborStateTwoWay
struct NextHop
class RoutingInfo
class LSATrackingInfo
class RouterLSA
class NetworkLSA
class SummaryLSA
class ASExternalLSA
class Area
struct AuthenticationKeyType
struct IPv4AddressRange
struct HostRouteParameters
struct LSAKeyType
class LSAKeyType_Less
struct DesignatedRouterID
class Router
Represents the full OSPF data structure as laid out in RFC2328.
class RoutingTableEntry
Typedefs
typedef unsigned long Metric
typedef IPv4Address RouterID
typedef IPv4Address AreaID
typedef IPv4Address LinkStateID
Enumerations
enum AuthenticationType { NULL_TYPE = 0, SIMPLE_PASSWORD_TYPE = 1, CRYTOGRAPHIC_TYPE = 2 }
Functions
const RouterID NULL_ROUTERID (0, 0, 0, 0)
const AreaID BACKBONE_AREAID (0, 0, 0, 0)
const LinkStateID NULL_LINKSTATEID (0, 0, 0, 0)
const IPv4Address NULL_IPV4ADDRESS (0, 0, 0, 0)
const IPv4AddressRange NULL_IPV4ADDRESSRANGE (IPv4Address(0, 0, 0, 0), IPv4Address(0, 0, 0, 0))
Variables
const DesignatedRouterID NULL_DESIGNATEDROUTERID = { IPv4Address(0, 0, 0, 0), IPv4Address(0, 0, 0, 0)}
Detailed Description
All OSPF classes are in this namespace.
Typedef Documentation
typedef IPv4Address OSPF::AreaID
typedef IPv4Address OSPF::LinkStateID
typedef unsigned long OSPF::Metric
typedef IPv4Address OSPF::RouterID
Enumeration Type Documentation
enum OSPF::AuthenticationType
Enumerator:
NULL_TYPE
SIMPLE_PASSWORD_TYPE
CRYTOGRAPHIC_TYPE
{
    NULL_TYPE = 0,
    SIMPLE_PASSWORD_TYPE = 1,
    CRYTOGRAPHIC_TYPE = 2
};
Function Documentation
const AreaID OSPF::BACKBONE_AREAID (0 , 0 , 0 , 0)
Referenced by OSPF::Router::ageDatabase(), OSPF::Router::calculateASExternalRoutes(), OSPF::Area::calculateShortestPathTree(), OSPF::Interface::floodLSA(), OSPF::Area::hasVirtualLink(), OSPF::Router::installASExternalLSA(), OSPFRouting::loadAreaFromXML(), OSPFRouting::loadConfigFromXML(), OSPFRouting::loadVirtualLink(), OSPF::Router::notifyAboutRoutingTableChanges(), OSPF::Area::originateRouterLSA(), OSPF::MessageHandler::processPacket(), OSPF::Router::pruneASBoundaryRouterEntries(), OSPF::Router::rebuildRoutingTable(), OSPF::Area::recheckSummaryLSAs(), OSPF::Router::removeExternalRoute(), and OSPF::Router::updateExternalRoute().
const IPv4Address OSPF::NULL_IPV4ADDRESS (0 , 0 , 0 , 0)
Referenced by OSPF::Area::calculateNextHops(), OSPF::Area::originateRouterLSA(), OSPF::HelloHandler::processPacket(), and OSPF::Interface::sendHelloPacket().
const IPv4AddressRange OSPF::NULL_IPV4ADDRESSRANGE (IPv4Address(0, 0, 0, 0) , IPv4Address(0, 0, 0, 0))
Referenced by OSPF::Area::addAddressRange(), OSPF::Area::getContainingAddressRange(), OSPF::Router::getContainingAddressRange(), and OSPF::Router::notifyAboutRoutingTableChanges().
const LinkStateID OSPF::NULL_LINKSTATEID (0 , 0 , 0 , 0)
const RouterID OSPF::NULL_ROUTERID (0 , 0 , 0 , 0)
Referenced by OSPF::InterfaceState::calculateDesignatedRouter().
Variable Documentation
const DesignatedRouterID OSPF::NULL_DESIGNATEDROUTERID = { IPv4Address(0, 0, 0, 0), IPv4Address(0, 0, 0, 0)}
Referenced by OSPF::LinkStateUpdateHandler::acknowledgeLSA(), OSPF::Interface::addDelayedAcknowledgement(), OSPF::InterfaceState::calculateDesignatedRouter(), OSPF::Interface::floodLSA(), OSPF::LinkStateRequestHandler::processPacket(), OSPF::LinkStateUpdateHandler::processPacket(), OSPF::Interface::reset(), and OSPF::Interface::sendDelayedAcknowledgements().