INET Framework for OMNeT++/OMNEST: OPP_Global Namespace Reference
OPP_Global Namespace Reference
Functions
std::string ltostr (long i)
Converts an integer to string.
std::string dtostr (double d)
Converts a double to string.
double atod (const char *s)
Converts string to double.
unsigned long atoul (const char *s)
Converts string to unsigned long.
std::string stripnonalnum (const char *s)
Removes non-alphanumeric characters from the given string.
Function Documentation
double OPP_Global::atod (const char * s)
Converts string to double.
Referenced by REDDropper::initialize().
{
    char *e;
    double d = ::strtod(s, &e);
    if (*e)
        throw cRuntimeError("Invalid cast: '%s' cannot be interpreted as a double", s);
    return d;
}
unsigned long OPP_Global::atoul (const char * s)
Converts string to unsigned long.
Referenced by RoutingTable6::configureInterfaceFromXML(), and WRRScheduler::initialize().
{
    char *e;
    unsigned long d = ::strtoul(s, &e, 10);
    if (*e)
        throw cRuntimeError("Invalid cast: '%s' cannot be interpreted as an unsigned long", s);
    return d;
}
std::string OPP_Global::dtostr (double d)
Converts a double to string.
{
    std::ostringstream os;
    os << d;
    return os.str();
}
std::string OPP_Global::ltostr (long i)
Converts an integer to string.
Referenced by DiffservUtil::colorToString(), and DiffservUtil::dscpToString().
{
    std::ostringstream os;
    os << i;
    return os.str();
}
std::string OPP_Global::stripnonalnum (const char * s)
Removes non-alphanumeric characters from the given string.
Referenced by ExtInterface::registerInterface(), PPP::registerInterface(), and EtherMACBase::registerInterface().
{
    std::string result;
    for (; *s; s++)
        if (isalnum(*s))
            result += *s;
    return result;
}